### ISSUE TITLE
Add crown to uppers  - Crown on the top, not the bottom

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#10]
Add crown to uppers  - Crown on the top, not the bottom

**Comment by TEDSTANDAGE** [comment]
Teddy--Can you look at this one as well? Should be a simple fix I believe, just moving the insert point of crown when it's put on uppers (not our normal partitions). Thanks

**Comment by ClassyTeddy** [comment]
I know that I looked at this issue in the past and fixed the problem where crowns were showing up on the bottom of the uppers, not the top. But I don't quite remember why we kept this issue. What were some of the other issues that needed addressed involving crowns with uppers?

**Comment by TEDSTANDAGE** [comment]
I don't remember either...Because there are no notes around the time it was moved from Ready for Testing to In Progress back in April I think we should close it.
