### ISSUE TITLE
2D Drawing cuts off for Extra Large Rooms

### ISSUE THREAD

**Issue by ClassyTeddy** [CCDevNelson/Snap-Updates#100]
The main view portion of the 2D reports appears to cut off at a certain point if a room is too large. This also appears to be the case for extremely large walls. The reason for this is that when a room becomes too large, it goes outside the bounds of the camera that is set for it and anything outside the bounds of the camera does not get captured.

**Comment by TEDSTANDAGE** [comment]
From the user:

"Hi Ted,

Attached are the plan views of a closet and a garage that I am working on.  You will see that the 3D rendering shows the complete room and the 2D plan view only shows part of the room.  This only seems to happen on the large room projects such as a garage or very big closet.  

I appreciate your help on getting this resolved.  Let me know if you have any questions.

Thank you,"

![2D Closet Plan View](https://user-images.githubusercontent.com/61025894/88717785-ea8de280-d0d5-11ea-9be5-ff1212f92ef3.jpg)

![3D Closet Plan View](https://user-images.githubusercontent.com/61025894/88717790-ed88d300-d0d5-11ea-9aca-3a28345da5f7.jpg)

![2D Garage Plan View](https://user-images.githubusercontent.com/61025894/88717797-efeb2d00-d0d5-11ea-9be5-f1b42dbf3a09.jpg)

![3D Garage Plan View](https://user-images.githubusercontent.com/61025894/88717807-f24d8700-d0d5-11ea-9e0a-11771fd22560.jpg)

**Comment by TEDSTANDAGE** [comment]
Update: Unable to replicate at this time (apparently Riya was able to at one point, but now we cannot replicate). I have asked Jerry to send me the project folders for projects he's having this issue on.
