### ISSUE TITLE
Delete one of the "Variable Width" buttons

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#101]
The TK prompt now shows two Variable Width buttons. We need to get rid of one of them (not sure which one is the correct one that gives us the extra width in the XML export).

![image](https://user-images.githubusercontent.com/61025894/86170327-d2737500-bacf-11ea-9b6f-cf1b1201fff1.png)

**Comment by riyajose96** [comment]
Deleted extra "Variable Width" button.
It's on the branch -- Delete-extra-Variable-Width-Button

**Comment by TEDSTANDAGE** [comment]
This looks good to me
