### ISSUE TITLE
GitHub branch that allows development users to use current "live" version

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#104]
I am wondering if there is a way I can pull from the GitHub desktop app the "live" version that non-development users are currently using. If there is a way to do this already, I apologize for not knowing and can someone point me to where I can do that? If there isn't, can we create a branch or something where I can pull from to get that version? This would also be helpful for Katie and others who are helping current users, to try and duplicate the issues they might be running into.

**Comment by RyanMDev** [comment]
Good idea, I just created a branch for this: `Version-1.1.0`

**Comment by TEDSTANDAGE** [comment]
Awesome, thank you
