### ISSUE TITLE
Partitions should be labeled as "Partition" rather than "Panel"

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#106]
Currently partitions are referred to and labeled by SNaP as "panels". Panel is a general term that can refer to many different types of components. The shop is asking that partitions actually be labeled as a "partition" rather than panels.

**Comment by riyajose96** [comment]
Partitions labeled as "Partition" instead of "Panel".
Need help with testing.
On the branch -- labeling-partitions-as-partition

**Comment by riyajose96** [comment]
These fixes are already now on master branch.

**Comment by TEDSTANDAGE** [comment]
Looks good to me
