### ISSUE TITLE
Add topshelf edgeband diagram to label

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#107]
Topshelf labels currently do not have an edgeband diagram like shelves, partitions, cleats, etc., do. The shop is asking that we add to topshelf labels the edgeband diagram that bolds the edges needed to be edgebanded like we do for other parts.

**Comment by TEDSTANDAGE** [comment]
Picture of topshelf label without edgeband diagram:

![image](https://user-images.githubusercontent.com/61025894/87074869-5c0ffa80-c1d4-11ea-8ea4-0d2e96ee923a.png)

**Comment by TEDSTANDAGE** [comment]
This one as well--Mark @CCDevNelson  is this something just on your end or is there something missing in the XML for topshelf that we need to add?

**Comment by CCDevNelson** [comment]
Again, the information looks to be correct in the XML so why it's not coming out on label "could" be with the print.

**Comment by TEDSTANDAGE** [comment]
@CCDevNelson Just following up on this one as well. Please advise, thanks

**Comment by CCDevNelson** [comment]
Ted,
This is NOT one of the new labels that I have programmed. I have not put those out for use yet on any of the saws. I have not tested Top Shelf yet on the new labels, but I will look at that when I get back on the label layouts.
