### ISSUE TITLE
Topshelf needs to be labeled as such

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#108]
Topshelf labels currently are showing the part name as "top". It needs to be labeled as "topshelf". Here is a picture of a topshelf label:

![image](https://user-images.githubusercontent.com/61025894/87074970-81046d80-c1d4-11ea-99f8-5997ef74093b.png)

**Comment by riyajose96** [comment]
These fixes are already now on master branch.

**Comment by TEDSTANDAGE** [comment]
Looks good to me
