### ISSUE TITLE
Add KD shelf above locking drawers

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#11]
Add KD shelf above locking drawers

**Comment by CCDevNelson** [comment]
Is this an automatic thing that needs to happen or a selection choice? If it's a hard fast rule, then it would be an automatic insert when ever a locking drawer is added. Could cause a conflict with KD insert on a drawer stack where it already comes with a KD on top. So if the Top drawer is changed to a locking drawer, then it would put in a second KD unless rules are written to check for this.

**Comment by TEDSTANDAGE** [comment]
From my last comment on Issue #12:

- When there is a TOP locking drawer, there MUST be a KD above that drawer (not necessary for SIDE locking drawer). A rule should be written that if a KD already exists above it (because of the other rules above or below, or because it is already the top drawer and "Top KD" is selected) that it does not add an extra one.

**Comment by TEDSTANDAGE** [comment]
This looks to be working correctly on the Teddy Fixes branch
