### ISSUE TITLE
Label needs to show Color of edgebanding rather than saying "L1"

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#110]
Here is what our label looks like right now when it is identifying which edges to edgeband:

![image](https://user-images.githubusercontent.com/61025894/87076322-71862400-c1d6-11ea-8233-def4eb9f3a67.png)

The circled "L1" should say the name of the color for the edgebanding for that edge rather than just saying "L1". In this job it didn't matter because it was all white, but there are times when the edgebanding is a different color than the melamine material.

**Comment by TEDSTANDAGE** [comment]
Mark, we need your guidance on what you need from the programming side to get the edgebanding color on the label (whether we need a new field exported on the XML, whether you're able to figure out the color from the already exported SKU, etc.). From the discussion we just briefly had I don't think we landed on what exactly you wanted/needed. If you could explain to Teddy/Riya here what we need we would appreciate it. Thanks, Ted

**Comment by CCDevNelson** [comment]
![EdgebandColorName](https://user-images.githubusercontent.com/44483142/87185592-e3c23b80-c29e-11ea-8750-b95995f7fd0c.png)

**Comment by RyanMDev** [comment]
I have some fixes for XML export I am about to commit.

While I have the code open, I can add this as well.

It also looks like there are some issues that only require name changes for parts in the xml:
#106 
#108 

Should I fix and include these?

**Comment by CCDevNelson** [comment]
I would think so...it would helps us at the shop to have these items corrected. 
MH - opinion

**Comment by TEDSTANDAGE** [comment]
Yeah i agree with mark if you’re in there doing that anyway I say go ahead and make those easy fixes

**Comment by RyanMDev** [comment]
Sounds good.

**Comment by RyanMDev** [comment]
These fixes are now on master: CCDevNelson/SNaP-Dev@279650af178050ec7d5c0278b62277db44506b14

**Comment by TEDSTANDAGE** [comment]
Edgeband color name now shows up in XML as a value listed. Will just need to see how it comes out on the label now.

![edgeband color XML](https://user-images.githubusercontent.com/61025894/87342846-c8ef0180-c500-11ea-9800-63db5679d3f9.png)

**Comment by CCDevNelson** [comment]
Color name is passing through to CADCode. Labels are now modified to reflect this information now.
