### ISSUE TITLE
Change "Show Drilling" to default to off

### ISSUE THREAD

**Issue by ClassyTeddy** [CCDevNelson/Snap-Updates#113]
Need to change the setting "Show Drilling" to off by default to hopefully help with lag.

**Comment by TEDSTANDAGE** [comment]
Teddy, Since you're updating defaults--will you set the default melamine material to Oxford White rather than Dura White please? We are having issues in production with dura white & edgebanding, so let's have Oxford White be the default until we have the dura issue resolved. Thanks, Ted

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Default-Changes` branch.

**Comment by TEDSTANDAGE** [comment]
The "show panel drilling" looks to be off, thank you. Please also change the default colors to Oxford White (in the Default-Changes branch, the default melamine material looks to be Select Walnut and default door/drawer face material looks to be Absolute Acajou both for the material and edgebanding).

![image](https://user-images.githubusercontent.com/61025894/87471009-81d14100-c5d2-11ea-98c7-311cd059e198.png)

**Comment by ClassyTeddy** [comment]
Alright, I'll be sure to change those now.

**Comment by ClassyTeddy** [comment]
Should be good to go now

**Comment by TEDSTANDAGE** [comment]
Thanks, they are all Oxford White for me now on that branch.
