### ISSUE TITLE
Add certain Paint/Stain colors to stain options

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#117]
Brock added the following colors on the spreadsheet for us to add to the stain color options (see SNaP Library shared Google Sheet):

Absolute Acajou (SN-0000032)
Custom Gray (PL-0000008)       
Pepperdust (PL-0000009)
Willow Grey (PL-0000010)
Witchcraft (SN-0000033)

We now need to add them to SNaP as options in the stain colors. We should visit differentiating between paint/stain at a later time.

**Comment by ClassyTeddy** [comment]
Ready for testing on the `New-Paint/Stain-Colors` branch

**Comment by TEDSTANDAGE** [comment]
Despite my inability to really differentiate between all these different gray colors (and trying to make sure they aren't just the "ghost" color that shows up sometimes when it can't find a blend file for a color), I think it looks good. We should have someone who isn't color blind verify this however.

**Comment by TEDSTANDAGE** [comment]
Actually I don't see Witchcraft as an option, that still needs to be added.

**Comment by ClassyTeddy** [comment]
I checked the other colors and they are all different shades of grey. I will look at witchcraft.

**Comment by ClassyTeddy** [comment]
Fixed the entry for witchcraft and it should be available on that branch.

**Comment by TEDSTANDAGE** [comment]
Available and working for me now, thank you

**Comment by TEDSTANDAGE** [comment]
This needs to be merged before we release version 1.2.0 so that these colors are available
