### ISSUE TITLE
Blind Corner Cabinet Partition has no Category

### ISSUE THREAD

**Issue by CCDevNelson** [CCDevNelson/Snap-Updates#118]
Blind corner cabinet is not assigned a Category number. Not sure if Brock needs to make a NEW category Item for these or should we just list it as a partition (1008) like the rest. Not sure how this will/will not affect down-stream things such as BC or whatever.
Either way, it MUST have a category number assigned to it.

**Comment by TEDSTANDAGE** [comment]
Let's just make it a partition

**Comment by CCDevNelson** [comment]
My previous post where I said partition (1008) is incorrect...partitions are 1004 in case this confused anyone else beside myself.

**Comment by TEDSTANDAGE** [comment]
Teddy, please assign BCPs a 1004 category to match partitions

**Comment by ClassyTeddy** [comment]
This issue is ready for testing on the `Adding-BCP-Category-Number` branch.

**Comment by TEDSTANDAGE** [comment]
Getting an error in this branch when trying to put in partitions:

![image](https://user-images.githubusercontent.com/61025894/91605092-c3b90b00-e924-11ea-828c-cd5817293a10.png)

**Comment by ClassyTeddy** [comment]
Try it now, I accidentally left something in.

**Comment by TEDSTANDAGE** [comment]
Works now, thank you. Let's keep the name of the piece as "Blind Corner Panel" and just change the category, unless you have to change the name of the piece to partition to get the category to 1004. The category looks to be correctly assigned as 1004:

![1004](https://user-images.githubusercontent.com/61025894/91606378-cddc0900-e926-11ea-919f-b87b74c0f0f9.png)

The name is partition though:

![image](https://user-images.githubusercontent.com/61025894/91606484-fe23a780-e926-11ea-8799-31c8347d940f.png)

![image](https://user-images.githubusercontent.com/61025894/91606514-0aa80000-e927-11ea-9b65-91257d4748d8.png)

**Comment by TEDSTANDAGE** [comment]
Or if we need them to be named partition for drilling purposes that's fine too, but still would prefer them to be called blind corner panels if possible.

**Comment by ClassyTeddy** [comment]
It is named partition because it uses the same part that the partitions use. I could change the name for just BCPs, but I would like to know from @CCDevNelson if we can do that or if it has to be named Partition, like the other partitions.

**Comment by TEDSTANDAGE** [comment]
Yeah I just meant to label it a BCP to differentiate it from normal partitions—like we differentiate between the different types of shelves. Mark can let us know if it would cause an issue somewhere, but I don’t think just changing the name on the label would cause an issue.

**Comment by TEDSTANDAGE** [comment]
> It is named partition because it uses the same part that the partitions use. I could change the name for just BCPs, but I would like to know from @CCDevNelson if we can do that or if it has to be named Partition, like the other partitions.

@CCDevNelson Please advise

**Comment by CCDevNelson** [comment]
You can call it whatever you want...I was suggesting that it be it's own category so that Duane can track it in BC if needed. There is one possible reason is that the drilling of a "Blind Partition" is very different, but again, that can be handled as a partition just with special "blind pard" drilling assigned to it. So really, it's up to the Higher Ups on if they need to be able to track them differently for say "trending" stats or something....

**Comment by TEDSTANDAGE** [comment]
Teddy, please have the part name be exported as Blind Corner Panel. I verified with Duane that they just want it to have the same category number as partitions (1004). Thanks, Ted

**Comment by ClassyTeddy** [comment]
This issue is ready for testing on the Adding-BCP-Category-Number branch.

**Comment by TEDSTANDAGE** [comment]
Looks good in my testing, thanks Teddy
