### ISSUE TITLE
Testing v1.2.0

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#119]
Everyone (particularly @ClassyTeddy @riyajose96 @kategodfrey @JBTattersall ), Ryan has v1.2.0 ready for us to test on the master branch. Please take time today and tomorrow to thoroughly test it (create projects and rooms, draw every assembly, try all the colors, prepare 2D views, find accessories, test new features you expected to see here, etc.). Use this issue thread to post results of your testing (good and bad). 

If you find an issue that shouldn't hold up the auto-update of this version, please create a new issue rather than commenting here. Only point out issues here if you find something that absolutely needs to be fixed before the release (or clearly state that whatever you found should not hold up the update). Also comment here after you've tested even to say nothing you found should hold up the release. Feel free to send questions to me directly before commenting here if you are unsure.

Let me know if you have any questions.

Thank you, 

Ted

**Comment by ClassyTeddy** [comment]
I did a lot of testing today including:

* Creating new projects and rooms
* Ensuring that multiple and single rooms can be exported
* Testing each material to make sure that they are displayed properly
* Going through each products prompts menu, making sure there are no errors that come up when right clicking on assemblies
* Did testing with Blind Corner Panels, making sure that most inserts work properly.
* On that note, tried going through most inserts to make sure that they were being inserted properly into Partitions.

Most of my testing was cursory, but I ran into no issues myself.

**Comment by riyajose96** [comment]
Testing looks good so far. Found no issues as such. 
-Tested 2D views and xml exports.
- Went through xml exports and checked labels/parts dropdowns.
-Created projects/rooms and tried all prompts.

**Comment by TEDSTANDAGE** [comment]
I know we changed the SNaP defaults to have "Show Panel Drilling" off, but did we disable that feature entirely should someone want to see the holes (even if it slows the program down)? I can't seem to turn the show panel drilling on--only door/hamper face holes show up (turned "Show Panel Drilling" on, saved the room, got out of SNaP, reopened the room and this is what I get):

![image](https://user-images.githubusercontent.com/61025894/88320853-0f97e500-ccd3-11ea-8906-73508d124c43.png)

I was testing a "hutch" style cabinet where drilling only goes down a certain amount then stops even though the partition extends down. Wanted to see the hole count to verify it was doing it correctly.

**Comment by ClassyTeddy** [comment]
When you enable the option, it will start displaying the drilling for newly placed partitions only. It will not update existing partitions.

**Comment by TEDSTANDAGE** [comment]
Ah okay, thank you for the explanation

**Comment by TEDSTANDAGE** [comment]
By the way, my testing has gone smoothly so far. From my talks with @kategodfrey hers have as well but I'll let her post her comments. Hoping to hear from @JBTattersall today as well.

**Comment by CCDevNelson** [comment]
That doesn't seem like a very good solution. The whole point of "showing holes" is for the customer from what I've been told. So that they know that there will be holes drilled on the partitions and they will be visible. Making a choice to turn them on and bog down a large drawing or turn them off and not be able to show them at all seems kind of "prehistoric" if you ask me.
I know the software isn't a true CAD software, but couldn't we do something with like having the holes be on a layer that can be turned on/off? Autocad for example, has layers and if they are turned off, doesn't effect the program what so ever. If you turn that layer on, and then do your rendering, then, yes, it takes longer, but at least you have the ability to go either way.

**Comment by TEDSTANDAGE** [comment]
I agree with Mark's assessment and thoughts above. Let's create a new issue to discuss rather than in this V1.2.0 testing thread as this shouldn't hold up the update.

**Comment by riyajose96** [comment]
Did little more testing today with respect to recent merge requests.
Hoped to see "Differentiate between adjustable shelf and KD shelf #105".
But in the XML, both adjustable shelves and KD shelves are just labeled as "shelf".

**Comment by RyanMDev** [comment]
Fixed this with commit: CCDevNelson/SNaP-Dev@12ffb109f65d178a24296136ef0a8a1ec07b63f7

**Comment by TEDSTANDAGE** [comment]
Thank you Ryan.

Okay though we haven't heard from @kategodfrey and @JBTattersall like I'd hoped, I think things are looking pretty stable and we should push the auto-update. Those two trained with Melissa with the latest version this week and didn't have anything to bring up from that so I think we are good. Teddy & Riya have been testing hard and I've put in a bit and it appears to be working pretty well (some general lagging/slowness when putting assemblies into a room that already has a lot in it or when putting in partitions with a larger amount of openings, etc., but that is fairly normal from what I have seen). Teddy/Riya, let me know if you agree

**Comment by ClassyTeddy** [comment]
I agree. I did as extensive testing as possible

**Comment by riyajose96** [comment]
Yeah, I also have noticed a general slow down whenever the scene is heavy.

**Comment by kategodfrey** [comment]
I haven't found any major issues that would delay the update! I also noticed noticed it would take a long time to load partitions... especially if I had a larger room with a lot of elements.

**Comment by CCDevNelson** [comment]
Sean R has done quite a lot of testing as well and said he hasn't seen anything either that would hold up the release. He didn't know he was suppose to post about that, just was going to post about any errors...

**Comment by SeanRadvan** [comment]
I'll test here on another computer after lunch, but adding drawer stacks in particular seems to cause quite a bit of lag, taking almost a min to come up, even on low object rooms.

**Comment by TEDSTANDAGE** [comment]
> I'll test here on another computer after lunch, but adding drawer stacks in particular seems to cause quite a bit of lag, taking almost a min to come up, even on low object rooms.

Yeah, this is a known issue: https://github.com/CCDevNelson/Snap-Updates/issues/89 and https://github.com/CCDevNelson/SNaP-Dev/issues/210. 

I actually just tested that again--for me it wasn't bad putting in my first drawer stack in a single opening in the scene (a couple seconds, if that). However, I then put in a three opening set of partitions and a 7 opening set of partitions--by the time I put in the 5th set of drawer stacks there was a 75 second lag for the drawer stack to be able to be put in the scene (with each set of partitions and each drawer stack taking longer to load than the previous). 

Do we think this something we can address promptly?

**Comment by RyanMDev** [comment]
I already have a solution in the works for this and it is on my high priority list (CCDevNelson/snap-dev#210).

Between preparing this update and drilling issues I just have not had the time to finish it up.

**Comment by RyanMDev** [comment]
Should we try to fix this before we release version 1.2.0?

**Comment by TEDSTANDAGE** [comment]
Yes, let's make this one fix before we release 1.2.0, I think it's important enough. Thank you Ryan

**Comment by TEDSTANDAGE** [comment]
Otherwise, it looks like we are good to go with the release once the fix is made

**Comment by SeanRadvan** [comment]
![Drawer ](https://user-images.githubusercontent.com/54151330/88426951-e47ec580-cda6-11ea-84a0-f701e641cfa4.png)
didnt see an issue for this, but it looks like placing a door, then a drawer stack, and using "fill opening" causes it too overlap and clip through the drawers.

**Comment by TEDSTANDAGE** [comment]
> ![Drawer ](https://user-images.githubusercontent.com/54151330/88426951-e47ec580-cda6-11ea-84a0-f701e641cfa4.png)
> didnt see an issue for this, but it looks like placing a door, then a drawer stack, and using "fill opening" causes it too overlap and clip through the drawers.

Thanks Sean, it is still an outstanding issue you created in the SNaP-Dev GitHub previously: https://github.com/CCDevNelson/SNaP-Dev/issues/162. We are working to address it but not for this version update since technically it still works if the user does it in the correct sequence and we can train them to do it correctly for now.

**Comment by ClassyTeddy** [comment]
The fix for lag is currently out and ready for testing on the master branch. Everyone, please test it, as well as the master branch as a whole, today and tomorrow. Thank you.

**Comment by SeanRadvan** [comment]
so after refetching origin and loading snap defaults, im still getting lag
on drawer stacks on 2 computers. it seems to be about 5-6 seconds per
drawer stack already placed, even when only a single pard is placed. doors
and hampers are only around 2-3 second per item even with all the drawers
placed.

**Comment by SeanRadvan** [comment]
looking at the history on github, i cant find any merge for a lag fix, are
we sure its live?

**Comment by ClassyTeddy** [comment]
I'm sure it is live on the master branch. It is the string of commits made 3 days ago that include adding a bunch of library .blend files, and adding the library manager file.

**Comment by TEDSTANDAGE** [comment]
Sean R, I'm assuming the fixes are in the three items Ryan added 3 days ago if you look at the History tab on your GitHub Desktop app. Make sure you are also comparing it with the speed of the current version (Version-1.1.0) which is a branch you can also access.

**Comment by SeanRadvan** [comment]
![1 1 time clcok](https://user-images.githubusercontent.com/54151330/89324735-a00fe700-d63c-11ea-8c96-efab5be7a64d.png)
1.1 "feels" faster. it took about 7 drawer stacks to have it take over 30 seconds, with the first 5ish being around 10 (still not great). 1.2 took around 50 seconds to place a stack around a similar number of drawers. I can do more testing, but what ive seen so far doesnt feel like an improvement, or at least enough of one.

**Comment by ClassyTeddy** [comment]
I tested placing 7 drawer stacks in 3 different versions of SNaP. 

The first version was using the branch `Version-1.1.0`:
![Total Draw time 1 1 0](https://user-images.githubusercontent.com/62624110/89327813-55449e00-d641-11ea-9981-f13f71bf89b9.png)
My total draw time was (Rounding each number to the nearest hundreth): 109.36 seconds

The second version was using the branch `Island-Fixes`, a very recent branch that was lacking the lag fix:
![Total Draw Time Pre 1 2 0 Lag Fix](https://user-images.githubusercontent.com/62624110/89327935-82914c00-d641-11ea-872b-933637ebb0bc.png)
My total draw time was: 276.65 seconds

The third version was using the branch `master`:
![Total Draw Time Post 1 2 0 Lag Fix](https://user-images.githubusercontent.com/62624110/89327994-963cb280-d641-11ea-8ef5-fedb91a68af9.png)
My total draw time was: 140.48 seconds

Now the reason as to why drawers started taking so much longer to draw between Version 1.1.0 and now is most likely because we bulked drawers up a lot. We added more new parts to them than any other object (Things like file rails and KD Shelves). Arguably, the drawers are our most bloated library item in the code. That is most likely why they in particular take much longer to draw. But the lag fix is working as intended, with a much needed speed up compared to right before Ryan fixed it. The lag fix should also generally speed up every other object's draw time as well.

**Comment by RyanMDev** [comment]
Please use the console for testing draw times ('Help' > 'Toggle System Console'). The program times itself when drawing items and will give you the exact draw time of each item you draw into the scene.

I tested this same layout on both 1.1.0 and on the master branch here are my results:
![perf](https://user-images.githubusercontent.com/6529544/89330739-8de67680-d645-11ea-97a1-441c4a25aa80.png)

![perf_table](https://user-images.githubusercontent.com/6529544/89330823-a8205480-d645-11ea-8688-8d4fc2466697.png)

**Comment by RyanMDev** [comment]
> Now the reason as to why drawers started taking so much longer to draw between Version 1.1.0 and now is most likely because we bulked drawers up a lot. We added more new parts to them than any other object (Things like file rails and KD Shelves). Arguably, the drawers are our most bloated library item in the code. That is most likely why they in particular take much longer to draw. But the lag fix is working as intended, with a much needed speed up compared to right before Ryan fixed it. The lag fix should also generally speed up every other object's draw time as well.

@ClassyTeddy this is spot-on.

**Comment by SeanRadvan** [comment]
![1 2 vs 1 1](https://user-images.githubusercontent.com/54151330/89333083-52e64200-d649-11ea-8066-3a5ae47a7a4b.png)
im showing the exact opposite results. (left is snap dev, right is 1.1) unless im doing something completely wrong, my results are not lining up. the only other thing i can think of is that this pc has no dedicated gfx card, ill try it again on another pc.

**Comment by ClassyTeddy** [comment]
@RyanMDev is your version 1.1.0 from the branch `Version-1.1.0` like Sean's is? That could be where this confusion is being caused.

**Comment by RyanMDev** [comment]
I am actually testing the release version and not the branch:  https://github.com/CCDevNelson/SNaP-Dev/releases/tag/v1.1.0

I wonder if this could be a Git issue with the branch `Version-1.1.0`. I will investigate.

**Comment by ClassyTeddy** [comment]
Well after doing a lot more testing, I think that the current master build is stable and can be rolled out as 1.2.0. I have ran into no major issues and the lag fix appears to be working just fine.

**Comment by SeanRadvan** [comment]
I havnt been able to confirm the lag fix but havn't seen any glaring issues.
