### ISSUE TITLE
Check height for 3rd KD to show up on drawer stack

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#12]
Check height for 3rd KD to show up on drawer stack

**Comment by CCDevNelson** [comment]
Not sure on this entry. What exactly needs to happen here? What are we checking the height of the partition for? What is the rule? Is this a suggestion (selection or option) or is it a hard fast rule? Where would the KD be inserted? How would that be determined?

**Comment by TEDSTANDAGE** [comment]
The wording about checking the height of the partition came from the old spreadsheet and I just copied it straight from there, I don't think we should focus on that.

I would think it should be a hard and fast rule as far as where SNaP should show the middle KD(s), but ultimately it would be up to the installer in the field. 

There are numerous rules about middle KDs we should make while we are doing this, and perhaps this issue should be merged with Issue #11  (just got off the phone with Sean Wilson about this):

- Middle KDs should only be 6" deep--they will only be drilled for and use the KD fittings for the front line of holes and then the installer will pocket hole the backside of the middle KD
- There should be a middle KD even when there are only two drawers
- When there are 3 or 4 drawers, I propose the middle KD show up above the second to bottom drawer
- When there are 5 or 6 drawers, I propose the middle KD show up above the third to bottom drawer
- We have situations where there are up to 8 drawers (stacks of jewelry drawers, etc.), so we should increase the max amount of drawers from 6 to 8.
- When there are 7 or 8 drawers, I propose we have two middle KDs, with one middle KD showing up above the third to bottom drawer and another above the fifth to bottom drawer
- When there is a TOP locking drawer, there MUST be a KD above that drawer (not necessary for SIDE locking drawer). A rule should be written that if a KD already exists above it (because of the other rules above or below, or because it is already the top drawer and "Top KD" is selected) that it does not add an extra one. (I will add this to Issue #11 as well)
- When there are Tab Pulls, there must be a KD above each drawer, otherwise some drawer faces would stick out more than others when closed (because the tab goes over and behind the drawer face and hits the middle KD, making it stick out a little more than it otherwise would)

**Comment by CCDevNelson** [comment]
Teddy, is this something you think you can handle? This will have lots of code with "IF" cases in it so let me know if you can or if I should transfer to Ryan.

**Comment by ClassyTeddy** [comment]
I probably can do this, but not in one day. There are just a lot of edge cases. So you can add it to my column for now and if I start it and it is really just too much, I'll ask for it to be moved to Ryan.

**Comment by TEDSTANDAGE** [comment]
One other note/clarification having to do when drawers are on top of hampers--there is always a KD above hampers and it is always full depth, not 6" deep, even when there are drawers above the hamper. When drawer stacks are placed on top of a hamper, we would not need a middle KD for those drawers unless there are 4 or more drawers (very uncommon).

**Comment by ClassyTeddy** [comment]
Think I finally got this issue worked out. Please check the Teddy-Fixes Branch to test it before I request to pull it to the master

**Comment by TEDSTANDAGE** [comment]
Thanks Teddy, looking good. I can put in 8 drawers now, the middle KDs look to be in the right place and KDs are being added to every top-locked drawer. 

If there was an existing middle KD where a KD above a top-locked drawer, do you have a rule in there so it doesn't duplicate the KD? Also, are we able to make middle KDs only 6" deep?

**Comment by ClassyTeddy** [comment]
That rule is in place. Lemme change their depths real quick.

**Comment by ClassyTeddy** [comment]
Only the middle KD's or the middle and the locked KD's?

**Comment by TEDSTANDAGE** [comment]
Good questions, I should have been more clear--for KDs that will be used above locking drawers, we want those full depth. For middle KDs that are not being used for locks, those can be just 6" deep--the 6" deep KDs are also only drilled for the front set of KD fittings and the backside of the KD will be pocketholed and secured by the installer. I am not sure if the KD fitting drilling is something you are working with?

**Comment by ClassyTeddy** [comment]
It is not at the moment but I do understand what you said. It will take me more time to figure out the depths then.

**Comment by ClassyTeddy** [comment]
Alright I completed the depths and pushed my changes

**Comment by TEDSTANDAGE** [comment]
The middle KD depths still look to be 6"?

![image](https://user-images.githubusercontent.com/61025894/80398767-fff03800-886c-11ea-845b-a692906ba493.png)

**Comment by ClassyTeddy** [comment]
This is what I get when I insert a new set of drawers on a 12 inch deep partition. Are you using a new set of drawers?

![image](https://user-images.githubusercontent.com/62624110/80399778-9a9d4680-886e-11ea-9b3d-073b4a7fe870.png)

**Comment by TEDSTANDAGE** [comment]
This looks to be working on the Teddy Fixes branch
