### ISSUE TITLE
Edit Mode and Object Mode

### ISSUE THREAD

**Issue by kategodfrey** [CCDevNelson/Snap-Updates#120]
We are training with melissa with the updated dev version. She has Edit Mode/ Object Mode but Jim and I do not. We aren't able to edit the geometry of our closets.

![image](https://user-images.githubusercontent.com/63115502/88218333-c08b7a80-cc14-11ea-8400-177ba53d3fc9.png)

**Comment by kategodfrey** [comment]
The Edit mode should show up between "Closest" and "Ruler"

**Comment by TEDSTANDAGE** [comment]
Can you get a screenshot from her computer please

**Comment by kategodfrey** [comment]
She closed it and now hers doesn't have it either.

**Comment by kategodfrey** [comment]
Never mind we figured it out lol. We had an empty screen and that is why it wasnt there
