### ISSUE TITLE
Remove door handle drilling info

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#124]
We need to remove the door handle drilling info for all doors--our installers do it onsite. Especially on tall doors, it is up to the customer as to where to put the handles.

**Comment by TEDSTANDAGE** [comment]
For clarity, we are keeping the drawer face and hamper face handle drilling, this is just about doors.

**Comment by ClassyTeddy** [comment]
This is ready for testing on the `Door-Drilling-Fixes` branch.
