### ISSUE TITLE
Door hinge drilling fixes

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#125]
Door hinge drilling information is not being passed through to the XML/labels. (Mark, please correct any info I may have wrong here). Need to check on that.

Along with making sure the drilling info is passed on, please create the following rule:

When we have an even hole door that is over 4 feet tall requiring 3 hinges, the middle hinge should be placed so that the space between the lower hinge and the middle hinge is the shorter distance whereas the distance between the middle hinge and the upper hinge will be the larger distance (since the hinge cannot be placed exactly in the middle). This should be taken into account when differentiating between left and right doors--the middle hinges should line up when two tall even holed doors are next to eachother because the smaller distance between the hinges will be on the low side of the door, not the high side. Sean W. requested this particular configuration due to installation concerns.

**Comment by CCDevNelson** [comment]
Ted is correct. No drill information is being passed for the Doors. Drill Test at 10:45am verified this.

**Comment by ClassyTeddy** [comment]
Alright so I have the door hinge drilling coming through now I think.  However, I am not sure most of the hinge drilling information in here is correct. If I could get the diameter of the hinge holes, how many there are, at what hole count exactly does it start requiring 3 hinges, the distance the drill holes should be from the top/bottom, the distance that the center of the drill hole should be away from the side of the door. Any other information would also be appreciated if necessary.

**Comment by ClassyTeddy** [comment]
If I could get the information stated above that would be great. Again, I want to know the values for:
* The diameter of the Hinge holes
* At what hole count does 3 hinges become necessary, 39 or 40
* The distance the hinge holes need to be away from the top and bottom
* The distance the hinge holes should be away from the side of the door
* For even holed doors, the center hole needs to be closer to the bottom hole. Is it just by one hole count?
* Do I need to add screw holes (They are in here, I don't know if you guys use them)
* If you guys do use these screw holes, I need their diameter and distance from the hinge hole.

Any other information you think I would need would be great too. Thanks

**Comment by TEDSTANDAGE** [comment]
@CCDevNelson mark can you please provide this information to Teddy?

Teddy, re: the even hole doors--on odd numbered hole doors the center hinge can be centered in the middle (height-wise) of the door but with an even hole count the middle of the door where the hinge would go does not line up with holes, but in between them, so we have to choose whether to go up or down and we are choosing to go down (for both right and left doors so the middle hinge lines up if the doors are opened right next to each other).

**Comment by ClassyTeddy** [comment]
I understood that. But by how much does get go up or down? Just one hole count?

**Comment by TEDSTANDAGE** [comment]
> If I could get the information stated above that would be great. Again, I want to know the values for:
> 
> * The diameter of the Hinge holes
35mm
> * At what hole count does 3 hinges become necessary, 39 or 40
40H
> * The distance the hinge holes need to be away from the top and bottom
78mm for top/bottom hinges, when there are three hinges then it is centered unless it is an even hole door then see below
> * The distance the hinge holes should be away from the side of the door
21mm for standard doors (both half and full overlay, no difference), 24mm for corner cab doors
> * For even holed doors, the center hole needs to be closer to the bottom hole. Is it just by one hole count?
it will be moved down to the next hole down, so really it moves down a distance equal to half the distance between two holes (16mm)
> * Do I need to add screw holes (They are in here, I don't know if you guys use them)
Yes
> * If you guys do use these screw holes, I need their diameter and distance from the hinge hole.
2mm diameter, 31mm from the side of the door for standard doors (34mm for corner cab doors), and 55mm and 100mm from the top/bottom of the door respectively for top/bottom hinges. Sorry you'll have to do the math to figure out the distance for the middle hinges
> 
> Any other information you think I would need would be great too. Thanks

**Comment by TEDSTANDAGE** [comment]
The screw holes only drill down a depth of 0.5mm (yes, barely touching it). I will get the depth of the hinge cups--there will be a difference for standard hinges and soft close hinges.

**Comment by TEDSTANDAGE** [comment]
I stand corrected (well, Sean W does), there is no difference in depth for the hinge cups--those are all drilled 14mm deep.

**Comment by ClassyTeddy** [comment]
This is ready for testing on the `Door-Drilling-Fixes` Branch. You can test this by either using drilling debug mode or looking at the xml(which is just looking at the dimensions). Keep in mind with the XML, the doors are still labeled as "panel" and either have 6 or 9 holes (depending on if it is over 40 holes)

**Comment by TEDSTANDAGE** [comment]
I don't see them being labeled as "panel"--Doors are being labeled right door and left door depending on the swing (the Type for doors is panel just like all other melamine pieces so that it knows it needs to be cut by the saw, etc.)--the left door and right door distinction is important because it should determine the location of the middle hinge.

**Comment by ClassyTeddy** [comment]
They are being labeled as "panel" in the OperationGroups under manufacturing.

**Comment by TEDSTANDAGE** [comment]
@CCDevNelson @RyanMDev Can we use this when we are ready for testing the door hinge drilling? Thanks, Ted

**Comment by RyanMDev** [comment]
Yes, I will merge Teddy's `Door-Drilling-Fixes` into my drilling fixes branch and use this as a starting point for fixing/testing door hinge drilling.

@CCDevNelson, is the door hinge drilling the next thing you want to test after the KD shelf drilling?

**Comment by TedCC1209** [comment]
We did some testing on Blind Corner Panels, Doors, and Hamper Faces. The BCP was good, but the doors and hamper faces had issues. @ClassyTeddy please let @RyanMDev know if you need him to address or if you can. Here is the test job:

https://drive.google.com/drive/folders/1QUsbXsWK9SGYPiqiBMV9dOSMc1pq_HXp?usp=sharing

Here are the parts tested:

1. Blind Corner Panel - 46.46x18
2. Single Door - 20H 18.58x25.04
3. Hamper Face - 19H 18.58x23.78
4. Even Hole Tall Double Doors - 62H 12.2x77.95
5. Odd Hole Tall Double Doors - 61H 12.2x76.69

Here are the results:

1. Blind Corner Panel - 46.46x18              Good

2. Single Door - 20H 18.58x25.04             No-Good

3. Hamper Face - 19H 18.58x23.78          No-Good

4. Even Hole Tall Double Doors - 62H 12.2x77.95              No-Good

5. Odd Hole Tall Double Doors - 61H 12.2x76.69               No-Good

The only part that actually drilled at all without having to edit the code was the Blind Corner Panel. Every thing else wouldn’t even run at all (as is). With editing tooling, sizing, drill side, etc. I was able to get most of them to drill something.

              2.) This seemed to drill correctly once I change the tooling. The Pilot holes on ALL the doors would not drill. This may be another tooling error, but I could not correct that one.

              3.) Was not able to drill this one.

              4.) One of the doors drilled correct the other one did not. If you have the middle hole off-set to the bottom of middle then the Right Door is correct and the left is not. Otherwise, it’s the other way around.

              5.) These seemed to drill correctly except (and this is true on the Even Hole doors as well), the Holes for the left doors were on the wrong side. Explanation: The holes for Doors should drill opposite of the clamps when the door is flat on the table. See attached

Mark

![DrillSideW](https://user-images.githubusercontent.com/61025894/100874281-915a0500-3461-11eb-894c-411aa05b907d.png)

**Comment by TedCC1209** [comment]
4) The smaller distance between hinges should be on the bottom side of the door--however, Sean W. seemed to think it was the Left Door that was drilled correct but according to Mark's write-up it would be the Right Door...So I don't know how to reconcile that.

@RyanMDev it sounds like Teddy will need you to address these issues--they are highest priority for us right now. Teddy is also likely out for the rest of today, so if you have questions please contact Mark or me. Thanks!

Reference https://github.com/CCDevNelson/Snap-Updates/issues/56

**Comment by RyanMDev** [comment]
> https://drive.google.com/drive/folders/1QUsbXsWK9SGYPiqiBMV9dOSMc1pq_HXp?usp=sharing

I've requested access to the project files.

**Comment by TedCC1209** [comment]
Sorry, thought I had the settings that anyone with the link could see it. You should have access now

**Comment by RyanMDev** [comment]
No worries I was able to create my own testing project with the info Mark provided.

Fixes available on branch: `Hinge-Drilling`.

2. Single Door - 20H 18.58x25.04 No-Good
- Disabled pilot hole drilling to test if this is interfering with drilling. I am wondering if the order of the holes and diameter drilled is giving the machine problems. Consider the drill order shown below:
![hinge_drill_hole_order](https://user-images.githubusercontent.com/6529544/100941755-fa1b9e80-34ae-11eb-868d-b596493e0b8f.png)

1. First hinge hole drilled at 35mm/1.378" diameter.
2. Left pilot hole drilled at 2mm/0.79" diameter.
3. Right pilot hole drilled at 2mm/0.79" diameter.
4. Second hinge hole drilled at 35mm/1.378" diameter.
5. Left pilot hole drilled at 2mm/0.79" diameter.
6. Right pilot hole drilled at 2mm/0.79" diameter.

Could it be that the machine is having trouble switching back and forth between drill diameters?
If this is the case maybe drilling all hinge holes first and all pilot holes after would help here?
Regardless I would be interested to see if hinge holes drill fine when pilot holes are not present.

3. Hamper Face - 19H 18.58x23.78 No-Good
- The hamper face included pull drilling that was drilled from the wrong side. Since we are not drilling pull holes, I removed these, hopefully that will allow the hinge holes to be drilled correctly.

4. Even Hole Tall Double Doors - 62H 12.2x77.95 No-Good
- Fixed left door drilling when middle offset is used.
- Fixed hinge drilling to drill on correct side (opposite of clamps)

5. Odd Hole Tall Double Doors - 61H 12.2x76.69 No-Good
- Fixed hinge drilling to drill on correct side (opposite of clamps)

**Comment by CCDevNelson** [comment]
Ryan,
If it would help, I could get you a file that we currently use for doors that drills both. Ned gave you that program, so you could look at what it's calling out for tooling on those two spindles. I suspect that it's just a difference in the tooling. Either the naming or sizing setup. I did notice that when I went into the program on say the large hole, it had a "lock" on the tool. If I took that lock off, it allowed me to select the correct spindle. I think this one has both, but I just grabbed one, let me know if it doesn't.

Mark
[STNDDOORSR01.zip](https://github.com/CCDevNelson/Snap-Updates/files/5632710/STNDDOORSR01.zip)

**Comment by RyanMDev** [comment]
Thanks, I will take a look.

**Comment by RyanMDev** [comment]
The program Ned gave me reads the XML and not a .BPP file. Am I missing the XML?

**Comment by CCDevNelson** [comment]
Sorry Ryan, I thought you could read the .bpp files. No, I don't have an XML file for the tooling.

**Comment by TedCC1209** [comment]
Hi @RyanMDev , the drilling looked correct on this except for the Hamper Face orientation and the pilot hole drilling. From @CCDevNelson :
"
![image](https://user-images.githubusercontent.com/61025894/102354629-136d2200-3f68-11eb-9058-ad0dc8d26a50.png)
![image](https://user-images.githubusercontent.com/61025894/102354647-19630300-3f68-11eb-9ea5-dede3725fbf7.png)

As you can see from the above pics, the hamper door could not drill at all. I am however, assuming that if it was oriented the correct way, that the drilling would probably be correct.

All the other doors drilled correctly EXCEPT for the “Pilot” holes. These are still not coming in with the correct tool called out."


Are you able to fix the orientation of the hamper faces for drilling? We can fix the pilot hole issue after this next update, but it would be nice if the hamper faces had the correct drilling in this next update. Let me know if this is possible.

Thanks, 

Ted

**Comment by TedCC1209** [comment]
@CCDevNelson I read through this again and saw that @RyanMDev disabled the pilot holes purposely to see if that was causing the hinge drilling issue.

**Comment by RyanMDev** [comment]
On branch `Hinge-Drilling`:

- Pass tool name and diameter for hinge drilling: CCDevNelson/SNaP-Dev@a7be90e3781d4aa9cb24c78c011045dfd5b92273

- Changed hamper door orientation and drilling with commit: CCDevNelson/SNaP-Dev@06559f5cfd8d6b3c04baedfa2d56ea9b3357632e

- Re-enable pilot hole drilling: CCDevNelson/SNaP-Dev@7eebe6225c032385eb313f2c37aecf570c1f95e2

**Comment by CCDevNelson** [comment]
Ryan,
After speaking with Ned this morning, it turns out that our tooling file in CADCode did not have the correct tooling to match the Skipper Machine (at least for that small bit). I made the changes needed and the XML that Ted sent me prior to these most current changes, works fine now. Other than the rotation of the Hamper Door of course. So we need to revert back to before the "Pilot" tool name was added.
And according to Ned, we don't ever want to "call-out" a specific tool (like what I asked you to do by putting in the "Pilot" name, so don't listen to me next time), FYI for future reference....

**Comment by TedCC1209** [comment]
Just noting for reference that another test job has been emailed this morning to Mark/Sean W. for testing.

**Comment by CCDevNelson** [comment]
Drill Test of 12_21_20
Drilling instructions missing in the XML for Doors and Hamper Faces. Blind corner Partitions drills correctly, but the Doors and Hamper Faces are missing the drilling info.
![BlindPard](https://user-images.githubusercontent.com/44483142/102812535-6853d280-4384-11eb-917a-635cfc7ac489.png)
![HampDoor](https://user-images.githubusercontent.com/44483142/102812541-6a1d9600-4384-11eb-9251-21378a7c420c.png)
![Door](https://user-images.githubusercontent.com/44483142/102812542-6be75980-4384-11eb-9e43-1cf8fdc2f111.png)
![DrillTestXMLPic](https://user-images.githubusercontent.com/44483142/102812545-6c7ff000-4384-11eb-907d-dd23cf4b5ff3.png)

**Comment by RyanMDev** [comment]
> Just noting for reference that another test job has been emailed this morning to Mark/Sean W. for testing.

Can we share that test job/XML here?

**Comment by RyanMDev** [comment]
> Just noting for reference that another test job has been emailed this morning to Mark/Sean W. for testing.

Not sure which commit/branch was used for the above test, however I have tested this on master branch commit: CCDevNelson/SNaP-Dev@fbe22c0bcb37b35bd99dfffd1c4e7d25fd1bcf1e

Hinge drilling for doors and hamper doors was working fine for me.

XML: 
[snap_job_hinge_drilling_test_12-21.zip](https://github.com/CCDevNelson/Snap-Updates/files/5727372/snap_job_hinge_drilling_test_12-21.zip)

Test room:
![hinge_drilling_xml_test_closet](https://user-images.githubusercontent.com/6529544/102840855-9a7f2780-43b8-11eb-9d51-b6e9abd82048.PNG)

Door/Hamper door parts:
![door_drilling](https://user-images.githubusercontent.com/6529544/102840917-c0a4c780-43b8-11eb-9168-8540aed369b8.PNG)

![hamper_door_drilling](https://user-images.githubusercontent.com/6529544/102840929-c6021200-43b8-11eb-985b-2ae8fb455091.PNG)

XML operation groups:

Door:
![right_door_xml](https://user-images.githubusercontent.com/6529544/102840957-d6b28800-43b8-11eb-8c4b-e6c794f20cb5.PNG)

![right_door_op_grp](https://user-images.githubusercontent.com/6529544/102840967-dadea580-43b8-11eb-82a9-1cfe82a40e3d.PNG)

Hamper door:
![hamper_door_xml](https://user-images.githubusercontent.com/6529544/102840991-e5993a80-43b8-11eb-9cbf-214fdca8eaf5.PNG)

![hamper_door_op_grp](https://user-images.githubusercontent.com/6529544/102840998-e8942b00-43b8-11eb-9913-dd4194769756.PNG)

**Comment by TedCC1209** [comment]
> > Just noting for reference that another test job has been emailed this morning to Mark/Sean W. for testing.
> 
> Can we share that test job/XML here?

https://drive.google.com/drive/folders/16a4dcSmD8P5qWnUJAPx5rS0gtEwDpKbF?usp=sharing

**Comment by TedCC1209** [comment]
@CCDevNelson Not sure if the last test was messed up because I used the Hinge_Drilling branch (I think I was confused about where changes/updates were being made, I am pretty sure all the changes should have been/were in there when I tested), but it looks like it all has been merged to the master branch now anyway. So, here is a new test from the current master branch:

https://drive.google.com/drive/folders/1SOHbnG4l_dIxXdIsCFj8DPOs8-3EALh3?usp=sharing

The parts to test are as follows:

1. Blind Corner Panel - 1 @ 14"x25.03"
2. Single Door - 1 @ 10.88"x25.04"
3. Double Doors - 2 @ 12.2"x55.28" (44H - even hole tall doors)
4. Double Doors - 2 @ 12.2"x54.02" (43H - odd hole tall doors)
5. Hamper - 1 @ 24.58"x23.78" (19H)
6. Hamper - 2 @ 24.58"x25.04" (20H)

**Comment by TedCC1209** [comment]
From @CCDevNelson on Thursday:

>Door hinge holes look to be correct. No pilot holes for them (the machine looked like it was drilling them, but no holes, so need to look into data to see what’s up with that, but could just be a depth issue.
>
>Blind corner panel, looks to be drilled correctly, but I’ll have to have Sean verify that Monday.
>
>Neither one of the Hamper Doors drilled at all. They wouldn’t even optimize the program when I brought it up. Just guessing, but I would assume that is because it couldn’t drill the door oriented the way it was passed to CADCode. I am JUST guessing here. I’ll have to look into that more to verify any of that.
>

**Comment by TedCC1209** [comment]
@ClassyTeddy, per the email from @CCDevNelson, the pilot hole drill depth needs to be changed from 0.5mm to 4mm (0.157"). Please confirm this is something you can address.

Thanks, Ted

**Comment by ClassyTeddy** [comment]
I should be able to address hopefully. I am currently helping J with something, then I will make sure that I know where to change the pilot hole drill depth.

**Comment by ClassyTeddy** [comment]
I believe I changed the depth on the pilot holes. Here is what it looked like on my end before:
![Pilot hole depth before](https://user-images.githubusercontent.com/62624110/103565842-47a87400-4e7e-11eb-8ab5-37b8d36c18b7.png)

And here is what it looks like now:
![Pilot hole depth after](https://user-images.githubusercontent.com/62624110/103565864-5131dc00-4e7e-11eb-95b3-b32a091080dc.png)

This should be all good to go on the `master` branch.

**Comment by TedCC1209** [comment]
The pilot holes look good there Teddy, we will test with the Hamper faces once we make the necessary changes there.

@RyanMDev this is what @CCDevNelson said after looking into the Hamper Face drilling issue further:

> Hamper Faces are for sure coming in the wrong orientation (as shown by the grey/blue).
>
> For it to drill a Hamper Face on the Skipper, it must be oriented as the green shaded area. With the holes opposite of the clamps of the machine. The collets that hold the 35mm bits are located such, that they cannot reach back that far (close to clamps).
> 
![image](https://user-images.githubusercontent.com/61025894/103587630-f1026080-4ea4-11eb-9b27-470b8c661740.png)
>
> The location pins rotated on me so those red dots should be where the lines point to….

**Comment by RyanMDev** [comment]
Here is an updated xml to test, created from the 'Hinge Drill Test 12-28-20' project: 
[snap_job_rotated_hamper_face_orientation.zip](https://github.com/CCDevNelson/Snap-Updates/files/5767802/snap_job_rotated_hamper_face_orientation.zip)

I've included an additional `Orientation` element which should tell CADCode the hamper parts should be rotated as shown above:
![m_orientation_xml](https://user-images.githubusercontent.com/6529544/103601198-fa4bf700-4ebd-11eb-9a2c-71eb02e8a37b.png)


From CADCode documentation:
![m_orientation_cadcode_documentation](https://user-images.githubusercontent.com/6529544/103601161-e86a5400-4ebd-11eb-90a0-3ef21a48f06b.png)

**Comment by CCDevNelson** [comment]
Ryan,
No difference, part still came in oriented wrong. But, also, I looked into this XML and I don't see those changes in this one. Could it be that this is the original one??
Mark

**Comment by RyanMDev** [comment]
> snap_job_rotated_hamper_face_orientation.zip

Interesting, if I download the one above, I am seeing the additional `Orientation` element as well as the hamper font parts referencing the ID.

Additional `Orientation` element should be on line 1007:
![orientation_element_ln](https://user-images.githubusercontent.com/6529544/103711377-2756e300-4f6c-11eb-9e53-8d287f214c94.png)

![orientation_element_notepad](https://user-images.githubusercontent.com/6529544/103711410-3a69b300-4f6c-11eb-8b3e-2c9de1333d5a.png)

Hamper front operation groups should reference this ID on lines 7390 and 7923:
![orientation_id_ln](https://user-images.githubusercontent.com/6529544/103711654-bcf27280-4f6c-11eb-90f8-38c0b239bee2.png)

![orientation_id_notepad](https://user-images.githubusercontent.com/6529544/103711790-080c8580-4f6d-11eb-8e30-f48a6b630aa3.png)

**Comment by CCDevNelson** [comment]
Ryan,
I was mistaken, those are in there...I was looking in the wrong place for them. They are indeed there and as stated above.
So that brings up the fact that it is not working to turn the part with these options.

**Comment by RyanMDev** [comment]
After looking into this, I found that the operation groups for hampers were giving the correct width and length to change the orientation, but the width and length on the labels were not reflecting this. 

The following XML fixes the hamper front labels to match the operation group width and length:

[snap_job_fixed_hamper_labels.zip](https://github.com/CCDevNelson/Snap-Updates/files/5798936/snap_job_fixed_hamper_labels.zip)

**Comment by TedCC1209** [comment]
From the email thread: "Ryan,  Downloaded the file last night and optimized it through CADCode, and ran it this morning. Looks good. The doors are orientated correctly on the table and everything looks good on them!!!"

**Comment by RyanMDev** [comment]
Great!

I have made the relevant changes with commit: CCDevNelson/SNaP-Dev@0c32ec1f73a7adf140924c50209a36734405c9cb
