### ISSUE TITLE
Double doors for corner shelves

### ISSUE THREAD

**Issue by kategodfrey** [CCDevNelson/Snap-Updates#126]
When adding doors to a corner shelving unit, there is an option to force double doors but the image doesn't reflect it. Also, there is no option for opening the doors to see inside.

![image](https://user-images.githubusercontent.com/63115502/88947954-23e56000-d246-11ea-97e4-9e88c9360af9.png)

**Comment by TEDSTANDAGE** [comment]
A few clarifications:

You mean two doors that open independently of each other which aren't connected lazy-susan style (a left and a right door for each opening that each open out, not having two doors on the left opening or two doors on the right opening). The user would need to choose which door has the handle (which would be placed on the side of the door closest to the corner) and which door will go all the way into the corner (without a handle--the customer reaches behind the second door to open after they opened the door with the handle).  

Whoever works on this can come to me re: sizing of the doors.
