### ISSUE TITLE
Change wall names in custom room

### ISSUE THREAD

**Issue by kategodfrey** [CCDevNelson/Snap-Updates#129]
Is there a way to rename the walls in a custom room? Right now all walls are labeled/named: "Wall." It's important to name the walls especially in the 2D views, to know which wall we are referencing.

![image](https://user-images.githubusercontent.com/63115502/88954213-db7e7000-d24e-11ea-96aa-0a540694bfdb.png)

**Comment by TEDSTANDAGE** [comment]
It would be nice to be able to rename any and all walls, whether in a custom room or not, with the default being as-is starting with Wall A and going alphabetically from there.

**Comment by TedCC1209** [comment]
This is possible @kategodfrey . Just click on the wall you want to rename:
