### ISSUE TITLE
Add Room Category to Room Builder

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#130]
We need to start classifying each room we build with the category of product it is (closet, laundry room, pantry, garage, kitchen, etc.). Duane will be getting us the list of categories soon. 

I think the best place to put this would be after clicking "Build Room" in the "Build Room" prompts under the Room name and above the Room Length with it saying "Room Category" on the left and then a drop down with the possible categories on the right. This should be a required field that must be chosen in order to build the room (if possible, let's not have a default and if they try to build a room without choosing a category it should bring up the red asterisk telling them that the category is a required selection):

![Room Category Room Build](https://user-images.githubusercontent.com/61025894/89072533-9bda8580-d32d-11ea-96f8-74b708a19a65.png)

If possible, it should be easy and possible to change the category of a room after you create the room and even after you start drawing in the room. This is in addition to us being able to easily and it being possible to change the name of a room as discussed in https://github.com/CCDevNelson/Snap-Updates/issues/92.

I don't know exactly how the XML export works or how it needs to attached to each part for each room (Mark I would like your input here) but I'm thinking the XML should export the Room Category here as the next item after "Description" but before the first "Part" of the room:

![Room Category XML](https://user-images.githubusercontent.com/61025894/89072517-95e4a480-d32d-11ea-9712-1da084dcfe2c.png)

**Comment by ClassyTeddy** [comment]
This feature is ready for testing on the `Creating-Room-Categories` Branch.

**Comment by TEDSTANDAGE** [comment]
@CCDevNelson Mark, can you test this one to see if it is going to do the job you and Duane are wanting? Here is where it shows up in the XML (this is the second of two rooms in the particular project):

![image](https://user-images.githubusercontent.com/61025894/91353360-06050f80-e7a0-11ea-8a82-32366a736417.png)


I like that this forces the user to pick the room category before they are able to alter the room dimensions.

**Comment by CCDevNelson** [comment]
There is nothing for me to test...no XML was posted here and I have not received this one to test in an email, please send me the XML in an email.

**Comment by TEDSTANDAGE** [comment]
Mark, here is an example XML with the room category for laundry rooms:

https://drive.google.com/file/d/0B7I2qIHfcFaNZDBPaUxDVzRxZk9jbUQtbXVUZDZQLVpEdjY0/view?usp=sharing

In case my dad didn't share with you the room sales category numbers he created, here is a link to a spreadsheet with the rooms and their corresponding category numbers:

https://docs.google.com/spreadsheets/d/1ObB3ink68fRkBEl1ttnTMnsjGExVk-gtjEgEc_yNqXg/edit?usp=sharing

**Comment by TEDSTANDAGE** [comment]
@CCDevNelson Mark, please advise--There is an XML for you to look at linked in my previous/above comment. Thanks, Ted

**Comment by CCDevNelson** [comment]
The XML has the Room Category in the "note" field as you requested and I can read that out to the csv file. It currently exports this in this specific XML:    Laundry:41150 

I have not heard back from Business Central on if this will work in this format or if they need me to parse it out to something else. Will advise as soon as I hear back from them if I need that changed at all in the XML, but I'm pretty sure they can work with some variation of this that I can supply them.
