### ISSUE TITLE
Upper and Lower Doors on double pard

### ISSUE THREAD

**Issue by kategodfrey** [CCDevNelson/Snap-Updates#131]
I need to put upper doors and lower doors on the same single opening but I am getting these two errors:

![image](https://user-images.githubusercontent.com/63115502/89076412-165ad380-d335-11ea-9f04-0f8c829219e4.png)
 
I see my doors there however, but when I go to put in dimensions I get this error:

![image](https://user-images.githubusercontent.com/63115502/89076461-37232900-d335-11ea-8a3c-1bfecfd8af47.png)

**Comment by TEDSTANDAGE** [comment]
Thanks Katie. Can you explain your situation more--it looks like you have oversized pards in this room, does this also happen when you have regular sized partitions? What type of door exists in the opening when you try and place the second door in that opening (Base, tall, etc. or do you get the same error no matter what?)

**Comment by SeanRadvan** [comment]
![image](https://user-images.githubusercontent.com/54151330/89199286-31ab2600-d563-11ea-9a17-1552256e72ac.png)
i cant seem to to replicate your error, it seems like your error is related to blind corner cabinets, is that where you were placing them?

**Comment by kategodfrey** [comment]
I was placing the doors over shelves instead of adding them through the door prompt.
