### ISSUE TITLE
drawer cleating bug

### ISSUE THREAD

**Issue by SeanRadvan** [CCDevNelson/Snap-Updates#135]
for some reason, if i have a drawer stack with cleat set to "none" but then if open the construction options on the pard it is in, it auto changes cleats back to above

**Comment by SeanRadvan** [comment]
![drawer cleating](https://user-images.githubusercontent.com/54151330/89310029-0ab72780-d629-11ea-8880-42500c615bdd.png)

**Comment by SeanRadvan** [comment]
confirmed it does the same thing for hampers.

**Comment by ClassyTeddy** [comment]
This is ready for testing on `Drawer-Cleating-Issues`

**Comment by SeanRadvan** [comment]
Tried both hamper and drawers, and looks to be working.

**Comment by TEDSTANDAGE** [comment]
I think this one is good to go
