### ISSUE TITLE
1/4" backing not properly exporting sku to xml

### ISSUE THREAD

**Issue by SeanRadvan** [CCDevNelson/Snap-Updates#136]
![image002](https://user-images.githubusercontent.com/54151330/89443618-5f2fd500-d705-11ea-8742-c118b91f4ef2.png)
When sending 1/4 backing for pricing they are not pulling a sku, on the current master branch. Needs to be tested for 3/4

**Comment by TEDSTANDAGE** [comment]
https://github.com/CCDevNelson/Snap-Updates/issues/133#issuecomment-668653909

**Comment by TEDSTANDAGE** [comment]
Sean, Ryan has a fix for https://github.com/CCDevNelson/Snap-Updates/issues/133 that I believe fixes this as well. Will you test it and see if you agree? Thanks, Ted
