### ISSUE TITLE
Tool Bar is frozen

### ISSUE THREAD

**Issue by kategodfrey** [CCDevNelson/Snap-Updates#139]
I went to put in Top shelf in this closet. Was able to do the first wall. I went to do the second wall but it won't let me drag and drop. I try to click on another product (e.g. Toe Kick) and it won't recognize I'm selecting it. I can't select anything in the Tool Bar (e.g. the tabs for projects, room builder... etc. or "File, Edit...etc.). I am not able to save is by Ctrl+S either. I am able to move around my image, however. So my whole screen isn't frozen, just the tool bar.

![image](https://user-images.githubusercontent.com/63115502/90074025-2c5e8180-dcaf-11ea-97dc-d469541d4845.png)

**Comment by kategodfrey** [comment]
I closed out of SNaP, then reopened and chose "recover Last Session," put in my top shelf for the first wall, and then it froze again like the first time.

**Comment by SeanRadvan** [comment]
If you try this in a new project does it still happen? I was able to
successfully place 4 top shelves and toe kicks in a new drawing.

**Comment by TEDSTANDAGE** [comment]
So I have found that the new top shelf is harder to place than how the old top shelf worked--it's harder to ensure you actually clicked the left partition and then the right partition--are you sure the top shelf was actually placed or is it still waiting for you to select the partitions?

**Comment by TEDSTANDAGE** [comment]
When you are in the middle of placing objects like top shelves the program acts exactly as you described which is why I am asking the above.

**Comment by kategodfrey** [comment]
@TEDSTANDAGE you are right. Thanks.

**Comment by kategodfrey** [comment]
Ok it is doing it again for me. I was able to place 2 more top shelves and then the last one froze on me again. Was able to snap it to the left side and when I went to snap it to the right it won't highlight the partition and everything freezes again.

**Comment by kategodfrey** [comment]
![image](https://user-images.githubusercontent.com/63115502/90160839-25834d80-dd47-11ea-9d4b-4a08e928f645.png)

**Comment by kategodfrey** [comment]
You can see it hanging out on the outside of the closet

**Comment by SeanRadvan** [comment]
Can you hit escape to cancel placing the object?

**Comment by TEDSTANDAGE** [comment]
Are you trying to place a topshelf that is longer than 96"?

**Comment by kategodfrey** [comment]
No I am not. I think I figured it out though, top shelf is just touchy i think. Now I was able to place the top shelf, but I can't get rid of the one hanging outside of the closet

**Comment by kategodfrey** [comment]
Ok I am good. I think I figured it all out. If it happens again I will open this issue again.
