### ISSUE TITLE
1/4" TK Skins as an option

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#14]
1/4" TK Skins as an option

**Comment by TedCC1209** [comment]
This is a high priority item now (not before the update, but this should be top of the list after) @ClassyTeddy

**Comment by ClassyTeddy** [comment]
I have a couple questions about this issue.

1. What should be added to the drawing when the option is enabled?
2. Where would you like the option? 
3. What does the XML need to include?

Any further description would be much appreciated.

**Comment by TedCC1209** [comment]
1. Add TK Skin option in TK Prompts

![TK Skin Button](https://user-images.githubusercontent.com/61025894/103653623-08336380-4f22-11eb-8ad9-246aec1ec1bd.png)

2. If the button is selected, a 1/4" piece of material (matching closet material color) should be placed across the front of the TK matching the height of the TK and the full width of the TK assembly (covering the seam made by the two TK end cap pieces that cap the TK front)
3. If the TK Skin option is selected, left and right return options should become available. If a left or right return is selected, the width of the original assembly (before the skin is added) should be inset 1/4" to account for the TK skin which should then return along the entire depth of the TK assembly for the side of the return that is selected.
4. If the TK Skin option is selected, there should also be an option that becomes available that says "TK back exposed", in which case the back side depth of the TK should be inset 1/4" to account for the TK skin which should then be placed along the back side of the TK
5. Ensure the TK skin option is available for islands
6. 1/4" TK skins should export in the XML in full 96" lengths, with the height of the TK skin being 1" taller than the height of the TK. The formula for the amount of lengths should be similar to cover cleat--add up all the widths of TK skins for that particular height and color in the room and follow a formula at least similar to the following:
  
  -If there is only one front piece of TK skin (with no returns or exposed TK back) and it is less than 93" long, export 1 length
  -Otherwise, add together all the TK Skin lengths (fronts, returns, and backs if applicable) in a room and if the total is under 80" export 1 length. If the total is over 80", divide the total by 96", then round up to the next whole number. Then, if that whole number is 1-3 lengths of TK Skin, add one extra length of TK skin. If the number is 4+ lengths, add two extra lengths of TK skin.

**Comment by TedCC1209** [comment]
When this is finished, we will also want to make sure the 2D views show the TK skin (no seams from the TK end caps capping the front/back pieces of the TK) and label that the TK is skinned.

**Comment by TedCC1209** [comment]
Sorry, and to clarify, "Toe kick" should always be spelled out when displayed in the SNaP prompts, though in 2D views labels can reference toe kicks with TK. I say TK out of habit and ease of writing here.

**Comment by TedCC1209** [comment]
If "Variable Height" is selected, the TK skin should export as the same extended height of the other exported TK pieces.

**Comment by TedCC1209** [comment]
We do not need to see the core of the 1/4" material in the scene--the installers will miter the corners together when there is a return, but because there are no "exposed ends" we don't need to see the core material in order to remind the user to select anything to cover exposed core material.

**Comment by ClassyTeddy** [comment]
This is partially ready for testing on the `Adding-TK-Skins` branch. I disabled them for island toe kicks at the moment because they were causing errors, but the option is fully available and ready for testing on the standard toe kicks.

**Comment by TedCC1209** [comment]
Awesome, thanks Teddy. The prompt option looks good and the returns work well. A couple fixes:

1. The skins are coming in only as white and the XML has "unknown" as to the color/SKU/etc. It should match the color of the closet (the corresponding 1/4" material like we do for 1/4" backs):

![White TK Skin](https://user-images.githubusercontent.com/61025894/105232827-2efab800-5b26-11eb-8d60-17fdf07d018f.png)

![White TK Skin](https://user-images.githubusercontent.com/61025894/105232887-4e91e080-5b26-11eb-9fe0-5d6b25643a17.png)

2. Then we need to be able to account for times when there are adjacent TKs of different depths--Right now the way it's set up there would be a 1/4" space between two adjacent TK assemblies of different depths unless the user manually extends the TK left or right the needed 0.25". This is because in this situation the TK skin of the deeper assembly technically only would return to the depth of the adjacent shallower TK assembly, not all the way to the back of the deeper assembly (the "skeletons" of the TK assembly behind the skins should be touching, essentially). I would love if it could automatically determine if there is an adjacent TK assembly of a different depth and it could figure these out itself, but for now I think we add a prompt asking if the following are applicable: a. Adjacent to a deeper TK assembly on left and b. Adjacent to a deeper TK assembly on right, in which case the TK assembly should be extended L/R 1/4" (towards the deeper assembly). It's okay if the left/right TK skin returns overlap the end cap of the adjacent TK assembly and it's okay if those longer lengths are included in determining how much TK skin to order.

Number 2 is a bit more complex but please let me know if you have any questions. Again, this is a great start.

Thanks, Ted

**Comment by ClassyTeddy** [comment]
> The skins are coming in only as white and the XML has "unknown" as to the color/SKU/etc. It should match the color of the closet (the corresponding 1/4" material like we do for 1/4" backs):

I am unsure as to why they are only coming in as Oxford white, but it looks like the "Unknown" sku is because there are 3 1/4"  materials that have Oxford White as the display name and 110100 as the color code:

PM-0000087 | Oxford White | Oxford White | OXFORD WHITE250 G1S 1/4
PM-0000088 | Oxford White | Oxford White | OXFORD WHITE250 G2S 1/4
PM-0000089 | Oxford White | Oxford White | OXFORD WHITE FF250 1/4

Which of those three materials should apply to 1/4" oxford white?

**Comment by TedCC1209** [comment]
Just like 1/4" backs,  for Oxford White, Cabinet Almond, Duraply White, and Duraply Almond, we should use the 1/4" material with the SKU PM-0000041 Dura White_Almond 10200 (one sided white the other side almond)

**Comment by ClassyTeddy** [comment]
> The skins are coming in only as white and the XML has "unknown" as to the color/SKU/etc. It should match the color of the closet (the corresponding 1/4" material like we do for 1/4" backs):

>Then we need to be able to account for times when there are adjacent TKs of different depths--Right now the way it's set up there would be a 1/4" space between two adjacent TK assemblies of different depths unless the user manually extends the TK left or right the needed 0.25". This is because in this situation the TK skin of the deeper assembly technically only would return to the depth of the adjacent shallower TK assembly, not all the way to the back of the deeper assembly (the "skeletons" of the TK assembly behind the skins should be touching, essentially). I would love if it could automatically determine if there is an adjacent TK assembly of a different depth and it could figure these out itself, but for now I think we add a prompt asking if the following are applicable: a. Adjacent to a deeper TK assembly on left and b. Adjacent to a deeper TK assembly on right, in which case the TK assembly should be extended L/R 1/4" (towards the deeper assembly). It's okay if the left/right TK skin returns overlap the end cap of the adjacent TK assembly and it's okay if those longer lengths are included in determining how much TK skin to order.

Both of these issues are fixed and ready for testing on the `Adding-TK-Skins` branch

**Comment by TedCC1209** [comment]
The colors look to be working correctly--showing up in the scene and exporting into the XML, thank you.

As for the issue about an adjacent deeper TK assembly--it looks to only be doing the 1/4" extension toward the deeper TK assembly if the return for that side is also selected (i.e., if I want it to extend 1/4" left for an adjacent deeper TK assembly on the left it will only extend if Left Return is selected, same for the right). Really it should work the opposite--we won't have a return on the side that we want extended toward the deeper assembly, so we certainly should not require a return on that side of the shallower TK assembly we want to extend. Let me know if that makes sense. Thanks, Ted

**Comment by ClassyTeddy** [comment]
I think that make sense. So basically, all you want me to do I remove the requirement to have a return selected?

**Comment by TedCC1209** [comment]
Yes that should fix it, I was just also explaining the real life application of why that is.

**Comment by TedCC1209** [comment]
@ClassyTeddy do you have an ETA on this? Thanks, Ted

**Comment by ClassyTeddy** [comment]
> @ClassyTeddy do you have an ETA on this? Thanks, Ted

@TedCC1209 Should have it done by tomorrow afternoon at the latest. I'm still wrapping up the functionality for the islands, and I still need to fix how the adjacent deeper TK is functioning.

**Comment by ClassyTeddy** [comment]
This is ready for testing on the `Adding-TK-Skins` branch.

**Comment by TedCC1209** [comment]
Teddy, I think the 1.2.4 update is messing with this branch. If I update then the TK prompts don't show the TK Skin option. If I don't update then the XML is exporting each piece of TK skin instead of exporting lengths like it was doing before (also it isn't doing the correct 1/4" white material, it is still Unknown). The first time I tried exporting an XML it took be to the 1.2.4 release notes too. So I think you need to get this branch up to speed. Let me know if I am missing something or doing something wrong though too. Thanks, Ted

**Comment by ClassyTeddy** [comment]
It looks like the update was overwriting the changed files with the files from the update. Pull the commit I just made and try again.

**Comment by TedCC1209** [comment]
This is looking good Teddy, thank you. The prompts are looking good, the adjacent deeper TK assembly option looks to be working correctly, it is exporting the correct white/almond 1/4" material. A few things to address as it relates to the skins on islands:

Islands--make sure to inset the 1/4" on the L/R ends when there is a 1/4" TK skin return there (I see you correctly didn't add the skin if it is up against the wall on that side, good catch). Also, the XML export for island toe kick skins is just exporting the exact sizes of the skins rather than adding an inch to the height and rather than exporting full lengths--it needs to add an inch to the height like the other TK skins and it should be incorporated in the logic to determine how many lengths are needed for the entire room and not separated out like it currently is.

**Comment by ClassyTeddy** [comment]
Both issues are done and ready for testing on the `Adding-TK-Skins` branch.

**Comment by TedCC1209** [comment]
This looks good to me. If there was a way to have it automatically detect the deeper adjacent TK assembly that would be great, but that can be an enhancement in the future. Also I think the option to skin the back side of TKs was accidentally skipped over, but that doesn't happen much so we can also have that be something to add in the future. So, unless @sarahhightower @kategodfrey or someone else sees something today that we need to address, I think this is good to merge.
