### ISSUE TITLE
Add option for shelves below hangs

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#142]
We should add the option to add shelves at the bottom of hang sections together with the options to adjust the vertical location and depth of those shelves.

**Comment by ClassyTeddy** [comment]
This is ready for testing on the `Adding-Individual-Shelf-Setbacks` branch

**Comment by SeanRadvan** [comment]
Was attempting to test this, where would i find these options?

**Comment by ClassyTeddy** [comment]
On that branch, there his a button at the bottom of the hang propmpts that says `Add Shelves Below Hang`. Check that box and it should add more prompts.

**Comment by SeanRadvan** [comment]
Looks like its working correctly to me. Off topic, while testing shelves,
it looks like when changing heights of the shelves, the top ones are being
set based on the top, while the last shelf is being set from the bottom, is
this intentional?

**Comment by SeanRadvan** [comment]
*regular shelf stacks, not for hangs, those are all looking to be based off
the bottom of the opening.

**Comment by ClassyTeddy** [comment]
So shelf stacks actually allow the user to select the Height of the Opening, not the position of the shelf itself. Shelf stacks openings start at the top and go down the partition. So Opening 1, is in between the top of the partition and the shelf, then opening 2 is in between the 1st shelf and the second shelf, and so on.

**Comment by ClassyTeddy** [comment]
Then the shelves on hangs are based on the position of the bottom rod. So they will always be below where the bottom rod would be.

**Comment by TEDSTANDAGE** [comment]
Looks good, but does not look to be adjusting size when back is present (noting for https://github.com/CCDevNelson/SNaP-Dev/issues/202)
