### ISSUE TITLE
Custom depth and location of shelves in door prompts

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#143]
We should add the options to customize the depth and vertical location of shelves added through door prompts.

**Comment by SeanRadvan** [comment]
![Shelf placement](https://user-images.githubusercontent.com/54151330/91066986-35245100-e5e7-11ea-8c3f-0656cd024df2.jpg)
option appears to be working, but placement appears to be off.

**Comment by ClassyTeddy** [comment]
What are the settings for your door?

**Comment by SeanRadvan** [comment]
Should have just been default settings, i just placed a stack and turned the option on. after looking again it looks like one of the self heights was set to 30.08, after changing it to 3.62 it fixed it. placing a second door in the other side worked correctly, however i noticed when i clicked shelf options it seemed to change the hieght of the other shelves, similar to the cleat issue we were having. Ill see if i can replicate it.

**Comment by SeanRadvan** [comment]
![shelf 6 14](https://user-images.githubusercontent.com/54151330/91069270-0c518b00-e5ea-11ea-97da-5f31cab5aed9.jpg)
![shelf option](https://user-images.githubusercontent.com/54151330/91069274-0d82b800-e5ea-11ea-8b88-c4f59fa8b5ab.jpg)
Ok am able to confirm that placing a shelf to 6.14 and then clicking shelf options does reset it down to 4.whatever. why its not happening to the 30 or what all sizes its affecting i dont know yet.

**Comment by ClassyTeddy** [comment]
Sounds like it is a rounding problem to do with the opening. Whenever it isn't exact, it will round down to the next hole number

**Comment by ClassyTeddy** [comment]
A fix for the above is on the `Adding-Individual-Shelf-Setbacks` branch and is ready for testing.

**Comment by TEDSTANDAGE** [comment]
Looks good, but does not look to be adjusting size when back is present (noting for https://github.com/CCDevNelson/SNaP-Dev/issues/202)

**Comment by kategodfrey** [comment]
Tested this branch. Works well. Would be nice to have shelves evenly spaced in the door prompt shelving options. And I am echoing @TEDSTANDAGE on the adjusting size when backing is present.

![image](https://user-images.githubusercontent.com/63115502/92517595-bd9c1780-f1cb-11ea-8bbc-3e3039abe676.png)

**Comment by TEDSTANDAGE** [comment]
@ClassyTeddy is it possible for the shelves to come in evenly spaced as the default, rather than 3H between them?

**Comment by ClassyTeddy** [comment]
It might be possible. Having shelves be evenly spaced is easier for normal shelves due to the fact that you only put in as many shelves as you want. So I would have to make the spacing of the shelves a lot more dynamic. But it would be doable.

**Comment by TEDSTANDAGE** [comment]
Maybe there would be a button that is clicked by default that says "evenly space shelves", and then the user can un-select it and do the custom heights as you currently have them if they choose to?

**Comment by ClassyTeddy** [comment]
I can do that. Do you want me to prioritize fixing this, or just continue to work on Flat Crown/Crown Molding for now and tackle this later?

**Comment by TEDSTANDAGE** [comment]
Sounds good, thank you Teddy. Go ahead and keep your train of thought and work on the crown issues, then we can get to this after.

**Comment by TEDSTANDAGE** [comment]
Before we merge this, let's have this branch evenly distribute the shelves in a stack. Essentially, take the number of holes in the partition that the shelves span, divide that by the number of spaces (number of shelves plus one extra space), and if that number isn't not a whole number then add a hole to either the space between the bottom and the lowest shelf or a space between the top and the highest shelf (or add two holes or however many is necessary to get a whole number for the rest of the spaces). You can probably figure out that math better than I can.

**Comment by TEDSTANDAGE** [comment]
> Before we merge this, let's have this branch evenly distribute the shelves in a stack. Essentially, take the number of holes in the partition that the shelves span, divide that by the number of spaces (number of shelves plus one extra space), and if that number isn't not a whole number then add a hole to either the space between the bottom and the lowest shelf or a space between the top and the highest shelf (or add two holes or however many is necessary to get a whole number for the rest of the spaces). You can probably figure out that math better than I can.

Probably easier to have the extra hole(s) be above the top shelf, that way all the prompts will show equal hole spacing since we display the number of holes a shelf is above the one below it, correct?

**Comment by ClassyTeddy** [comment]
That is correct.

**Comment by ClassyTeddy** [comment]
Doors having evenly spaced shelves is ready for testing on the `Adding-Individual-Shelves-Setback` branch. The change is only for shelves that are added in the doors prompts. Let me know your thought on it. Thanks.

**Comment by TEDSTANDAGE** [comment]
Thank you Teddy, it's a good start. Is it possible to have it be that when you move a lower shelf up/down, that all the shelves above it then adjust to evenly space between that shelf and the top of the assembly? Then, if there isn't enough space to have at least 3H between the shelves above when they are evenly spaced, that it doesn't allow the user to choose such a large space (a notification coming up and saying as such would be nice). As of now, if you adjust a shelf, all of the shelves above the adjusted shelf then move the same amount up/down with it without adjustment. A user would obviously have to start with shelf 1 then move to shelf 2, etc., otherwise it would mess up what they adjusted previously, but I think that would be better than having shelves be moved up and out of the assembly like the following:

![evenly spaced shelves](https://user-images.githubusercontent.com/61025894/94951407-1001e880-0499-11eb-885f-c9e8d19b1512.png)

Let me know if that makes sense. Feel free to give me a call. Thanks, Ted

**Comment by TEDSTANDAGE** [comment]
Also, your displayed numbers as it relates to the hole count for the amount of space are referring to door/drawer face height measurements rather than the actual space. If you want to be accurate as to the amount of space between the shelves, it would be the height a partition would be for that hole count minus 1.5" (two 0.75" thick shelves). Example: 10H space would be 13.35" (10H partition) minus 1.5" to be 11.85" actual space.

Note: Technically an additional 3/8" space would be there if the lower shelf were a KD and the shelf above it were adjustable, and there would be 3/8" less space if the shelf above was a KD and the lower shelf was adjustable, because a KD shelf sits 3/8" lower than an adjustable shelf, but I don't think we need to be this particular in this instance.

**Comment by TEDSTANDAGE** [comment]
> Also, your displayed numbers as it relates to the hole count for the amount of space are referring to door/drawer face height measurements rather than the actual space. If you want to be accurate as to the amount of space between the shelves, it would be the height a partition would be for that hole count minus 1.5" (two 0.75" thick shelves). Example: 10H space would be 13.35" (10H partition) minus 1.5" to be 11.85" actual space.
> 
> Note: Technically an additional 3/8" space would be there if the lower shelf were a KD and the shelf above it were adjustable, and there would be 3/8" less space if the shelf above was a KD and the lower shelf was adjustable, because a KD shelf sits 3/8" lower than an adjustable shelf, but I don't think we need to be this particular in this instance.

Check out the suspended drawer spacing distances:

![suspended drawer space](https://user-images.githubusercontent.com/61025894/94955785-fca64b80-049f-11eb-8f48-1f3bcfccbd22.png)

**Comment by ClassyTeddy** [comment]
Ready for testing on the Adding-Individual-Shelf-Setbacks branch.

**Comment by TEDSTANDAGE** [comment]
Teddy, as we talked about yesterday, we are going to adjust this a bit. I have confirmed the designers are on board. Here is the change we need to make:

As it stands, when it evenly spaces the shelves, it divides the total number of holes by the number of open spaces (number of adjustable shelves plus one), then rounds down to the nearest whole hole number and then puts all of the "remainder" holes into the space above the top adjustable shelf. This is how I asked you to do it. Example:

27H of space, 3 adjustable shelves, 4 spaces. 27 divided by 4 equals 6.75, so it would round down to 6H space below all the adjustable shelves and then there is a 9H space above the top adjustable shelf. This ends up looking a little goofy:

![image](https://user-images.githubusercontent.com/61025894/95617171-da707880-0a1f-11eb-9b30-792c171d1a92.png)

New change: We should put the "remainder" holes one per open space starting with the lowest opening and moving up. In the above first example there would be 7H below the adjustable shelves and 6H above the top adjustable shelf:

![image](https://user-images.githubusercontent.com/61025894/95617205-e52b0d80-0a1f-11eb-86f1-351eaf3b6bd9.png)

The issue becomes more pronounced with higher shelf counts and smaller the distances between the shelves:

![image](https://user-images.githubusercontent.com/61025894/95617229-ef4d0c00-0a1f-11eb-9511-1caf49de807c.png)

With the change it should end up looking like this:

![image](https://user-images.githubusercontent.com/61025894/95617247-f5db8380-0a1f-11eb-8a1b-d29186113b56.png)

Let me know if you have any questions.

Thanks, 

Ted

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Adding-Individual-Shelf-Setbacks` branch.

**Comment by TEDSTANDAGE** [comment]
Looks really good to me, thank you Teddy. Can we have the number of allowed shelves behind doors be increased to 15 shelves? Otherwise I think this is good to go. @sarahhightower @JBTattersall have you guys ever gone above 15 shelves behind a tall door? 14 might be the top I remember seeing, but I figure we might as well go to 15.

@kategodfrey @sarahhightower @JBTattersall please test this. Thanks, Ted

**Comment by TEDSTANDAGE** [comment]
Teddy, I am getting those little squares on these hole spacing prompts like I was seeing in https://github.com/CCDevNelson/Snap-Updates/issues/158. Not sure what those come from?

![small boxes](https://user-images.githubusercontent.com/61025894/96280787-46596080-0f8d-11eb-9e8b-2f5e0f20e6ba.png)

**Comment by ClassyTeddy** [comment]
I can up the number of shelves when I get the chance. I have no idea why those squares show up. I will look into it when I get to that issue.

**Comment by sarahhightower** [comment]
@TEDSTANDAGE I've never gone above 15 shelves  so I think maxing it out at the number works fine. 

Also, tested. Works great and I didn't see any rectangles or squares :)

![Shelf Stack Visual](https://user-images.githubusercontent.com/72047269/96285258-8d4a5480-0f93-11eb-8c62-8721f71f6c27.PNG)

**Comment by TEDSTANDAGE** [comment]
Great, thank you @sarahhightower . If you unselect "Evenly Space Shelves" do you get the rectangles?

**Comment by sarahhightower** [comment]
You're welcome @TEDSTANDAGE. Also, I still do not see rectangles when I unselect "evenly space shelves". 

![Shelf Stack Visual](https://user-images.githubusercontent.com/72047269/96287125-5164be80-0f96-11eb-9be6-531ca8226ee4.PNG)

**Comment by TEDSTANDAGE** [comment]
This looks good to go except upping the shelves to 15. Thank you Teddy

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Adding-Individual-Shelf-Setbacks` branch.

**Comment by TEDSTANDAGE** [comment]
This looks like extra holes are being placed above the top adjustable shelf again rather than being spread out one at a time in the spaces below the lower shelves?

![image](https://user-images.githubusercontent.com/61025894/96642023-6618bd80-12da-11eb-85b9-e114943894de.png)

**Comment by ClassyTeddy** [comment]
Hmmm, perhaps I forgot to make it account for all the new shelves, lemme take a look after I finish the bottom capping

**Comment by ClassyTeddy** [comment]
I hope I have the math working now. It was already accounting for the extra shelves, so I had to change the formula in place. I hope I found one that works well for all combinations of door size and shelf quantity. Should be good to go now on the `Adding-Individual-Shelf-Setbacks` branch.

**Comment by TEDSTANDAGE** [comment]
Looks pretty good to me, still a little more space at the top than at the bottom in a few situations I found but I think it's sufficient. @JBTattersall @sarahhightower @kategodfrey please let us know what you think. Thanks, Ted

**Comment by kategodfrey** [comment]
Looks good to me! I only notice more space when I add more shelves. The less shelves I have the less noticeable the "off" spacing.

**Comment by sarahhightower** [comment]
All looks good to me as well! I see the option to add up to 15 shelves, no rectangles and spacing works just fine as I adjust the number of shelves. Thank you!

**Comment by TedClassy1209** [comment]
Teddy I think we are good to go on this one. Thanks, Ted
