### ISSUE TITLE
Left and Right returns for molding

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#144]
Need to have option for left and right returns for crown molding (not flat crown, but the molding from the Closet Options tab). Made the partitions "end panels" did not make the molding return back when I tried it with Katie today, though I believe it likely should. If this is already possible, please let me know.

**Comment by meltnaz** [comment]
That should do it. If you've added the crown and then change it to end partitions, it won't return. You have to delete crown (hit the x in the closet options tab next to molding) and then add again, and it then it should return. You can also edit the piece (in edit mode) by extruding (hot key E) and to extend it that way. I'm meeting with Katie and Jim on Wednesday, I can go over it with them then.

**Comment by TEDSTANDAGE** [comment]
I thought there was a way, thanks!
