### ISSUE TITLE
Projects not displaying after update

### ISSUE THREAD

**Issue by SeanRadvan** [CCDevNelson/Snap-Updates#146]
![SeanCapture](https://user-images.githubusercontent.com/54151330/90532865-97370f00-e12c-11ea-8699-a0d613a63337.PNG)
Ive seen on two computers now that old projects are not properly being displayed in ver 1.2, and new project wont display after snap is reloaded. The jobs are still able to be opened and saved from the documents folder, but without it displaying as a project certain functions such as adding rooms to a job are lost.

**Comment by TEDSTANDAGE** [comment]
If you are counting Lori's, her issues were happening before the update. Wasn't Kimberli having this issue prior to the update as well?

**Comment by SeanRadvan** [comment]
I dont recall if it was Kimberli but ive seen issues with projects being replicated in the past. I dont think it has anything to do with 1.2 in particular, but if we have an auto update to 1.2 roll out, i expect to get a lot of calls for it in the coming days.

**Comment by TEDSTANDAGE** [comment]
The auto update is rolled out--I confirmed it worked on Lori's laptop yesterday.

**Comment by TEDSTANDAGE** [comment]
Sorry if I misread your last comment, you meant people are going to want a 1.2.1 quickly if this has to do with 1.2.0 and is a widespread issue.

**Comment by RyanMDev** [comment]
What does the project folder look like?

Also, what is the name of the .ccp file?

**Comment by SeanRadvan** [comment]
I can get a screenshot of her project folder. Which .ccp file would you be looking for? Just a random project that isnt loading?

**Comment by RyanMDev** [comment]
It looks like the parser is complaining about something in the name of one of the project .ccp files.

I am wondering what the name of each .ccp is, one of them appears to be causing a problem.

**Comment by RyanMDev** [comment]
Can you have her put each project .ccp file in a folder, zip and send it over?

**Comment by SeanRadvan** [comment]
Shes not very tech savy, so ill have to teamviewer in and do it, ill try to get that done by end of day.

**Comment by SeanRadvan** [comment]
This is 1 / 2 computers having this issues, she has dozens of projects, here are the first ones and the ones the first one that doesnt display after. Let me know if you need something else.[https://drive.google.com/file/d/1XLBZGmLzqPGVf09WJo8QPvY0KWe6KSGG/view?usp=sharing](url)

**Comment by RyanMDev** [comment]
I have requested access to your shared file.

**Comment by RyanMDev** [comment]
Got it thanks.

This is interesting. It looks like the 'Judkins.ccp' is actually a .pdf file that was some how renamed to from 'Judkins.pdf' to 'Judkins.ccp'.

Viewing the source of this file, I see this is stated at the top:

![judkins_pdf](https://user-images.githubusercontent.com/6529544/90569447-c2d4ec00-e162-11ea-98e4-f61f32a595ef.png)

Whereas a normal .ccp file will look more like this:
![judkins_ccp](https://user-images.githubusercontent.com/6529544/90569917-95d50900-e163-11ea-92f6-4e5bd79077e2.png)



Changing the 'Judkins.ccp' file extension to .pdf then allows me to open and view the 2D plans for the Judkins project:

![judkins_2d_view](https://user-images.githubusercontent.com/6529544/90569681-2a8b3700-e163-11ea-8745-eb076bf9cde8.png)

**Comment by RyanMDev** [comment]
On startup, SNaP is attempting to load each project's .ccp file. When it gets to the Judkins project, it reads 'Judkins.ccp' and tries to find the `Root` element but it does not exist because this is actually a pdf file.

Renaming 'Judkins.ccp' with it's correct file extension: 'Judkins.pdf', should allow all other projects to then properly load, except of course the Judkins project which would now have a missing .ccp file.

If we know the names of the rooms in this project and the project info, we can restore her 'Judkins.ccp' file.

**Comment by RyanMDev** [comment]
However, when an error like this happens and a .ccp file cannot be read, this error should be caught and SNaP should skip over the corrupted project file and continue loading other projects instead of stopping execution.

An error message should also be shown informing the user which project(s) had an issue loading.

Using issue CCDevNelson/SNaP-Dev#235 for this.

**Comment by SeanRadvan** [comment]
So as long as the offending file is removed / changed to .pdf it should
load correctly? Is there an easier way to figure out which ones are
affected rather then removing all files and readding them to the folder 1
at a time and checking?

**Comment by RyanMDev** [comment]
> So as long as the offending file is removed / changed to .pdf it should load correctly?

Yes.

> Is there an easier way to figure out which ones are affected rather then removing all files and readding them to the folder 1 at a time and checking?

The offending file will be the next project in the list that is not being loaded in the UI.

So in the case above, Judkins.ccp was the offending file:
![judkins](https://user-images.githubusercontent.com/6529544/90664367-ae92fc80-e1ff-11ea-9f8b-14ea5452cb7b.png)
