### ISSUE TITLE
Default TK height in opening construction options

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#149]
I thought that the default TK height had been changed to 4.39" in the opening construction options but now I am noticing that it is not, the 4.39" default TK height is only being reflected in the Closet Options and not in the opening construction options prompts (where it is still 2.5"). This should be updated.

**Comment by TEDSTANDAGE** [comment]
Also the default height for openings is 83.90 when I thought we changed it to 83.25 previously. This needs to be fixed again.

Also, how can a user change those defaults themselves? The Closet Options defaults don't change the defaults of what the openings are put in by default. Thanks

**Comment by kategodfrey** [comment]
A user can change their defaults to whatever they want/ use most and then they just go to file→ save startup file.
It will open a prompt window asking you if you really want to save the defaults as they are, just click OK.
Then close out of SNaP and open it back up again.

**Comment by TEDSTANDAGE** [comment]
That's not working though, or at least it isn't affecting the defaults of when an opening is placed--they/I can change the Closet Options defaults, save the startup file, etc., but when I go to put in partitions they still come in as 47.37's and at an 83.90" hang height (even after closing SNaP and reopening, etc.).

**Comment by kategodfrey** [comment]
Yeah, you are right. I am having that problem as well.

**Comment by TEDSTANDAGE** [comment]
Teddy, if you can't figure this out quickly can you push it to Ryan with high priority? We already have one user who isn't happy about this and is asking to go back to an old version...

**Comment by ClassyTeddy** [comment]
So it looks like the `Default Hang Height`, the `Default Panel Height`, the `Default Upper Panel Height`, and the `Toe Kick Setback` options all function differently than they may appear. Hitting the small double arrows changes all of partitions/toe kicks in the scene to change to that amount. Partitions will always come in as 47.37's, and the user will have to click the double arrows to change them all at once. It used to function where you could set the default and then all placed partitions would go in at the right height. but now it doesn't, and I don't know why it was changed. Also, it looks like the toe kick default heights were not changed to be 4.39".

**Comment by TEDSTANDAGE** [comment]
Did that change? Because it sounds like (and I'm pretty sure I remember it as well) users previously were able to change the default partitions/hang height/etc. which would be effective when they placed an opening in a scene rather than having to hit the refresh buttons in Closet Options (which changes all partitions in the scene) after the fact.

**Comment by ClassyTeddy** [comment]
It looks like it was changed yes. I believe it was changed when Ryan added the oversized partitions, perhaps unintentionally.

**Comment by RyanMDev** [comment]
Let me take a look at this...

**Comment by ClassyTeddy** [comment]
I don't know if you already know this @RyanMDev, but it looks like the change that actually affected this was the lag fix. The three commits you made July 31st where you removed the fd_library, added the library manager, and added all the blend files seem to be what caused the problem. I reverted those three changes on a branch and got the defaults to work again.

**Comment by RyanMDev** [comment]
Alright, looks like this has to do with the pre-built product and insert files.

Specifically the following:
All hanging opening blend files
Toe Kick.blend

Removing these will restore functionality of the closet defaults.

**Comment by RyanMDev** [comment]
@ClassyTeddy you are correct, however we only need to remove a few blend files.

**Comment by ClassyTeddy** [comment]
Right. I was just testing to make sure that was the problem.

**Comment by ClassyTeddy** [comment]
Do you want me to make a branch with those changes for you to merge? Or are you already in the process of doing so?

**Comment by RyanMDev** [comment]
I got it.

**Comment by RyanMDev** [comment]
Additionally, users can fix this (or be helped) on their own installation with the 'Open Location in Browser' command in the library browser which will bring them to the location of the files needed to be removed:

![loc_in_browser](https://user-images.githubusercontent.com/6529544/90674318-d1c4a880-e20d-11ea-9407-d7614e9b9d62.png)

![del_prebuilts](https://user-images.githubusercontent.com/6529544/90674501-12242680-e20e-11ea-9e17-55526c3a0dc9.png)

**Comment by TEDSTANDAGE** [comment]
Can we make this a 1.2.1 update to push asap instead of having to walk every user through this? It affects everyone.

**Comment by RyanMDev** [comment]
Certainly.

**Comment by RyanMDev** [comment]
While double checking and testing everything works as expected, I found that all defaults are working with the exception of the 'Toe Kick Setback'.

Looks to be a separate issue, should I resolve this as well before committing to 1.2.1?

**Comment by RyanMDev** [comment]
Actually it looks like the 'Toe Kick Setback' issue is part of CCDevNelson/SNaP-Dev#158 which I still have in progress.

So this was not working in previous versions either.

**Comment by TEDSTANDAGE** [comment]
Toe kicks are coming in at 1.5" setback from the shallowest selected partition correct? I think it's fine if that's the case even if they can't change the default.

**Comment by SeanRadvan** [comment]
I have reciecved a complaint about toekick height default not able to be
changed.

**Comment by RyanMDev** [comment]
> Toe kicks are coming in at 1.5" setback from the shallowest selected partition correct?

Correct.

**Comment by RyanMDev** [comment]
> I have reciecved a complaint about toekick height default not able to be changed.

This is 'Toe Kick Setback' not height unless that was a typo.

**Comment by RyanMDev** [comment]
'Toe Kick Height' is fixed along with the other defaults with: CCDevNelson/SNaP-Dev@326055f8cff0f02dc00d93cc35290346da2440a1

**Comment by TEDSTANDAGE** [comment]
Looks like it is working for me. If we push this as an update and a user hasn't upgraded to 1.2.0 yet, will it cause an issue to go directly from 1.1.0 to 1.2.1? We are running into some issues going from 1.0.0 to 1.2.0 so I thought I'd ask if something similar might happen here if they have multiple updates at once.

**Comment by TEDSTANDAGE** [comment]
Also, not sure it is related, but it is taking a while for SNaP to load up when I try and open it now after this. Is anyone else having the same thing happen? It sits with this window for 10-15ish seconds before the program loads:

![image](https://user-images.githubusercontent.com/61025894/90686025-903cf900-e21f-11ea-8009-09d47d8c685d.png)

**Comment by RyanMDev** [comment]
> will it cause an issue to go directly from 1.1.0 to 1.2.1?

No, it should not.

**Comment by RyanMDev** [comment]
The users attempting to update from 1.0.0, are they applying the updater patch first?

**Comment by SeanRadvan** [comment]
One of them attempted too, but i dont know how tech savvy she is and if she
did it right. I ended up just hosting the 1.2 build on a google drive and
doing a fresh install from there. Coincidentally its the same person who
had the issues with the default hang and toe kick heights.

**Comment by TEDSTANDAGE** [comment]
@kategodfrey @ClassyTeddy @SeanRadvan @JBTattersall Have you all tested this?

**Comment by RyanMDev** [comment]
In my testing I found the 'Default Upper Panel Height' was still being affected.

So I had to fix with this with commit: CCDevNelson/SNaP-Dev@b08e0c852ef462fd2c141c25d5e3c8e8c7490675

Then retested updating from both 1.1.0 (with updater patch) and 1.2.0, both worked fine on my end.

Live update should be ready to go unless anyone else found anything?

**Comment by ClassyTeddy** [comment]
I tested the fix and it worked for me.

**Comment by kategodfrey** [comment]
It worked for me as well.

**Comment by TEDSTANDAGE** [comment]
Great, it is also working for me. The delay issue I had before also no longer is an issue so we can disregard that as well. 

Teddy I say we go live with the 1.2.1 update unless you disagree, I'll let you give the go ahead. Thanks for getting on this so fast @RyanMDev .

**Comment by ClassyTeddy** [comment]
Yeah, I think that we are all good for the update as well.

**Comment by RyanMDev** [comment]
@TEDSTANDAGE No problem.

@ClassyTeddy Sounds good.

Update v1.2.1 is now live!

**Comment by TEDSTANDAGE** [comment]
It sounds like Melissa's update didn't go well--she got an error code, something about being unauthorized and then to click for a a manual download. She is taking screenshots for us which we will post once available.

**Comment by TEDSTANDAGE** [comment]
Nevermind--she got it to work now, not sure what was going on. Haven't heard anything from normal users yet.

**Comment by RyanMDev** [comment]
Is she on an installation or testing from SNaP-Dev branch Version-1.1.0/Version-1.2.0?

What is the current verison she is attempting to update from?

It sounds like what would happen if the updater patch was not applied to version 1.1.0 or previous when attempting to update.

**Comment by TEDSTANDAGE** [comment]
She was on a SNaP-Dev branch, not an installation, and I'm not sure exactly what version she was on when it tried to update for her. I had her go through GitHub to fetch the latest Master version and after a couple openings and closings of SNaP it finally worked and she is up to date now.

**Comment by TEDSTANDAGE** [comment]
Want to report on some positive news—Heard about a super easy and smooth v1.2.1 update from one of our designers here and there is excitement about all the enhancements we are making. Thank you everyone

**Comment by TEDSTANDAGE** [comment]
Not sure if we were doing one (I sent an email to all users about the 1.2.1 update anyway) but I don't see a release log for 1.2.1 at the following link where the other release logs are located (not sure if users are being taken to the log upon completion of the update):

https://ccdevnelson.github.io/SNaP-Dev/

**Comment by RyanMDev** [comment]
Here it is: [https://ccdevnelson.github.io/SNaP-Dev/v121](https://ccdevnelson.github.io/SNaP-Dev/v121)

Forgot to add a link to it from the index page, but the link above will be opened automatically after a successful update to v1.2.1.

**Comment by RyanMDev** [comment]
Alright you should now see v1.2.1 release notes linked on [https://ccdevnelson.github.io/SNaP-Dev/](https://ccdevnelson.github.io/SNaP-Dev/)
