### ISSUE TITLE
Crown molding to the ceiling needs inverted base

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#154]
If crown molding goes to the ceiling then along with the crown molding lengths exported, it also needs to export the same number of lengths of the following that will be used as inverted base:

MD-0000025 | BASE ALDER 3 1/4X1/2 WM633 | BASE ALDER 3 1/4X1/2 WM633 | BASE ALDER 3 1/4X1/2 WM633 | 1 | 1 | 1.586667 | LF | MD | 60100 | 809160 | 0 | SPELLMAN | CC05A
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

In the closet options for the molding, before a user can insert crown molding, they need to be required to select whether or not any portion of the crown molding goes to the ceiling (or soffit). If yes, then the inverted base needs to be exported along with the crown. If not, then just the crown molding needs to be exported. The inverted base does not necessarily need to be visually in the scene in SNaP, just in the XML export.

**Comment by ClassyTeddy** [comment]
This is ready for testing on the `Flat-Crown-and-Crown-Molding-Improvements` branch.

**Comment by TEDSTANDAGE** [comment]
The correct base molding is being exported with crown now it looks like. We have some issues with the crown molding itself, but as far as this issue is concerned it looks good. Thanks, Ted
