### ISSUE TITLE
Top Shelf is breaking XML export

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#157]
We have been trying to test Mark's pricing software. Katie kept drawing the test closet and no XML could be exported from it. I did the same thing, trying to export the XML at the end after drawing the entire closet and kept getting the same results (no XML exported). So, I started from the beginning of the closet, saving and exporting an XML after each opening and assembly added. After putting in topshelf over a 56.25" two-opening section and extending it to the right 12" to go over the wrap around area, that is when no XML was able to be exported. My assumption from that is that it is the top shelf breaking the XML export.

![image](https://user-images.githubusercontent.com/61025894/91179555-82fa9100-e69b-11ea-9e1b-3bef8f98fca9.png)

Blend file:
https://drive.google.com/file/d/1OTblnelEtcMKk9ZgAtjcXcN-xj635i2F/view?usp=sharing

ccp file:
https://drive.google.com/file/d/1icyoRu0Gt_HY8gZDahc9plejJJCKJhxn/view?usp=sharing

**Comment by TEDSTANDAGE** [comment]
Not sure if we can have an error message pop up when XNaP fails to export an XML.

**Comment by ClassyTeddy** [comment]
There should be an error message in the terminal. Can you open it and try to export again?

**Comment by TEDSTANDAGE** [comment]
Ah yes you're right:

![XML export error](https://user-images.githubusercontent.com/61025894/91183034-d2db5700-e69f-11ea-9917-77a8980c7315.png)

**Comment by TEDSTANDAGE** [comment]
Here is the whole thing, sorry:

![image](https://user-images.githubusercontent.com/61025894/91183128-f0102580-e69f-11ea-8c7f-86afd1a5f8a1.png)
![image](https://user-images.githubusercontent.com/61025894/91183153-f900f700-e69f-11ea-9d9f-cf92e2134b6d.png)

**Comment by TEDSTANDAGE** [comment]
Here is the toggle system console when trying to export from the entirety of Katie's project, not just the test that I was doing (not sure if it will be anything different):

![image](https://user-images.githubusercontent.com/61025894/91183643-92300d80-e6a0-11ea-9c72-6a9315ba1822.png)

![image](https://user-images.githubusercontent.com/61025894/91183664-98be8500-e6a0-11ea-8e71-30a31db8bbeb.png)

**Comment by ClassyTeddy** [comment]
Looks like top shelf is the problem. I'll take a look at it.

**Comment by ClassyTeddy** [comment]
This is ready for testing on the `Fixing-Top-Shelf-XML-Error` branch.

**Comment by SeanRadvan** [comment]
I was able to build a room with a top shelf and it managed to create an
XML, but didnt confirm what its contents are.

**Comment by TEDSTANDAGE** [comment]
I was able to export an XML from her project now and it included top shelf too, thank you
