### ISSUE TITLE
Handle placement for second handle in "Use Double Pulls"

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#159]
Need to fix the vertical location of the second handle when the user selects "Use Double Pulls"

![image](https://user-images.githubusercontent.com/61025894/91208877-be0ebb80-e6bf-11ea-947d-7122989df552.png)

Might wait until we merge the separate drawer stack library to do this fix if that will make you have to double up the effort.

**Comment by ClassyTeddy** [comment]
Ready for testing on the branch `Separating-Drawer-Boxes`

**Comment by SeanRadvan** [comment]
Looks to be working correctly, also drawers appear to be loading MUCH
faster on that branch.

**Comment by TEDSTANDAGE** [comment]
Looks good, thank you
