### ISSUE TITLE
Material for file rails

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#160]
I'm not sure if this is just for the separate drawer stack library branch I am testing, but the file rails aren't being exported with the correct material (no SKU number is being exported for file rails):

![image](https://user-images.githubusercontent.com/61025894/91209535-c0254a00-e6c0-11ea-8f99-2d4d5886530b.png)

![image](https://user-images.githubusercontent.com/61025894/91209554-c61b2b00-e6c0-11ea-90e4-da9af6e17405.png)

It should be the following with the top edge having edgebanding:

PM-0000004 | White Paper 12310 | WHITE  PAPER 1/2 G2 | WHITE  PAPER 1/2 G2
-- | -- | -- | --

**Comment by ClassyTeddy** [comment]
This is currently for all drawer stacks. I will take a look at this as well as issue #159 and I will put them both on the branch `Separating-Drawer-Boxes`

**Comment by ClassyTeddy** [comment]
Ready for testing on the branch `Separating-Drawer-Boxes`

**Comment by TEDSTANDAGE** [comment]
Looks good, thank you
