### ISSUE TITLE
Hardware export in XML

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#161]
Even if you change the handle/pull hardware and "replace all" in a room, the XML exported from the room still just has the default 121.90.302 handle info. I have not tested this with any other hardware yet, just noticed the pulls.

**Comment by ClassyTeddy** [comment]
Ready for testing on the branch `Separating-Drawer-Boxes`

**Comment by TEDSTANDAGE** [comment]
Looks good, thank you
