### ISSUE TITLE
2D View Enhancements / Sections

### ISSUE THREAD

**Issue by nailsonlandim** [CCDevNelson/Snap-Updates#163]
TODO

- [x] Add section depth dimension label on elevations (see examples)

- [x] Get rid of label "Section Number" option in the main labels

- [x] Add sections widths to plan view

**Comment by nailsonlandim** [comment]
Got rid of Section Number label. It's branch is issue_#163-sections

**Comment by TEDSTANDAGE** [comment]
> Got rid of Section Number label. It's branch is issue_#163-sections

I see that the option is gone, thank you

![No Section Number option](https://user-images.githubusercontent.com/61025894/92310240-482d0e80-ef61-11ea-87ec-3fb28debe63b.png)

**Comment by nailsonlandim** [comment]
I think i got the way to add measures on plan view after analyzing the elevations code.

![image](https://user-images.githubusercontent.com/70038700/92533354-a9c2d680-f208-11ea-9bb2-7b3601071dfa.png)

Tell me @TEDSTANDAGE how do I displace them on the view? how can it meets the requirements?

**Comment by TEDSTANDAGE** [comment]
Copying my Skype message here:

"Nice! Great start. We don't need the partitions heights on the plan views (the 47.37s, 78.86s, etc.), or the KD notations. Match the examples I gave you if possible"

I noticed that the example plan views I gave you don't have the individual section/opening widths on them, my bad. Preferably they would have them. Can I see the above plan view with the partitions heights and KD notations removed, leaving the partitions depths, sections widths, and wall widths? Trying to decide whether it would look better with the dimension number turned to be oriented with the wall (Like the Wall names are currently), or if just having them all the same orientation like they are now would be better. My initial thought is that having them turned to be oriented like the Wall names are would be better but would like to see how it looks currently.

**Comment by nailsonlandim** [comment]
I am looking for a filter, So it won`t affect elevations. 

If I label just the sections widths it looks like this:

![image](https://user-images.githubusercontent.com/70038700/92623897-433bc800-f29d-11ea-9991-66b9e4f43bf8.png)

I guess having them on the same orientation that Walls have is fine.

**Comment by nailsonlandim** [comment]
I've found a possible solution. I would like to have a confirmation from @RyanMDev if it seems good accordingly code quality/standards 

```python
        restricted_assemblies = ['partition', 'door', 'drawer', 'shelf']
            if obj.mv.type == 'VISDIM_A':
                father = obj.parent.name
                count = 0
                for restricted in restricted_assemblies:
                    if restricted in father.lower():
                        count += 1
                if count == 0:
                    pv_scene.objects.link(obj)
```

![image](https://user-images.githubusercontent.com/70038700/92670300-1feb3a00-f2ea-11ea-8248-729426d513d8.png)

Now I can filter unwanted dimensions on plan view. 

It is available at the same branch ( issue_#163-sections )

**Comment by RyanMDev** [comment]
> ```python
>         restricted_assemblies = ['partition', 'door', 'drawer', 'shelf']
>             if obj.mv.type == 'VISDIM_A':
>                 father = obj.parent.name
>                 count = 0
>                 for restricted in restricted_assemblies:
>                     if restricted in father.lower():
>                         count += 1
>                 if count == 0:
>                     pv_scene.objects.link(obj)
> ```

You are adding this in the `create_plan_view_scene` function in the 2d views `__init__.py` module correct?

**Comment by RyanMDev** [comment]
Actually I found it, you had two similarly named branches `issue_#163-sections` and `issue#163-sections`

**Comment by nailsonlandim** [comment]
> Actually I found it, you had two similarly named branches `issue_#163-sections` and `issue#163-sections`

Is that OK, what do you think?

**Comment by nailsonlandim** [comment]
@TEDSTANDAGE I am confirming it with Ryan, but it seems that Dimensions aren't meant to be rotated. 

I could realize that every dimension on 2D view is upwards, always. and if you rotate a 2D view the text keeps upward.

![image](https://user-images.githubusercontent.com/70038700/92811869-3ac6b880-f395-11ea-959c-d2de802511b3.png)

![image](https://user-images.githubusercontent.com/70038700/92811915-44e8b700-f395-11ea-984e-ac2a6502cef6.png)

rotated:

![image](https://user-images.githubusercontent.com/70038700/92812187-80838100-f395-11ea-81e1-5f12cb2a8d72.png)

The wall text is a Text object, so it stays where SNaP says to. 

So I am thinking on moving on and work with Section depth. What do you think?

**Comment by RyanMDev** [comment]
> ```python
>         restricted_assemblies = ['partition', 'door', 'drawer', 'shelf']
>             if obj.mv.type == 'VISDIM_A':
>                 father = obj.parent.name
>                 count = 0
>                 for restricted in restricted_assemblies:
>                     if restricted in father.lower():
>                         count += 1
>                 if count == 0:
>                     pv_scene.objects.link(obj)
> ```

Looks like this is a good solution to what you are trying to accomplish.

I would just change the way you are identifying restricted parts and not use the string names.

It is possible for a user to change the name of a part/assembly through the UI, in which case it would fail to be caught by your filter:
![rename_assembly](https://user-images.githubusercontent.com/6529544/92825648-a5232d00-f384-11ea-9f71-d0cd6f99088c.png)

There are bool properties that the parent object (the base point of the assembly: '`obj_bp`') has to identify the part type. These are available in the `lm_closets` namespace (`obj.parent.lm_closets`). It will be more reliable to use these to identify restricted parts than to use the string name.

Here are the matching props you will need:
'partition' > `is_panel_bp`
'door' > `is_door_bp`
'drawer' > `is_drawer_front_bp`
'shelf' > `is_shelf_bp`

So maybe something like this:

```
            if obj.mv.type == 'VISDIM_A':
                father = obj.parent
                father_props = father.lm_closets

                restricted_assemblies = [
                    father_props.is_panel_bp,
                    father_props.is_door_bp,
                    father_props.is_drawer_front_bp,
                    father_props.is_shelf_bp
                    ]

                if any(restricted_assemblies):
                    #Skip this object and continue loop
                    continue
                else:
                    #If not a restricted object then link to plan view scene
                    pv_scene.objects.link(obj)
```

**Comment by RyanMDev** [comment]
> @TEDSTANDAGE I am confirming it with Ryan, but it seems that Dimensions aren't meant to be rotated.
> 
> I could realize that every dimension on 2D view is upwards, always. and if you rotate a 2D view the text keeps upward.

Although it is possible to rotate the dimension text with Blender's blf module, this functionality was not originally built into the 2D views and could become a bit complicated and involved to add.

If you think it is worth it, I can point you in the right direction.

> The wall text is a Text object, so it stays where SNaP says to.

This is true, the wall text is an actual Blender text object, so those can be manipulated in the same was as any other Blender  object.

Dimensions and dimension text is drawn 'on top of' (not selectable in the 3D viewport) the 3D viewport in openGL in the same way that Blender draws it's own interface text.

**Comment by nailsonlandim** [comment]
Thanks for the information @RyanMDev 

I am looking at the depth and add them to elevations too.

![Anotação 2020-09-10 213717](https://user-images.githubusercontent.com/70038700/92832297-d5cb8c80-f3ad-11ea-8adc-406c0ea0d063.png)

I can see that obj_bp has lots of children 

![Anotação 2020-09-10 214156](https://user-images.githubusercontent.com/70038700/92832823-8174dc80-f3ae-11ea-93c8-b869ecaf41ad.png)

Can you give me a direction on that too? Thanks in advance!

**Comment by nailsonlandim** [comment]
Hi, @TEDSTANDAGE I've updated the code to follow SNaP conventions as Ryan recommended. 

My question is: will we pursue the dimensions rotation?

**Comment by TEDSTANDAGE** [comment]
Thanks Nailson. Let’s wait on the rotation, we can work on that later.

**Comment by RyanMDev** [comment]
> I am looking at the depth and add them to elevations too.

Actually, it looks like the panel depth dimensions are being added to the elevation views already. They are just moved out of the camera view on the in elevations so that they only are seen from the top on plan views.

If you zoom out a bit in elevation views you can see this:

![panel_depth_dims](https://user-images.githubusercontent.com/6529544/92950140-0ee91880-f411-11ea-9fdb-d96244b94d3a.png)

The Z location of this dimension object is being set here to be -100 inches just to keep it out of view from an elevation view:
https://github.com/CCDevNelson/SNaP-Dev/blob/3c24a8be3d179aa5ccd5e661bf14c05d970b44a3/SNaP/2.78/scripts/addons/snap_db/library_scripts/Library-Classy_Closets/data_closet_carcass.py#L2707

**Comment by nailsonlandim** [comment]
Thanks Ryan!

**Comment by nailsonlandim** [comment]
Working on sections depth I got stuck trying to traverse children/parents.

I can set better positions for section depths because I get this information from the shelf (for instance).
 
![Sections Depths Issue 1](https://user-images.githubusercontent.com/70038700/93245515-d3788200-f761-11ea-804e-034fba261183.png)

But actually I am overlaying dimension texts because I can't retrieve the correct Z coordinate from it.

![Sections Depths Issue 2](https://user-images.githubusercontent.com/70038700/93245811-3f5aea80-f762-11ea-9b76-478655e361d9.png)

If I search for a shelf location on SNaP I can do it, but when I try to iterate it I cant retrieve its value 

![Sections Depths Issue 4](https://user-images.githubusercontent.com/70038700/93244950-e048a600-f760-11ea-8f28-c4be02634c78.png)

On SNaP I can see that an INSERT is 2 levels above the Shelf Cutpart. and it's parent has the correct location.

But on my code I can't fetch it correctly? any clue @RyanMDev ? 

![Captura de tela 2020-09-15 145438](https://user-images.githubusercontent.com/70038700/93246737-9614f400-f763-11ea-9f62-57e3b41c6ff2.png)

Here is my code. 

```python
    def add_panel(self,size,x_location,text):
        panel_mesh = utils.create_cube_mesh(self.product.obj_bp.mv.name_object,(size[0],size[1],size[2]))
        panel_mesh.parent = self.product.obj_bp.parent
        panel_mesh.location = self.product.obj_bp.location
        panel_mesh.location.x = x_location
        panel_mesh.rotation_euler = self.product.obj_bp.rotation_euler
        panel_mesh.mv.type = 'CAGE'
        
        # Previous Dimension
        # dim = fd_types.Dimension()
        # dim.parent(panel_mesh)
        # dim.start_x(value = 0+unit.inch(2))
        # dim.start_y(value = size[1]-unit.inch(3))
        # dim.start_z(value = unit.inch(0))
        # dim.set_label(text)

        # Actual Proposal
        for child in self.product.obj_bp.children:
            desired_assemblies = [
                child.lm_closets.is_shelf_bp
            ]
            
            if any(desired_assemblies):
                ch_dim = fd_types.Dimension()
                ch_dim.parent(child.parent)   
                ch_dim.start_x(value = child.location[0] + unit.inch(2))
                ch_dim.start_y(value = size[1]-unit.inch(3))
                ch_dim.start_z(value = child.location[2] + unit.inch(2))
                ch_dim.set_label(text)
```

Even with this problem solved, I've another one. It is an overlay on the plan view, actually, all visible objects on scene are selected for render. any tip on its selection?


```python
        camera = self.create_camera(pv_scene)
        bpy.ops.object.select_all(action="SELECT")
        bpy.ops.view3d.camera_to_view_selected()
        camera.data.ortho_scale += self.pv_pad
```

**Comment by ClassyTeddy** [comment]
I might be able to help a little bit here for the retrieval of individual shelf depths. I think that the problem that you might be getting here is the child in this instance is the entire shelf stack, not the individual shelves. So, when you retrieve `child.location[2]`, you are actually getting the Z Location of the shelf stack. I would recommend that you add a second for loop that loops through the children of child, which will find the individual shelves of the shelf stack. Something like this:
``` 
for child in self.product.obj_bp.children:
     for nchild in child.children:
                desired_assemblies = [
                    nchild.lm_closets.is_shelf_bp
                 ]
                if any(desired_assemblies):
                      ch_dim = fd_types.Dimension()
                      ch_dim.parent(nchild.parent)   
                      ch_dim.start_x(value = child.location[0] + unit.inch(2))
                      ch_dim.start_y(value = size[1]-unit.inch(3))
                      ch_dim.start_z(value = nchild.location[2] + unit.inch(2))
                      ch_dim.set_label(text)
```

I am not positive that this is the issue, but it let me know if it helps.

**Comment by nailsonlandim** [comment]
Thanks Teddy!

**Comment by RyanMDev** [comment]
@nailsonlandim are you trying to display the depth of each individual shelf or just the depth of the opening/section?

**Comment by nailsonlandim** [comment]
> @nailsonlandim are you trying to display the depth of each individual shelf or just the depth of the opening/section?

Ted asked me to show on elevations the shelves with a setback on prompt, so AFAIK I think I need to be able to add a dimension at any shelf.

**Comment by TEDSTANDAGE** [comment]
We need it to be able to show when the depth of a shelf is setback from the standard depth of the section, but perhaps that is just something the user needs to do themselves rather than it being an automatic thing? We certainly don't want each shelf in every shelf stack or set of shelves labeled with its depth, but we should notate when something is out-of-standard.

**Comment by RyanMDev** [comment]
Alright, that makes sense.

A couple things that might help:

**1) Don't forget to check if a shelf is hidden or not. This can be done with:**

```
for child in shelf_bp.children:
    if child.mv.type == 'CUTPART':
        shelf_is_hidden = child.hide
```
![nailson_help_shelves](https://user-images.githubusercontent.com/6529544/93403587-d09e8f80-f83c-11ea-9490-c0431008f452.png)

**2) Shelves use an Array Modifier to adjust shelf quantities of shelves that are identical sizes.**

Every shelf assembly has a 'Z Quantity' prompt that uses an Array Modifier named 'ZQuantity' on the shelf object. This creates copies of the original shelf object so we can adjust shelf amount quickly and efficiently.

It is still just one object so you will only be able to retrieve the Z location of the original shelf and not the arrayed copies. You can calculate the location of the arrayed shelves by using the data in the array modifier. From the 'ZQuantity' modifier you will be able to retrieve the number of shelves that are arrayed and the distance between each shelf.

```
num_shelves_in_array = cutpart_obj.modifiers["ZQuantity"].count
distance_between_shelves = cutpart_obj.modifiers["ZQuantity"].constant_offset_displace
```

Let's use this 'Hang Short' as an example here, there are actually only two un-hidden shelf objects that we see here:

![nailson_help_shleves_2](https://user-images.githubusercontent.com/6529544/93404740-d8abfe80-f83f-11ea-95a5-7036f9fe5609.png)

![nailson_help_shleves_3](https://user-images.githubusercontent.com/6529544/93404745-dd70b280-f83f-11ea-8b48-5734bed29f09.png)

To check if an array is being used on a shelf:
`is_arrayed = cutpart_obj.modifiers["ZQuantity"].count > 1
`

**Comment by TEDSTANDAGE** [comment]
Nailson, when you are adding the section depths to the elevations, please also add the top shelf depth to the elevations as well. Thanks, Ted

**Comment by nailsonlandim** [comment]
Hi @TEDSTANDAGE 

I've added the section depths. Tell me where you want it to stay or remove it. I've added the top shelf depth too, tell me where you want it placed.

![image](https://user-images.githubusercontent.com/70038700/97023002-43c9ae80-152b-11eb-901e-b11fb1ddf244.png)

I know that I've placed too many dimensions, but IMHO it's easier to remove one existing dimension you don't want than add a not existing one.

![image](https://user-images.githubusercontent.com/70038700/97023267-a02cce00-152b-11eb-9e82-463a43c2bc18.png)

I've placed the dimensions at 3/4 of the opening to match vertically the H numbers.

Available at: https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23163-sections-depth

**Comment by TEDSTANDAGE** [comment]
Thank you Nailson, please change it to only have one section depth per opening unless there is a non-standard shelf setback somewhere (see the examples in https://github.com/CCDevNelson/Snap-Updates/issues/164)

Adjustable shelves are "setback" 0.25" by default--they should still say the depth of the section though and not the actual depth of the adjustable shelf. So, where you have 15.75" it should say 16" and where you have 11.75" it should say 12". It's really about the depth of the partition and not the shelf (again, unless the shelves are setback different than the default standard 0.25").

The topshelf depth looks great, thank you. If you can add a hash mark pointing from the dimension to the TS that would be good.

**Comment by nailsonlandim** [comment]
Hi @TEDSTANDAGE 

I've applied the changes you've asked.

![image](https://user-images.githubusercontent.com/70038700/97063201-ad21df80-1574-11eb-969e-876b022c22ca.png)

There is a 7" shelf, IDK if makes sense while designing a closet.

Thanks,
Nailson

**Comment by TEDSTANDAGE** [comment]
Hi Nailson, can you move the topshelf (TS) depth to be centered on the TS rather than being on on the left side of the TS? Thanks, Ted

**Comment by nailsonlandim** [comment]
> Hi Nailson, can you move the topshelf (TS) depth to be centered on the TS rather than being on on the left side of the TS? Thanks, Ted

Sure!
