### ISSUE TITLE
Deleting projects error

### ISSUE THREAD

**Issue by SeanRadvan** [CCDevNelson/Snap-Updates#165]

**Comment by SeanRadvan** [comment]
Was testing the newest merges this morning and noticed that clicking X to remove project, raises a "are you sure prompt" then errors out when confirmed.[](url)
![room x](https://user-images.githubusercontent.com/54151330/91734584-f4d14f80-eb5f-11ea-9207-355b7a9f2606.jpg)

**Comment by RyanMDev** [comment]
Fixed with commit: CCDevNelson/SNaP-Dev@da19577069e0859a3213a8b972b91d90fb1afe14

**Comment by TEDSTANDAGE** [comment]
Thank you Ryan
