### ISSUE TITLE
Hanger colors changed when snap was updated

### ISSUE THREAD

**Issue by kategodfrey** [CCDevNelson/Snap-Updates#166]
I received this message from a user:

Katie, a relatively small thing, but did you notice the hangars from any of the hangs don't have a color any more? They come out in a gray color in the renderings, I can't see why this would be intentional so I guess it is an error, any way they do not look as realistic. Just my two cents, I just upgraded so I just noticed this. Thanks.

**Comment by TEDSTANDAGE** [comment]
Teddy can you look into this and see what may have happened?

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Fixing-Hanger-Colors` branch.

**Comment by TEDSTANDAGE** [comment]
I see color now, thank you Teddy:

![image](https://user-images.githubusercontent.com/61025894/92277210-53236880-eea7-11ea-9ac9-4b8a67e33b0d.png)

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Double-Jewelry-Drawer-Box` branch.
