### ISSUE TITLE
Toe kick placement and sizes

### ISSUE THREAD

**Issue by SeanRadvan** [CCDevNelson/Snap-Updates#167]
![toekick](https://user-images.githubusercontent.com/54151330/91868257-66c19b80-ec29-11ea-8273-5a48f04a0e4e.jpg)
When placing a toekick from right to left, it overhangs on the pard. Aslo, when checking the sizes, a "normal" toekick being placed on a pard and correctly being inset, shows its width as the same as the pard size, which might be correct depending on how we cut them. For some reason the oversized one is showing as smaller then the pard.

**Comment by TEDSTANDAGE** [comment]
We always place toekicks left to right--same with top shelf, etc. We train everyone to do that as well.

The "size" on the TK prompt is not accurate as to the actual width of the TK, but it is accurate as to the width of the sections it is under with the partitions, so we have just kept it. 

Can you explain what you mean by an "oversized one"?

**Comment by SeanRadvan** [comment]
The on to the right, which was placed left to right. its showing as smaller
then the pard, but if we aren't addressing placement order, its a non issue.
