### ISSUE TITLE
Create "Select All" button for 2D view renderings

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#173]
We should have a "Select All" button for selecting which views to render on 2D views. Also, the default of that window should be bigger to allow for up to 8 walls to see at the same time (currently default is so you can only see 5 rows):

![Select All Button](https://user-images.githubusercontent.com/61025894/92129542-83d8a480-edb8-11ea-9863-0066c7251617.png)

**Comment by RyanMDev** [comment]
Select all is actually available in the drop down menu to the right of the 'Render Selected Scenes' button, similar to rooms.

![sel_all_2d_views](https://user-images.githubusercontent.com/6529544/92783751-e6064c00-f35a-11ea-80a5-8f3150cac0d1.png)

![sel_all_rooms](https://user-images.githubusercontent.com/6529544/92784252-5b721c80-f35b-11ea-9683-d79774a3d5a3.png)

**Comment by TEDSTANDAGE** [comment]
Ah good to know, thanks Ryan. Now that I am learning the other options in that drop down it doesn't seem as hidden to me either. I do think having the select all button directly above the individual room buttons would be more intuitive rather than in the drop down, but I think I will close this issue as it is not critical and there are other options in that drop down I think it is good for users to see/learn if they don't already know amount them (like me).

**Comment by RyanMDev** [comment]
There are also global dimension options and commands available in the 3D view header in the 'Tools' menu.

![dim_tools](https://user-images.githubusercontent.com/6529544/92839753-2be00600-f395-11ea-9e2c-caf295c2ebe4.png)
