### ISSUE TITLE
"Open Drawers" for Double Jewelry drawers

### ISSUE THREAD

**Issue by TedClassy1209** [CCDevNelson/Snap-Updates#175]
When we show the drawers open on assemblies that have double jewelry, if possible, let's show the top drawer of the double jewelry option only coming out half as far as the rest of the drawers in the assembly:

![image](https://user-images.githubusercontent.com/61025894/92142315-7c20fc00-edc8-11ea-8cee-35eff1d2665f.png)

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Double-Jewelry-Drawer-Box` branch.

**Comment by TEDSTANDAGE** [comment]
Looks good, thank you Teddy

![image](https://user-images.githubusercontent.com/61025894/92309171-12375c80-ef58-11ea-8a2d-a74e6518aa54.png)
