### ISSUE TITLE
Outlet and light switches do not show up on wall

### ISSUE THREAD

**Issue by kategodfrey** [CCDevNelson/Snap-Updates#178]
Light switches and outlets act like other accessories/options like windows and doors in that, I can drag and drop them on a wall, then I right click to enter in it's dimensions and location, but when I click out of the prompt the outlet and/or switch does not appear on the wall.

![image](https://user-images.githubusercontent.com/63115502/92271878-6a5d5880-ee9d-11ea-8384-dae03d71d685.png)

**Comment by TEDSTANDAGE** [comment]
I am unable to replicate this. I think your screenshot was taken of the wrong view as well. I can go into an outlet prompt, change all sorts of locations, and click out of it and the outlet is still there.

My initial guess is you are changing the location of the wrong axis which is moving it away from the wall or to a location you didn't intend? Outlets don't seem to be coming in snapped to a particular wall in the correct orientation, etc. (except when placed on a single wall room or Wall B of a square room), so there is a lot of manipulation that needs to occur after an outlet is inserted. I would just make sure you know which axis you are changing the location/rotation for. I could be wrong with this guess though, so let me know. We can go through this together next week as well.
