### ISSUE TITLE
Wood stains not displaying in the drawings

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#18]

**Comment by TEDSTANDAGE** [comment]
Only Trytoo Savatre not working--the only one with the display name showing ST at the end, perhaps that's the issue?

**Comment by TEDSTANDAGE** [comment]
Two stains not working/being reflected in the drawings--Arbor Myrtle and Trytoo Savatre (both still display ST at the end in the drop down menu...).

![image](https://user-images.githubusercontent.com/61025894/77687393-8e665680-6f5b-11ea-8bc2-aee3a20fa60a.png)

**Comment by ClassyTeddy** [comment]
I just want to add for now that it appears that Fog Grey also is not working.

**Comment by TEDSTANDAGE** [comment]
This issue appears to be fixed with the exception of Fog Gray which I created a new Issue #33 for.
