### ISSUE TITLE
Decrease the amount of white space on the 2D views

### ISSUE THREAD

**Issue by TedClassy1209** [CCDevNelson/Snap-Updates#182]
Now that we have multiple elevations/views exporting onto one page, we need to maximize the space. Right now there is a lot of white space, meaning the drawings aren't quite as big as they could be and we aren't efficiently using the space on the paper. There needs to be some "buffer" to allow for dimensions, notes, etc., but right now there is an excess amount of it:

![image](https://user-images.githubusercontent.com/61025894/92309845-c8ea0b80-ef5d-11ea-94c3-cfa110a2fb27.png)

The ideal way to address this would be to have the walls "connected"--essentially lay out the walls together like they were an accordion you are flattening out, but this may be a tall task (I am unsure). Here is how that looks with all three walls of a closet (A-C) connected with the corners of the room being a shared line in the drawing:

![image](https://user-images.githubusercontent.com/61025894/92309955-7c530000-ef5e-11ea-8c52-ebb72d3a0222.png)

Alternatively, we could (1) decrease the buffer on the rendered views generated when rendering the views from each wall's "scene" or perhaps we could (2) overlap the rendered images on the exported .pdf so that the buffers of each view overlap each other.

**Comment by TEDSTANDAGE** [comment]
After some manipulation with Paint, here is an example of better utilizing the space using the SNaP export example above:

![Less white space](https://user-images.githubusercontent.com/61025894/92310101-d99b8100-ef5f-11ea-9a00-5836c7fcfa35.png)

**Comment by nailsonlandim** [comment]
After analysis, I think the best approach is: generate the elevations images with a better resolution (using camera zoom adjustments) and use a library to handle these images, generating what you need.

In the actual state, the resolution of the elevation is poor (in my humble opinion) and I am working to address that.

I found that Pillow is a library that can fit our current environment (Python 3.5.1 on Windows)

**Comment by RyanMDev** [comment]
You can adjust the resolution of the render in the 'Render Settings'. By default the resolution is set to 50% of 1920x1080 (960x540). These are Blender's default render settings.

To set these properties in Python, use:
```
bpy.context.scene.render.resolution_x
bpy.context.scene.render.resolution_y
bpy.context.scene.render.resolution_percentage
```

![render_settings](https://user-images.githubusercontent.com/6529544/93809675-6bfb8000-fc02-11ea-94d0-8f8929fa7f99.png)

**Comment by RyanMDev** [comment]
> I found that Pillow is a library that can fit our current environment (Python 3.5.1 on Windows)

This could also be a valid solution.

Although I do remember trying to install Pillow previously.

IIRC, I could not get it installed on Python 3.5.1 because of a problem with a dependency that the compatible version of Pillow relied on and in the end I was only able to install PIL (the old version of Pillow) for Python 3.5.1.

It has been quite a while since I tried this though so you might see different results. I also removed PIL after it did not do what I needed it to, so you will not see it currently installed.

**Comment by RyanMDev** [comment]
If you need more control over render settings, you can find all render settings in Blender's 'Properties' area (This is hidden from users in SNaP).

![properties_panel](https://user-images.githubusercontent.com/6529544/93812531-9f400e00-fc06-11ea-949f-212aa55c8bdd.png)

The tab with the camera icon has the render settings:
![props_panel_2](https://user-images.githubusercontent.com/6529544/93812813-fd6cf100-fc06-11ea-8634-fd0d267ea688.png)

**Comment by nailsonlandim** [comment]
> > I found that Pillow is a library that can fit our current environment (Python 3.5.1 on Windows)
> 
> This could also be a valid solution.
> 
> Although I do remember trying to install Pillow previously.

Sure!

> 
> IIRC, I could not get it installed on Python 3.5.1 because of a problem with a dependency that the compatible version of Pillow relied on and in the end I was only able to install PIL (the old version of Pillow) for Python 3.5.1.

I installed Pillow, the latest one without major issues 

![image](https://user-images.githubusercontent.com/70038700/93832918-89097080-fc4d-11ea-9fa8-b9dcf93b4c0f.png)

The only issue we face on blender is that we can only work with PNG files. JPEG crashes silently.

**Comment by RyanMDev** [comment]
I am fine with including Pillow if it helps you achieve what you are trying to accomplish.

**Comment by nailsonlandim** [comment]
I found out a way to remove the whitespace without touching the padding or any render setting by now. It is included at the Plans and Elevations option on 2D views -> Elevations Layout. (I will apply it on other options once it pass all tests, after any refinement)

Here is a preview.

![image](https://user-images.githubusercontent.com/70038700/94067322-140c7700-fdc4-11ea-987d-ff3a5a720942.png)

![image](https://user-images.githubusercontent.com/70038700/94067366-25558380-fdc4-11ea-9f2c-44cbbefe188e.png)

It is available at: https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23182-reduce-whitespace-2dviews

I appreciate any comment to refine it and make it better.

**Comment by TEDSTANDAGE** [comment]
Good start, thank you Nailson. It is definitely a better use of the space on the paper. We might add a little more buffer on the outside border of the paper itself so there is a little more room on the edges (the vertical wall line on the right side of the far right elevation looks to be right on/sharing the line of the border of the page and the word Wall on the far left elevation on the page also seems to be touching the border line). Even like 1/4" space would be good I think).

I am also running into a little issue:

![image](https://user-images.githubusercontent.com/61025894/94187732-3e5e4300-fe5d-11ea-9d5f-e171f1115c1f.png)

![image](https://user-images.githubusercontent.com/61025894/94187693-31415400-fe5d-11ea-987a-23e1474b0113.png)

![image](https://user-images.githubusercontent.com/61025894/94187712-369e9e80-fe5d-11ea-8f87-a0d09ee7c0c1.png)

The 3rd elevation (that would have the drawers and doors on the niche wall) isn't showing up and the plan view isn't centered on the first page. This happened with all paper sizes.

**Comment by nailsonlandim** [comment]
Thanks, @TEDSTANDAGE for the feedback and I´ll address it immediately. 

I will add spaces at the left and right edges and fix the Plan View. I will also check why it is not rendering the elevation.

Can you share the project file? BTW if you have any interesting project file send me, please.

**Comment by TEDSTANDAGE** [comment]
> Can you share the project file? BTW if you have any interesting project file send me, please.

The project is the "Example large custom room" I sent to you previously. Let me know if you are not running into the same issue I am with it and I can try other projects/rooms.

The render of that wall shows up in the list of walls rendered and I can preview it, it just isn't transferring over when I export to a pdf:

![image](https://user-images.githubusercontent.com/61025894/94192602-07d7f680-fe64-11ea-8290-8e5420e238fb.png)

**Comment by nailsonlandim** [comment]
> > Can you share the project file? BTW if you have any interesting project file send me, please.
> 
> The project is the "Example large custom room" I sent to you previously. Let me know if you are not running into the same issue I am with it and I can try other projects/rooms.

Found it, sorry.

> 
> The render of that wall shows up in the list of walls rendered and I can preview it, it just isn't transferring over when I export to a pdf:
> 
> ![image](https://user-images.githubusercontent.com/61025894/94192602-07d7f680-fe64-11ea-8290-8e5420e238fb.png)

Understood.

**Comment by nailsonlandim** [comment]
I committed a fix for the mentioned issues. 

**Plan View on top (Large custom room)**

![image](https://user-images.githubusercontent.com/70038700/94212880-c1a68580-feab-11ea-98e4-ee88142b48cb.png)

**Remaining elevations (Large custom room)**

![image](https://user-images.githubusercontent.com/70038700/94212917-df73ea80-feab-11ea-9f0b-1d5bc7fbb557.png)

**Plan View + 1st Elevation (Example simple walk-in)**

![image](https://user-images.githubusercontent.com/70038700/94212894-d125ce80-feab-11ea-9c12-68f3b707ba9a.png)

I think I can connect the walls if I displace the wall a bit to right.

**Comment by TEDSTANDAGE** [comment]
This is great Nailson, thank you.  Have you guys tested this @kategodfrey @JBTattersall ?

If we are going to connect walls, we will need to get rid of the second vertical line that show the thickness of the wall:

![second vertical line](https://user-images.githubusercontent.com/61025894/94469337-ca80ab00-017a-11eb-8b0d-a462f990db4d.png)

Let's have that be a separate issue though--I think the spacing you have going on here is a good enough start. We will probably need to play around with some other things too (like the following example--we might want the option to have even more elevations there if we could fit them all onto one page, I think Jim would like that).

![image](https://user-images.githubusercontent.com/61025894/94469495-10d60a00-017b-11eb-9592-4dc19bda76dd.png)

As far as I am concerned I think this is good for now. Jim/Katie what do you think?

Thanks, 

Ted

**Comment by nailsonlandim** [comment]
> Let's have that be a separate issue though--I think the spacing you have going on here is a good enough start. We will probably need to play around with some other things too (like the following example--we might want the option to have even more elevations there if we could fit them all onto one page, I think Jim would like that).
> 
That's good, I appreciate It being pushed to the limits.

I can add more elevations with ease, just tell me the arrangement you need.

**Comment by TEDSTANDAGE** [comment]
@JBTattersall @kategodfrey please test this today as well, I think we should be merging the fixes Nailson has made Re: the multiple elevation arrangement options to the master version but want your guys' input before we do that.

**Comment by kategodfrey** [comment]
The spacing looks great! 

Now just figuring out the placement dimensions so they aren't stacked on top of each other. When I tested this branch I had my dimensions labeled and some questions/concerns came to mind, (island 2D image, partition depths...) but I can put those in a new issue thread.

**Comment by TEDSTANDAGE** [comment]
> The spacing looks great!
> 
> Now just figuring out the placement dimensions so they aren't stacked on top of each other. When I tested this branch I had my dimensions labeled and some questions/concerns came to mind, (island 2D image, partition depths...) but I can put those in a new issue thread.

Check out some of the other things Nailson is working on regarding the dimensioning, he’s right in the middle of a bunch right now.

**Comment by nailsonlandim** [comment]
Thanks, @kategodfrey for the feedback, and I appreciate anything you can share to make it better.

**Comment by TEDSTANDAGE** [comment]
> > The spacing looks great!
> > Now just figuring out the placement dimensions so they aren't stacked on top of each other. When I tested this branch I had my dimensions labeled and some questions/concerns came to mind, (island 2D image, partition depths...) but I can put those in a new issue thread.
> 
> Check out some of the other things Nailson is working on regarding the dimensioning, he’s right in the middle of a bunch right now.

And please feel free to add more to what he’s already working on — did you test with Jim today and does he agree about the spacing?
