### ISSUE TITLE
2D Views - Allow for 11x17 ledger size paper

### ISSUE THREAD

**Issue by TedClassy1209** [CCDevNelson/Snap-Updates#183]
Right now we are tied to 8.5x14 legal size paper. To more efficiently use the space of the paper, we should allow for using 11x17 paper (which the user can scale down to 8.5x11 letter size paper for physical printing).

**Comment by nailsonlandim** [comment]
@TEDSTANDAGE I've added an option for that, you can check it at https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23183-allow-ledger-size.

I changed the logo to a higher resolution one, from the media kit and made adjustments on labels to reduce labels whitespace on _11x17_. If you want to I can change the font size.

**Comment by TEDSTANDAGE** [comment]
This looks great to me, thank you Nailson

**Comment by nailsonlandim** [comment]
![1](https://user-images.githubusercontent.com/70038700/95466743-0d006f80-0953-11eb-811a-8ab4137fb56b.png)

![2](https://user-images.githubusercontent.com/70038700/95466872-328d7900-0953-11eb-9550-32ad256a70b2.png)

![3](https://user-images.githubusercontent.com/70038700/95466879-34573c80-0953-11eb-9dd5-ff7163ea1e21.png)

![4](https://user-images.githubusercontent.com/70038700/95466885-36b99680-0953-11eb-8d26-d7ed8945b28e.png)

![5](https://user-images.githubusercontent.com/70038700/95466895-39b48700-0953-11eb-9b36-0506a0297aab.png)

![6](https://user-images.githubusercontent.com/70038700/95466899-3ae5b400-0953-11eb-9561-d41ef2111b70.png)

![7](https://user-images.githubusercontent.com/70038700/95466908-3caf7780-0953-11eb-958a-2881dee5249b.png)

![8](https://user-images.githubusercontent.com/70038700/95466919-4042fe80-0953-11eb-8754-7f757ca4cf6b.png)

![9](https://user-images.githubusercontent.com/70038700/95466926-42a55880-0953-11eb-86b6-f7eea4f6130f.png)

![10](https://user-images.githubusercontent.com/70038700/95466929-43d68580-0953-11eb-8240-cd8f44d54329.png)

![11](https://user-images.githubusercontent.com/70038700/95466933-45a04900-0953-11eb-94b7-3348768b8a47.png)

![12](https://user-images.githubusercontent.com/70038700/95466945-489b3980-0953-11eb-93c1-294a4d555362.png)

![13](https://user-images.githubusercontent.com/70038700/95466952-4a64fd00-0953-11eb-9051-6b17b0cdbbe5.png)

![14](https://user-images.githubusercontent.com/70038700/95466960-4b962a00-0953-11eb-9955-fd09b10320fb.png)

![15](https://user-images.githubusercontent.com/70038700/95466968-4df88400-0953-11eb-8c43-3e9606b86188.png)
