### ISSUE TITLE
Error adjusting pards after 1.2 update

### ISSUE THREAD

**Issue by SeanRadvan** [CCDevNelson/Snap-Updates#185]
![Screenshot 2020-09-10 142604](https://user-images.githubusercontent.com/54151330/92804577-469e8480-f36d-11ea-92f7-d18351bb46cb.png)
Had an issue where when a user tried to open drawings from, according to them, the 1.1 build, trying to change the widths of an opening would cause this issue to pop up.
Other things of note that might be relevant. The user was not creating projects before drawing rooms, so none of the folders had associated CCP files as far as i could tell. The user was also drawing rooms using the "custom" setting in room builder, which is lacking a "build room" button that adds it to current projects.

**Comment by TEDSTANDAGE** [comment]
Teddy/Ryan can correct me, but I believe the partitions/carcass in 1.2 work differently than they did in 1.1, so they will have to delete the old partitions and put new ones in if they are trying to make changes to old drawings.

**Comment by TEDSTANDAGE** [comment]
Also, it sounds like they are not following the protocols and procedures they would have been taught in their SNaP training, so if they aren't setting up their projects and rooms correctly I'm not sure why they expect everything else to be working. If they want to set up some SNaP training, Katie can they contact you?

**Comment by SeanRadvan** [comment]
I did notice that constructions options wasn't opening correctly as well.
Is there an easy way to redraw all the rooms or is it easier to make
new ones?

**Comment by RyanMDev** [comment]
> I believe the partitions/carcass in 1.2 work differently than they did in 1.1, so they will have to delete the old partitions and put new ones in if they are trying to make changes to old drawings.

This is correct, the new partitions include blind corner panels and additional options. The 1.2 prompts/options page is looking for the blind corner panel inside the carcass in order to retrieve and display the options. However the blind corner panels and options do not exist in carcasses created with 1.1.

**Comment by RyanMDev** [comment]
@ClassyTeddy we can prevent this from happening by checking if the prompt exists before attempting to retrieve the value.

This way if a user is attempting to use old library data/drawings, the prompts page will just skip drawing prompts that do not actually exist on the old version of a product or insert. Instead of throwing an error.

I added this check that prevents the error that Sean posted above on line 1802 in `data_closet_carcass.py` with commit: CCDevNelson/SNaP-Dev@1b10417e110246bbfeb7507dd7154a5fd5096046

**Comment by RyanMDev** [comment]
> I did notice that constructions options wasn't opening correctly as well. Is there an easy way to redraw all the rooms or is it easier to make new ones?

There is not currently a way to redraw an entire room with the newer products. Although it could be done, I think the above solution should be okay.

**Comment by ClassyTeddy** [comment]
> @ClassyTeddy we can prevent this from happening by checking if the prompt exists before attempting to retrieve the value

I am aware of this and I will try to be sure to check to see if a prompt exist before the value is retrieved to avoid errors like these in the future.

**Comment by SeanRadvan** [comment]
Is there a way / reason to push the commit to live? Would i be able to
replace a file on their pc to test if fix works or will any changes be
undone by the updates when they open blender?

**Comment by RyanMDev** [comment]
> Is there a way / reason to push the commit to live? Would i be able to replace a file on their pc to test if fix works or will any changes be undone by the updates when they open blender?

The fix is very simple and only contains one line of code in the file: `data_closet_carcass.py`.

As long as they are up to date on version 1.2.1 you can replace this file on the PC in question with the new one that was updated in this commit to test the fix:

> commit: [CCDevNelson/SNaP-Dev@3c24a8b](https://github.com/CCDevNelson/SNaP-Dev/commit/3c24a8be3d179aa5ccd5e661bf14c05d970b44a3)

**Comment by SeanRadvan** [comment]
Good news, it fixed the bug. bad new, it made another one.
![Screenshot 2020-09-11 113401](https://user-images.githubusercontent.com/54151330/92955795-ac951580-f41a-11ea-8b36-6af097d33d6f.png)

**Comment by RyanMDev** [comment]
Fixed with commit: CCDevNelson/SNaP-Dev@ec8ead215961f69f876f01145c45e07b603f5f8a

**Comment by SeanRadvan** [comment]
![Error](https://user-images.githubusercontent.com/54151330/93096909-ccfee300-f659-11ea-861d-81c44d9ddfef.PNG)
The first two fixes seem to work well, not sure if this error is related.

**Comment by RyanMDev** [comment]
Fix for the doors interface not showing with older library data: CCDevNelson/SNaP-Dev@8fd66abf06bffc82aa3b282713e03961fcdbe266

**Comment by TEDSTANDAGE** [comment]
@SeanRadvan Any update on how this worked? Thanks, Ted

**Comment by SeanRadvan** [comment]
If i remember correctly, changing the files ryan mentioned did indeed fix
the issue. If we could roll them into the next live build (if they
aren't already) that should fix it.
