### ISSUE TITLE
Unique 1/4" backing material not exporting correctly

### ISSUE THREAD

**Issue by TedClassy1209** [CCDevNelson/Snap-Updates#187]
1. I did an oxford white closet and as tests I did unique 1/4" mahogany backs and cedar backs. The XML has a dura wht_alm back exported in both instances, I think perhaps because of the rule we created to make sure we had the correct one side white one side almond 1/4" back material for dura white, oxford white, dura almond, and cabinet almond closets?

2. Then I did a test with an arbor myrtle closet with the 1/4" mahogany back and cedar back. The 1/4" mahogany was exported correctly but got an "unknown" back for the cedar veneer. Something might be up with the cedar backs now?

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Unique-Backing-Not-Exporting` branch.

**Comment by TEDSTANDAGE** [comment]
Teddy, it is still not exporting correctly. I did an Oxford white job with three different 1/4" backs--one was a default back to match the closet (white), another was a unique cedar back, and another was a unique mahogany back. All three exported as wht_alm when only the one should have:

![image](https://user-images.githubusercontent.com/61025894/94585986-8ef6e700-0235-11eb-93a0-f0d5a406af8f.png)

![image](https://user-images.githubusercontent.com/61025894/94586005-93230480-0235-11eb-8b4b-bcf3fba582e3.png)

![image](https://user-images.githubusercontent.com/61025894/94586014-974f2200-0235-11eb-80d5-1943d9cc9c7e.png)

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Unique-Backing-Not-Exporting` branch.

**Comment by TEDSTANDAGE** [comment]
Great, it's working well for me. Thank you Teddy.
