### ISSUE TITLE
Get rid of middle KD in drawer stacks for certain situations

### ISSUE THREAD

**Issue by TedClassy1209** [CCDevNelson/Snap-Updates#188]
Let's get rid of the middle 6" deep KD when a drawer stack of 3 or less drawers is sitting above a hamper or base doors (unless of course there is a top lock on a drawer then it still needs a full KD above it). Drawer stacks 4 or more drawers can still use the middle 6" deep KD even when above a hamper or base doors.

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Removing-Middle-KD-Shelves-In-Small-Drawer-Stacks` branch.

**Comment by TEDSTANDAGE** [comment]
Looks good in my testing.
