### ISSUE TITLE
Discontinued colors

### ISSUE THREAD

**Issue by kategodfrey** [CCDevNelson/Snap-Updates#189]
Hi all. We have 4 colors that are being discontinued so we can remove them from our list of materials:

INTRIGUE
LUXE
MEMENTO
ZAHARA

I will continually update you all whenever our list of materials or our "Top 40" list change.

**Comment by ClassyTeddy** [comment]
This is ready for testing on the `Removing-Some-Colors` branch.

**Comment by TEDSTANDAGE** [comment]
This looks good, these options do not appear available anymore. Thank you
