### ISSUE TITLE
Simplify Dog Ear Prompts

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#191]
Dog ear prompts should be simplified--the height of the dog ear is always 8" and it is always from the front, not the rear. The only option should just be what we want the depth of the top of the dog ear to be, and it would probably be easier to do it by section rather than by partition. Currently there are just too many options available:

![Dog Ear Options](https://user-images.githubusercontent.com/61025894/93933696-dd0c6780-fcd6-11ea-99be-0623f49682df.png)

We can get rid of the items I have crossed out in red. Preferably it would be by opening/section and not by partition (like the way we do our opening/section depths) and it should be reworded to say "Dog Ear To Depth:  _______". 

I looked at the conversation in the following issue:  https://github.com/CCDevNelson/SNaP-Dev/issues/48 and I wish they would have talked to engineering because we don't do this (if we do something like it, it's once a year or two and not for angled ceiling, but rather to account for piping or conduit, and that would be manually cut).

Side note: I will create a separate issue, but we need to add the option to "dog ear" the bottom of the partitions to create corbel partitions that will perhaps go right under this section (or in the "extend left/right side" area) so I thought I'd throw this out just to keep it in mind as we fix the regular dog ear option.

**Comment by RyanMDev** [comment]
Fixed in SNaP 2.0. commit: Classy-Closets/snap-2.0@5fa085f438750e537dfbdea67a6b848e6fdd4cbc

This issue has been moved to the SNaP 2.0 project board (Ready for testing).
