### ISSUE TITLE
Need option for middle KD for shelves behind doors

### ISSUE THREAD

**Issue by TedClassy1209** [CCDevNelson/Snap-Updates#192]
@JBTattersall pointed out this issue. If a tall door unit is on an exposed end of a run of cabinets there is no way to create a middle KD because when you select the shelves it selects all of them, not individual shelves. So, if you use the Closet Properties to try and make one a KD, it makes them all KD shelves if you select it. The door and partition prompts also only have top and bottom KD options. Preferably the shelves behind doors would work like shelf stack shelves (or like shelves in hangs) where you can select an individual shelf within the stack to adjust its properties in the Closet Properties options to make it a "Locked Shelf":

![image](https://user-images.githubusercontent.com/61025894/94184659-18cf3a80-fe59-11ea-9c95-e61e4d6b2262.png)

This is also the same with adding shelves in hangs--the dust cover shelves are separate and individual so that you can select them separately and adjust its properties, but when you add a number of shelves through the prompts you cannot select an individual shelf within them to adjust its properties like making it a locked/KD shelf.

**Comment by ClassyTeddy** [comment]
This is actually possible and ready for testing on the `Adding-Individual-Shelf-Setbacks` branch.

**Comment by TEDSTANDAGE** [comment]
That made this easy, so when we are ready to merge that branch this issue should be fixed. Thanks Teddy
