### ISSUE TITLE
Force single door

### ISSUE THREAD

**Issue by kategodfrey** [CCDevNelson/Snap-Updates#193]
I know we can force double doors, but is there a way to force a single door? It looks like anything over 24" wide doesn't allow single doors and automatically creates double doors. Would love to be able to have the option of just one door and which way I want it to swing.

![image](https://user-images.githubusercontent.com/63115502/94203813-f77c4780-fe74-11ea-92b8-04c566da11e1.png)

**Comment by TEDSTANDAGE** [comment]
We don’t do single doors over 24”, too much weight for the hinges. 

We also already have the option for single doors of which way it swings.
