### ISSUE TITLE
Blind Corner Door and Handle locations

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#194]
When a door is placed into a section with a blind corner panel on the left  it is placed in the correct place with the correct gap between the BCP and the door, and the handle appears to be in the correct place:

![image](https://user-images.githubusercontent.com/61025894/94286605-124ccb80-ff0a-11ea-88d5-1ca34f12dd1f.png)

However, when you change the swing to a left swing, the door moves to exactly on the BCP:

![image](https://user-images.githubusercontent.com/61025894/94286656-25f83200-ff0a-11ea-956a-b96cade389e5.png)

Then when you Open Door, the handle is in an incorrect position:

![image](https://user-images.githubusercontent.com/61025894/94286766-4aeca500-ff0a-11ea-98b2-a89a85ed3bf3.png)

When you place a door in a section with a BCP on the right, the door and handle are both in incorrect positions:

![image](https://user-images.githubusercontent.com/61025894/94286940-85564200-ff0a-11ea-8300-18e802c29d32.png)

Opening the door looks like this:

![image](https://user-images.githubusercontent.com/61025894/94287162-d0705500-ff0a-11ea-90aa-180dcc328a56.png)

If you switch it to a left swing in this situation, the door and handle appear to be in the correct position:

![image](https://user-images.githubusercontent.com/61025894/94287382-11686980-ff0b-11ea-816a-cc1a457c580c.png)

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Blind-Corner-Door-Location-Fixes`

**Comment by TEDSTANDAGE** [comment]
Looks good in my initial testing. @JBTattersall please test this one and let us know if it fixes what you were seeing.

Teddy, another thing I have noticed when trying to "open" doors here is that I get an error the first 1 or 2 times I enter an amount to open, but then it works when I keep trying. Here is the error:

![weird error](https://user-images.githubusercontent.com/61025894/94586780-8226c300-0236-11eb-9287-253cf2ed0334.png)

**Comment by ClassyTeddy** [comment]
I can't seem to replicate the error. Does it happen when you place a door and do anything? Or just when you open the door. Is there anything else in the closet? Are there any specific setting you have for the door or the partition?

**Comment by TEDSTANDAGE** [comment]
Usually I try typing in 0.5 as the amount to open, it has only happened on doors in BCP sections that I have noticed. Not sure if swing directions matters. Can you try that and see if it happens to you?

**Comment by ClassyTeddy** [comment]
Just can't recreate it. I know what the error is, but I don't know where or why it is happening when you open the door.

**Comment by TEDSTANDAGE** [comment]
I figured it out--it sometimes automatically adds a period for some reason after I type in 0.5 really quick, leaving it with "0.5." which obviously would create an error because that isn't a real number. Perhaps when we fix https://github.com/CCDevNelson/Snap-Updates/issues/190 and have "open doors" or "open hamper" say 100% rather than 1.00000% it won't happen anymore.

**Comment by JBTattersall** [comment]
The blind corner right swing handle placement worked fine on a couple of different tests
