### ISSUE TITLE
Error while rendering

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#200]
So I'm 99% sure this is just because my laptop shouldn't be trying to render, but I got the following error when trying to render:

![image](https://user-images.githubusercontent.com/61025894/95271167-11f9dd80-07f2-11eb-896e-541dce331895.png)

It then gave me the following link:  https://nvidia.custhelp.com/app/answers/detail/a_id/3633 which says as follows:

<<start quote>>

OpenGL “TDR detected” Meaning
Updated 10/06/2016 05:51 PM
WHAT DOES THE OPENGL "TDR DETECTED" MESSAGE MEAN?
I have seen this Event Log Message:

A TDR has been detected.
The Application must close.

What does it mean?

If you received this message from an application (in the Event Log or on a pop up message), the application was unable to continue rendering because the Microsoft Windows imposed time limit (TDR) was exceeded. This is normally the case when the workload sent to the graphics card is greater than what the graphics card can process in the normal alloted time of two seconds.

You can find more information on this page:

Timeout Detection and Recovery (TDR)

How can this be fixed?

Two possible solutions to try would be:

Reduce the graphics workload if possible, such as by rendering to a lower resolution or by reducing the detail.
Increase the timeout value to allow more time to complete more intensive rendering. Microsoft provides information on how to modify the Windows Registry to achieve this.

<<end quote>>

Are there any settings I can change in Blender or on my computer to avoid this error? 

Thanks, 

Ted

**Comment by RyanMDev** [comment]
Go to render>render settings. There you will find 'Render Quality', the
default is 128. Lower this for PCs and laptops with older/under-powered
hardware.

[image: render_quality.png]

**Comment by TEDSTANDAGE** [comment]
Great, thank you Ryan

**Comment by SeanRadvan** [comment]
Quick follow up on this, can we lower the render quality by default?
Rendering issues is probably the number one complaint I take calls
about.

**Comment by TEDSTANDAGE** [comment]
> Quick follow up on this, can we lower the render quality by default? Rendering issues is probably the number one complaint I take calls about.
>

Sean, for those making those complaints, do they have the recommended better graphics card or are they using an underpowered machine (like me)?
