### ISSUE TITLE
Raised Panel / Wood door XML export

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#202]
Right now when doors / drawer faces are replaced by wood in the Closet Options, they are being exported as the closet material of the job. We need them to be exported as wood doors / drawer fronts. Mark, @CCDevNelson can you let us know what fields you need in the XML for raised panel doors/drawer fronts/hamper faces? 

Thanks, 

Ted

**Comment by TEDSTANDAGE** [comment]
By the way, I am not sure if this was or was not working previously, so if it was already exporting in the XML correctly before then perhaps one of our changes between then and now broke it. I don't know the history of this feature in SNaP as it is not something I have worked with since I came on.

**Comment by CCDevNelson** [comment]
Well, we need Door/Drawer Face Style, Color (Paint or Stain), Glaze option, Center Rail (yes or no), and over all size of the Door/Drawer Face. It was assumed that I would take that, based on the Style, and calculate all the parts and sizes from that. There might be more things that I can't think of off the top of me head, but those should be good starting blocks.

**Comment by TEDSTANDAGE** [comment]
> Well, we need Door/Drawer Face Style, Color (Paint or Stain), Glaze option, Center Rail (yes or no), and over all size of the Door/Drawer Face. It was assumed that I would take that, based on the Style, and calculate all the parts and sizes from that. There might be more things that I can't think of off the top of me head, but those should be good starting blocks.

Great, thank you Mark. Teddy, I think you can start with this, let us know if you need more info. Thanks, Ted

**Comment by ClassyTeddy** [comment]
So, I have almost all the information ready, but I am getting an error when trying to write it to the XML, which I will have to ask Ryan about. 

I do have a question though. I couldn't find any information on the center rail for any of the doors. When is a door supposed to have a center rail?

**Comment by TEDSTANDAGE** [comment]
A few months back you looked into adding a center rail on wood doors but were unable to do so I believe. So, right now we don't have the option available to choose that but we need the option on tall doors--we also need to be able to choose the height of where that center rail is located on the door. So, for now I guess just put a placeholder in there until we are able to add the option.

**Comment by ClassyTeddy** [comment]
All right

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Wooden-Door-Exports` Branch.

**Comment by TEDSTANDAGE** [comment]
Mark, how does this look for what you need for RP doors?

![image](https://user-images.githubusercontent.com/61025894/96771318-578fdc00-1396-11eb-861f-121e77557ec5.png)

XML:

https://drive.google.com/file/d/0B7I2qIHfcFaNZDBPaUxDVzRxZk9jbUQtbXVUZDZQLVpEdjY0/view?usp=sharing

Teddy, did you make this applicable to drawer faces and hamper faces as well or just doors? I tried exporting a wood drawer face  (in the same job as above) and it came out as melamine.

**Comment by TEDSTANDAGE** [comment]
Mark, I am also wondering if this should be a "Draw" class rather than "make"

**Comment by ClassyTeddy** [comment]
This was just for doors. Drawers can be a separate issue that I will tackle after this is good to go.

**Comment by CCDevNelson** [comment]
That looks good. I think you might be right on the "Draw" class thing, but I'm not sure that would work, cause isn't so that what ever is marked as Draw doesn't export to the XML? We might have to leave it a "make" and I'll just have to deal with the Category Number as a flag for me to take different steps when reading it in.

**Comment by TEDSTANDAGE** [comment]
White/almond cover cleat still ends up in the XML for pricing purposes even though it is set to "Draw" so it shouldn't mess that up if we were to change RP to draw too.

I did have a question about the RP material--it is showing the White PL Post as the "material" since I chose Oxford White as the stain. That is just the stain though and not the base material. Will pricing just be based on the size and style of the door or do we need more info in the XML for those purposes?

**Comment by TedClassy1209** [comment]
Teddy, as promised see the following wood door order form which gives the minimum face size for the different raised panel drawer fronts (ignore the customer info):

![image](https://user-images.githubusercontent.com/61025894/97343080-4afefe00-1844-11eb-8a6b-d62df9f2024f.jpeg)

**Comment by ClassyTeddy** [comment]
Is this for both Door and Drawer faces? Also, are these the minimum sizes for the associated glass inset doors/drawers?

**Comment by TedClassy1209** [comment]
The minimums are for drawer faces but would apply to doors as well I guess. 

There isn't really a minimum for CFG doors, but let's make a 10H minimum for them as it doesn't make much sense to go smaller than that. 

We don't really want to allow for glass inset drawer faces, they are a pain. The designer can make a special request if they want but we shouldn't have the option available on SNaP.

**Comment by TedClassy1209** [comment]
Teddy is this good to go with the exception of the minimum drawer face hole size? If so, can we go ahead and push to Ryan to merge?

**Comment by ClassyTeddy** [comment]
Yeah, it should be ready to go aside from the minimum drawer face hole size, but I haven't tested it in awhile.

**Comment by ClassyTeddy** [comment]
Actually, I need to do some cleanup on this one.

**Comment by ClassyTeddy** [comment]
Wooden Drawer and Wooden Door exports should be exporting properly now and are ready for testing on the `Wooden-Drawer-Exports` and the `Wooden-Door-Exports` branches respectively. I will tackle issue #37 at a later time.
