### ISSUE TITLE
Fog Grey exporting as Dura White_Fog Grey 15200 (PM-0000359)

### ISSUE THREAD

**Issue by TedClassy1209** [CCDevNelson/Snap-Updates#203]
We need Fog Grey to export as Fog Grey (PM-0000376)

**Comment by ClassyTeddy** [comment]
This is ready for testing on the `Fog-Grey-Exporting-Issue` branch.

**Comment by TEDSTANDAGE** [comment]
Fog Grey now exporting correctly. Thank you
