### ISSUE TITLE
Change "Extend Left Side" and "Extend Right Side" option

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#206]
Currently to make hutch partitions you can use the "Extend Left Side" and "Extend Right Side" option in the Construction Options of the partition prompts:

![Hutch Option](https://user-images.githubusercontent.com/61025894/96491848-9a677d80-11f7-11eb-8e8a-a1292f88da5e.png)

However, it limits the user to standard partition heights when they rarely are standard heights--usually you're trying to match the height of a standard partition next to the hutch (or the build height of the rest of the closet) but you have to account for a 0.75" or 1.5" countertop under the hutch and the fact that there is another partition under the countertop (remembering that a 30H partition plus a 30H partition stacked on each other do not match the height of a 60H partition). 

So, I would change this option to be a custom "extension" amount, starting with zero and the extension amount just being how far down the partition is extending. The user would have to do their own math. Please change the word "panel" here to "partition" as well.

We also don't need the option to change the hang height of the left and right partitions, it should match the rest of the openings.

**Comment by TEDSTANDAGE** [comment]
If it's possible to "Extend to Countertop" where it would take into account how far down it needs to go to be right on top of the countertop that would be great.

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Creating-Bottom-Capping-Library-Item` branch. The reason it is on this branch is because I plan on using my changes here to also help solve Issue#181

**Comment by ClassyTeddy** [comment]
Also, I did not add an "Extend to Countertop" option as it wouldn't be possible to grab the specific countertop that is below the partition, I would instead grab all countertops that might exist in the room, and I foresee that causing issues.

**Comment by TEDSTANDAGE** [comment]
Looks good Teddy, thank you. 

Also this option will work great when extending a partition to the floor in a desk, fridge, or other situation so it isn't just limited to hutch cabinet situations.
