### ISSUE TITLE
Variable width TK

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#21]
Need option to make toe kicks have a variable width (for situations where there is a filler or where the TK goes wall to wall, etc.)

**Comment by TEDSTANDAGE** [comment]
There is currently a variable height button when you right click on a TK, perhaps a variable width button could go right underneath it

**Comment by TEDSTANDAGE** [comment]
I am going to add an issue I just found regarding the "Variable Height" feature that is currently available on TKs since it is nearly identical to the variable width feature we are wanting to add. Here is an example of a 4.39" tall TK where I have "Variable Height" checked:

![image](https://user-images.githubusercontent.com/61025894/81706243-bf73eb00-9424-11ea-929d-8daefeedd590.png)

Here is the exported XML where the TK pieces are being incorrectly exported exactly 4.39" tall:

![image](https://user-images.githubusercontent.com/61025894/81706572-f6e29780-9424-11ea-8494-204a1bb6151b.png)

I think default should be to add 3" to the height of the TK front, TK back, & TK end caps in the XML export when Variable Height is checked.

The Variable Width option, when added, should also add 3" to the width/length of the TK front, TK back, & TK end caps in the XML export when Variable Width is checked.

**Comment by riyajose96** [comment]
![image](https://user-images.githubusercontent.com/64493941/81980370-55ee0b00-95e3-11ea-938a-25a86bfc62ad.png)

I have created prompt for variable breadth. Can find the code in the branch 'riya-fixed'.

**Comment by TEDSTANDAGE** [comment]
Thanks Riya, perhaps I jumped the gun and you haven't pushed it yet but I am not seeing anything updated on that branch yet:

![image](https://user-images.githubusercontent.com/61025894/81981445-28a25c80-95e5-11ea-8f84-13380d7d60b8.png)

Also, let's make the prompt say "Variable Width" rather than Variable Breadth. 

Another thing I was thinking--look at how the "Variable Section" works in the Construction Options of the Opening Starter Prompts for the openings/partition prompts since that is currently functioning in adding length to cleats/shelves in the XML export of those sections. That may help us get the Variable Height and Variable Width TK options functioning.

**Comment by riyajose96** [comment]
![image](https://user-images.githubusercontent.com/64493941/81991071-48418100-95f5-11ea-820b-4982640008b0.png)
I have changed it to "Variable Width" and pushed it to branch "riya-fixed".

**Comment by TEDSTANDAGE** [comment]
Was able to pull from that branch with the changes, thanks! I now have the Variable Width option:

![image](https://user-images.githubusercontent.com/61025894/82071174-9785c100-968a-11ea-88f8-58c25efba093.png)

As we knew, the variable height and width options are not functional as far as actually exporting parts reflecting the variable, despite the now-available options:

![image](https://user-images.githubusercontent.com/61025894/82071457-f814fe00-968a-11ea-83cf-4795a2a71b9a.png)

The vertical TK parts have exactly the TK as the part heights (TK end caps, TK front, & TK back should be extended 3") and the left to right TK parts still are just the width of the TK minus the widths of the endcaps (the TK Front, TK back, and TK Stringers should be extended 3"). Riya, please look at the functionality of the variable section option in the partition prompts and see if you can apply that to the variable height/width prompts in the TKs, or see if you can figure out another way. If you cannot figure this out, please ask that this issue be pushed to Ryan.

**Comment by riyajose96** [comment]
Okay Ted, I shall look into it.

**Comment by TEDSTANDAGE** [comment]
I emailed this to Teddy & Riya, but I'll put it here as well for organization/documentation's sake. Riya's addition and Ryan's changes look good to me in my initial testing (The XML export looks to be correctly extending the heights of the TK end caps, TK front, & TK back by 3" when variable height is selected, and extending the width of the TK Front, TK back, and TK Stringers when variable width is selected). If you could both test please and when you agree please let Ryan know, and if you find any issues please let us all know. Thanks
