### ISSUE TITLE
Adding "Center Rail" option to door prompts when replaced by wood or CFG doors

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#213]
Even if we can't get SNaP/Blender to show the center rail on wood or cut-for-glass doors in the scene yet, can we add the option to the door prompts so we can at least get it on the XML that the door has a center rail? We would want the option to say "Center Rail" and only be available when the door has been replaced by a wood or CFG door.

Mark @CCDevNelson , default is going to be that the center rail is in directly the middle. How would you like it reflected if the user wants a custom location of the center rail? Just an "offset" from center figure, with a positive number being up from center and a negative number being down from center?

**Comment by CCDevNelson** [comment]
Ted,
We can start with that and see what issues we run into with that, but I think I should be ok with a +- number.

**Comment by ClassyTeddy** [comment]
Ready for testing on the Center-Rail-Option` branch

**Comment by TEDSTANDAGE** [comment]
Looks good to me, thank you Teddy. @CCDevNelson what do you think of this in the XML:

![image](https://user-images.githubusercontent.com/61025894/97311092-3a895c00-1821-11eb-9fe5-cf387b6143e4.png)

Also @CCDevNelson , do you need anything added to the Label for RP doors/faces or is where we are currently putting the style/glaze/center rail info sufficient?

Thanks, 

Ted

**Comment by TedClassy1209** [comment]
@CCDevNelson once we get the go ahead from you, we can push to Ryan to get this merged and we can get you some example XMLs. Thanks, Ted

**Comment by CCDevNelson** [comment]
Ted,
There are several items I need in the XML, but I can't give them to you yet. Duane is still in the process of creating the categories for new parts (and by the way, I think he is changing some of the current categories as well) And I'm pretty sure the stain/paint/glaze options just got increased, so I'm not sure where we stand on this at the moment. I think this needs to be brought up in the next meeting so we can discuss all of these changes.

**Comment by TedClassy1209** [comment]
Okay then Teddy I think this particular change can be merged for now and we can address the other additions and changes once those decisions are made by Duane.
