### ISSUE TITLE
Add City, State, and Zip Code to Project Info

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#218]
Right now Project Address is one line on the Project Info menu. We need additional lines for City, State, and Zip Code (each its own line) which also need to be exported to the XML.

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Adding-Fields-to-Project-Info` branch. Please test how it functions with old projects, in addition to testing it with newly made projects.

**Comment by kategodfrey** [comment]
Looks good. @TedCC1209 would we want City, State and Zip to all be on the same line instead of three separate to save space?

**Comment by TedCC1209** [comment]
> Looks good. @TedCC1209 would we want City, State and Zip to all be on the same line instead of three separate to save space?

No, we need them separated for other purposes.

**Comment by TedCC1209** [comment]
Thanks Teddy, I could not get an XML to export from old jobs in this branch. New jobs exported fine. The prompts look good. I wouldn't worry too much about old jobs not exporting XMLs if it's not a quick fix. 

@CCDevNelson Mark, how does this look to you in the XML?

![Project info](https://user-images.githubusercontent.com/61025894/100652585-5f7f5c00-3304-11eb-95dd-9e8006d8563e.png)

Thanks, 

Ted
