### ISSUE TITLE
Top Shelf Molding Error

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#22]
When trying to insert Top Shelf Molding, get an error saying "Could not find Product Class..." Is this because we don't have any moldings available to choose from?

![image](https://user-images.githubusercontent.com/61025894/77450131-17d92580-6db0-11ea-98e7-0dd72bcfaab9.png)

**Comment by meltnaz** [comment]
The "top shelf molding" can be removed from the catalog. It is a remnant from older versions. 

The correct catalog item is "flat crown." Tha item is working correctly.

Moldings such as large and small traditional crown molding are locating in molding in the closet options tab

**Comment by TEDSTANDAGE** [comment]
Teddy this should just be how you deleted the library/catalog item real quick for me the other day I would think.

**Comment by ClassyTeddy** [comment]
I did that in my branch. So it should be fixed now.
