### ISSUE TITLE
More 2D View cleanup items

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#226]
Nailson & Antonio, a few changes we need to make on 2D View exports after some conversations with various experienced folks here at Classy:

1. Delete the hash/tick/dimension marks and lines for the section widths on both elevations and plan views (leaving us with just the number) [EDIT: also delete the same dimension marks/lines for the partition heights on elevations):

![delete width marks](https://user-images.githubusercontent.com/61025894/100148108-87307900-2e59-11eb-9560-c7ae82fd33d8.png)

2. When you are identifying shelf depths (when they differ from the section depth), they need to come from the center of the shelf (in contrast with section & partition depths which come from bottom left of the section):

[EDIT: fixed the following picture:]
![delete width marks](https://user-images.githubusercontent.com/61025894/100151614-9fef5d80-2e5e-11eb-8680-bfe14a1dee2a.png)

3. Delete partition depths from plan view

4. Don't draw top and bottom cleats in elevations:

Before (current with cleat drawn):

![Cleat before](https://user-images.githubusercontent.com/61025894/100148438-00c86700-2e5a-11eb-8f1c-a97087f41a44.png)

After (no cleat drawn):

![Cleat after](https://user-images.githubusercontent.com/61025894/100148585-2f464200-2e5a-11eb-9564-fae805c6fbec.png)

5. Add onto the Plan view the assembly names from the following list, centered justified in the middle of the section:

-Hamper = "Hamp."

-Hang Double and Hang Double Tall = "DH" 
-Hang Long = "LH"
-Hang Medium = "MH"
-Hang Short = "SH"
*If hangs have added shelves, need to have the number of shelves on a separate line right below the hang name--the dust cover shelf counts as a shelf, so need to add together all dust cover shelves and additional adjustable shelves.
*Example:
"SH
5 Shlvs"
(centered justified in the section)

Slanted Shoe Shelves = "[# of shelves] SSS"
Shelf Stack = "[# of shelves] Shlvs"
Glass Shelves = "[# of shelves] Glass Shlvs"

Doors (single vs double) = "1 Door" or "2 Doors" 
*If doors have added shelves, need to have number of shelves on a line right below "1 Door" or "2 Doors"--the bottom KD counts as a shelf, so the shelf count will be  the number of additional adjustable shelves plus the bottom KD.

Drawers = "[#of drawers] Drws"

Other assemblies don't need to be notated. If there are multiple assemblies within the same section, they should be listed on separate lines--top assembly on top and bottom assembly on the bottom.

Examples:

![Shortened Assembly Name](https://user-images.githubusercontent.com/61025894/100148946-ad0a4d80-2e5a-11eb-8efe-dd98b2ac19a4.png)

![image](https://user-images.githubusercontent.com/61025894/100151451-6585c080-2e5e-11eb-9d5e-ce808a96b3be.png)

**Comment by nailsonlandim** [comment]
Hi @TedClassy1209, 

Items 1, 2, and 3 are straightforward

Item 4 is a bit trickiest but as it is part of a new scene we can hide from it.

I made a mind map for Item 5 to avoid any misunderstanding.

![Plan View Assembly Names (1)](https://user-images.githubusercontent.com/70038700/100236285-39287d80-2f0c-11eb-943e-bfb8ef74f065.png)

**Comment by nailsonlandim** [comment]
1, 2, and 3 done.

![image](https://user-images.githubusercontent.com/70038700/100364010-49a82900-2fdc-11eb-97fe-3b36ed45ef27.png)

![image](https://user-images.githubusercontent.com/70038700/100363982-3f862a80-2fdc-11eb-8d6b-0ec46ce97107.png)

**Comment by nailsonlandim** [comment]
**Item 4 Done** 

![image](https://user-images.githubusercontent.com/70038700/100485160-d8509f00-30dd-11eb-9df8-af7fee88f501.png)

We did it unlinking the cleats from the elevations

Available at: https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23226-2dview-cleanup

**Comment by TedClassy1209** [comment]
These are looking really good, thank you guys

**Comment by AntonioGloria** [comment]
Hello, Antonio here.
Here is a mock-up of what the plan view would look like, taking into account the notes regarding assembly names, plus the fixes that have been made so far.
![2D Views_MockUp_PlanView](https://user-images.githubusercontent.com/74732175/100680952-4bede880-3338-11eb-94ef-ffd0a2674f99.png)

**Comment by TedCC1209** [comment]
Thanks Antonio, for the most part your mock-up looks like what we are looking for (it captures everything we have asked for so far), but here are just a few things in addition to the changes your pics reflects:

1. Increase the font size of the assembly labels (LH, DH, SH, etc.)--maybe 1.5-2x as big as it is right now?
2. Make dimensions and labels go parallel with the wall for walls not going left to right (Walls A and C in your mock-up). Walls going left to right on the plan view can keep their current configuration.
3. Move wall width dimension to the outside of the dimension hash mark .
4. Move section width dimension to just outside of the wall but not outside the wall width dimension hash mark (between the two lines)--if there are different section widths for uppers and lowers in a particular spot, can we push the wall width dimension hash mark and width dimension for that wall out a bit to allow for one more line of text to show the upper section width?

Here is a crude attempt to show what I am saying/looking in my points, above, I am sure you could make it look a lot cleaner but trying to cut/rotate/expand with Paint 3D has its limitations:

![Plan View Mockup](https://user-images.githubusercontent.com/61025894/100760739-51d2e080-33af-11eb-99b2-15fc828025ad.png)

**Comment by TedCC1209** [comment]
Actually--Let's just get rid of section widths from the plan view.  So, disregard what I wrote for number 4 from above and just get rid of it all together, it'll be cleaner and the widths are available on the elevations. Thanks!

**Comment by AntonioGloria** [comment]
Here's the updated mock-up for the plan views with the latest notes.
![2D Views_MockUp_PlanView](https://user-images.githubusercontent.com/74732175/100803978-aeef8600-33f1-11eb-9477-69b619af7be0.png)

**Comment by TedCC1209** [comment]
Looks good Antonio, thank you. If you can update the font for the wall height that would be good too, and the DH on the left side of Wall B should be centered in the opening (assuming you all would do those things anyway). Thanks, Ted

**Comment by AntonioGloria** [comment]
We have added some more 2D Views fixes. Here's the link:
https://github.com/nailsonlandim/SNaP-Dev/commits/issue_%23226-2dview-cleanup

And here's a preview of the fixes:
![image_2020_12_07T22_08_48_334Z](https://user-images.githubusercontent.com/74732175/101415469-97ab0f80-38ad-11eb-95bc-60281e200792.png)

**Comment by nailsonlandim** [comment]
Hi @TedCC1209 @kategodfrey @JBTattersall @sarahhightower 

I've applied the labels on plan views.

It's available with Antonio's changes, at https://github.com/nailsonlandim/SNaP-Dev/commits/issue_%23226-2dview-cleanup

![image](https://user-images.githubusercontent.com/70038700/101531337-defad400-3971-11eb-8b07-4ed8247ffadc.png)

**Comment by TedCC1209** [comment]
Looking much cleaner, thank you both. 

1. Sarah got the following traceback errors with a job with an angled wall (aren't getting this error with square or custom rooms):

![Traceback error 2d views cleanup](https://user-images.githubusercontent.com/61025894/101533451-13ab6300-3953-11eb-856b-cd446da73386.png)

2. Sarah ran into a few other things we are trying to narrow down before we bring them up to you. One of them, however, is the issue where the 2D views are making 120" walls 119" (or similar). Wall B on this one should be 120" (square room...):

![image](https://user-images.githubusercontent.com/61025894/101533620-4d7c6980-3953-11eb-93ec-7d3885577779.png)

If her providing the project files for you would help, let us know. Though I think it's pretty replicable since it has happened a bunch in the past.

Thanks, 

Ted

**Comment by nailsonlandim** [comment]
Hi @TedCC1209 ,

Can you send us the file? 
I think I know what's going on and it has to do with wall angles and so far I just dealt with right angles.

**Comment by sarahhightower** [comment]
Sure. Here is the angled wall file.

https://drive.google.com/drive/folders/1ciR38vFa-oXJlnXb6uV9mF_WgNXiRAKp?usp=sharing

**Comment by nailsonlandim** [comment]
Thanks @sarahhightower !

**Comment by nailsonlandim** [comment]
Hi @TedCC1209 @sarahhightower 

> 
> 1. Sarah got the following traceback errors with a job with an angled wall (aren't getting this error with square or custom rooms):
> 
Just fixed, I also adjusted wall height hashmarks to deal with it.

Thanks,
Nailson

**Comment by nailsonlandim** [comment]
Hi @TedCC1209 @sarahhightower @kategodfrey @JBTattersall,

Fixed Item 2:

![image](https://user-images.githubusercontent.com/70038700/101677765-c2c36980-3a3b-11eb-8bdd-53ec6e6c6b5a.png)

Now on Plan Views, the dimension is parallel to the wall.

It's available at: https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23226-2dview-cleanup

**Comment by TedCC1209** [comment]
Hi @sarahhightower can you test and verify this is working for you know? Once it is, I think we can push this branch. Thanks, Ted

**Comment by sarahhightower** [comment]
Worked for me! Thanks Nailson! 

[2D Views Test.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5675097/2D.Views.Test.pdf)
