### ISSUE TITLE
2D Views - Fix Angled Lines

### ISSUE THREAD

**Issue by nailsonlandim** [CCDevNelson/Snap-Updates#227]
Fix angled lines--sometimes partition / wall lines aren't perfectly straight up and down but rather come out as a perspective/angled

**Comment by AntonioGloria** [comment]
@TedCC1209 
Fixed this issue
![image](https://user-images.githubusercontent.com/74732175/101954451-c123ae00-3bc1-11eb-99cd-2abd002613be.png)
Fix is available at: https://github.com/nailsonlandim/SNaP-Dev/tree/3DLabels

**Comment by TedCC1209** [comment]
Awesome! Thanks Antonio.  @kategodfrey @sarahhightower @JBTattersall can you guys test this as well too please?

**Comment by sarahhightower** [comment]
Attaching my 2D test plans. I notice there is no line for the drawer depth. The other labeling looks good. 

[2D Views.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5682066/2D.Views.pdf)

**Comment by TedCC1209** [comment]
@sarahhightower @kategodfrey @JBTattersall this particular issue is about vertical partition lines sometimes showing up weird and not perfectly vertical, not about labels or anything:

![image](https://user-images.githubusercontent.com/61025894/101988315-11e4e680-3c56-11eb-81e4-3847d849651a.jpeg)

To test, this is likely just take doing multiple rooms with various configurations to see if the old problem ever shows up.

The branch to find this fix is in Nailson's repository under the branch called 3DLabels

**Comment by TedCC1209** [comment]
This is looking really good from what I see. Thanks!

I will create a new issue if necessary, but looking at Sarah's example and from what I am seeing, did we lose the hash mark for the depth notation behind doors/drawer faces?

![image](https://user-images.githubusercontent.com/61025894/101994961-8f731b80-3c83-11eb-9bdc-b38daecd4a42.png)

**Comment by TedCC1209** [comment]
@AntonioGloria are you doing the hash mark fix on this issue or would you prefer I created a new one? I am fine either way just let me know.

Thanks, 

Ted

**Comment by AntonioGloria** [comment]
@TedCC1209 I can work on the hash mark fix on this issue.

**Comment by TedCC1209** [comment]
Hi Antonio, I am just wondering if you are close on the hash mark fix--we are needing it for the update we want to roll out. Let me know if you think it'll be completed today. 

Thanks, 

Ted

**Comment by AntonioGloria** [comment]
Hi @TedCC1209
The hash mark fix is ready, I have just uploaded it.
![image](https://user-images.githubusercontent.com/74732175/102376976-c8fc9d00-3f89-11eb-95c7-0bce769818a3.png)
The fix can be found here: https://github.com/nailsonlandim/SNaP-Dev/tree/3DLabels

**Comment by TedCC1209** [comment]
Great, thanks! Worked on my testing too. @sarahhightower @kategodfrey @JBTattersall please test as well.


@ClassyTeddy I think you can do the pull request on this and the rest of the "Ready to Merge" items to set up for the update.

Thanks, 

Ted

**Comment by kategodfrey** [comment]
Looks good on my end

![image](https://user-images.githubusercontent.com/63115502/102388567-2fd08500-3f8f-11eb-89ce-ae5995e75a15.png)

**Comment by kategodfrey** [comment]
Wall C I have a shelf space below the drawer stack to see if it would mess up the hash... it's not a real design

**Comment by sarahhightower** [comment]
This appeared to work for me. Thanks! 

![Test Image](https://user-images.githubusercontent.com/72047269/102394690-5b576d80-3f97-11eb-8da1-1e359d1a3a37.JPG)
