### ISSUE TITLE
Multiple "Metals" folders

### ISSUE THREAD

**Issue by SeanRadvan** [CCDevNelson/Snap-Updates#228]
![Metals](https://user-images.githubusercontent.com/54151330/101056006-bde84c80-3547-11eb-9a3b-2a5698f20f6e.jpg)
While changing the colors on the handle pulls it appears there are two similar folders named "metals" and "finished metals" in snap. Both contain separate files named "metals" and "rod materials" but I am unsure which folder Teddy's logic pulls from in the mv_defaults. If one is redundent, can we delete it, and possibly combine metals and rod materials at the same time?

**Comment by ClassyTeddy** [comment]
So this is something that is going to be fixed/changed with the new version. We plan on removing a lot of redundancies. But at the moment, I believe those two folders are necessary for different parts of the code. But, as we move to the new version of SNaP, one of the folders we will make redundant and remove.
