### ISSUE TITLE
Default bottom KD in drawers and shelf stacks

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#229]
I thought the default was to have bottom KDs in drawer stacks and shelf stacks previously. It looks like it may have changed in past fixes and we just didn't catch it. While testing Nailson and Antonio's 2D View improvements, Sarah noticed that bottom KDs were not default-ly and automatically put in when the drawers/shelf stacks were placed into the scene. The bottom shelf of the shelf stacks looks sized like it is a KD, but it is not a KD (not exporting as  KD, not a "locked shelf" in the properties menu, and does not have the KD label on 2D views).

Teddy, can we have the defaults for these assemblies be to have a bottom KD? 

Thanks, 

Ted

**Comment by TedCC1209** [comment]
@ClassyTeddy the designers are asking that this be elevated. Is this an easy fix to get done today/tomorrow? Thanks.

FYI @kategodfrey @sarahhightower

**Comment by ClassyTeddy** [comment]
This should be ready for testing on the `master` branch

**Comment by ClassyTeddy** [comment]
This should be ready for testing on the `master` branch

**Comment by sarahhightower** [comment]
Tested, and it worked for me. Thanks!

**Comment by kategodfrey** [comment]
Tested and it worked for me as well. Thank you.
