### ISSUE TITLE
Update Moderno Door Color Options

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#235]
We need to update the Moderno Door color options to the following:

U Cannes
U Cassis
U Driftwood
U Ember
U Mystic
U Nizza
U Silva
U Skye

@SeanRadvan , are you able to do this or does @ClassyTeddy need to?

Thanks, 

Ted

**Comment by TedCC1209** [comment]
@SeanRadvan @ClassyTeddy can we get this fixed this morning and sent to Ryan before the new update please? @SeanRadvan please let @ClassyTeddy know if you need him to handle this one, I wasn't sure if it was something you could address yet. Thanks, Ted

**Comment by SeanRadvan** [comment]
Sorry just saw this, to clarify it looks like you want cannes, cassis,
skye, added and luxe, zahara removed is that correct?  It looks like it
pulls the names based on the ModernoDoorColors.csv, just need to find where
it pulls the blender file from and get the colors for it to load. If you
have the company website that would be great.

**Comment by TedCC1209** [comment]
Thanks Sean. I need the list in SNaP to match the list I put in the OP, whatever that ends up being on adding/deleting. None of these are new colors, they are all currently available Uniboard textured melamine colors in SNaP.

**Comment by ClassyTeddy** [comment]
@SeanRadvan I just got to this one, it was a really quick change that is ready to go now. Should be ready for testing on the `master` branch now.

**Comment by SeanRadvan** [comment]
Perfect, just for my learning would you mind telling me what files / lines
had to be changed?

**Comment by ClassyTeddy** [comment]
So in this situation, if you look at this commit 5d766dbc, all I needed to do was change what options were available in the `ModernoDoorColors.csv`, because we already had all of those colors available as .blend files.

**Comment by TedCC1209** [comment]
This looks good. Thanks
