### ISSUE TITLE
Drawer Prompts on master build 12 / 18.

### ISSUE THREAD

**Issue by SeanRadvan** [CCDevNelson/Snap-Updates#236]
Was testing the master branch post ryans merge yesterday and got this popup when opening drawer prompts. 
![drawer](https://user-images.githubusercontent.com/54151330/102633330-8237b000-410d-11eb-9f18-d7abe27458a6.jpg)

**Comment by TedCC1209** [comment]
I am getting the same thing

**Comment by ClassyTeddy** [comment]
None of the merges that Ryan has made should have affected the drawers. It looks like there is a logic error happening with double jewelry drawers in the prompts menu.

**Comment by SeanRadvan** [comment]
Doing some more testing, but on multi drawer stacks it only has an option for "Drawer 1 Height," is this correct / related?

**Comment by ClassyTeddy** [comment]
Yes and yes, once SNaP reaches the error, it stops creating more options in the prompts menu. I am pushing a fix now, SNaP was building an old version of the drawers that lacked some necessary values for Double Jewelry Drawers. I am also adding a small line of logic to avoid the error on older drawer stacks.

**Comment by ClassyTeddy** [comment]
Fix should be available on the `master` branch now.

**Comment by SeanRadvan** [comment]
![drawr update](https://user-images.githubusercontent.com/54151330/102636889-73073100-4112-11eb-8142-ad3424a4ae3e.jpg)
Looking better. I'm not sure what the requirements are for the double jewelry but i don't see a prompt for it.

**Comment by ClassyTeddy** [comment]
I believe you need either a 6 or 7 hole drawer and a depth of at least 16 inches

**Comment by TedCC1209** [comment]
Looks good for me now, and the double jewelry works in the parameters Teddy identified.
