### ISSUE TITLE
XML Export "Elements not closed" error

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#238]
Exported a test job to XML on the master branch and got the following message from XML Notepad when trying to open the XML:

![XML Export Error 12-21-20](https://user-images.githubusercontent.com/61025894/102782930-64f62200-4357-11eb-8e04-c0f4fe54aa86.png)

It would then only open the XML in regular Notepad and not my XML Notepad viewer.

**Comment by ClassyTeddy** [comment]
Can you send over the .xml file so I can take a look at it.

**Comment by TedCC1209** [comment]
Yes see the following:

https://drive.google.com/file/d/0B7I2qIHfcFaNZDBPaUxDVzRxZk9jbUQtbXVUZDZQLVpEdjY0/view?usp=sharing

So in this job at one point I tried putting in a Top Shelf piece but was having issues clicking the partition that I wanted because it had tall doors on each side of it, so I ended up pressing "Esc" to exit out of placing that part. Could that have caused the issue?

I didn't have issues with the XML on another test job so this one could have been user error or what I put above I guess.

**Comment by ClassyTeddy** [comment]
Try it on the master branch again. It was not because of the Top Shelf Mishap, there was an error when it was writing to the XML that was caused by the Wooden Door Export changes that caused it to not finish writing to the XML. I removed the issue and it should be working now.

**Comment by TedCC1209** [comment]
Great, it exported fine now. Thanks!
