### ISSUE TITLE
2D Views - Dimensions need inch mark

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#239]
We need to add the inch (") notation mark to the wall height and build height dimensions. Right now they don't have any unit of measure attached to them:

![2D Views dimensions need inch mark](https://user-images.githubusercontent.com/61025894/102783942-e9957000-4358-11eb-8f7c-7b6feca8827c.png)

**Comment by nailsonlandim** [comment]
Fixed

![image](https://user-images.githubusercontent.com/70038700/102786416-363f7200-437e-11eb-936f-69fc90828b62.png)

https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23239-dimensions-needs-inch-mark

**Comment by TedCC1209** [comment]
Thanks for adding those Nailson. Is there a reason your wall height and build height dimensions come out more bold/are a different text than mine?

[2D Views.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5725278/2D.Views.pdf)

**Comment by kategodfrey** [comment]
Tested this and it looks good. My wall heights are not bolded...

[12-22 Test.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5732178/12-22.Test.pdf)
