### ISSUE TITLE
Top shelf exposed ends showing particle board, not edgebanding

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#24]
The edgebanding for top shelf exposed ends doesn't appear to be working/showing up like it should. I think this was an issue that may have been broken and fixed before and is now broken again? See below.

![image](https://user-images.githubusercontent.com/61025894/77781372-afd64980-7012-11ea-94b0-d8ea4f46ec26.png)

**Comment by meltnaz** [comment]
Not sure if this is the issue, but even if you mark the edges as finished in the dialog box, they do not show the edge banding until you either save the drawing or click on "update materials" button at the bottom of the materials window.

**Comment by ClassyTeddy** [comment]
I believe what Melissa said is the issue. I had to hit update materials to update the edge banding on the top shelf. So I think this issue should be considered fixed.

**Comment by TEDSTANDAGE** [comment]
Why can’t we make it just automatically show so we don’t have to click update materials? Let’s make this as user friendly as possible

**Comment by ClassyTeddy** [comment]
We probably could have it automatically update, but depending on how we go about doing that, it could cause more issues. I'll see what I can do.

**Comment by ClassyTeddy** [comment]
Hey Ted, I think I managed to get it to automatically show now. If you want to test it, you need to pull off of the TeddyChanges Branch, not the master branch.

**Comment by TEDSTANDAGE** [comment]
Thanks Teddy, it automatically shows for me now (when I pulled from your branch). Nice work
