### ISSUE TITLE
Room Category Error Custom Rooms

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#240]
While testing the master branch I tried creating a custom room. The first issue is that I never got a prompt for the room category. Secondly, after I collected the walls and then attempted to add the room to the active project I got the following error message:

![Custom Room Room Category Error](https://user-images.githubusercontent.com/61025894/102785233-ddaaad80-435a-11eb-97fc-9ed2ad52250a.png)

**Comment by TedCC1209** [comment]
If this fix is going to take a lot of time, we can revert the room category feature addition and work on it after the update is good to go. I would like users to see that we are adding this, but it isn't a "must-have" for this update. So, if it's quick, go ahead and make the fix, otherwise it's okay to prioritize the other items we are pointing out. Thanks, Ted

**Comment by ClassyTeddy** [comment]
A fix for this should be ready to go on the `master` branch

**Comment by TedCC1209** [comment]
This works now, thank you
