### ISSUE TITLE
2D Views: Exposed annotation hash mark

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#241]
I noticed that the Top Shelf exposed notation has mark is coming in at the bottom corner of the shelf again rather than at the top corner--I thought we had that fixed before? 

Also the CT exposed notation has mark is coming in as though the countertop is 1.5" thick even when it is melamine and only 0.75" which makes it look like the hash mark is floating/out of place. Can we have it determine the thickness of the CT to determine where the Exposed annotation has mark comes in? Alternatively, can we just have the exposed notation has mark for countertops come in as though the CT is 0.75" thick--that way, if the CT is 1.5" thick because it is HPL, granite, or quartz the notation hash mark will point to the center of those countertops. 

[2D Views.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5725291/2D.Views.pdf)

**Comment by TedCC1209** [comment]
The countertop label hash mark is the same as the CT exposed annotation hash mark-- it is coming in as though the CT is 1.5" thick even when it is only 0.75" thick melamine material. It should also either come in exactly at the top of the CT or it should always assume it is 0.75" thick--though this will be more noticeable than the exposed label hash mark, so it would be nice if it could determine the thickness of the CT and be placed based according to that height.

**Comment by nailsonlandim** [comment]
Hi @TedCC1209 @kategodfrey @sarahhightower 

Fixed, Also found a way to correctly label the material based on the countertop cutpart name.

![image](https://user-images.githubusercontent.com/70038700/102941846-7bed5f00-4492-11eb-95de-3a1d36397d26.png)

![image](https://user-images.githubusercontent.com/70038700/102941953-c4a51800-4492-11eb-8e38-450c72b20fb7.png)

Available at: https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23241-exp-annotation-hash-mark

**Comment by TedCC1209** [comment]
These look to be coming in at the right heights now, thank you for fixing that. The labels do not seem to follow the left and right ends when they have l/r overhang, however.

[2D Views.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5735720/2D.Views.pdf)

**Comment by nailsonlandim** [comment]
Thanks for point the overhang issue. I think that`s a fast fix. Thanks!

**Comment by sarahhightower** [comment]
Countertop labels look good. A couple other things I noticed while running this test;

Test 1: 

I used the countertop prompts to change the countertop selection for each area. I chose to do HPL on wall A, Melamine on wall B, and Granite on wall C. The drawer section with the melamine counter incorrectly notes it's height 41.91". A 4.39" toe kick was used in the design so the area with the melamine counter should be 41.16". Also, the countertops all say that they are oxford white so I decided to run a second test. 

Test 2: 

I cleared the 2d views, saved the file and then opened it back up. Then, I used the countertop prompts to change the countertops on wall A and C to granite, and kept wall Bs countertop melamine. Then, in the "countertop selection" of "closet materials" I chose nordic black granite. Despite changing the prompt and the countertop selection it kept my original countertop selections of test 1.  Possibly the challenge here is having different countertops but this is a possible scenario. Example; a bench could have different material than a dresser countertop. 

[Test 1 - 2D Views.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5736133/Test.1.-.2D.Views.pdf)

[Test 2 - 2D Views.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5736135/Test.2.-.2D.Views.pdf)

![Test 2 Screenshot](https://user-images.githubusercontent.com/72047269/103016770-d07af380-44ff-11eb-9c35-7c13d9953e28.png)

**Comment by TedCC1209** [comment]
> Countertop labels look good. A couple other things I noticed while running this test;
> 
> Test 1:
> 
> I used the countertop prompts to change the countertop selection for each area. I chose to do HPL on wall A, Melamine on wall B, and Granite on wall C. The drawer section with the melamine counter incorrectly notes it's height 41.91". A 4.39" toe kick was used in the design so the area with the melamine counter should be 41.16". Also, the countertops all say that they are oxford white so I decided to run a second test.
> 
> Test 2:
> 
> I cleared the 2d views, saved the file and then opened it back up. Then, I used the countertop prompts to change the countertops on wall A and C to granite, and kept wall Bs countertop melamine. Then, in the "countertop selection" of "closet materials" I chose nordic black granite. Despite changing the prompt and the countertop selection it kept my original countertop selections of test 1. Possibly the challenge here is having different countertops but this is a possible scenario. Example; a bench could have different material than a dresser countertop.

@nailsonlandim , let's create new issues for what Sarah has pointed out. I replicated them all myself. 

1. The build height issue is something you and @AntonioGloria should be able to address I believe--it just looks like it accounted for a 1.5" thick CT for both melamine and HPL/granite tops when it should have just been 0.75" for the melamine CT (the 41.91" build height for her job is correct for the HPL and Granite, just not the melamine). Not sure what the logic you all have in there currently, but it should account for different types of countertops within the same room--the XML and the renderings correctly show the melamine CT as 0.75" thick and the HPL & Granite as 1.5" thick.

2. The other issues about having multiple types of countertops within a room may need to be addressed by @ClassyTeddy because all countertops are currently being assigned the color chosen in the Countertop Material prompt from the Closet Materials menu and being assigned whether Melamine, HPL, or Granite is selected in the prompts for each particular CT. This is likely a more involved fix... The XML currently exports HPL and Granite as the color of the closet with a material ID that does not contain a SKU number (we don't have SKUs yet for all the countertop materials though either so we need Brock to add those to the csv).

**Comment by nailsonlandim** [comment]
Hi @TedCC1209  Solved the following issue:

> These look to be coming in at the right heights now, thank you for fixing that. The labels do not seem to follow the left and right ends when they have l/r overhang, however.
> 
> [2D Views.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5735720/2D.Views.pdf)

![image](https://user-images.githubusercontent.com/70038700/103042111-46f71000-4557-11eb-9d7b-64ffee2335ed.png)

Now (Exp.) labels will behave correctly, available at: https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23241-exp-annotation-hash-mark.
