### ISSUE TITLE
2D Views Plan View - Top Shelf & Countertops

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#242]
Top shelf appears to show up in the plan view of 2D Views while countertops do not seem to show. Can we have both show up on the plan view but have them in gray rather than black?

[2D Views.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5725313/2D.Views.pdf)

Thanks, 

Ted

**Comment by nailsonlandim** [comment]
Hi @TedCC1209 @sarahhightower @kategodfrey 

Found out the bug that caused that. Now countertops will be correctly displayed.

The problem was caused (my bad) because when unlinking cleats I did not deselect any existing selected object, and the way Blender works it needs to set an object as active to unlink it from a different scene (in this case a 2D view).

So as a note for any developer in the future, make sure you have deselected objects on scene previously
```python
bpy.ops.object.select_all(action='DESELECT')
```

Available together with 241: https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23241-exp-annotation-hash-mark

**Comment by nailsonlandim** [comment]
Sorry, I`ll add the Countertops just as the Topshelves are added. 

About the color I`ll check that with Antonio.

**Comment by nailsonlandim** [comment]
Hi @TedCC1209,

I've added the Countertop at the Plan View,

![image](https://user-images.githubusercontent.com/70038700/103224028-ec1e3980-4905-11eb-9151-6907b5701790.png)

Tell me what you think.

Available at: https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23241-exp-annotation-hash-mark

**Comment by TedCC1209** [comment]
Thanks Nailson, I am seeing the CTs on the plan view now. 

Can you tell me what the dotted lines are in your example? Are those uppers? I think we kept those as solid lines, no?

**Comment by nailsonlandim** [comment]
> Can you tell me what the dotted lines are in your example? Are those uppers? I think we kept those as solid lines, no?

Yes, they are uppers. In fact, makes sense to be solid lines but as far as I remember they were dashed in this situation.

**Comment by kategodfrey** [comment]
@TedCC1209 This is what I got:
![Screenshot 2020-12-29 112044](https://user-images.githubusercontent.com/63115502/103305339-1d5f3e00-49c8-11eb-81b4-78e8aeccb830.png)

**Comment by kategodfrey** [comment]
I just see issues in the fine details. For the countertop issue specifically:

1) In the plan view, the countertop doesn't connect on the left side. 

Other small issues:

2) The closet components are layered when there are uppers and lowers.
3) The ceiling height is hidden under the left corner (Job Name, Job Number, Install Date...)

**Comment by kategodfrey** [comment]
![lines](https://user-images.githubusercontent.com/63115502/103306007-c490a500-49c9-11eb-9bc6-4104f77f00cf.png)

**Comment by TedCC1209** [comment]
> > Can you tell me what the dotted lines are in your example? Are those uppers? I think we kept those as solid lines, no?
> 
> Yes, they are uppers. In fact, makes sense to be solid lines but as far as I remember they were dashed in this situation.

Alright, well let's make them solid please. Also please let me know what you're thinking for fixes on what Katie pointed out and an ETA if possible. Thanks, Ted.

**Comment by nailsonlandim** [comment]
Hi @kategodfrey 

> 1. In the plan view, the countertop doesn't connect on the left side.

That seems a faster fix. probably just a tweak on how the countertop is "positioned" on PV. (ETA, 1-2h, today) 1-2 PM Arizona Time

> The closet components are layered when there are uppers and lowers.

Are you referring to the text? 
![image](https://user-images.githubusercontent.com/70038700/103310126-a17bea80-49f5-11eb-9e71-428dd210e8dd.png)

> The ceiling height is hidden under the left corner (Job Name, Job Number, Install Date...)

I can adjust the 2D view image handling to use the canvas until right below the texts. (ETA, 3-4h, today) 5-6 PM Arizona Time

I would also appreciate it if you could send the file, I am not that creative (for closet designs), and if you have any interesting file/project you want to share I thank you!

**Comment by nailsonlandim** [comment]
Hi @kategodfrey ,

![image](https://user-images.githubusercontent.com/70038700/103310674-eeac8c00-49f6-11eb-9b79-68d9496c4274.png)

These glitches are due to the blender render (specifically Freestyle renderer). I think @AntonioGloria could explain it better.

Unfortunately, we can't do much to fix it. unless Antonio has something in his hat.

**Comment by kategodfrey** [comment]
> 
> > The closet components are layered when there are uppers and lowers.
> 
> Are you referring to the text?
> ![image](https://user-images.githubusercontent.com/70038700/103310126-a17bea80-49f5-11eb-9e71-428dd210e8dd.png)
>   **Yes, the text is stacked and hard to read**
> > The ceiling height is hidden under the left corner (Job Name, Job Number, Install Date...)
> 
> I can adjust the 2D view image handling to use the canvas until right below the texts. (ETA, 3-4h, today) 5-6 PM Arizona Time
> **Great thank you!**
> I would also appreciate it if you could send the file, I am not that creative (for closet designs), and if you have any interesting file/project you want to share I thank you!
**Yes I can do that for you. I will create a subfolder in the one I shared with you the other day that will have closet designs. I have put my file in it of the project above, it's called "countertest." **

https://drive.google.com/drive/folders/1QxfCLpfCkLOux5RXor4cWOdUw9YZ1acN?usp=sharing

**Comment by nailsonlandim** [comment]
Hi @kategodfrey 

I need permission to access the folder. Thanks!

**Comment by AntonioGloria** [comment]
Hi @kategodfrey,
 
> These glitches are due to the blender render (specifically Freestyle renderer). I think @AntonioGloria could explain it better.
> Unfortunately, we can't do much to fix it

@nailsonlandim is correct. This glitch is related to orthographic views and to the fact that many objects are meeting or intersecting at those spots.

**Comment by kategodfrey** [comment]
@nailsonlandim @AntonioGloria Ok that makes sense. It's no big deal!

and @nailsonlandim can you give me your email address so I can give you access?

**Comment by nailsonlandim** [comment]
> @nailsonlandim @AntonioGloria Ok that makes sense. It's no big deal!
> 
> and @nailsonlandim can you give me your email address so I can give you access?

nailson.landim@bairesdev.com

**Comment by kategodfrey** [comment]
Great. You should be able to open it now!

**Comment by nailsonlandim** [comment]
Hi @kategodfrey 

I fixed the issue on countertops. Now it shows correctly it.

**Comment by kategodfrey** [comment]
I can see the line now connects👍, but the list of closet components are still stacked in that third opening with the hamper.

![image](https://user-images.githubusercontent.com/63115502/103317594-db92bf80-49e8-11eb-86e0-3acd43bb7f55.png)

**Comment by kategodfrey** [comment]
And we want that dotted line to be solid.

**Comment by nailsonlandim** [comment]
> I can see the line now connects👍, but the list of closet components are still stacked in that third opening with the hamper.
> 
> ![image](https://user-images.githubusercontent.com/63115502/103317594-db92bf80-49e8-11eb-86e0-3acd43bb7f55.png)


> And we want that dotted line to be solid.

I am working on it right now. As soon as I have it I'll push and tell you. 
I wanted to push it so you can have it faster. Sorry for any inconvenience,

**Comment by kategodfrey** [comment]
All good! Just didn't want to forget about it. Thank you!!

**Comment by nailsonlandim** [comment]
Hi @TedCC1209 

I've fixed the PV labels issue.

![PV_labels](https://user-images.githubusercontent.com/70038700/103382976-cd6b9e80-4acf-11eb-8af8-fce44f9b44d8.png)

It's available at https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23241-exp-annotation-hash-mark

At this very moment, Antonio and I are working on the solid lines. 

Correct me if I am wrong, but for now, those dashed lines means that the upper is overlapping the countertop and that's not the case.

**Comment by TedCC1209** [comment]
> Correct me if I am wrong, but for now, those dashed lines mean that the upper is overlapping the countertop and that's not the case.

Yes they are overlapping but from this view the TS would be in front of/on top of the CT

**Comment by nailsonlandim** [comment]
Hi @TedCC1209 @kategodfrey 

The reason why dashed lines occur is that at Plan View the upper is positioned inside the other opening. And right now the TS is under the openings. 

![image](https://user-images.githubusercontent.com/70038700/103542975-8806f280-4e7c-11eb-9e65-0af43354450a.png)

So the rendered image is this:

![image](https://user-images.githubusercontent.com/70038700/103541676-8a684d00-4e7a-11eb-9dc6-70bba56f1fbe.png)

If I manually place the CTOP and uppers... (an experiment) 

![image](https://user-images.githubusercontent.com/70038700/103543558-7d992880-4e7d-11eb-9b17-861ca6e03c33.png)

The rendered image is this: 

![image](https://user-images.githubusercontent.com/70038700/103543638-a3bec880-4e7d-11eb-9164-fdd018129c22.png)

Is there any particular reason to create these cages like this @RyanMDev @ClassyTeddy

**Comment by sarahhightower** [comment]
Tested and all of the above mentioned issues (besides the dotted lines and overlapping height/text) appear correctly in my test. 

![Test Image](https://user-images.githubusercontent.com/72047269/103545915-7bc06c80-4e5f-11eb-996f-221e16d4aba0.JPG)
