### ISSUE TITLE
2D Views: Add Filler Annotation

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#243]
We need to add a filler annotation when a filler is present--width of filler should be on top line with the word filler on a second line below, center justified text and centered below the filler on the same level/line as the opening width dimensions. See the following example:

![Filler annotation](https://user-images.githubusercontent.com/61025894/102799101-456af380-436f-11eb-8f25-f460664992a9.png)

**Comment by nailsonlandim** [comment]
Got it @TedCC1209  
One question, It`s needed the just the filler amount or do you need also the deduction (if there is any) 

![image](https://user-images.githubusercontent.com/70038700/102817688-0197de80-43af-11eb-9956-dcb57d64c1eb.png)

**Comment by nailsonlandim** [comment]
Hi @TedCC1209 ,

Done.

![image](https://user-images.githubusercontent.com/70038700/102827199-e504a200-43c0-11eb-9fa1-19eda654ae01.png)

Available at: https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23243-add-filler-annotation

**Comment by TedCC1209** [comment]
Just the filler is good. The placement on your examples looks great.

**Comment by kategodfrey** [comment]
Looks good.

[filler2D Views.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5732307/filler2D.Views.pdf)

**Comment by TedCC1209** [comment]
The filler annotation looks good, thank you Nailson.

A little concerned about the following though, which issue @kategodfrey also ran into on this branch--after labeling and hitting "Prepare 2D Views" and while selecting which views we wanted prior to selecting "Render Selected Scenes" we got the following error and green objects:

![Filler Branch Error](https://user-images.githubusercontent.com/61025894/103008575-93f4cb00-44f2-11eb-8031-c44d1d6bc085.png)

![image](https://user-images.githubusercontent.com/61025894/103008720-cd2d3b00-44f2-11eb-8008-cb42a1897dec.png)

This did not happen all the time though, and I couldn't figure out when exactly it would occur (my error came on an older/existing project but I also didn't run into the issue on other older/existing projects...not sure what @kategodfrey 's situation was).

**Comment by nailsonlandim** [comment]
I`ll check that error. Thanks for sharing the error messages, they have the information I need.

**Comment by sarahhightower** [comment]
Filler looks good to me as well. I did not encounter the same error as Katie.

**Comment by TedCC1209** [comment]
@nailsonlandim this didn't come up in our meeting today, but a reminder to look into the issue @kategodfrey and I ran into with the error and green walls

**Comment by nailsonlandim** [comment]
Can you or @kategodfrey share the file? that would speed up the bug-catching process.

**Comment by SeanRadvan** [comment]
So i was able to replicate this error i think. From what i can tell it
happens if a room has previously been rendered, clearing 2d views from the
drop down seems to stop it, but it should probably clear 2d views when
opened.

**Comment by kategodfrey** [comment]
https://drive.google.com/drive/folders/1QxfCLpfCkLOux5RXor4cWOdUw9YZ1acN?usp=sharing

@nailsonlandim let me know if I need to give you access to this folder. My blend file for this error is the only file in the folder right now.

**Comment by nailsonlandim** [comment]
Hi @TedCC1209 @kategodfrey

Fixed.

Available at: https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23243-add-filler-annotation

**Comment by TedCC1209** [comment]
Thanks Nailson! I don't think the was related to your fixes in this branch so thank you for taking care of it anyway :) It now acts like I thought it acted in the past (with it just adding the image files when hitting render again rather than coming up with the error and turning the room green).
