### ISSUE TITLE
Flat Crown Overhang

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#247]
Right now Flat Crown overhang defaults to 1.25" (this measures from the front of the crown so the 1.25" overhang is the 0.75" thickness of the crown plus 0.5" topshelf overhang).

Can we change a few things on this please?

1. Can we have the measurement be from the back of the crown so it doesn't add the extra 0.75" thickness of the crown (the current default would then be 0.5" instead of 1.25")
2. Can we have it be that when you place the crown it determines whether top shelf is present or not--if topshelf is present, have the flat crown overhang default to the topshelf overhang that exists and if topshelf is not present, have no overhang so that the back of the crown is flush with the partitions/top KDs?

Thanks, 

Ted

**Comment by ClassyTeddy** [comment]
> Can we have it be that when you place the crown it determines whether top shelf is present or not--if topshelf is present, have the flat crown overhang default to the topshelf overhang that exists and if topshelf is not present, have no overhang so that the back of the crown is flush with the partitions/top KDs?

So we have two major options here. We can have it detect to see if there is a topshelf upon placement of the flat crown and adjust the value of `Front Overhang` to change only upon placement (Meaning that the Flat crown will not automatically adjust with the top shelf, nor vice versa) This would be fairly easy and all I would really need to do is find a way to check and see if top shelf is present. 

The other option is to have it be more dynamic, which would include the flat crown front overhang adjusting when the topshelves front overhang is adjusted and vice versa. This type of dynamic adjustment of values is definitely possible, it will just take a lot longer to accomplish.

While the second option is definitely better, I don't know if it is currently necessary, and can probably be tackled at another time, but if you would like me to try and get it done now, I can.

@TedCC1209 Your thoughts on this would be appreciated.

**Comment by ClassyTeddy** [comment]
> Can we have it be that when you place the crown it determines whether top shelf is present or not--if topshelf is present, have the flat crown overhang default to the topshelf overhang that exists and if topshelf is not present, have no overhang so that the back of the crown is flush with the partitions/top KDs?

So we have two major options here. We can have it detect to see if there is a topshelf upon placement of the flat crown and adjust the value of `Front Overhang` to change only upon placement (Meaning that the Flat crown will not automatically adjust with the top shelf, nor vice versa) This would be fairly easy and all I would really need to do is find a way to check and see if top shelf is present. 

The other option is to have it be more dynamic, which would include the flat crown front overhang adjusting when the topshelves front overhang is adjusted and vice versa. This type of dynamic adjustment of values is definitely possible, it will just take a lot longer to accomplish.

While the second option is definitely better, I don't know if it is currently necessary, and can probably be tackled at another time, but if you would like me to try and get it done now, I can.

@TedCC1209 Your thoughts on this would be appreciated.

**Comment by ClassyTeddy** [comment]
> Can we have it be that when you place the crown it determines whether top shelf is present or not--if topshelf is present, have the flat crown overhang default to the topshelf overhang that exists and if topshelf is not present, have no overhang so that the back of the crown is flush with the partitions/top KDs?

So we have two major options here. We can have it detect to see if there is a topshelf upon placement of the flat crown and adjust the value of `Front Overhang` to change only upon placement (Meaning that the Flat crown will not automatically adjust with the top shelf, nor vice versa) This would be fairly easy and all I would really need to do is find a way to check and see if top shelf is present. 

The other option is to have it be more dynamic, which would include the flat crown front overhang adjusting when the topshelves front overhang is adjusted and vice versa. This type of dynamic adjustment of values is definitely possible, it will just take a lot longer to accomplish.

While the second option is definitely better, I don't know if it is currently necessary, and can probably be tackled at another time, but if you would like me to try and get it done now, I can.

@TedCC1209 Your thoughts on this would be appreciated.

**Comment by ClassyTeddy** [comment]
> Can we have it be that when you place the crown it determines whether top shelf is present or not--if topshelf is present, have the flat crown overhang default to the topshelf overhang that exists and if topshelf is not present, have no overhang so that the back of the crown is flush with the partitions/top KDs?

So we have two major options here. We can have it detect to see if there is a topshelf upon placement of the flat crown and adjust the value of `Front Overhang` to change only upon placement (Meaning that the Flat crown will not automatically adjust with the top shelf, nor vice versa) This would be fairly easy and all I would really need to do is find a way to check and see if top shelf is present. 

The other option is to have it be more dynamic, which would include the flat crown front overhang adjusting when the topshelves front overhang is adjusted and vice versa. This type of dynamic adjustment of values is definitely possible, it will just take a lot longer to accomplish.

While the second option is definitely better, I don't know if it is currently necessary, and can probably be tackled at another time, but if you would like me to try and get it done now, I can.

@TedCC1209 Your thoughts on this would be appreciated.

**Comment by TedCC1209** [comment]
Let's go with the first option. Thanks Teddy

**Comment by ClassyTeddy** [comment]
This should be ready for testing on the `Flat-Crown-Overhang-Adjustments` branch.

**Comment by sarahhightower** [comment]
Tested and worked great for me. Thanks!

**Comment by TedCC1209** [comment]
Thanks Teddy, this is looking good. One thing is about returns showing a mitered look. Here is what you had fixed in https://github.com/CCDevNelson/Snap-Updates/issues/148 and the following bullet:

- The returns are now extended and clip with the front in order to make it appear mitered and to not reveal core

It looks like this isn't happening anymore:

![FC returns](https://user-images.githubusercontent.com/61025894/103236051-ef62f680-4900-11eb-852e-8f33cbb35539.png)

This will affect the XML export as well if it isn't adding the additional length on the returns.

Otherwise this is looking good.

**Comment by ClassyTeddy** [comment]
Ah, the returns aren't being adjusted using the new overhang calculation (from the back instead of the front). I will tackle it once I finish the backing issue.

**Comment by ClassyTeddy** [comment]
This is ready for testing on the `Flat-Crown-Overhang-Adjustments` branch.

**Comment by TedCC1209** [comment]
Still seeing the core of the material when I have returns (in all scenarios I could try--to ceiling, not to ceiling, etc). Also, it recognizes when there is top shelf present but seems to just add what the "Extend Front" amount is from the topshelf rather than looking to see what the depth of the particular top shelf is in determining the location of the FC. See as follows for both these items (left opening is 12" deep, middle opening 16" deep, and right opening 12" deep):

![FC TS](https://user-images.githubusercontent.com/61025894/103539437-4d3d9400-4e55-11eb-8c7f-847915caed5e.png)

**Comment by ClassyTeddy** [comment]
I can keep looking into the returns and the core issue, but the second issue you brought up about placement will be a bit trickier. I will start by having flat crown adjust the front overhang prompt on placement based on the top shelf depth like you suggested

**Comment by ClassyTeddy** [comment]
This should be ready for testing on the `Flat-Crown-Overhang-Adjustments` branch.

**Comment by TedCC1209** [comment]
Looks good to me, thank you Teddy

**Comment by sarahhightower** [comment]
In my test the core of the material was no longer available and the crown recognized the top shelf depth. Thanks! 

I also tested using KDs and then applying flat crown. The flat crown was automatically placed in the location of the deepest partition and did not recognize that the KD was a shallower depth.  Is it possible to have the flat crown recognize the KD depth for placement? Thanks! 

![Visual](https://user-images.githubusercontent.com/72047269/103668650-8ef13c00-4f34-11eb-88b5-e8f9fc67b8ec.JPG)

**Comment by TedCC1209** [comment]
> I also tested using KDs and then applying flat crown. The flat crown was automatically placed in the location of the deepest partition and did not recognize that the KD was a shallower depth. Is it possible to have the flat crown recognize the KD depth for placement? Thanks!
> 
> ![Visual](https://user-images.githubusercontent.com/72047269/103668650-8ef13c00-4f34-11eb-88b5-e8f9fc67b8ec.JPG)

Good catch @sarahhightower -- Yes, when there is no topshelf the flat crown should be the depth of the opening and not the depth of the left partition clicked. @ClassyTeddy is that a straight forward fix?

**Comment by ClassyTeddy** [comment]
Yes and no. It depends on how we want it to function. It would be fairly complicated to have the flat crown automatically adjust to the lowest depth found in between the panels selected due to the fact that flat crown currently only knows the depths of the panels you select.

 If we want it to select the smaller panel of the two panels selected, that would be fairly simple.

And it is not possible to have it automatically place flat crown at multiple different depths. You have to place a new flat crown for each depth.

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Flat-Crown-Overhang-Branch`

**Comment by TedCC1209** [comment]
Looks to be acting correctly as far as seeing TS, etc.

Looks like returns needs to have 0.75" added to the back as they stop short of the going all the way to the back of the partition:

![extend returns](https://user-images.githubusercontent.com/61025894/103684195-6a06c400-4f48-11eb-95a2-085725dfde8d.png)

**Comment by ClassyTeddy** [comment]
A fix for that is now ready for testing on `Flat-Crown-Overhang-Adjustments`

**Comment by TedCC1209** [comment]
Looks good, thank you Teddy!

**Comment by sarahhightower** [comment]
Tested and worked great. Thanks!
