### ISSUE TITLE
Lakeshore Oak - Available from both CL and SALT

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#25]
Need to clarify that Lakeshore Oak is available as CL and S materials. I think this may have been confusing, though info for both are in the spreadsheet/csv.

In SNaP, currently only S Lakeshore Oak is available as edgebanding while CL Lakeshore Oak is not:

![image](https://user-images.githubusercontent.com/61025894/77782508-9f26d300-7014-11ea-974d-be2e42181dcf.png)

Both S Lakeshore Oak and CL Lakeshore Oak are available as 3/4" material to choose from in SNaP, but the S Lakeshore Oak needs to be moved from the regular melamine drop down to the textured melamine dropdown:

![image](https://user-images.githubusercontent.com/61025894/77782590-bfef2880-7014-11ea-984b-2436fee4136d.png)

![image](https://user-images.githubusercontent.com/61025894/77783448-1f016d00-7016-11ea-8562-014e9a6bf1ff.png)

**Comment by TEDSTANDAGE** [comment]
Sorry, missed the screenshot of the S Lakeshore Oak available in the regular melamine dropdown:

![image](https://user-images.githubusercontent.com/61025894/77783639-730c5180-7016-11ea-8664-ffedc0f985c5.png)

**Comment by CCDevNelson** [comment]
CL Lake Shore Oak was previously a Metro color.
Brock forgot to change the Metro Lake Shore Oak to CL Lake Shore Oak. He has now done that and is sending you a new list.

**Comment by TEDSTANDAGE** [comment]
Just spoke with Brock. The info (SKU, etc.) is already in the spreadsheet under M instead of CL, so Brock isn't sending a new list. We just need to change M to CL. 

Also, I don't think this item should be closed because S Lakeshore Oak still needs to be moved from the melamine to textured melamine drop down, and the CL Lakeshore Oak edgebanding still needs to be added.
