### ISSUE TITLE
Capping Filler option

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#253]
We should add the option for a capping filler--this is where there is a regular flush inset filler like is currently available and then a piece of molding is placed on top of the filler and overlapping the front of the adjacent partition 1/4". The height of the capping filler is sized like a door and the width should be oversized. The capping filler would be edged 1L/2S (1 height length and both width lengths)

**Comment by JJanneh** [comment]
Option-to-edge-bottom-edge branch
![Screenshot (74)](https://user-images.githubusercontent.com/76751383/104778071-ffb90500-5739-11eb-97d3-528127f31ee8.png)

**Comment by JJanneh** [comment]
Capping-Filler-Option Branch
![Capping_Filler](https://user-images.githubusercontent.com/76751383/105411624-da703f00-5bf0-11eb-861c-524ace5a5dfd.PNG)

**Comment by JJanneh** [comment]
CheckBox Option
![Capping_Filler_Check_Box](https://user-images.githubusercontent.com/76751383/105412069-71d59200-5bf1-11eb-8edb-5a35e6b0d11c.PNG)

**Comment by JJanneh** [comment]
Check box option for Left & Right Capping Filler with a drop down menu to enter value.
![Screenshot (118)](https://user-images.githubusercontent.com/76751383/106511174-1c20a580-648d-11eb-8b7f-cc702b099fb7.png)

**Comment by TedCC1209** [comment]
@JJanneh , the capping filler should just be a check box, it doesn't need to be an amount. You can have them say "Add Capping Left Filler" and "Add Capping Right Filler" respectively.

**Comment by JJanneh** [comment]
Changed to Checkbox and renamed to Add Capping Left Filler" and "Add Capping Right Filler
![Add Capping L   R Filler](https://user-images.githubusercontent.com/76751383/106517552-e207d180-6495-11eb-99b4-fa57ae01ca13.PNG)

**Comment by TedCC1209** [comment]
@JJanneh like we talked this morning, please remember that the capping option shouldn't show up until an amount other than 0 is entered into the L/R fillers respectively.

When it is selected then a melamine capping filler needs to be placed into the scene. Reiterating some things in the OP but adding a bit more:

It needs to cap the filler and front of the adjacent partition (making it flush with any doors or fronts in the adjacent opening). It should overlap the outside partition by 1/4" and then width-wise it goes to the outside edge of the filler (i.e., a 2" filler would have a 2.25" wide capping filler on it), then the height is sized like a door for the partition size. The capping filler would be edged 1L/2S (1 height length and both width lengths).

**Comment by JJanneh** [comment]
@TedCC1209 @TylerStandage Capping-Filler-Option Branch Ready to Test
![Capping_Right_Filler](https://user-images.githubusercontent.com/76751383/108272077-fe12a080-712e-11eb-873f-c8c57aaccb75.PNG)

**Comment by TylerStandage** [comment]
@JJanneh thanks, this looks good to me.  I've noted the size and location of the cap in the image below.  Moving to testing. @TedCC1209 let me know if this looks good to go from your perspective. 

![image](https://user-images.githubusercontent.com/77167318/108283648-85184680-7138-11eb-96f1-61486b00fe38.png)

**Comment by ClassyTeddy** [comment]
I do know that this issue is not totally good to go, but we would like input to make sure that the sizing is correct. We do still need to add edge banding logic and edge banding to the scene.

**Comment by TylerStandage** [comment]
The sizing is correct as far as I can tell.  @ClassyTeddy @JJanneh is the edgebanding piece the work you're discussing on #272 or is that separate?

**Comment by ClassyTeddy** [comment]
According to Ted
> The capping filler would be edged 1L/2S (1 height length and both width lengths).

Currently, this isn't the case, both in the scene and on the export for the capping filler

**Comment by TylerStandage** [comment]
@ClassyTeddy @JJanneh sounds good.  You're good to go on the sizing. Just need to do the edge banding. Thanks!

**Comment by JJanneh** [comment]
@TylerStandage Capping-Filler-Option Branch Ready to Test

**Comment by TylerStandage** [comment]
Hi @JJanneh , I still see that the long and two short edges aren't edge banded.  I'm on the capping-filler-option branch. Is that the right one? 

![image](https://user-images.githubusercontent.com/77167318/108574991-b1190080-72cd-11eb-96d5-c3412b50639d.png)

**Comment by TylerStandage** [comment]
@JJanneh I see now that it has been updated on the option-to-edge-bottom-edge branch.  Looks good to me!  @TedCC1209 can you confirm. I'll look at the xml export next week as well.  Thanks!!

**Comment by TedCC1209** [comment]
This looks good to me, tested in the Option-to-edge-bottom-edge branch. Thanks @JJanneh
