### ISSUE TITLE
3/4 backing incorrectly displaying

### ISSUE THREAD

**Issue by SeanRadvan** [CCDevNelson/Snap-Updates#254]
![Backing](https://user-images.githubusercontent.com/54151330/103013323-2e0c4180-44fa-11eb-9e64-01448dbc8167.jpg)
On multi pards it appears that the left most opening always displays the 3/4 in backing differently from other openings with 3/4 backing. Tested on multiple opening sizes, upper / lower and changing order in which ones are enabled first, appears to be happenign in all. Unknown if it is affecting any data or is purely cosmetic.

**Comment by ClassyTeddy** [comment]
It appears that it just isn't removing the cleat and cover cleat objects on the first opening when 3/4" backing is selected. I will look into it after I finish the current issue with flat crown I am working on.

**Comment by TedCC1209** [comment]
Was it the changes about cleat not being drawn in 2D that caused this? https://github.com/CCDevNelson/Snap-Updates/issues/226 . Just a thought. Please don't spin your wheels on this too long Teddy, we have too many other pressing issues for you to address. If you're unable to get it, please ask Ryan to look into it and move onto other items. This can just be a known glitch for now. Thanks, Ted

**Comment by ClassyTeddy** [comment]
I figured out the problem, just working on a solution. The hutch backing is being considered a backing that needs to have a cleat, so I need to find a way to change some of it's variables when the first opening is made 3/4", but I also need to make sure that it doesn't change the thickness of the hutch backing. I should have this done soon.

**Comment by ClassyTeddy** [comment]
This is ready for testing on the `master` branch.

**Comment by SeanRadvan** [comment]
Tested, looking good.

**Comment by TedCC1209** [comment]
Tested and the 1st opening issue looks fine. However, after extending the hutch partitions and putting on a hutch back, I tried to open the Construction Options in the partition prompts and they wouldn't open and when I tried to make changes in the Opening Sizes prompts for the partitions nothing worked and errors popped up when I exit the partitions prompts. Here are some of the errors I have gotten:

![Hutch errors](https://user-images.githubusercontent.com/61025894/103379628-7f40a600-4aa3-11eb-8c05-664fbd50cb35.png)

![Hutch errors2](https://user-images.githubusercontent.com/61025894/103379632-81a30000-4aa3-11eb-97a2-9dff87256bf8.png)

**Comment by TedCC1209** [comment]
The above errors look to only occur when I have a capping bottom on

**Comment by ClassyTeddy** [comment]
A fix for the above error should be ready for testing on the `master` branch

**Comment by TedCC1209** [comment]
Looks good, thanks Teddy

**Comment by sarahhightower** [comment]
Tested and worked well for me.
