### ISSUE TITLE
2D Views: Fix allowable areas for images/views

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#260]
This is a priority item that I believe @nailsonlandim can address quickly. We need to restrict plan and elevation views from overlapping items on the Legend or from eachother. There needs to be a small buffer:

![overlaps](https://user-images.githubusercontent.com/61025894/103544627-a01b4980-4e5d-11eb-8b9f-ac975cd0a5f7.png)

**Comment by nailsonlandim** [comment]
Hi @TedCC1209 

Fixed the overlapping. 

![image](https://user-images.githubusercontent.com/70038700/103579717-91fa1700-4eb7-11eb-9db2-771b405e2934.png)

![image](https://user-images.githubusercontent.com/70038700/103579910-fa48f880-4eb7-11eb-8db0-b995a0832149.png)

![image](https://user-images.githubusercontent.com/70038700/103580187-7ba08b00-4eb8-11eb-8a15-79c4f477a87b.png)

![image](https://user-images.githubusercontent.com/70038700/103580333-c6220780-4eb8-11eb-9d6d-fd5488d140e5.png)

Fix available at: https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23260-fix-image-areas

**Comment by TedCC1209** [comment]
Awesome, thank you Nailson. 

@sarahhightower @kategodfrey

**Comment by sarahhightower** [comment]
Looks good to me. Thanks!

**Comment by kategodfrey** [comment]
Looks good!

![image](https://user-images.githubusercontent.com/63115502/103668889-e099c680-4f34-11eb-8593-d9e6b15d2ce3.png)
