### ISSUE TITLE
2D Views: Some labels not clearing

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#261]
It seems certain labels aren't clearing out after clearing all 2D views and re-labeling a scene. It'd be nice if there were a "clear all labels" option or something so that the user knows they are starting out clean (if there is already one and I am just dumb for not knowing, please let me know). For this following example, there may be an issue with CT and flat crown specifically, but the old partition height also remains and overlaps the new partition height which should be the same height as the partition capping the left side of CT:

![not removing](https://user-images.githubusercontent.com/61025894/103545220-80d0ec00-4e5e-11eb-8b21-b9aa340c2d30.png)

**Comment by TedCC1209** [comment]
Also, when I re-do labels, many labels just seem to be added on top of old ones which then makes the labels extra dark because (I assume) of the multiple layers on top of each other

**Comment by nailsonlandim** [comment]
Hi @TedCC1209 

We fixed it by clearing and hiding unnecessary hashmarks and texts.

It's available at: https://github.com/nailsonlandim/SNaP-Dev/tree/master

It also includes the hotfix.
