### ISSUE TITLE
Capping Bottoms: Force Bottom KD

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#263]
For capping bottoms, we need to force bottom KDs for the openings the capping bottom covers. This is not priority

**Comment by JJanneh** [comment]
@TedCC1209 @TylerStandage @ClassyTeddy Currently forcing bottom KDs for the openings the capping bottom covers.

**Comment by TylerStandage** [comment]
Hi @JJanneh, this looks good!  Moving to ready for testing to let @TedCC1209 confirm.

**Comment by TedCC1209** [comment]
The forced bottom KDs look good, thank you @JJanneh .

But now the capping bottoms look to be being incorrectly placed under hutched L/R partitions (extended down partitions) rather than being up against where the bottom KDs would be placed and inset between the hutched partitions. This may be because of the new prompt menus?

Correct capping bottom placement (how it currently is in the Master branch) in a hutch situation:

![Capping BOttom COrrect](https://user-images.githubusercontent.com/61025894/110383546-ab375500-8019-11eb-9546-299684c91a5a.png)

Incorrect capping bottom placement in this branch:

![Capping BOttom Incorrect](https://user-images.githubusercontent.com/61025894/110383762-fd787600-8019-11eb-8248-68707c3879fe.png)

**Comment by JJanneh** [comment]
@TedCC1209 @TylerStandage @ClassyTeddy Thanks. Issue with the bottom KDs placed and inset between the hutched partitions error corrected.
Ready for Testing **Force-Bottom-KD** Branch

**Comment by TedCC1209** [comment]
This looks good as well, thanks @JJanneh
