### ISSUE TITLE
Need to adjust the cover cleat export logic

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#264]
Braeden is testing the pricing program which goes off the XML which may bring up more of these types of issues, but currently the program is exporting too much cover cleat.

The following job has one opening 16.5" wide--meaning only 33" worth of cover cleat is needed:

![cover cleat test](https://user-images.githubusercontent.com/61025894/103794870-7ea79280-5002-11eb-8760-de9ba029f8db.png)

Three full 96" lengths of cover cleat were exported with the job, however, when one length would suffice.

I honestly don't remember what the cover cleat export logic is right now, but let's do the following to determine the amount of cover cleat needed for a job:

Add up all the opening widths in the closet. If the closet is white or almond, multiply that number by two (if a different color, don't multiple it by anything). If that amount is 80" or less then export one length of cover cleat to the XML with no extra lengths provided. If it is more than 80", divide the number by 96 then round up to the nearest whole number to get the number of lengths needed. If it is 1-3 lengths, add one extra length to the XML export. If it is 4 or more lengths, add two extra lengths.

Let me know if this makes sense or not @ClassyTeddy.

Thanks, 

Ted

**Comment by ClassyTeddy** [comment]
It makes sense Ted but that is exactly how the cover cleat should be exporting already. The only difference is I cant add up all the opening widths. Instead, whenever I find a cover cleat when exporting, it should add the length fo the cover cleat to a consistent number. Then, after every other part has been exported, I divide the number by 2, check to see if it is white or almond, then I do the rest of the logic to determine how many pieces need to be exported.

**Comment by TedCC1209** [comment]
@ClassyTeddy can you get this one done this morning and do a pull request please?

**Comment by ClassyTeddy** [comment]
I can take a look, but I don't know if i can get it done quickly. I'll do my best to get it done quickly

**Comment by ClassyTeddy** [comment]
This is ready for testing on the `Cover-Cleat-Export-Logic` branch. I tested it myself and I believe it is good to go, but I would like an extra pair of eyes.
A couple of things of note, I still left a lot of the logic intact, let me just quickly run through what it is

1. I get the length of every cover cleat part
2. I add all the lengths together
3. I check to see if it is 80 inches or less, if it is, I set the needed full lengths to 1 and skip to step 7
4. If it is greater than 80 inches, I get the needed full lengths by dividing the total length by 96, then by 2
5. I then check the material, if it is white or almond, I double the number of needed lengths
6. I then check my number of needed lengths to add extra
        If I have 2, I add one
        If I have 3, 4, or 5, I add two
        If I have 6 or greater, I add three
7. I then export the needed number of full lengths

**Comment by TedCC1209** [comment]
> 4. If it is greater than 80 inches, I get the needed full lengths by dividing the total length by 96, then by 2
> 5. I then check the material, if it is white or almond, I double the number of needed lengths

When it is white or almond, can you have it double the total length before determining the total needed lengths, rather than doubling the number of lengths needed? Let me know if that makes sense--when you double the needed lengths rather than the total length of cover cleat before determining the needed lengths, it exaggerates leftover material.

**Comment by ClassyTeddy** [comment]
Hey Ted. That makes sense, I'll change it from how it was set up before.

**Comment by ClassyTeddy** [comment]
That does make sense, however, we set it up like this because of how the cover cleat length is retrieved. I get the length of **each** cover cleat. 

So in your example, you say this:
> Add up all the opening widths in the closet. If the closet is white or almond, multiply that number by two 

So, I don't add up all the opening widths, I add each cleat length. So it basically is already multiplied by 2. Which is why I divide by 96, and then divide by 2, because we split the cover cleats. However, we don't split them if they are white or almond (because we have the quarter inch material), so I then multiply by 2 to correct the dividing by 2. After all the multiplying and dividing, I then round the number, and check for extra needed length.

If this is still wrong let me know, but as far as I know the math is all good on it.

**Comment by TedCC1209** [comment]
After our phone convo and your moving that one line so that it determines the needed lengths after multiplying by two for white/almond, it looks to be working good now. Thanks
