### ISSUE TITLE
2D Views Labels not appearing

### ISSUE THREAD

**Issue by ClassyTeddy** [CCDevNelson/Snap-Updates#265]
> I performed two tests on the Master branch because I thought I might have forgot to reopen SNaP after I loaded SNaP defaults. The second test, with a new design, shows similar errors to the first time. I’ve attached the 2D design plan and noted the errors I see below;
1. All partition and Top Shelf dashes are missing
2. All pard sizes are missing
3. Toe Kick size is not noted
4. The shelves that are behind the doors are not visible.
5. Ceiling height/closet height/dresser height missing on elevations
6. Plan view and elevation views are missing wall labels (A, B, C, etc)
7. Plan view is missing component notations
8. Plan view is missing wall lengths and ceiling height

I am not positive, but I believe that the issue might stem from the following commit:
https://github.com/CCDevNelson/SNaP-Dev/commit/48c9fdbc17b304023cc24d90a8896f2b92cb8aa7

This was the pull request for the main 3d labels branch. There appears to be a conflict between the 3d labels branch, and one of the other two branches that were merged yesterday, which were the `issue_#241-exp-annotation-hash-mark` and the `issue_#239-dimensions-needs-inch-mark` branches.

I am unsure if this is relevant, but when the glitch happens, this pops up in the terminal (the area in-between * is what disappears when the commit is reverted and the parts appear properly labeled again):
```
DAG zero... not allowed to happen!
Saved: 'C:\Users\roy99\AppData\Local\Temp\blender_a17584\Plan View.jpg'
 Time: 00:00.28 (Saving: 00:00.11)

******************
Warning: edge 8 - 10 appears twice, correcting
Warning: edge 10 - 0 appears twice, correcting
Warning: edge 0 - 1 appears twice, correcting
Warning: edge 1 - 0 appears twice, correcting
Warning: edge 10 - 8 appears twice, correcting
Warning: edge 8 - 0 appears twice, correcting
Warning: edge 0 - 10 appears twice, correcting
Warning: edge 9 - 11 appears twice, correcting
Warning: edge 1 - 9 appears twice, correcting
Warning: edge 11 - 9 appears twice, correcting
Warning: edge 9 - 1 appears twice, correcting
*******************

Error: strokes set empty
Saved: 'C:\Users\roy99\AppData\Local\Temp\blender_a17584\Wall B.jpg'
 Time: 00:00.43 (Saving: 00:00.07)

<!> event has invalid window
```

@nailsonlandim @AntonioGloria Here is a GitHub issue for better organization.

**Comment by ClassyTeddy** [comment]
Hey @nailsonlandim, I just tested https://github.com/CCDevNelson/SNaP-Dev/tree/hotfix and I am still not seeing all the labels. I am currently only making a 2D view report for one partition and door, but I don't see the partition height.

**Comment by TedCC1209** [comment]
The hotfix looks to be working, thanks Nailson. @sarahhightower can you test it too please to verify?

The only thing I might say is that the font for the partition heights on the elevations is very small, smaller than I remember them being, but perhaps I overlooked it before. Thoughts @kategodfrey @sarahhightower?

![image](https://user-images.githubusercontent.com/61025894/103907138-1cac6300-50be-11eb-8f7d-eca98501fa47.png)

**Comment by TedCC1209** [comment]
@ClassyTeddy can we get this merged with the master so we can test its compatibility there?

Thanks, 

Ted

**Comment by ClassyTeddy** [comment]
It has been merged and master is ready for testing.
