### ISSUE TITLE
TL Oxford White not exporting correctly.

### ISSUE THREAD

**Issue by SeanRadvan** [CCDevNelson/Snap-Updates#268]
When Braden was checking jobs in the pricing software, he received and error that went away when he switch the color of the snap job off of TL Oxford White.  I was able to replicate the error and confirm the software was working correctly with other colors, so I dont believe its anything on that end.  I confirmed "tl oxford white" exists in the csv, but in the xml the color was coming out as "TL oxford."

**Comment by TedCC1209** [comment]
Thanks Sean. 

He's using the current user version correct? Was the XML he was testing from his version or was the XML sent from someone else? And if it was from someone else, what version were they using?

Then, was the error he was receiving on the pricing software or on SNaP?

I just exported a job from SNaP in TL Oxford White and it correctly came out as TL Oxford White in the XML:

![TL Oxford White](https://user-images.githubusercontent.com/61025894/104058040-5fe6fe80-51b0-11eb-8c68-0ec9b394940f.png)

Thanks, 

Ted

**Comment by TedCC1209** [comment]
The edgebanding name also correctly states TL Oxford White:

![edgebanding](https://user-images.githubusercontent.com/61025894/104058421-ebf92600-51b0-11eb-943b-c6de8eb6cec2.png)

If there is a different output name for TL Oxford White that needs to be in the XML, we can make that change, we just need to know what it needs to be. Thanks, Ted

**Comment by CCDevNelson** [comment]
Ted, Looking through the XML (and I just spotted this in your pic above) but the edgeband2sku is "Unknown". This was a problem awhile back that we were having. But this should be a SKU number passed here. "Unknown" is not in the csv file, thus it causes an error.

**Comment by TedCC1209** [comment]
> Ted, Looking through the XML (and I just spotted this in your pic above) but the edgeband2sku is "Unknown". This was a problem awhile back that we were having. But this should be a SKU number passed here. "Unknown" is not in the csv file, thus it causes an error.

Thanks and good catch, if you (or anyone else) can identify when "Unknown" is passed as the SKU number please create a new issue so it can be addressed. I will look into it as well.

**Comment by TedCC1209** [comment]
If it's just TL Oxford White having "Unknown" incorrectly as the SKU number then we can just do that here.

**Comment by ClassyTeddy** [comment]
A material exports as unknown when it cannot find a material name with the given SKU number upon export. The given SKU number is determined by the given material name and the given thickness of the part, and the material names are determined by the import. Set up this way, there should rarely be a time when the export has "Unknown" as the SKU number. It is possible, that it is looking for a color at the wrong thickness, and that is what is causing the error. I will look into why this is happening.

**Comment by RyanMDev** [comment]
Yes. In this case, two SKUs have the same `ItemTypeCode` and `ItemColorCode` and SNaP does not know which one to use:

![multiple_skus_warn](https://user-images.githubusercontent.com/6529544/104239741-da618980-540f-11eb-971d-1e63b1ab3aa6.png)


![multiple_skus](https://user-images.githubusercontent.com/6529544/104239715-cfa6f480-540f-11eb-8e60-2347d4ecbc31.png)

**Comment by TedCC1209** [comment]
Just spoke with Brock and we should eliminate the SKU number EB-0000415 and just use EB-0000398 for TL Oxford White edgebanding. I will eliminate it on the shared google sheet if @ClassyTeddy you want to delete it from the SNaP ccitems csv.

@SeanRadvan I'm not sure if this fixes the issue Braeden was running into so we will keep this issue open

**Comment by ClassyTeddy** [comment]
Ready for testing on the `CSV-Change-1/11/21` branch.

**Comment by TedCC1209** [comment]
TL Oxford White edgebanding now exports the correct SKU:

![TL White](https://user-images.githubusercontent.com/61025894/104324216-63c29b80-54a4-11eb-92b3-9c99b24f126f.png)
