### ISSUE TITLE
Door Prompt Error when door above hamper & drawers

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#269]
@kategodfrey found this issue. Getting an error when trying to open up door prompts when the door is placed above a hamper & drawers (just a hamper seems to be okay and just drawers seems to be okay):

![Door prompt error2](https://user-images.githubusercontent.com/61025894/104062511-db987980-51b7-11eb-971a-011d2addff2a.png)

![Door prompt error](https://user-images.githubusercontent.com/61025894/104062453-c3285f00-51b7-11eb-91a6-7df2ed75d5ab.png)

This needs to be addressed before we push out the update. @kategodfrey please post any other info you have from your testing. 

Thanks, 

Ted

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Fixing-Doors-Above-Multiple-Assemblies` branch. This issue should fix the prompt error, and doors should now still have their defaults working when placed above two assemblies. More than two assemblies however, some of the defaults/interconnectedness (like starting with a top KD or accounting for BCP's) with partitions gets turned off due to that being too much logic to realistically have in place.

**Comment by TedCC1209** [comment]
> Ready for testing on the `Fixing-Doors-Above-Multiple-Assemblies` branch. This issue should fix the prompt error, and doors should now still have their defaults working when placed above two assemblies. More than two assemblies however, some of the defaults/interconnectedness (like starting with a top KD or accounting for BCP's) with partitions gets turned off due to that being too much logic to realistically have in place.

Thanks Teddy--that's fine for now as long as the prompt menus will still come up and changes can be made in those scenarios, even if the defaults aren't perfect.

**Comment by sarahhightower** [comment]
I was able to stack multiple assemblies and open the door prompts okay. I did this error message when creating the top doors of my section on the right, but it didn't appear to affect the functionality of any of the components. 

![SNaP_  C__Users_shightower_Documents_SNaP Projects_Training Day 1_41110_Door Test blend  1_11_2021 9_37_50 AM](https://user-images.githubusercontent.com/72047269/104212423-72507a80-53f2-11eb-9c0e-4e2396d7eeb8.png)

![3](https://user-images.githubusercontent.com/72047269/104212376-682e7c00-53f2-11eb-9606-d91e96c6cff7.JPG)

**Comment by ClassyTeddy** [comment]
I just made a change @sarahhightower, let me know if that fixed the error popping up.

**Comment by sarahhightower** [comment]
@ClassyTeddy  I pulled the branch again to test it and now access to all products and components has disappeared. 

![SNaP 1_11_2021 10_03_58 AM](https://user-images.githubusercontent.com/72047269/104214229-6c5b9900-53f4-11eb-885b-14760fa9a6b6.png)

**Comment by kategodfrey** [comment]
@ClassyTeddy @sarahhightower Same thing happened for me. Everything is gone.

**Comment by ClassyTeddy** [comment]
Yep, I just need to find the syntax error I created, give me one moment

**Comment by ClassyTeddy** [comment]
Pull the origin and try again please.

**Comment by kategodfrey** [comment]
@TedCC1209 @ClassyTeddy Worked for me! I tried a few different scenarios and it seemed to work well for each one.

**Comment by sarahhightower** [comment]
Okay, everything reappeared and I completed another test this time including hampers and shelves in my stacked components. No errors appeared and the door prompts worked. Thank you!

**Comment by SeanRadvan** [comment]
Looks like its working to me, stacked a door / drawer on a hamper and was
able to access the prompts.

**Comment by TedCC1209** [comment]
Cool, thank you everyone. @ClassyTeddy can you get this merged, then we can test again one last time before Ryan sets the update up (hopefully tomorrow)?
