### ISSUE TITLE
2D Changes Material Back to Oxf White

### ISSUE THREAD

**Issue by kategodfrey** [CCDevNelson/Snap-Updates#270]
When I have a material other than white it changes back to oxf white when I do a 2D render. Also, my 2D views legend says my material is white... My first try I used Aprese Ski and this time I used Cannes. We will probably want this fixed before the release. Sorry I didn't catch it before.

![image](https://user-images.githubusercontent.com/63115502/104068252-d2aca580-51c1-11eb-9cea-868ddd29f32c.png)
![image](https://user-images.githubusercontent.com/63115502/104068263-d8a28680-51c1-11eb-9f6b-9909955a445c.png)

**Comment by TedCC1209** [comment]
Thanks Katie. For some reason I thought both of these issues existed previously and they were just known bugs but perhaps I am mistaken, but that doesn't mean they don't need to be addressed. I know I have noticed that the countertops often revert to white or to another default material sometimes after a 2D view rendering.

@sarahhightower @nailsonlandim @AntonioGloria @ClassyTeddy @SeanRadvan @JBTattersall and others have you noticed, has the legend ever had the correct color exported to it or has it always said Oxford White? 

@ClassyTeddy @nailsonlandim @AntonioGloria @JJanneh please take a look at these and let us know what you think--I don't know if this is a 2D export issue or something else. Thanks, Ted

**Comment by JJanneh** [comment]
Ok will be testing this out

**Comment by ClassyTeddy** [comment]
I can confirm that this issue exists on the current user branch (1.2.1), saving appears to not be the issue (it happens whether I do or don't save before I create the 2D export), it only changes to Oxford White when `Save 2D Drawing As` button is pressed, and it doesn't change the material selected, so pressing the `Update Materials` button or selecting a new color will have the scene return to normal.

**Comment by sarahhightower** [comment]
@TedCC1209 I looked at old plans and no matter the color, the legend always showed Oxford White. The countertop, however; showed correctly in some plans that I looked at.

**Comment by JJanneh** [comment]
I selected several color pallets and noticed the color gets changed to the selected color pallet. Then when attempting to save 2D render. Save 2D Drawing As button is pressed, and it doesn't change the material selected, until render is completed then it reverts back to Oxford White after several different 2D Render and file names I have created the same result.
![Before_Saving_](https://user-images.githubusercontent.com/76751383/104215286-cad54700-53f5-11eb-835c-e4c9c45bf9ec.png)
![After_2D_Completed](https://user-images.githubusercontent.com/76751383/104216268-11777100-53f7-11eb-8ef9-0ef7d31aed02.png)
@ClassyTeddy @sarahhightower @kategodfrey

**Comment by TedCC1209** [comment]
Thank you everyone. These do need to be addressed--because they were existing issues @kategodfrey are you okay if we do the update now and address these issues for the next update?

**Comment by ClassyTeddy** [comment]
I think I have a fix working on the `2D-Views-Changing-Material-To-White` branch.

**Comment by sarahhightower** [comment]
I ran two tests. In both tests the color still reverted to white after to the 2D, but the ledger had the correct color. 

![image](https://user-images.githubusercontent.com/72047269/104220346-97e28180-53fc-11eb-8287-1bf16a38d45b.png)

**Comment by ClassyTeddy** [comment]
You can fix the color reverting to white in the scene by selecting the 'Update Materials' button

**Comment by sarahhightower** [comment]
I did see that, but I assumed the fix was trying to address this so you didn't have to do it. Its great to have an option that helps us get the correct color back and, in my opinion, this is fine for the current update we've been working on. But, in the future it would be ideal not to have to have to "update materials" to get the right color back.

**Comment by SeanRadvan** [comment]
hitting update materials and changing paint to "none" appears to be working
correctly in the drawings.

**Comment by TedCC1209** [comment]
This is fine for the legend portion of things so go ahead and merge this, but the issue should remain open until the main issue of the closets turning back white has been addressed.
