### ISSUE TITLE
Fillers: Option to edge bottom edge

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#272]
For fillers of upper cabinets, sometimes the bottom of the filler needs to be edgebanded to avoid the customer seeing exposed particle board. We need to add this option, likely just a "Edge Bottom of Filler" button at the bottom of the left/right filler column sections in the Construction Options menu that it currently being adjusted in https://github.com/CCDevNelson/Snap-Updates/issues/252 and https://github.com/CCDevNelson/Snap-Updates/issues/221. This also means the material settings for fillers need to show the core material so that the user can see whether the particle board is exposed or not.

**Comment by JJanneh** [comment]
![Screenshot (65)](https://user-images.githubusercontent.com/76751383/104631649-c610cd00-5659-11eb-9271-582e0910af88.png)

**Comment by TedCC1209** [comment]
Thanks J, can you make this a button option? If selected then the bottom edge is edgebanded and if not selected then it is exposed (no edgebanding) with the default being no edgebanding.

**Comment by JJanneh** [comment]
Ok a button, not a check box option similar to the Extend L/R correct?

**Comment by TedCC1209** [comment]
By button I mean check box, sorry

**Comment by JJanneh** [comment]
Edge Bottom of Filler CheckBox option
![Screenshot (67)](https://user-images.githubusercontent.com/76751383/104639659-e6925480-5664-11eb-9877-df3a543ad458.png)

**Comment by TedCC1209** [comment]
Thank you--what is the "Edge Banding Selected" option you have under it? I do not think that is necessary.

**Comment by JJanneh** [comment]
Ok. I can remove it Thanksfor the feedback it's greatly appreciated

**Comment by JJanneh** [comment]
Option-to-edge-bottom-edge Branch
![Screenshot (69)](https://user-images.githubusercontent.com/76751383/104646927-5d801b00-566e-11eb-9db8-3a57c1ad9fd8.png)

**Comment by JJanneh** [comment]
This is ready for testing on the Option-to-edge-bottom-edge-branch.

**Comment by TedCC1209** [comment]
> Option-to-edge-bottom-edge Branch
> ![Screenshot (69)](https://user-images.githubusercontent.com/76751383/104646927-5d801b00-566e-11eb-9db8-3a57c1ad9fd8.png)

Hi J, 

This graphic shows it pointing to the bottom of a partition, not the bottom of a filler. Are you having it edgeband the short bottom edge of the filler or are you having it edge the bottom of the partition? This issue concerns edgebanding the bottom of fillers. And are you including XML export logic into this so that when "Edge Bottom of Filler" is selected (which we will need a Left and Right option for so that the user can select which filler they want edgebanded on the bottom), that the filler will have the bottom short edge edgebanded? 

Sorry, based on your picture I thought I would ask these questions before getting into testing.

Thanks, 

Ted

**Comment by JJanneh** [comment]
I have the option set up only so far to select the on/off currently .I do
not have the XML export logic currently in place just yet. Need to get with
Teddy. Still need work to do some fine tuning.

**Comment by JJanneh** [comment]
I have the option set up only so far to select the on/off currently .I do
not have the XML export logic currently in place just yet. Need to get with
Teddy. Still need work to do some fine tuning.
![Screenshot (77)](https://user-images.githubusercontent.com/76751383/104930215-1772d200-5962-11eb-8753-9b4d2f893ffb.png)

**Comment by JJanneh** [comment]
![Screenshot (84)](https://user-images.githubusercontent.com/76751383/105073905-ee773d80-5a44-11eb-8bd7-ad396a4af45f.png)
Edge Bottom Left & Right

**Comment by TedCC1209** [comment]
I am assuming the most recent iteration of the option to edge the bottom of the fillers can be found in the Set-back-filler-option branch for https://github.com/CCDevNelson/Snap-Updates/issues/252 (correct me if I am wrong). If so, @JJanneh here are a couple changes to make please--1. please switch the order of the Extend Left/Right Side Forward row and the Edge Bottom of Left/Right Filler row:

![filler options](https://user-images.githubusercontent.com/61025894/105093092-67838e80-5a5f-11eb-8f8f-42f3b357b295.png)

This will keep the filler options together and the left/right end options together.

Next, please change the wording from "Left Edge Bottom of Filler" and "Right Edge Bottom of Filler" to say "Edge Bottom of Left Filler" and "Edge Bottom of Right Filler", respectively.

Thanks, 

Ted

**Comment by JJanneh** [comment]
![Edge_Bottom_of_Filler](https://user-images.githubusercontent.com/76751383/105096192-f5fa0f00-5a63-11eb-9f73-40ad452caaab.PNG)
Set-back-filler-option branch is correct branch.

**Comment by TedCC1209** [comment]
Thanks, and then as discussed above, the option to edge the bottom of the filler should just be a check box since it it just a yes/no option and not an amount, and defaulted to not being checked.

**Comment by JJanneh** [comment]
![Edge_Bottom_of_Filler_Checkbox](https://user-images.githubusercontent.com/76751383/105097495-ebd91000-5a65-11eb-8051-8f3df76c287b.PNG)

**Comment by JJanneh** [comment]
**Edge Bottom of Filler** Check box option is currently exporting XML data @TedCC1209 @ClassyTeddy
![Edge_Bottom_of_Filler_xml_Export_Data](https://user-images.githubusercontent.com/76751383/105514806-2d99ce80-5c91-11eb-9e21-c7a9e9a53798.PNG)
  
<Item ID="IDI-0">
 <Name>000.0008.01</Name>
 <Description>Edge Bottom Filler Options</Description>
 <Note>Closet:41110</Note>
<Part ID="IDP-0" LabelID="IDL-0" MatID="IDM-0" OpID="IDOP-0">
 <Name>Bottom Cleat</Name>
 <Quantity>1</Quantity>
 <Width>3.64</Width>
 <FinishedWidth>3.64</FinishedWidth>
 <Length>26.56</Length>
 <FinishedLength>26.56</FinishedLength>
 <Thickness>0.75</Thickness>
 <FinishedThickness>0.75</FinishedThickness>
 <Routing>SK1</Routing>
 <Class>make</Class>
 <Type>panel</Type>
<Unit>

**Comment by TedCC1209** [comment]
> **Edge Bottom of Filler** Check box option is currently exporting XML data @TedCC1209 @ClassyTeddy
> ![Edge_Bottom_of_Filler_xml_Export_Data](https://user-images.githubusercontent.com/76751383/105514806-2d99ce80-5c91-11eb-9e21-c7a9e9a53798.PNG)
> 
> 000.0008.01 Edge Bottom Filler Options Closet:41110 Bottom Cleat 1 3.64 3.64 26.56 26.56 0.75 0.75 SK1 make panel

Hi J, your example picture here is of a bottom cleat, not a filler. Filler pieces will be named "Left Filler" and "Right Filler" in the XML. 

No edgebanding is being passed in the XML to fillers in my testing on the branch Option-to-edge-bottom-edge (this branch also does not look like it has been updated with all the latest changes to the master branch). If there is a different branch I should be testing, please advise. 

Then also in the OP I wrote the following: "This also means the material settings for fillers need to show the core material so that the user can see whether the particle board is exposed or not." Right now fillers do not look to be showing the core material. Again though, this is in the Option-to-edge-bottom-edge branch so if there is somewhere else I should be testing please let me know. 

Thanks, Ted

**Comment by JJanneh** [comment]
@TedCC1209 just talked to @ClassyTeddy I still need to place the XML logic for the Left and Right Fillers

**Comment by JJanneh** [comment]
![L_Filler_EDGE_BANDING](https://user-images.githubusercontent.com/76751383/105533754-cb00fc80-5ca9-11eb-9070-f4ace24ba222.PNG)
![Screenshot (104)](https://user-images.githubusercontent.com/76751383/105533853-ec61e880-5ca9-11eb-8a3a-03251f11c5cd.png)

**Comment by JJanneh** [comment]
Option-to-edge-bottom-edge branch Branch ready for testing. Currently exporting edge banding data 
 ![Screenshot (106)](https://user-images.githubusercontent.com/76751383/105736138-b4e57d00-5ef1-11eb-9756-10bad953f4e5.png)

**Comment by JJanneh** [comment]
**Option-to-edge-bottom-edge** branch ready for testing

**Comment by sarahhightower** [comment]
The material core is not shown to test the feature, even after pulling the Option-to-edge-bottom-edge branch and loading SNaP defaults. Please let me know if I'm missing something here...

![1](https://user-images.githubusercontent.com/72047269/105775558-38b85d00-5f24-11eb-91bf-5fb1c614135d.png)

**Comment by TedCC1209** [comment]
@JJanneh It looks like you are getting this branch back up to speed after the update. When that's ready and after you get the material core to show (the bottom of the filler should look like the bottom of the partition in @sarahhightower 's example when the option to edge the bottom is not selected), please let us know so we can test. Thanks, Ted

**Comment by JJanneh** [comment]
Yes it appears that after I updated SNaP this morning. Some of the prompts
are missing and will update again shortly.

**Comment by JJanneh** [comment]
@ClassyTeddy I have the Edge Banding exporting L/R but the material is not changing when selected in SNaP.

**Comment by JJanneh** [comment]
No Edge Banding Showing CheckBox function needs work. XML data is currently exporting on selection
![Screenshot (113)](https://user-images.githubusercontent.com/76751383/105912184-50f1b000-5fe8-11eb-8c57-1a1223ec083b.png)

**Comment by TedCC1209** [comment]
J, as we discussed it is incorrectly showing edgebanding on the long vertical edge at all times whether your option is selected or not--that edge will be up against a wall so it should not be showing edgebanding:

![FILLER EDGING](https://user-images.githubusercontent.com/61025894/106007487-96a78a80-6073-11eb-9133-9565c6f04194.png)

Then you are also currently working on (with the help of @ClassyTeddy ) how to get the bottom edge edgebanding to show up in the scene when the option is selected in the prompts--the XML looks to be exporting correctly based on the selection in the prompts. Thanks, Ted

**Comment by TedCC1209** [comment]
@JJanneh As we talked about on the phone this morning, if the XML is working, the prompts are working, and if the bottom edge is showing edgebanding now when selected in the prompts then this is ready to test (if you can't get the vertical edge to show core material it's okay). Please let us know when latest updates are in your branch to test. Thanks, Ted

**Comment by JJanneh** [comment]
XML is working, the Edge Bottom L/R Filler are working once they are selected , and the bottom edge is showing core material. The option to display the change in core material still not completed. The Prompt to select edge banding Left and Right is currently functioning.
Ready to Test  Option-to-edge-bottom-edge branch

**Comment by TedCC1209** [comment]
>  The option to display the change in core material still not completed. 

What further information do you need from me or @ClassyTeddy to accomplish this? This is similar to an "exposed end" on a topshelf or the edgebanding for exposed ends on flat crown.

Thanks, Ted

**Comment by JJanneh** [comment]
ready to test Edge Bottom Filler Left and Right

**Comment by JJanneh** [comment]
@ClassyTeddy This is similar to an "exposed end" on a **topshelf** or the edgebanding for exposed ends on **flat crown**.
Code below shows **Core Material** 
def add_filler (assembly):
    # filler = assembly.add_assembly(Edge_Bottom_of_Filler)
    filler = assembly.add_assembly(PART_WITH_ALL_EDGES)
    filler.obj_bp.mv.comment_2 = "1036" 
    props = props_closet.get_object_props(filler.obj_bp)
    props.is_filler_bp = True
    filler.set_name("Panel")
    filler.material("Edge_Bottom_of_Filler")  
    filler.x_rot(value = 0)
    filler.y_rot(value = 0)
    filler.z_rot(value = 0)        
    filler.cutpart("Shelf")
    filler.edgebanding('Edge',l1 = True,l2 = True,w1 = True,w2 = True)
    filler.set_material_pointers("Closet_Part_Edges","Edgebanding")
    filler.set_material_pointers("Core","LeftEdge")
    filler.set_material_pointers("Core","RightEdge")
    filler.set_material_pointers("Core","BackEdge")
    for child in filler.obj_bp.children:     # filler.obj_bp.children:
        if child.cabinetlib.type_mesh == 'CUTPART':
            child.mv.use_multiple_edgeband_pointers = True    
    return filler

**Comment by ClassyTeddy** [comment]
This is how both the Top Shelf and the Flat Crown display core material as I understand it. However, you seemed to have copy and pasted a lot of unnecessary information. Below is all that is necessary to display core material.
```python
filler.edgebanding('Edge',l1 = True,l2 = True,w1 = True,w2 = True)
filler.set_material_pointers("Closet_Part_Edges","Edgebanding")
filler.set_material_pointers("Core","LeftEdge")
filler.set_material_pointers("Core","RightEdge")
filler.set_material_pointers("Core","BackEdge")
for child in filler.obj_bp.children: # filler.obj_bp.children:
  if child.cabinetlib.type_mesh == 'CUTPART':
    child.mv.use_multiple_edgeband_pointers = True
```

**Comment by JJanneh** [comment]
@ClassyTeddy Ok I will remove the additional information and re-test it again.

**Comment by JJanneh** [comment]
@ClassyTeddy I figured out a way to show edgebanding in the UI but still needs work. The Logic needs to be worked on a bit more.
Photo below show Edgebanding ON/OFF ![Edgebanding Off](https://user-images.githubusercontent.com/76751383/108380979-9c047a80-71c4-11eb-988f-4c97c8c96be4.png)
![Edgebanding ON](https://user-images.githubusercontent.com/76751383/108380981-9c9d1100-71c4-11eb-871b-5f2a4b9a957b.png)

**Comment by ClassyTeddy** [comment]
I can help you with the logic later.

**Comment by JJanneh** [comment]
@TedCC1209 @ClassyTeddy @TylerStandage Option-to-edge-bottom-edge Branch is Ready for Testing
Edgebanding and Capping and XML Exporting confirmed.
![Screenshot (356)](https://user-images.githubusercontent.com/76751383/108425723-17335400-71f8-11eb-8526-1e679e99ac58.png)

**Comment by TylerStandage** [comment]
@JJanneh Thanks J I see that the bottom edge banding is now showing!   Earlier in this thread I see that Ted had requested that we remove the edge banding on the long edge as this will be against the wall. Please update that piece as well.

**Comment by JJanneh** [comment]
@TedCC1209 @TylerStandage Option-to-edge-bottom-edge Branch is Ready for Testing
![Screenshot (368)](https://user-images.githubusercontent.com/76751383/108566837-4ca57380-72c4-11eb-98af-9f00057ffb27.png)

**Comment by TylerStandage** [comment]
@JJanneh @TedCC1209 I see that this is working in the UI, as is the #253 capping filler option issue!  I'll take a look at the xml this weekend or Monday.

**Comment by TedCC1209** [comment]
Tested the Option-to-edge-bottom-edge branch for this issue https://github.com/CCDevNelson/Snap-Updates/issues/272 and the capping filler https://github.com/CCDevNelson/Snap-Updates/issues/253.

The edgebanding looks great and the XML looks accurate as well. Great job @JJanneh and team. 

My only thoughts on this have to do with the menu / UI in this branch:

![Filler Menu](https://user-images.githubusercontent.com/61025894/109029355-006d8100-7680-11eb-8e56-be8f8e5cab6d.png)

My suggestions are in the image above.

Then, I believe this is already a known issue that we can address later if we think it'll be too complicated for now, but it would be nice if when "Add Left Filler" or "Add Right Filler" is deselected that the values for the filler amount and setback amount are zeroed out and the add capping filler and edge bottom of filler options are also automatically deselected.

Otherwise it looks great!

**Comment by JJanneh** [comment]
Ok @TedCC1209 Updated branch now on checkbox prompt selection "Add Left Filler" or "Add Right Filler" is deselected that the values for the **filler amount and setback amount are zeroed out** and **the add capping filler and edge bottom of filler options are also automatically deselected**.
![UI Change_Filler_Options](https://user-images.githubusercontent.com/76751383/109035905-51807380-7686-11eb-85dc-6599c6ecf1d9.PNG)

**Comment by JJanneh** [comment]
@ClassyTeddy I removed the Left, Right and Back only removes the edgebanding on all but the outside. ![Screenshot (453)](https://user-images.githubusercontent.com/76751383/109220032-a51dba80-7775-11eb-97bb-53172a402974.png)

**Comment by TedCC1209** [comment]
This looks the same as before--even when deselected, if reselected then all options under "add L/R filler" remain selected and filled in with what was there previously. It's not a big thing though so I don't know that we need to worry about it (it all disappears from view anyway).

Jobs created in this branch (Option-to-edge-bottom-edge) also correctly export fillers with edgebanding and capping fillers in the XML-Export-filler branch for the export logic created in https://github.com/CCDevNelson/Snap-Updates/issues/271, so that is good as well. Thanks @JJanneh 

I think this is good to go..
