### ISSUE TITLE
CL colors crashing SNaP

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#273]
After creating a new room, if I set my material color to a CL color (try CL Rialto) prior to putting in partitions then SNaP will crash when I try to put partitions on a wall. 

If I put in white partitions first, then it changes to CL Rialto fine if I change it after the fact. It didn't matter the number of openings for the partitions when I put it in. 

Confirmed with @kategodfrey that it happened on hers as well.

Here is the logfile from after the last crash:

[logfile.zip](https://github.com/CCDevNelson/Snap-Updates/files/5804947/logfile.zip)

I'm at a loss on this one.

**Comment by RyanMDev** [comment]
Fix for this is on master: CCDevNelson/SNaP-Dev@809b43d020aaac3b1dca2038676778f1ac1baf3c

**Comment by TedCC1209** [comment]
Thank you Ryan--the fix worked for me this morning

**Comment by sarahhightower** [comment]
The fix worked for me as well. Thank you!
