### ISSUE TITLE
XML exporting wrong fog gray and hardrock maple material

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#275]
What SNaP is currently exporting Fog Grey or Hardrock Maple are selected as the material: 

PM-0000359 --> Dura White_Fog Grey 15200 3/4
PM-0000361 --> Dura White_Hardrock  15200 3/4

What SNaP needs to be exporting: 

In replacement of PM-0000359: PM-0000376 --> Fog Grey 3/4
In replacement of  PM-0000361: PM-0000384 --> Hardrock Maple 3/4

**Comment by TedCC1209** [comment]
Any chance a fix for this can be included in the update? Thanks, Ted

**Comment by ClassyTeddy** [comment]
I will look into this one.

**Comment by ClassyTeddy** [comment]
Can I change the display name for the following materials:

PM-0000359 --> Dura White_Fog Grey 15200 3/4
PM-0000361 --> Dura White_Hardrock 15200 3/4

Currently their display names are:
Fog Grey
Hardrock Maple

Can I change them to be:
Dura Fog Grey
Dura Hardrock Maple

If not, then I can still solve the issue, I will have to put in logic that if it runs into the Fog Grey or Hardrock Maple Display name, then the ItemColorCode needs to be set. This, however, will cause issues if we ever want to incorporate either Dura colors into SNaP at some point.

**Comment by TedCC1209** [comment]
> Can I change the display name for the following materials:
> 
> PM-0000359 --> Dura White_Fog Grey 15200 3/4
> PM-0000361 --> Dura White_Hardrock 15200 3/4
> 
> Currently their display names are:
> Fog Grey
> Hardrock Maple
> 
> Can I change them to be:
> Dura Fog Grey
> Dura Hardrock Maple
> 
> If not, then I can still solve the issue, I will have to put in logic that if it runs into the Fog Grey or Hardrock Maple Display name, then the ItemColorCode needs to be set. This, however, will cause issues if we ever want to incorporate either Dura colors into SNaP at some point.

I don't think we want those SKU numbers available to choose so the display name doesn't matter right now--the one side white_one side fog gray (or hardrock maple) will only be utilized when we add the garage line of products and we need the interior of cabinets to be white and the exterior a different color. So, the display name of those two actually probably doesn't matter since we don't want them to be available to choose right now.

**Comment by TedCC1209** [comment]
If you need to set their display name as something, I would go with the following:

White_Fog Grey
White_Hardrock Maple

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Wrong-Colors-Exporting` branch.

**Comment by TedCC1209** [comment]
XML exported the correct SKU for me now, thanks Teddy

**Comment by TedCC1209** [comment]
@ClassyTeddy have you done a pull request for this yet? If not, please do

**Comment by ClassyTeddy** [comment]
It is on the master, Ryan pulled it as well as the discontinued colors.
