### ISSUE TITLE
Potential Update Issue with Drawer Library & Door Prompts

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#278]
If I do the update from the 1.2.1 branch on GitHub like we were doing to test the update, will I end up with exactly what users should be experiencing when they do the update or would the release candidate repo need to be updated again for me to get to see what users should be experiencing right now?

@sarahhightower is reporting that the drawers are still a basic library item rather than a whole set of different drawers stacks [EDIT--drawers can be found both in the old basic library and in the new drawer stack library], and is also reporting that the door prompt menu is still the old one, not the new one. I was not present during their updating to ensure they did it correctly, loaded snap defaults correctly, etc., which is why I am wondering if there is a branch I can test the user version & update from. Currently none of those issues are replicable for me.

**Comment by SeanRadvan** [comment]
I was just testing this on my laptop that was updated like an end user
would and it appears that drawers are listed under BOTH basic items and as
stacks of drawers in their own tab. I just got a call about drawers not
displaying correctly in 2D views, but am unsure if thats related yet.

**Comment by ClassyTeddy** [comment]
I also haven't seen/can replicate those issues. I am unsure as to why those issues might be happening because all the relevant files for doors and drawers are in the snap_db folder, which is the folder that gets updated. @RyanMDev can you help shed some light on this issue?

**Comment by TedCC1209** [comment]
> I was just testing this on my laptop that was updated like an end user would and it appears that drawers are listed under BOTH basic items and as stacks of drawers in their own tab. I just got a call about drawers not displaying correctly in 2D views, but am unsure if thats related yet. ![Drawer](https://user-images.githubusercontent.com/54151330/105091746-897c1180-5a5d-11eb-8db4-39f78ae66c18.png)
> […]

Confirming for everyone that even when @SeanRadvan loaded SNaP defaults that the drawer stack options were still available in both his Basic Library and the separate Drawer Stack Library.

**Comment by RyanMDev** [comment]
I am looking into this.

Updating from the 1.2.1 branch will be the same as users have with the exception of old files outside of the snap_db folder being left around. This is most likely what is happening.

**Comment by RyanMDev** [comment]
Loading SNaP defaults now ran automatically after an update.

**Comment by RyanMDev** [comment]
> the drawers are still a basic library item rather than a whole set of different drawers stacks,

Do they have both drawers as a basic item **and** the new separated drawers?

or

No new drawers and only the older basic library item?

**Comment by TedCC1209** [comment]
> > the drawers are still a basic library item rather than a whole set of different drawers stacks,
> 
> Do they have both drawers as a basic item **and** the new separated drawers?
> 
> or
> 
> No new drawers and only the older basic library item?

Just talked with her and like @SeanRadvan it is in both places (there are new drawers and the old basic item drawers)

**Comment by RyanMDev** [comment]
> Just talked with her and like @SeanRadvan it is in both places (there are new drawers and the old basic item drawers)

Alright, in that case the old .blend file and .png image have somehow been left around. Deleting both of these will resolve the problem.

**Comment by RyanMDev** [comment]
> also reporting that the door prompt menu is still the old one, not the new one

Then this is probably similar in that the old .blend file for doors was not updated correctly. Removing the .blend file will make it draw doors from the new logic.

**Comment by ClassyTeddy** [comment]
Actually, the .blend file does not affect the prompts menu. It can cause errors in that the prompt menu might look for prompts that don't exist, but it should always be the new prompts menu.

**Comment by RyanMDev** [comment]
@ClassyTeddy you are right, that couldn't be it then.

**Comment by RyanMDev** [comment]
I cannot replicate any doors showing the old prompts menu.

However, when I open a project made with 1.2.1 library data (door) in 1.2.2, the "shelves" menu does not display. This is because the new prompt page is looking for new prompts that the old doors do not have.

Notice that the "Shelf Options" tab is selected but nothing is showing. This could make it appear that the door prompts menu is showing the old one.

![door_prompts122](https://user-images.githubusercontent.com/6529544/105097798-0c04d100-5a5e-11eb-9ab1-7137df5d7c1a.png)

In this case, the following error is also shown in the console:

![door_error](https://user-images.githubusercontent.com/6529544/105097908-2fc81700-5a5e-11eb-8ae8-b674a2b728a4.png)

Can you confirm if the same might be happening?

**Comment by TedCC1209** [comment]
> I cannot replicate any doors showing the old prompts menu.
> 
> However, when I open a project made with 1.2.1 library data (door) in 1.2.2, the "shelves" menu does not display. This is because the new prompt page is looking for new prompts that the old doors do not have.
> 
> Notice that the "Shelf Options" tab is selected but nothing is showing. This could make it appear that the door prompts menu is showing the old one.
> 
> ![door_prompts122](https://user-images.githubusercontent.com/6529544/105097798-0c04d100-5a5e-11eb-9ab1-7137df5d7c1a.png)
> 
> In this case, the following error is also shown in the console:
> 
> ![door_error](https://user-images.githubusercontent.com/6529544/105097908-2fc81700-5a5e-11eb-8ae8-b674a2b728a4.png)
> 
> Can you confirm if the same might be happening?

@sarahhightower is currently training someone right now and will have to confirm when she gets done later this afternoon

**Comment by sarahhightower** [comment]
I've been creating all new files in 1.2.2 today and seeing this door prompt. To replicate the error and I just created a new file in 1.2.2 for you to have here.  Also, the person that I was training and was using 1.2.2 SNaP has the same door prompts. If we stay on the "Door Options" tab and change the shelves there all seems to be working well. If we attempt to change to the "Shelf Options" and close the prompt we get an error. 

https://drive.google.com/file/d/18OcIYbmeny-rzNaSnsjAS_hhFqJKj3B0/view?usp=sharing

![SNaP_  C__Users_shightower_Documents_SNaP Projects_Islands_41110_SNaP Test blend  1_19_2021 3_47_39 PM](https://user-images.githubusercontent.com/72047269/105103425-cfd96c80-5a6d-11eb-9756-ae469c914617.png)

![SNaP_  C__Users_shightower_Documents_SNaP Projects_Islands_41110_SNaP Test blend  1_19_2021 3_50_28 PM](https://user-images.githubusercontent.com/72047269/105103941-9bb27b80-5a6e-11eb-969f-b169a4ecf3d4.png)

**Comment by RyanMDev** [comment]
Thanks, and were you using an install of 1.2.2 for this testing?

**Comment by sarahhightower** [comment]
Yes, I was using 1.2.2 for this testing.

**Comment by sarahhightower** [comment]
I am just seeing your updated post with the second question. It was an earlier version up until this morning when I updated it to 1.2.2.

**Comment by RyanMDev** [comment]
Alright, I can replicate this as well when updating from earlier versions.

So this is a case of the .blend file not being updated correctly.

The old door prompts menu is not actually being shown. Instead, the new one cannot draw correctly because old drawers do not contain the correct prompts. The old doors are being drawn in because the pre-built .blend file for them was somehow not updated from 1.2.1 to 1.2.2.

To confirm this fixes your issue as well. You can rebuild the doors .blend file with the new logic with the following steps:

1) Enable library manager in user preferences.
![aa](https://user-images.githubusercontent.com/6529544/105107436-fcd94f80-5a6c-11eb-8224-049a47ce9b3c.png)

2) Open library manager panel.
3) Select 'Closets' and check 'Doors' then hit the 'Build' button.
![aaa](https://user-images.githubusercontent.com/6529544/105107510-24c8b300-5a6d-11eb-895b-f318290436f3.png)

Then drop a new door into the scene to check the prompts menu.

**Comment by RyanMDev** [comment]
> Removing the .blend file will make it draw doors from the new logic.

This will also work.

**Comment by sarahhightower** [comment]
> Alright, I can replicate this as well when updating from earlier versions.
> 
> So this is a case of the .blend file not being updated correctly.
> 
> The old door prompts menu is not actually being shown. Instead, the new one cannot draw correctly because old drawers do not contain the correct prompts. The old doors are being drawn in because the pre-built .blend file for them was somehow not updated from 1.2.1 to 1.2.2.
> 
> To confirm this fixes your issue as well. You can rebuild the doors .blend file with the new logic with the following steps:
> 
> 1. Enable library manager in user preferences.
>    ![aa](https://user-images.githubusercontent.com/6529544/105107436-fcd94f80-5a6c-11eb-8224-049a47ce9b3c.png)
> 2. Open library manager panel.
> 3. Select 'Closets' and check 'Doors' then hit the 'Build' button.
>    ![aaa](https://user-images.githubusercontent.com/6529544/105107510-24c8b300-5a6d-11eb-895b-f318290436f3.png)
> 
> Then drop a new door into the scene to check the prompts menu.

This worked for me! Thanks!

**Comment by TedCC1209** [comment]
Great, thank you @RyanMDev @sarahhightower , we will be passing on these instructions to other end users as well for them to fix the door prompts.

How are we addressing removing the old drawers from their basic libraries? Is this something they can go and remove the blend file? If so, where can they/we find it?

**Comment by RyanMDev** [comment]
1) Navigate to the "Closet Products - Basic" category.
2) Use "Open Location in Browser" to view the .blend files and thumbnails.
![open_loc_browser](https://user-images.githubusercontent.com/6529544/105113695-41b7b300-5a7a-11eb-80fb-11b9e3699ef4.png)


3) For removing old **drawers**: delete 'Drawers.blend' and 'Drawers.png'
![fix_drawers](https://user-images.githubusercontent.com/6529544/105113460-d79f0e00-5a79-11eb-8831-c140d9a1fb6b.png)

4) For **doors**: delete **only** "Doors.blend" but **not** "Doors.png"
![doors_fix](https://user-images.githubusercontent.com/6529544/105113574-0c12ca00-5a7a-11eb-98d1-e34acc73f929.png)

**Comment by TedCC1209** [comment]
Thanks @RyanMDev !

@kategodfrey are you able to send these instructions to users tomorrow?

**Comment by kategodfrey** [comment]
Yes I will do that.
