### ISSUE TITLE
Update Failed for a User

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#279]
@SeanRadvan had a call/voicemail from a user saying the update "failed" (many others' updates have been fine). Is there a place for @SeanRadvan to download a fresh version of 1.2.2 that he can manually go put on this user's (and new users') computer? This would be helpful from a tech support standpoint.

**Comment by SeanRadvan** [comment]
I downloaded the 1.2.2 update.zip and would like to be able to know how to apply that as well, to have more tools in my belt.

**Comment by RyanMDev** [comment]
Alright, there are two options here:

1) **Manual update from a previous version.**
    a) Download update zip from the `Snap-Updates` repo here: 
https://github.com/CCDevNelson/Snap-Updates/releases/tag/v1.2.2

    b) Unzip and you should have a folder inside named `Snap-Updates-1.2.2`, rename this folder to `snap_db`. Remember that when you unzip the folder you will get a containing folder `Snap-Updates-1.2.2\Snap-Updates-1.2.2\<snap_db files>`. You should now have a top-level folder named `snap_db` with python files inside.

    c) On a user's installation of 1.2.1 or earlier, navigate to `SNaP\2.78\scripts\addons` find the snap_db folder there and delete it.

    d) Move the newly prepared `snap_db` folder (v1.2.2 update) into `SNaP\2.78\scripts\addons`.

    e) The updater runs "Load SNaP Defaults" automatically after an update. Since you are doing a manual update here you will also need to manually run "Load SNaP Defaults" after you start SNaP up again.

2) **Fresh install of version 1.2.2.**

    a) Download the full installation of SNaP version 1.2.2 from the `SNaP-Dev` repo here:
https://github.com/CCDevNelson/SNaP-Dev/releases/tag/v1.2.2

    b) Unzip and move SNaPs root folder (`SNaP`) to the desired location.

    c) Open SNaP and run "Load SNaP defaults"

**Comment by TedCC1209** [comment]
Thank you @RyanMDev 

@SeanRadvan I think what Ryan just posted is everything you need but please let us know if there is something else.

Thanks, Ted
