### ISSUE TITLE
Developer running into parse error

### ISSUE THREAD

**Issue by JJanneh** [CCDevNelson/Snap-Updates#280]
I'm getting the following error when i open a room, export room, and save a room.
![Screenshot (92)](https://user-images.githubusercontent.com/76751383/105203862-d36a0380-5b00-11eb-93ad-a1ff910c3f41.png)

**Comment by ClassyTeddy** [comment]
This is an issue that I would like @RyanMDev to help with only after the more pressing update issues are resolved.

**Comment by RyanMDev** [comment]
Investigate your .ccp project files, one of them has a syntax error on line 19.

**Comment by JJanneh** [comment]
@RyanMDev Removed all Previous saved Projects/Rooms and Started from Scratch. Export of XML files currently is working now.
