### ISSUE TITLE
Delete "Inset Front" option for Doors and Drawers

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#29]
We should delete this option as we don't do this. If we want the "inset" look we create a frame on top of / around our normal construction.

**Comment by TEDSTANDAGE** [comment]
The inset front option looks to be deleted in the Teddy Fixes branch. Thanks

**Comment by meltnaz** [comment]
Can we go back to this...We do use inset drawers in pantry applications. I must have missed this conversation, but just noticed that this option was missing.

![WeltyRevised-Pantry](https://user-images.githubusercontent.com/32275766/82381218-a6e47180-99de-11ea-82e2-c8e604b7dbdf.png)

**Comment by TEDSTANDAGE** [comment]
Are there 3/4” faces on the drawers in your pic Melissa and is that how we build them? We certainly don’t door inset doors on our residential jobs, and I’m pretty sure the inset door option was not accurate on our construction of those types of drawer boxes but I could be wrong. If we want to bring back the inset drawers I can work with Sean on how we construct them and make sure SNaP reflects it. Let me know

**Comment by meltnaz** [comment]
The pantries in both showrooms have inset drawers. I had a pantry install with 3 inset drawers about a week ago (job # 163437, if you want to look it up). It's an option that we have as far as I'm aware, unless I'm using the wrong terminology for it?

**Comment by TEDSTANDAGE** [comment]
I’ll look it up and check with Sean on engineering and then we will look at bringing the inset option back for drawers and what changes will need to be made to it

**Comment by meltnaz** [comment]
Ok, thank you.

**Comment by TEDSTANDAGE** [comment]
Spoke with Sean W, and we can talk about this further at the meeting tomorrow, but we do not do "inset drawers" where a drawer face goes in between the partitions and is inset of the section like the picture there shows (how SNaP previously showed "inset drawers").

What we do do (and what it is I think you're thinking of) is pull-out drawer boxes, where we have a drawer box with no face. If it's a melamine pull-out drawer box we finish the front of the box with HPL laminate so there is no exposed particle board and it has a nice finish. If it's a dovetail drawer box then the box comes finished / painted and we have the scoop option with those as well. 

Another option we have at the showrooms is drawers with no handles where the drawers spaced far enough apart to put your hand in and pull out by the top of the face--but with this option the face still caps the partitions, they are not inset like the picture above.

Two ways of approaching this that I see:

1. Add a "no drawer face" option to the drawer prompts. If it is a dovetail drawer box (which we don't have in SNaP yet) then the different options should pull up in that case.

2. Create a new library item for pull out drawer boxes. This might be preferred, especially if it can be used to insert pull-out drawer boxes behind doors and account for that. (Note: at the same time, we should create pull-out shelves).

Let me know what you think, and again we can talk about this further at the meeting tomorrow as well.
