### ISSUE TITLE
Larger Prompt Menus

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#290]
Some users are saying some of the prompt menus are hard to read because of small text. Is there a way (perhaps it is a user preference in blender?) to adjust the text size of prompt menus?

**Comment by AntonioGloria** [comment]
Hi @TedCC1209,
The size of the text can be adjusted for menus or prompts with Blender by going to File > User Preferences... > Themes > Text Style
The menu looks like this:
![image](https://user-images.githubusercontent.com/74732175/105543998-16bea080-5cc0-11eb-9712-c2992bb376c9.png)
The three highlighted sliders are the values that affect UI text size. Hope this helps.

**Comment by TedCC1209** [comment]
Thanks @AntonioGloria ! 

@sarahhightower see above. Going too big makes it look a little funny, but a size 14 text might be good for the users who are having issues reading smaller text.

**Comment by sarahhightower** [comment]
Very helpful information. Thank you!
