### ISSUE TITLE
Error Given when trying to generate 2D view in Custom Room

### ISSUE THREAD

**Issue by kategodfrey** [CCDevNelson/Snap-Updates#296]
I received this email from a user in CO:

"I found another snag...
I have a really large job that was designed in last update (August)
but now when I go to make 2 d's, it does not work. 
I may need to go back to the last version until this job is complete- it's far too large to redraw (72K)
Is there a way?"

I then tried to generate a 2D view on a custom room I drew in version 1.2.1 and got this error:

![image](https://user-images.githubusercontent.com/63115502/106170073-54eb1280-614d-11eb-928e-10aa0eb2fa55.png)

Any help would be appreciated @ClassyTeddy @RyanMDev @nailsonlandim 
Thank you!

**Comment by sarahhightower** [comment]
I had a similar issue when I tested a custom room, except my room completely disappeared when I attempted to "prepare 2d views". 

![SNaP_  C__Users_shightower_Desktop_Client Files_Sold_Weissman-Hunt, Amy_Living Room blend  1_28_2021 9_32_49 AM](https://user-images.githubusercontent.com/72047269/106169537-b78fde80-614c-11eb-83e2-4e2058222524.png)

**Comment by nailsonlandim** [comment]
Hi @kategodfrey and @sarahhightower ,

Got it here, I can fix it to avoid crashing it again. Confirm if removing existing doors and placing them again prevent it from happening.

**Comment by nailsonlandim** [comment]
@ClassyTeddy and @RyanMDev , besides checking door prompts, any idea on how to differentiate if a project was done on a previous version?

**Comment by kategodfrey** [comment]
> 
> 
> Confirm if removing existing doors and placing them again prevent it from happening.

Can you explain what you mean by this? Like should I take out all the doors and replace them all? Or just one and see if I get an error?

**Comment by kategodfrey** [comment]
Never mind that doesn't apply to me because I only have one set of doors... I took them out and put them back in and was able to generate the 2Ds.

**Comment by kategodfrey** [comment]
So with this information... should I tell the user she needs to take out all the doors and replace them?

**Comment by ClassyTeddy** [comment]
> @ClassyTeddy and @RyanMDev , besides checking door prompts, any idea on how to differentiate if a project was done on a previous version?

I don't know if there is a way, but there still might be. @RyanMDev please let us know if this is something currently in place.

**Comment by nailsonlandim** [comment]
Yes @kategodfrey, that's the fast fix.

Doors were changed, and the old files miss some data that was included in version 1.2.2. Replacing all doors in a project will add doors that have this information.

To avoid a crash I will write a fix. 

If doors keep unchanged on a project after the fix, in some scenarios, the shelf count on Plan View tags can be wrong.

**Comment by RyanMDev** [comment]
> @ClassyTeddy and @RyanMDev , besides checking door prompts, any idea on how to differentiate if a project was done on a previous version?

@nailsonlandim, you need to check if the prompt exists before attempting to retrieve the value.

For older library data, the prompts you are looking for may not exist since they were drawn with a previous version.

```
1540: bot_kd = fd_types.Assembly(assembly).get_prompt('Bottom KD')

1550: if bot_kd.value():
1551:     shelf_count += 1
```

First check if the prompt is not `None` and then check the value.

```
1550: if bot_kd and bot_kd.value():
```


Or
```
1550: if bot_kd:
         if bot_kd.value():
```

**Comment by nailsonlandim** [comment]
Thanks @RyanMDev for the prompt answer, that's what I am planning to do. besides checking the prompt existence, there's anything else to help to define the "file version"? 

I was thinking of firing an alert because of what I mentioned previously about the shelf count.

**Comment by RyanMDev** [comment]
> there's anything else to help to define the "file version"?

Currently, there is not. Although SNaP 2.0 will include this.

**Comment by nailsonlandim** [comment]
Hi @TedCC1209 @kategodfrey 

Fixed. I tested it on example large room project. 

Available at: https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23296-2dviews-custom-room-error

**Comment by kategodfrey** [comment]
Thank you @nailsonlandim So I actually can't test this anymore since I resaved my last project with custom walls and doors... @sarahhightower said she would for me. 

Any ETA on when we can release a hot fix for this so our users can render their older files?

**Comment by nailsonlandim** [comment]
> Thank you @nailsonlandim So I actually can't test this anymore since I resaved my last project with custom walls and doors... @sarahhightower said she would for me.
> 
> Any ETA on when we can release a hot fix for this so our users can render their older files?

Hey @RyanMDev , can you give me a hand?

**Comment by sarahhightower** [comment]
@nailsonlandim I tested this on a different custom room in your #296 branch. When bringing in new doors I got an error message, but it didn't prevent me using the door prompt. Then I tried generating the 2D views and I got another error message, but again it didn't prevent me from getting my 2d plans. Below are the errors I received. 

![SNaP_  C__Users_shightower_Desktop_Client Files_Sold_Esch, Pug and Lee_Master blend  1_28_2021 2_06_45 PM](https://user-images.githubusercontent.com/72047269/106200789-c4c0c380-6174-11eb-8df5-aa89dc14c12f.png)

![SNaP  C__Users_shightower_Desktop_Client Files_Sold_Esch, Pug and Lee_Master blend  1_28_2021 2_09_36 PM](https://user-images.githubusercontent.com/72047269/106200799-c8544a80-6174-11eb-850a-b708dc48cb5d.png)

**Comment by nailsonlandim** [comment]
Understood @sarahhightower , can you send me the file? So I can test here too. In the while, I'll write the fix with the given error messages. Thanks!

**Comment by RyanMDev** [comment]
> Hey @RyanMDev , can you give me a hand?

@nailsonlandim do you see that these two are both stemming from `data_closet_doors.py`?

It is the same issue as before. The blind corner panel prompt does not exist in the old closet carcasses.

I can fix this.

Can you double-check `fd_2dviews/__init__.py` for any place where `get_prompt` is used and make sure it will not cause an issue if the prompt does not exist?

> @nailsonlandim I tested this on a different custom room in your #296 branch. When bringing in new doors I got an error message, but it didn't prevent me using the door prompt. Then I tried generating the 2D views and I got another error message, but again it didn't prevent me from getting my 2d plans. Below are the errors I received.
> 
> ![SNaP_ C__Users_shightower_Desktop_Client Files_Sold_Esch, Pug and Lee_Master blend 1_28_2021 2_06_45 PM](https://user-images.githubusercontent.com/72047269/106200789-c4c0c380-6174-11eb-8df5-aa89dc14c12f.png)


> @nailsonlandim, I removed all my doors and replaced them. When I replaced them I got an error message each time that seemed to disable my door prompt for a moment, but then worked. Ultimately I was able to generate my 2D though. Here's the error message I got when replacing my doors.
> 
> ![SNaP_ C__Users_shightower_Desktop_Client Files_Sold_Weissman-Hunt, Amy_Living Room blend 1_28_2021 10_02_24 AM](https://user-images.githubusercontent.com/72047269/106173492-371fac80-6151-11eb-87da-3cdaba54d44c.png)

**Comment by nailsonlandim** [comment]
> Can you double-check fd_2dviews/__init__.py for any place where get_prompt is used and make sure it will not cause an issue if the prompt does not exist?

Got it, thanks.

**Comment by sarahhightower** [comment]
> Understood @sarahhightower , can you send me the file? So I can test here too. In the while, I'll write the fix with the given error messages. Thanks!

Sure. Here you go!

https://drive.google.com/file/d/1V_0adpXTxh1sF3qJ2fRSayxPK9jIo9G0/view?usp=sharing

**Comment by RyanMDev** [comment]
Fix for door error when placing in older carcasses is available on commit: CCDevNelson/SNaP-Dev@42df5485805c9512852ea0c7e56e860134ae2c1f

**Comment by kategodfrey** [comment]
Thanks!! Let me know when I can let the user know it will work on her computer.

**Comment by RyanMDev** [comment]
@nailsonlandim did you have anything to add to this?

> Hi @TedCC1209 @kategodfrey
> 
> Fixed. I tested it on example large room project.
> 
> Available at: https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23296-2dviews-custom-room-error

**Comment by nailsonlandim** [comment]
Hi @RyanMDev 

I think that's it. Tell me what you think

**Comment by RyanMDev** [comment]
> Thanks!! Let me know when I can let the user know it will work on her computer.

@kategodfrey the hotfix update (version 1.2.4) is now up. The update should be available the next time she opens SNaP.

**Comment by kategodfrey** [comment]
Thank you guys for working on this today!!
