### ISSUE TITLE
Doors in opening with BCP: Default swing for single doors

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#299]
The default swing for single doors in openings that contain a blind corner panel should be the following:

Left BCP opening - left swing
Right BCP opening - right swing

**Comment by JJanneh** [comment]
@ClassyTeddy Ok im looking at the **common_parts.py** setting default swing for single doors in openings that contain a blind corner panel.
![common_panel_BCL_BCR](https://user-images.githubusercontent.com/76751383/108092947-6fbcf280-703a-11eb-96c1-e5c863c229ff.PNG)

Left BCP opening - left swing
Right BCP opening - right swing

**Comment by JJanneh** [comment]
@TylerStandage @TedCC1209 Left BCP opening - left swing  Right BCP opening - right swing defaults set as per your request.

**Comment by TylerStandage** [comment]
This looks great, J. Good work.  @TedCC1209 I'm moving to testing. Let us know if it's ready to merge.

**Comment by TedCC1209** [comment]
This looks good on the default-swing-opening-with-BCP branch. Thanks @JJanneh
