### ISSUE TITLE
Drawer box depths for lateral file rails

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#304]
For melamine drawer boxes, the drawer box depth for drawer boxes that have lateral file rails should be as follows:

Lateral Letter - 14" deep box
Lateral Legal  - 17" deep box

This should _not_ change the Drawer Rear Gap for other drawer boxes in the assembly, only the drawer box containing the lateral file rails.

**Comment by TedCC1209** [comment]
This also means that a minimum depth needs to be put into place for these:

Lateral Letter - minimum section depth 16"
Lateral Legal - minimum section depth 19"

**Comment by ClassyTeddy** [comment]
Hey Ted, wanted to clarify what the goal of this issue is. Do you want the box to be forced to be a 14" deep box when there is a lateral letter file rail, regardless of the depth of the partition?

**Comment by TedCC1209** [comment]
> Hey Ted, wanted to clarify what the goal of this issue is. Do you want the box to be forced to be a 14" deep box when there is a lateral letter file rail, regardless of the depth of the partition?

Yes. Otherwise there is a small gap between the file rail and the back side of the box which isn’t ideal. This way the file rail will be snug against the front and back sides of the box. Thanks, Ted

**Comment by JJanneh** [comment]
@TedCC1209 @ClassyTeddy Thanks for guidance. @TylerStandage 
Before Updated Logic and Drawers 
![Screenshot (579)](https://user-images.githubusercontent.com/76751383/110383792-08330b00-801a-11eb-82ab-72551d8ae5bc.png)
After Updated Logic and Drawer Rebuild
![Screenshot (589)](https://user-images.githubusercontent.com/76751383/110383804-0e28ec00-801a-11eb-8645-355ebb141b58.png)
Ready for Testing Branch **lateral-file-rails-#304**
