### ISSUE TITLE
Filler setback amount appearing before necessary 

### ISSUE THREAD

**Issue by sarahhightower** [CCDevNelson/Snap-Updates#308]
The "Left Filler Setback Amount" and "Right Filler Setback Amount" appear before selecting "Add Left Filler" or "Add Right Filler". This prompt would not be used unless there is filler so it would work best if it doesn't appear until the filler option is selected.

![1](https://user-images.githubusercontent.com/72047269/107974679-2e620f80-6f74-11eb-9f0c-41f1ad6946ac.png)

**Comment by TedCC1209** [comment]
Looks like this issue is addressed in the Option-to-edge-bottom branch.

**Comment by TylerStandage** [comment]
Yes, true. This came up in conversation and J was able to fix it along with the other filler work he was doing.  I'll close this out.
