### ISSUE TITLE
Door Material Not Exporting Correctly

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#316]
Melamine doors are being exported as the same material as the closet even when a different material is chosen in the door/drawer face material. This had been working previously so I am unsure what changed. Here is an example SNaP Project where it exported the same as the rest of the closet:

https://drive.google.com/drive/folders/1RbPat1eQxt9-qCT57Acqk_k_0P-5_6B3?usp=sharing

**Comment by ClassyTeddy** [comment]
This issue is ready for testing on the `Door-Material-Not-Exporting` branch.

**Comment by TylerStandage** [comment]
Thanks Teddy.  @TedCC1209 I'm seeing this exporting correctly now.  Same for you?

**Comment by TedCC1209** [comment]
Looks good, thanks @ClassyTeddy
