### ISSUE TITLE
Update SNaP Library in Support of Pricing Software

### ISSUE THREAD

**Issue by TylerStandage** [CCDevNelson/Snap-Updates#321]
Update to latest: https://docs.google.com/spreadsheets/d/1Ct8TNYSVwu4HVSvmL9g3ovgMTJB-FsqerqUbqH-3ggc/edit#gid=1888329563

@RyanMDev  @ClassyTeddy  I assume we can go ahead and update to the latest version of our pricing sheet?  We've made recent updates, especially to the hamper section.

**Comment by TylerStandage** [comment]
Let's be sure this gets into the 2.0 release

**Comment by ClassyTeddy** [comment]
So I can update the CCItems fairly easily, but I would like to ask @RyanMDev if there is anything that needs to be done to CCItems for the 2.0 version of SNaP, or should I just make a new branch and pull request to update the file as normal?

**Comment by RyanMDev** [comment]
@ClassyTeddy there should be no changes required, go ahead and submit a pull request updating the file as normal.
