### ISSUE TITLE
Fog Gray Stain not working

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#33]
All stains appear to be working for me on Version 1.1.0 except for Fog Gray--when you select Fog Gray the color in the scene just stays displayed as the previously selected stain color. 

The spelling is Fog "Grey", unsure if the difference between Gray & Grey is causing the issue.

**Comment by RyanMDev** [comment]
Fix for this is available in CCDevNelson/SNaP-Dev@d093891b7cfaa379f0ff8b02e1bf7692e48cb711

**Comment by TEDSTANDAGE** [comment]
Fog Grey stain works for me now, thank you
