### ISSUE TITLE
Glass Inset door melamine material not showing

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#34]
When doors are put in as glass inset, the color of the melamine material of the door is just a ghost color. If there is a way of selecting or changing the melamine material for it I do not know how because it does not respond to changing the room material settings, moderno door settings, or otherwise. I am unsure if this was an issue before 1.1.0 was put in or not.

**Comment by TEDSTANDAGE** [comment]
UPDATE: The glass inset door wood material responds to the stain color selection but should have the option to match the melamine material of the job.

**Comment by RyanMDev** [comment]
Fixed with commit: CCDevNelson/SNaP-Dev@48bab9b2637a17c86ec989c7748a1d70089b030c

Now when materials are assigned to wood doors, if the stain color is 'None' then the melamine color selection is used instead. Otherwise the stain color is used.

**Comment by TEDSTANDAGE** [comment]
I may have screwed this up. Can you put it back to the version without this commit so I can test melamine glass-inset doors again without it? We would only want the glass-inset doors to match the melamine color of the closet (and when we are able to choose a separate melamine door/drawer face material from the rest of the job, to match that melamine door/drawer face color) when the melamine glass-inset door is selected. If it is a wood glass-inset door, we would want a "none" stain selection to be the ghost color if no other stain is selected.

**Comment by RyanMDev** [comment]
No problem, reverted these changes with commit: CCDevNelson/SNaP-Dev@fe1ae34027a95e9f8d1e4bc8036cac6f28bbcb81

**Comment by TEDSTANDAGE** [comment]
Turns out it was working as it should before, just was user (my) error. Please close
