### ISSUE TITLE
Allow for two different textures/materials in same closet, particularly melamine slab doors

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#4]
Two parts, related:

1. Allow for different slab melamine door material and edge than the rest of the closet. Likely should be a selection on the main dropdown, similar to how COS allows for this separate selection.

2. Allow for different textures/materials in the same closet so that an island or component can be a different material than the rest of the closet (can "unique material" option be added to be used in this situation like we do for the cedar backs?)

**Comment by CCDevNelson** [comment]
Already #52 in Main post
