### ISSUE TITLE
Create full overlay option for doors

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#42]
Currently only drawers have the option to switch between full and half overlay sizing. Doors just come in half overlay right now. We should create a full overlay option for doors (width only), keeping half overlay as the default with a button added for the full overlay option.

**Comment by ClassyTeddy** [comment]
This option is ready for testing on the Tedy_Fixes Branch

**Comment by TEDSTANDAGE** [comment]
Looks good, thanks!
