### ISSUE TITLE
Simplify Drawer Face Full/Half Overlay Option

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#43]
Currently, the drawer prompts have options for full/half overlay as it relates to the top, bottom, right, and left:

![image](https://user-images.githubusercontent.com/61025894/79781060-c90ca600-82f1-11ea-95ad-d817714f5fff.png)

We should simplify this. Default should remain with drawer faces being inserted as half overlay. Then, the option button (a single button for the assembly) should simply allow for full overlay which would only change the width (never the height) of the drawer faces, and it should be all or nothing (all drawer faces in that assembly and both left and right sides of the face being full overlay, or none at all)

**Comment by TEDSTANDAGE** [comment]
A now unnecessary side note: as it currently exists, even when you change the top or bottom buttons to be full or half overlay on the drawers, it doesn't change the height of the drawer faces--rather it simply moves the entire assembly up/down or the top KD up/down... meaning the top KD/slides/etc. aren't even lining up with the hole system of the partitions. This doesn't matter now since we are getting rid of this option to be full overlay on the top/bottom anyway, just pointing out that the option right now doesn't even match our hole system.

**Comment by ClassyTeddy** [comment]
Pushed a fix for this issue that is ready for Testing on the Teddy-Fixes Branch.

**Comment by TEDSTANDAGE** [comment]
Nice work, thank you. It looks good to me

**Comment by TEDSTANDAGE** [comment]
Keeping the default the same (half-overlay), is it possible to change the prompt option to say "Full Overlay" (and starting off unchecked) rather than it saying "Half Overlay" (and starting off checked like it is)?

**Comment by ClassyTeddy** [comment]
Yeah, I just have to switch some things around

**Comment by TEDSTANDAGE** [comment]
I saw we switch it then if it's not difficult. It will reflect that the Classy standard is half overlay and that full overlay is the exception.

**Comment by TEDSTANDAGE** [comment]
The new fix with the switched wording on the prompt looks good to me and it appears to be functioning correctly
