### ISSUE TITLE
Color issues 4/22/20

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#44]
I went through and tested colors after the new .csv was entered and found the following.

1. The following colors show up purple (my understanding was that colors that didn't have a corresponding image would not show up on the drop down list, but maybe these items were given a temp purple image?):

-U Esterel
-U Mimosa
-U Mistral
-U Monaco
-Graphite Spectrum (this one should probably just not show up until the garage options / one side white one side color material options are available anyway)

2. Fog gray now does not show up as a stain option despite the fix in SNaP-Updates Item #33 

3. SNaP-Update issues #25 / #26 still exist.

**Comment by ClassyTeddy** [comment]
Those first 5 colors were given temp colors, they were the colors that I updated in the Teddy-Fixes Branch. As for Fog gray, and issue #25 / #26, I waited for the new csv to be added to the master branch (which happened yesterday) to update the names. Will work on fixing those last three items today.

**Comment by TEDSTANDAGE** [comment]
Thank you Teddy and please go ahead and take the temp color image out for graphite spectrum as well.

**Comment by TEDSTANDAGE** [comment]
Teddy, are/were you able to fix those 4 Uniboard colors like you were able to fix Coastal Pear?

**Comment by ClassyTeddy** [comment]
I did not fix coastal pear, but I did add textures to those 4 uni board colors and fix them.

**Comment by TEDSTANDAGE** [comment]
Ah okay it looks like that Coastal Pear issue was something different, my bad

**Comment by CCDevNelson** [comment]
Ted, you understand, Teddy fixing those color does NOT fix anybody's Version 1.1.0 that gets installed unless 1 or two things happens:
1.) If we install it (meaning Sean remotely or in house), we can then add those files manually.
2.) An update is issued to post those to everyone's version 1.1.0 going to Version 1.1.1

**Comment by TEDSTANDAGE** [comment]
I understand how this works Mark

**Comment by ClassyTeddy** [comment]
After getting some more info from Ryan and scanning through the new .csv, I noticed that there is no Lakeshore Oak in the new merged spreadsheet at all. So on the master branch, they do not come up in the materials list. Also on the master branch, fog grey is working as well. The 4 uniboard colors and the removal of Graphite spectrum should also be fixed when I merge TeddyFixes with the Master Branch.

**Comment by TEDSTANDAGE** [comment]
I closed this issue to separate and clarify certain sub issues identified.
