### ISSUE TITLE
Topshelf Depth

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#46]
<<This is not a priority issue, just putting it out there>>

Currently, when a top shelf is entered it defaults being inserted with a 0.5" overhang on the depth of the left partition where the top shelf was placed, even if the middle or right partitions it covers are deeper than the left partition:

![image](https://user-images.githubusercontent.com/61025894/80000209-b4571c00-8471-11ea-8920-942263c513b5.png)

Instead, if possible, it would be nice if the topshelf defaulted to being 0.5" deeper than the deepest of the partitions it covers rather than just defaulting to the left partition (taking into account dog-ear depths). Then, if the depth of any of the partitions it covers is changed, it would be nice if the topshelf depth would adjust with it to the deepest of those partitions.

**Comment by TEDSTANDAGE** [comment]
Note that the default does not currently take into account dog-ear depths (i.e., it goes 0.5" over the depth of the partition, not the depth of the top of the partition where it has been dog eared):

![image](https://user-images.githubusercontent.com/61025894/80001623-6e02bc80-8473-11ea-9ef0-c0a4ab4c6376.png)

**Comment by CCDevNelson** [comment]
From a programing stand point, When you select to put Top Shelf (or Toe kicks for that matter), You selet the Start and end partitions. As far as the code knows it needs to fill in the space between those two. It has no idea if there are 2 other pards or ten other pards between that space. So unless the program was re-written to have you select each partition (in order, left to right), would be the only way to have the code know what partitions it s covering when it's applied in the drawing.
There might be a way to create a bounding box between the first and second pick points, then look through that group of parts, see if any come up as a partition (which is currently not how they are listed, just Panel right now, but so are other items), and then see which one has the greater depth. But then you are just taking a guess on which one that you tie it to for further changes.

**Comment by TEDSTANDAGE** [comment]
Perhaps this isn't possible at the moment for top shelf and that's fine, it's not hard to extend the topshelf forward. For the TK issue in #45 I think we probably can make it at least relate to the shallowest of the two partitions (the left and right that you click) rather than always just the left, so perhaps the topshelf can at least relate the the deepest of the two partitions (the left and right that you click) for the time being rather than just always the left.

**Comment by ClassyTeddy** [comment]
This is ready for testing on the `Top-Shelf-Improvements` branch
