### ISSUE TITLE
Only 18 Edgebanding Options

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#47]
**Disregard #44**

After the new csv was put in, now only 18 edgebanding colors appear:

![image](https://user-images.githubusercontent.com/61025894/80016458-00ad5680-8488-11ea-8e9b-a9b5fdfec85c.png)

Mark, can you push this to Ryan? Not sure if something was changed in a certain column of the csv that is causing this, but that's a lot of missing edgeband options.

**Comment by ClassyTeddy** [comment]
After seeing what was no longer available and by using my current understanding of the snap_import.py, I assume that there are a large portion of missing materials because the materials ItemTypeCode was changed in the merged .csv. In order to fix this problem, we either have to change the ItemTypeCode in the spreadsheet (which I don't know if Brock or any other department needs those numbers), or Ryan will have to change the way SNaP imports so that more item type codes can be used.

**Comment by RyanMDev** [comment]
@ClassyTeddy 

Previously, the color menu would show which material files do not have matching material files.

It is still useful for us to see which materials these are. So instead I am printing a list of these materials to the console on startup:

![no_render_file_for_eb](https://user-images.githubusercontent.com/6529544/80026136-78827d80-8496-11ea-9221-e83abaa7e36d.png)

These will all be an issue with the 'DisplayName' in CCItems not matching  any material file name.

**Comment by RyanMDev** [comment]
Additionally, the following file will determine which edge band types to include in the menus and what the display name should be.

`SNaP/2.78/scripts/addons/snap_db/db_init/EdgeTypes.csv`

![edge_type_codes](https://user-images.githubusercontent.com/6529544/80027560-cef0bb80-8498-11ea-8eb9-db330be2f08a.png)

![eb_typecode](https://user-images.githubusercontent.com/6529544/80027994-4fafb780-8499-11ea-9d5e-c958cd4fdd38.png)


You can use this the same as the material type menus similar to this:
https://github.com/CCDevNelson/SNaP-Dev/issues/173#issuecomment-617905590

To include new edge banding types, add them to this file and they will be imported.

So if we want to include say edge banding colors with 'TypeCode' 1030 then we add 1030 to this file.
![new_eb_type](https://user-images.githubusercontent.com/6529544/80028699-5f7bcb80-849a-11ea-937a-60b1c8ac4df1.png)
![new_eb_type_menu](https://user-images.githubusercontent.com/6529544/80028840-a79aee00-849a-11ea-943a-5b393bb18811.png)
![new_eb_menu](https://user-images.githubusercontent.com/6529544/80029025-fcd6ff80-849a-11ea-8460-8475a2c353e6.png)

**Comment by TEDSTANDAGE** [comment]
The colors/edgebanding look good after our re-work of the csv last week Teddy
