### ISSUE TITLE
Purple colors

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#48]
Teddy said he has fixed in his "Teddy Fixes" branch the following issue identified in #44 that I previously closed and have split up into separate issues after a conversation with Teddy:

The following colors show up purple (my understanding was that colors that didn't have a corresponding image would not show up on the drop down list, but maybe these items were given a temp purple image?):
-U Esterel
-U Mimosa
-U Mistral
-U Monaco
-Graphite Spectrum (this one should probably just not show up until the garage options / one side white one side color material options are available anyway)

Need to test.

Further, the Lakeshore Oak now appears in both CL and S in the Textured Melamine materials, but the corresponding edgebanding does not appear in the edgebanding dropdowns (#25 #26 ) -- this could be a part of the larger issue affecting all the other missing edgebanding materials though (Issue #47).

**Comment by TEDSTANDAGE** [comment]
Fetched Teddy-Fixes branch and tested these colors. The Uniboard colors now reflect the actual color and are no longer purple in that branch. Graphite Spectrum now shows the yellow yield sign, so I assume Ryan's rule for excluding those from the list should make that go away?

![image](https://user-images.githubusercontent.com/61025894/80018111-6b5f9180-848a-11ea-95d0-0f00e76b5c60.png)

The Lakeshore Oak issue seems to be resolved in the Master branch as both CL and S show up in the Textured Melamine materials and we will wait to see about the edgebanding part of that when the larger edgebanding issue is addressed.

**Comment by ClassyTeddy** [comment]
Ted, my version of the branch removed the graphite spectrum. However, my version does not have the new updates from the Master Branch, including the new rule that Ryan added for excluding items without corresponding material.blend files. This is why I tried to pull the branches earlier today, but just know for now that when the branches merge, the graphite spectrum will be gone.

**Comment by TEDSTANDAGE** [comment]
Great, thanks Teddy

**Comment by RyanMDev** [comment]
@ClassyTeddy I can help you here. Can you create a branch with just the following commit:
'Updated 5 blender files'

**Comment by RyanMDev** [comment]
Teddys commit:  e617a6db1d7b4f45b608cad5f56ab3316facd629 is now on master. This fixes the purple colors issue
