### ISSUE TITLE
Multiple elevations on 2D plans

### ISSUE THREAD

**Issue by TedClassy1209** [CCDevNelson/Snap-Updates#5]
Two things re: 2D plans:

1. Allow for multiple elevations to be on one page.

2. Allow for elevations to be on the same page as the plan view if able to fit.

**Comment by CCDevNelson** [comment]
Already Posted as #38 On Main Post

**Comment by TEDSTANDAGE** [comment]
Examples:

![image](https://user-images.githubusercontent.com/61025894/89741904-0c7a5400-da4a-11ea-9ad5-bcfdc9e1a6f1.png)

![image](https://user-images.githubusercontent.com/61025894/89741907-13a16200-da4a-11ea-8333-57d63487cebf.png)

**Comment by crbbdev** [comment]
I started working on this issue on this branch: https://github.com/CCDevNelson/SNaP-Dev/tree/issue_%23005-multiple_elevations

**Comment by crbbdev** [comment]
The main limitation to move the images closer is the rendering process. Some examples below.

![Wall_A](https://user-images.githubusercontent.com/69485485/91304101-f4f3d880-e776-11ea-89bf-b594770c524d.png)

![Wall_B](https://user-images.githubusercontent.com/69485485/91304120-fae9b980-e776-11ea-9797-1eb1ff151764.png)

Not sure why these images are being rendered with these margins but we could try to adjust the camera zoom.

**Comment by nailsonlandim** [comment]
That is a good question @TEDSTANDAGE 

I am checking it and AFAIK @RyanMDev added padding to each type of 2D scene (Plan view and Elevation)

I am performing a few tests to force it to edge cases but I guess we will face the opposite, lots of white space.

**Comment by nailsonlandim** [comment]
We can work to change that to each layout (4 walls, 5-6 walls, 7+ walls) and make something that fits better.

**Comment by nailsonlandim** [comment]
I've changed the Elevations page layout select box to a different position, to be more intuitive.

![2D Views - Plan and Elevations](https://user-images.githubusercontent.com/70038700/91447429-0dcfbd00-e84f-11ea-9fe7-965a0dfd2d2e.png)

Now I am working on your request and I will validate each one (4 walls, 5-6 walls, and 7+ walls) as I work on it, to avoid rework and to guarantee it is what you need.

![img20200826_12363810](https://user-images.githubusercontent.com/70038700/91447996-b7af4980-e84f-11ea-8f4c-a5285597a997.png)

**Comment by TEDSTANDAGE** [comment]
Thanks--I like the new location of the layout configuration button. 

Looking forward to exporting 4+ walls

**Comment by nailsonlandim** [comment]
Hi,
 @TEDSTANDAGE,

If you want to take a look, we've finished the layout for 4 elevations and we are working on the other options.

We found out that 5 basic layouts can form what you want. for instance, the layout for 4 elevations is a combination of #2 and #3.

We created a function that has these base layouts and we use it to make what we want, also this option makes the code more maintainable.

If you want to test it, I forked the repository. (https://github.com/nailsonlandim/SNaP-Dev)

[2D View.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5163852/2D.View.pdf)

![img20200901_12413680](https://user-images.githubusercontent.com/70038700/92016883-57297c00-ed29-11ea-83ed-4d2821cf9252.png)

**Comment by TEDSTANDAGE** [comment]
Thank you Nailson, I think it is looking good so far. I believe you already know this, but just note that elevations will always be on the same row as other elevations on a page--an elevation would never be place up/down of another elevation. Only plan views would be placed above elevations in layout #'s 4 and 5 of your above diagram (and plan views would never be below an elevation in those layouts). Looking forward to seeing the 5+ elevation options.

**Comment by TEDSTANDAGE** [comment]
I am not seeing the configuration options in the forked repository like I did on the previously created branch--can you give me instructions on how to find those options?

**Comment by TEDSTANDAGE** [comment]
![Untitled](https://user-images.githubusercontent.com/61025894/92022998-f8f09f00-ed10-11ea-9769-25bb4b0dd562.png)

**Comment by nailsonlandim** [comment]
> Thank you Nailson, I think it is looking good so far. I believe you already know this, but just note that elevations will always be on the same row as other elevations on a page--an elevation would never be place up/down of another elevation. Only plan views would be placed above elevations in layout #'s 4 and 5 of your above diagram (and plan views would never be below an elevation in those layouts). Looking forward to seeing the 5+ elevation options.

Understood, fixing this. 



> I am not seeing the configuration options in the forked repository like I did on the previously created branch--can you give me instructions on how to find those options?

It is on branch issue_#005-multiple_elevations in my forked repository (https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23005-multiple_elevations)

**Comment by TEDSTANDAGE** [comment]
Got it, okay thank you I was able to test it now. We have not used a separate repository before (only branches from the other main repository in the past) so I am still getting used to it.

**Comment by nailsonlandim** [comment]
> Got it, okay thank you I was able to test it now. We have not used a separate repository before (only branches from the other main repository in the past) so I am still getting used to it.
> 
> Note/edit--I am cool with the forked repository, it is nice to be able to have different versions open at the same time.

Thanks!

**Comment by nailsonlandim** [comment]
@TEDSTANDAGE  I've finished the layouts, take a look again and if you need to change anything let me know.

**Comment by TEDSTANDAGE** [comment]
Thanks Nailson I will check it out. @kategodfrey will you check this out too please? Call me for help on how to use a forked repository rather than just a new branch. Thanks, Ted

**Comment by TEDSTANDAGE** [comment]
This worked well for 6 walls--the first page was the plan view above 3 elevations and the second page was the last 3 elevations. However, when I tried doing 8 walls, I got the following error (I tried twice, that's why the error is showing twice):

![traceback error 2D views 8 walls](https://user-images.githubusercontent.com/61025894/92130182-488aa580-edb9-11ea-9c06-ffc37f82148a.png)

**Comment by nailsonlandim** [comment]
Thanks Ted, I will check it right now. Could you send the project file too?

**Comment by nailsonlandim** [comment]
I have tested it and I could reproduce the bug I caused. I just uploaded the fix, sorry for the inconvenience.

**Comment by TEDSTANDAGE** [comment]
> I have tested it and I could reproduce the bug I caused. I just uploaded the fix, sorry for the inconvenience.

No problem, we are working through this. I will test again.

**Comment by TEDSTANDAGE** [comment]
Nailson, the blacked out / weird 2D views I think may have been happening even before you were working on this so it could be unrelated. Not sure if anyone else in the group has experienced it before?

**Comment by TEDSTANDAGE** [comment]
8 walls worked for me this time with the plan view being on the first page by itself, 3 elevations on pages 2 and 3, and 2 elevations on the 4th page. Thanks!

**Comment by nailsonlandim** [comment]
> Nailson, the blacked out / weird 2D views I think may have been happening even before you were working on this so it could be unrelated. Not sure if anyone else in the group has experienced it before?

Ok, I will double-check it. 

What I could experience is that when you render again a 2d view you see these glitches. I usually close and open SNaP and render the 2d views again.

**Comment by TEDSTANDAGE** [comment]
> > Nailson, the blacked out / weird 2D views I think may have been happening even before you were working on this so it could be unrelated. Not sure if anyone else in the group has experienced it before?
> 
> Ok, I will double-check it.
> 
> What I could experience is that when you render again a 2d view you see these glitches. I usually close and open SNaP and render the 2d views again.

Yes, those glitches usually (if not always) seem to happen when I try to render a second time within a single running of the program, and restarting the program and starting fresh seems to fix the issue.

**Comment by TEDSTANDAGE** [comment]
@ClassyTeddy @kategodfrey @JBTattersall @SeanRadvan Can I get you all to test this? If you need help figuring out using a forked repository rather than just a separate branch let me know and I can walk you through it like Teddy walked me through it. I know we don't have the elevations sharing walls yet and I'm not sure when/if that is going to happen, but I believe this is a good start to having multiple elevations on one page and not having the extensive paperwork or as much cut/paste with .pdf editing software that will have to happen by the user.

Some instructions to get the new layouts and preparing 2D views (not worrying about dimensions):

Step 1, In 2D Views, press Prepare 2D Views:

![Prepare 2D Views Step 1](https://user-images.githubusercontent.com/61025894/92309343-9e964f00-ef59-11ea-8c6a-105126170c5a.png)

Step 2, select the walls and views you want rendered and then press Render Selected Scenes:

![Step 2](https://user-images.githubusercontent.com/61025894/92309347-a229d600-ef59-11ea-8c02-91d757e8f29c.png)

Step 3, select the Elevations Layout you want (Plan and Elevations will get the automatic layouts discussed above):

![Step 3](https://user-images.githubusercontent.com/61025894/92309396-051b6d00-ef5a-11ea-9d54-79e112e22657.png)

Step 4, click 2D Reports and select Save 2D Drawing As..., then save your file ensuring that the file name ends with ".pdf":

![Step 4-1](https://user-images.githubusercontent.com/61025894/92309440-693e3100-ef5a-11ea-949b-6bfc0df9c96b.png)
![Step 4-2](https://user-images.githubusercontent.com/61025894/92309444-6ba08b00-ef5a-11ea-9318-87f95c02f8e8.png)

**Comment by TEDSTANDAGE** [comment]
There is still a lot of white space between the various elevations/plan views. Were you able to address that @nailsonlandim ?

**Comment by nailsonlandim** [comment]
> There is still a lot of white space between the various elevations/plan views. Were you able to address that @nailsonlandim ?
> 
> Edit: I will create a new issue for addressing the white space.

Thanks for the feedback, I will take a look at that. doing the two following steps:

1) Reduce the padding on 2D rendered images. 

2) Using transparency using PNG images. It seems more complicated than we previously thought

I also want to add that looking at the current code base we are tied to Legal size, If you prefer, create an issue for that too. As it needs a select box and pass the property to the entire 2D views class.

**Comment by kategodfrey** [comment]
Tested this version and it worked great. I agree, there is a lot of unused white space and it would be nice to have the walls next to each other. But just having the multiple elevations on one page is a great update!
