### ISSUE TITLE
Riya's GitHub SNaP-Dev download pathway

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#51]
I want to make sure we aren't going to run into any pathway errors or issues with this--Riya cloned the SNaP-Dev repository from the GitHub desktop app and it looks to be in a little different than mine (and Teddy's--Teddy and I verified we have the same folders/subfolders). Here is what is in mine:

![IMG_5442](https://user-images.githubusercontent.com/61025894/80539451-5be5ba00-895c-11ea-948f-f457f9945d1b.jpg)

![IMG_5443](https://user-images.githubusercontent.com/61025894/80539456-5ee0aa80-895c-11ea-8954-9784e89cdd79.jpg)

![IMG_5444](https://user-images.githubusercontent.com/61025894/80539470-6902a900-895c-11ea-9a7a-a95d6ce57592.jpg)

Here is Riya's:

![IMG_5438](https://user-images.githubusercontent.com/61025894/80539496-75870180-895c-11ea-9ff7-ecd619d04b8c.jpg)

![IMG_5439](https://user-images.githubusercontent.com/61025894/80539506-77e95b80-895c-11ea-9eb4-824f99f97529.jpg)

![IMG_5440](https://user-images.githubusercontent.com/61025894/80539510-7a4bb580-895c-11ea-9d50-0f74139096d6.jpg)

![IMG_5441](https://user-images.githubusercontent.com/61025894/80539517-7ddf3c80-895c-11ea-8379-5fc48a7c9e8b.jpg)

Might this create issues or no?

**Comment by ClassyTeddy** [comment]
As I currently understand it it should not. In SNaP-Dev, we can see though same folders and files on GitHub.com, so she is cloning the latest working version.
