### ISSUE TITLE
Change SNaP closet defaults / startup settings

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#52]
Currently when there is an update to the csv file or certain other things, it requires us to "Load SNaP Defaults", which then gets rid of the defaults the user has set. This can be frustrating to those of us who are often loading and re-loading different versions/branches of SNaP. I'd like to set the startup file up with more common defaults (note that the defaults can be found in Closet Options as well as the Opening Sizes and Construction Option prompts):

-Have the "Add Pards" option shown 

-Have only the "Projects" tab open with SNaP Updater, Room Builder, etc. closed

-Re-Order the tabs as follows: SNaP Updater, Projects, Room Builder, Closet Materials, Closet Options, Closet 2D Setup, 2D Views, Advanced Options (Melissa, let me know if you disagree on this one)

-Default Wall Height: 96" (currently is 108")

-Material: Oxford White (should be set to dura white once we can change the door/drawer face material to be different, at which time Oxford White would be the default door/drawer face material)

-Edgebanding: Oxford White for Edge and Secondary Edge

-Default hang height: 83.25" (currently is 83.90)

-Default panel height: 47.37" (as-is)

-Default panel depth: 12" (as-is)

-Toe Kick Height: 4.39" (currently is 2.5" in both Closet Options and Construction Options--a 4.39" TK height corresponds with a 78.86" tall pard with a hang height of 83.25", the most common I see)

-Toe Kick Setback: 1.5" (Closet Options has the default setback at 1.12", but when you insert a TK now it is correctly defaulting to a 1.5" setback)

Melissa will have a bunch of things to add to this, so please wait to start working on this issue until she chimes in. Thanks!

**Comment by meltnaz** [comment]
On the order of tabs, I would place closet options above closet materials

Inside the closet options tab, can we default the list to start with wood doors, currently glass inset doors is the default 

For materials: add oxford white as the paint finish default

In 2D views Dimension options defaults  change defaults as shown here:

![defualt SNaP settings-dimension options](https://user-images.githubusercontent.com/32275766/80740515-0bda3500-8acd-11ea-9dbf-b3671a963a39.png)

For view portal:
Disable Grid floor
Add Z axis
(you'll find these in the view menu under viewport settings)

**Comment by TEDSTANDAGE** [comment]
Let's also have the default be for "Show Panel Drilling" to be enabled in Closet Options > Closet Defaults.

**Comment by ClassyTeddy** [comment]
I am currently working on this issue and I would just like to check to see if there are any other defaults we want applied at the moment. Some examples I have are the default flooring and paint options for rooms, the default stain color, and the default counter top selections. 

I also found a way change the defaults for user preferences. Things like themes, fonts, the way you control the 3D viewport, etc. I believe that this can be used to "Classy-fy" the interface as suggested in issue #32.

**Comment by TEDSTANDAGE** [comment]
Let's start with what we've given you for now, we may be wanting to update things as we move forward and make more additions to the program. As to the items you identified:

-Flooring/wall paint I say leave as is

-Set Oxford White as default stain/paint color

-Keep default countertop as melamine - same as Material Selection (looks like we need to update our countertop materials library)

I will let Katie know to contact you re: themes/fonts, etc.

**Comment by TEDSTANDAGE** [comment]
Thanks Teddy, just a few items:

1. "Add Pards" does not seem to be open on default:

![image](https://user-images.githubusercontent.com/61025894/81698181-77e86180-941a-11ea-8c6d-0fed0650a16f.png)

It should look like this:

![image](https://user-images.githubusercontent.com/61025894/81698214-82a2f680-941a-11ea-9d44-a682c4122427.png)

2. The 2D dimensions don't look to be updated to what Melissa requested. Here is what is default when I opened it:

![image](https://user-images.githubusercontent.com/61025894/81698348-b2ea9500-941a-11ea-8edb-366299d8cf1b.png)

It should be set to what Melissa had in her picture, above.

3. The default stain color looks to be set to "none" rather than Oxford White so let's update that as well:

![image](https://user-images.githubusercontent.com/61025894/81698491-eaf1d800-941a-11ea-9bfc-d605bb83c269.png)

**Comment by ClassyTeddy** [comment]
Hey Ted,

1. I had set it to be open, it is odd that it is not, I will check it and do some testing.
2. Unfortunately, my laptop cannot open the 2D Views tab, it does not even show up in the toolbox (After investigating, it appears to be a admin/firewall error, preventing python from automatically installing a specific library. It could also be a general installation error, but I am the only one with the issue, so I'm not sure)
3. I'll change the stain color, but do you want a default glaze and glaze style?

**Comment by TEDSTANDAGE** [comment]
Thanks Teddy, no glaze needed

**Comment by ClassyTeddy** [comment]
Made those two changes that I could, please test it again on the Snap-Defaults-Changes branch

**Comment by TEDSTANDAGE** [comment]
The stain color default looks to be changed to Oxford White but the Add Pards options still aren't open for me:

![image](https://user-images.githubusercontent.com/61025894/81712071-154a9200-9429-11ea-8dab-bd57aa845be3.png)

It says it is open, but the options aren't there as you can see and I have to go up and click it again for the options to actually show up. That's odd.

**Comment by ClassyTeddy** [comment]
I have a theory as to why the add pards folder is not showing up for you. The current default is looking at this file path to find the .pngs:

C:\Users\teddyr\Documents\GitHub\SNaP-Dev\SNaP\2.78\scripts\addons\snap_db\library_scripts\Library-Classy_Closets\products\Closets

If SNaP is looking for the FULL file path, then it is not showing up for you because this file path doesn't exist on your computer (There is no user named teddyr). This is pretty unavoidable as it is currently set up, and the best thing you can do is simply save a new startup file for yourself where the folder is open.

**Comment by TEDSTANDAGE** [comment]
@meltnaz please let us know how this works for you

**Comment by meltnaz** [comment]
I experienced the same...it's open to add pards, but images of pards are not showing.

I'd like closet options tab to go above materials tab. When I train people, I find that going through the options and talking through the overall closet build has a higher importance than the material options. My preference is to set tabs in order of importance to learning the tool and then designers can change it to their preferences later.

**Comment by ClassyTeddy** [comment]
Alright, I will make the change to bring closet options up higher. The add pards thing is currently unavoidable, but I feel it is the smallest issue, so instead of finding a complicated solution using file paths, I am going to leave it as is. 

Also, I can't change the 2D views on my work computer but I will make a note that the next time I am working on my desktop at home to change the defaults for that as well.

**Comment by RyanMDev** [comment]
@ClassyTeddy While reviewing your pull request for the `Snap-Defaults-Changes ` branch, I found a solution for the disappearing images/file browser path. So I will add the changes for the 2D view options as well before I approve and merge that branch.

**Comment by ClassyTeddy** [comment]
Awesome, thanks Ryan.

**Comment by RyanMDev** [comment]
Strange that you cannot view the 2D view options. No errors in the console when you try to bring it up? Feel free to create an issue for this if you find any more info, if nothing else at least we can keep track that it happens on occasion.

**Comment by ClassyTeddy** [comment]
I have a personal issue on my work laptop that won't allow me import a specific python library required for the 2D views addon in SNaP. It works for me at home, where my system is less restricted. It appears to be the only addon that is affected which is odd, but I have been working around it at the moment.

**Comment by TEDSTANDAGE** [comment]
Everything looks good to me for defaults except that 2D Views needs to be moved below 2D Setup. 

Add Pards comes up good for me now at startup. 

![image](https://user-images.githubusercontent.com/61025894/82073095-9bffa900-968d-11ea-8834-40f01c7e1e8c.png)

**Comment by RyanMDev** [comment]
> Everything looks good to me for defaults except that 2D Views needs to be moved below 2D Setup.

Set '2D Views' panel below '2D Setup' panel here: https://github.com/CCDevNelson/SNaP-Dev/issues/47#issuecomment-629390109
