### ISSUE TITLE
XML Drilling Data Ref #55

### ISSUE THREAD

**Issue by CCDevNelson** [CCDevNelson/Snap-Updates#56]
Drilling Ref #55 in SNaP-Dev "Ready for Testing"

Drilling depth is too deep. One sided drilling needs to be a Max of 14mm or 0.5in deep.

![DrillDepth](https://user-images.githubusercontent.com/44483142/80823985-6c7f7580-8b92-11ea-83bc-34ce0f82dfcb.png)

**Comment by ClassyTeddy** [comment]
This is ready for testing on the `Fix-Panel-Drilling-Depth` branch.

**Comment by CCDevNelson** [comment]
Guys, we have lost ALL drilling now! The skipper see the barcode, but only a few parts even loaded, and those that did, were sent out the other end of the machine without drilling a single hole. It's like ALL the drilling is there, but not.
I am able to look at some of the parts in my copy of CADCode and I notice that there are several partitions that have holes drilling  off the end of the partition. Not sure this would cause the total pattern to not drill, but should be fixed anyways.
I am forwarding the XML I have of this job to Ned @ CADCode to see if he can figure out what is going on with it.

**Comment by TEDSTANDAGE** [comment]
@RyanMDev 

Sorry for tagging you in a SNaP-Updates issue Ryan since Teddy is our single point man for you to avoid confusion, but Teddy is out the rest of the week and we want to be sure you are notified of this and seeing if you can think of a reason this might be happening. Teddy should be back on Monday.

Thanks, 

Ted

**Comment by RyanMDev** [comment]
No problem, I understand.

When was it last working?

Is this a result of using the master branch with the most recent commit (CCDevNelson/SNaP-Dev@009f7219b4ef213efdd83a6fe28d39e75944a0a4)?

**Comment by TEDSTANDAGE** [comment]
It was drilling (granted too deep and from the bottom) at the beginning of June, and the results of that testing led to the creation of the recent drilling updates like https://github.com/CCDevNelson/Snap-Updates/issues/84 and https://github.com/CCDevNelson/SNaP-Dev/issues/209. 

We have not done any actual physical machine testing in the interim, so I wouldn't say it's necessarily the result of the most recent commit. For the most recent test we used the XML you provided in https://github.com/CCDevNelson/SNaP-Dev/issues/221.

**Comment by RyanMDev** [comment]
[snap_job_no_pformat.zip](https://github.com/CCDevNelson/Snap-Updates/files/4899840/snap_job_no_pformat.zip)

Here is a modified xml.

Can you test this and see if the same errors occur?

**Comment by TEDSTANDAGE** [comment]
Mark @CCDevNelson would it be possible to pick a KD shelf or two and a couple partitions from this XML for us to try to test on the machines tomorrow?

**Comment by TEDSTANDAGE** [comment]
Thank you Ryan

**Comment by TEDSTANDAGE** [comment]
Hi Mark @CCDevNelson, I'm thinking the following parts from the XML Ryan provided yesterday would be good to test:

IDP-4 (47.37x12 partition, I'd guess it's a single)
IDP-7 (78.86x12 partition, double)
IDP-10 (24x12 KD from closet carcass)
IDP-78 (24x12 KD from assembly)

Let me know what you think. Thanks, Ted

**Comment by CCDevNelson** [comment]
Ted I ran some of that job trough CADCode last night, and printed the labels for a few of the parts.
NONE of the KD's have drilling. and the 78.86 partitions still have too many holes.
But, we can test what I have....

**Comment by TEDSTANDAGE** [comment]
Thank you Mark, I think we test a couple of the partitions then to see how they do then

**Comment by RyanMDev** [comment]
Fixed extra drill holes on partitions with commit: CCDevNelson/SNaP-Dev@b2ff74eb22f5935b6b11a5289f5af76728547327

**Comment by CCDevNelson** [comment]
Drill test on the 47.37 partitions from XML Test: **_snap_job_no_pformat.xml_**........

Single drilled correctly, double sided one did NOT drill at all. Also noticed that it is making a label for each side, and that's not suppose to happen. It should be one label, wit one drill pattern for that partition.

No KD's had drilling on them, so no testing on those was able to be done.

**Comment by CCDevNelson** [comment]
Drilling test today results:

1.) Everything is drilling from the bottom side up. This needs to be changed to drilling from the top down (This is for ALL single sided drillings).
2.) Double sided partition did NOT drill either side and just spit the part out the end of the machine.
3.) Blind Corner Partition (46.46 but is coming out 46.45), drilled the row of holes on the wrong end of the partition. Holes should be on front side (next to the edge banding edge) but when drilled, they were on opposite side.
4.) on ALL the partitions - The front line of holes are 37mm from the front edge (edge banded side) The back line of holes should be 43mm from the back edge - they currently are drilling at 37mm from the back and this is incorrect.

[Drilling_7_20_20.zip](https://github.com/CCDevNelson/Snap-Updates/files/4955547/Drilling_7_20_20.zip)

**Comment by TEDSTANDAGE** [comment]
I think perhaps a phone conference call with Ryan, Mark and Ned participating could be helpful with regard to figuring out the drilling issues here. @RyanMDev , if you think it would be helpful perhaps Mark can set up a time for you all. What do you think?

**Comment by RyanMDev** [comment]
Sounds like a good idea to me.

**Comment by TEDSTANDAGE** [comment]
Thank you Ryan. 

Mark @CCDevNelson , please coordinate that meeting between the three of you to get the drilling sorted out.

**Comment by CCDevNelson** [comment]
Results from extensive drill/XML testing today:

1.) All parts are still drilling from the bottom up.
2.) All parts are also drilling "flipped" front-to-back.
3.) KD Shelves are now drilling the 4 KD fitting holes in the correct spots (with regard to #2 above, anyways)
4.) Doors did not have hinge drill info so no holes were drilled. Also, even though holes for the handles showed, they errored due to incorrect drill info for those holes. These aren't going to be drilled on the machine (at least at this point) so these need to be removed.
5.) Made several tries at modifying XML data to correct drilling side and front-to-back flip with NO positive results. It does seem that there is no way the XML file can tell our machine what side to default drill on or which end to swap location to when the side changes. So this does look to be a CADCode fix at this point.

**Comment by TEDSTANDAGE** [comment]
Thank you for all of that work Mark, we will wait for Ned then to hopefully have a fix for these items we can't manipulate through the XML data.

**Comment by TEDSTANDAGE** [comment]
Mark, I am just following up to see if we have an ETA from Ned. Thanks, Ted

**Comment by CCDevNelson** [comment]
I spoke to Ned yesterday, but there was no update on any timeline. He did say it was much more complicated than first thought. He also sent some test file for me to run on the skipper to see if it drills as expected in his screen shot. I will be running these test as soon as I can get on the machine.

**Comment by RyanMDev** [comment]
Posted two new XML files to test:

https://github.com/CCDevNelson/SNaP-Dev/issues/218#issuecomment-696296086 - Now that we have single-sided drilling coming from the top down on a left-side drilled panel, this flips the face for right-side drilled panels so that they are drilled the same (from the top down).

https://github.com/CCDevNelson/SNaP-Dev/issues/218#issuecomment-696419155 - This fixes the Blind Corner Panel drilling to drill holes on the front/edgebanding edge.

**Comment by TedCC1209** [comment]
https://github.com/CCDevNelson/Snap-Updates/issues/125#issuecomment-737208502
