### ISSUE TITLE
XML Data needed to be added for Shop Production

### ISSUE THREAD

**Issue by CCDevNelson** [CCDevNelson/Snap-Updates#57]
I need to have several fields added to the label portion of the XML for information needed fin the shop for production.

**Comment by CCDevNelson** [comment]
![ItemInfo](https://user-images.githubusercontent.com/44483142/81431212-a82bb980-9115-11ea-90ca-cca81d1a6cf9.JPG)
I need the "Room Name" added to a Label field. Ned is telling me that I can't access info at the Item level.

**Comment by CCDevNelson** [comment]
As well as all of the info that is being written to vars at the bottom of the XML. This needs to go into a Label as well.
I'm thinking we should put ALL these along with the above issue, into a Label that is like the LAST label for each Item. I think that would work, but I am going to check with Ned on that one.
![VarInfo](https://user-images.githubusercontent.com/44483142/81431650-57689080-9116-11ea-9b11-68949b3f5ff1.JPG)

**Comment by CCDevNelson** [comment]
This is going to be tried and handled a different way for the moment...please hold off on doing anything with this at this time.

**Comment by CCDevNelson** [comment]
New update on this:
Ryan does need to add these things to "Item" level XML.
![ItemVarPic1](https://user-images.githubusercontent.com/44483142/81597100-01942280-937a-11ea-8e4a-f33a1ec37913.png)
![ItemVarPic2](https://user-images.githubusercontent.com/44483142/81597104-03f67c80-937a-11ea-9b17-08338956cf41.png)
Ryan, I need these two items added as vars at the Item level. Pic1 shows the values I need, and second pic show where and how they are named and added. VERY much the same way the vars are added to the end of the job, but these will be at the Item Level. This is so I can access them for our label printing. Any questions on this, please give me a call.
Mark

**Comment by TEDSTANDAGE** [comment]
Teddy, please ask Ryan to push it to the top of his to-do list. Thanks, Ted

**Comment by CCDevNelson** [comment]
Another change to the XML:
Working with CADCode on the labeling for the shop, I need to have the 4 **edge[_x_]name & edge[x]sku** changed to edgebanding1, edgebanding2, edgebanding3, and edgebanding4
This is needed so that the software will pickup edge information.
![EdgebandChange](https://user-images.githubusercontent.com/44483142/81746876-05987100-945c-11ea-802a-3efa477ca7b9.jpg)

**Comment by RyanMDev** [comment]
https://github.com/CCDevNelson/SNaP-Dev/issues/185#issuecomment-627611771

> Dose this look correct?
> 
> ![eb_filed_nmaes](https://user-images.githubusercontent.com/6529544/81748046-029e8000-945e-11ea-8fbf-c11414f1f5f6.png)

**Comment by CCDevNelson** [comment]
Ryan,

No. it should be edgeband1 for the one that was the "edge1name"
for the edge1sku I was just saying it could go to edgeband1sku, edgeband2sku, etc.

**Comment by CCDevNelson** [comment]
The edge1name just wasn't being picked up by cadcode, so it has to be edgeband1, edgeband2, etc. just can't have the "name" after it.

**Comment by RyanMDev** [comment]
Alright, so more like this then:

![eb_filed_names_2](https://user-images.githubusercontent.com/6529544/81749722-07186800-9461-11ea-9d53-abfb19b0e940.png)

**Comment by CCDevNelson** [comment]
Sort of....it should be **edgeband** not edgebanding though....I think I messed up on the first post.

**Comment by RyanMDev** [comment]
Is this better?

![eb_filed_names_3](https://user-images.githubusercontent.com/6529544/81751577-8f4c3c80-9464-11ea-9739-72cd3e1402e0.png)

**Comment by CCDevNelson** [comment]
Perfect!!
