### ISSUE TITLE
Correct Melamine Drawer Box Sizes (and add ability for custom size drawer box depth)

### ISSUE THREAD

**Issue by TedClassy1209** [CCDevNelson/Snap-Updates#59]
Right now drawer boxes are being sized a 2" shallower than the section they are in (i.e., a 16" deep section gets a 14" deep box). The following are the current exported drawer box part sizes for a 10H drawer box in a 16" deep 24" wide section:

![image](https://user-images.githubusercontent.com/61025894/81727121-52208400-943d-11ea-8434-6a0b40a690cf.png)

![image](https://user-images.githubusercontent.com/61025894/81727151-5a78bf00-943d-11ea-996e-91d5345953eb.png)

The 2" shallower rule is a good default for sections greater than 16", but for 16" and shallower sections we need to default to 1.25" shallower rule, meaning a 14.75" deep box in a 16" deep section (the sides need to be extended .75" and the bottom needs to be .75" deeper in the above example) 

Also, we should allow for custom drawer box depths (depending on what is behind a box, like an outlet or other obstacle, we might want a shallower box).

**Comment by TEDSTANDAGE** [comment]
The height of the drawer box front/back/sides needs to be fixed as well to match our system. Here is the chart:

![image](https://user-images.githubusercontent.com/61025894/81729769-61093580-9441-11ea-8ef9-b8a509fd9276.png)

Note how the 4H drawer side height is 2.00--a true 4H drawer box height would be 2.68, but we do 2.00 tall EXCEPT when there is a side lock, then we need a True 4H drawer box height of 2.68".

Note how the 3H drawer side height is 1.62.

The 5H and over drawer boxes are more standardized with the 32mm hole system.

**Comment by TEDSTANDAGE** [comment]
Teddy, we just talked about this but I wanted to get it here as well--we use the 2" tall drawer boxes for both 3H and 4H drawers. We never use the 1.62" 3H drawer box. 

Not sure if you can disable locks for just 3H drawers, but they don't really work for 3H drawers.

**Comment by ClassyTeddy** [comment]
This issue has a fix on the Teddy-Fixes 5/12/20 Branch

**Comment by TEDSTANDAGE** [comment]
This looks really good, thank you Teddy. We should probably just create a new issue for the "True" 4H box side height for side locks on 4H drawers and push this fix as-is. Also it'd be nice to test this with the correct drawer box material export as well when that's possible.

**Comment by ClassyTeddy** [comment]
This is ready for testing on the `Double-Jewelry-Drawer-Box` branch.

**Comment by TEDSTANDAGE** [comment]
Looks good, thank you
