### ISSUE TITLE
Add File Rail option to 10H boxes

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#60]
Need to add 1/2" file rail option to 10H drawer boxes--need the option for letter size and legal size and for vertical (front to back) or lateral (side to side) orientation. Whoever is assigned this item, please see me for application and sizing.

**Comment by TEDSTANDAGE** [comment]
Where can I test this

**Comment by ClassyTeddy** [comment]
Teddy-Fixes5/12/20

**Comment by TEDSTANDAGE** [comment]
This is looking good from what I've tested

**Comment by TEDSTANDAGE** [comment]
Need to make sure it is exporting as the correct material when it is on the branch that has the correct drawer box material.

**Comment by ClassyTeddy** [comment]
I will close this issue for now, and we can see about it using the correct material when the branch get merged to the master.
