### ISSUE TITLE
Cleat & Cover Cleat Size

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#64]
Cleats and cover cleats look to both be exporting in the XML at 3.65 inches tall.

![image](https://user-images.githubusercontent.com/61025894/81950614-0266c780-95b9-11ea-81dd-d8e4aac8b31f.png)

Cleats need to be 3.64 and cover cleat needs to be 3.68 tall.

**Comment by CCDevNelson** [comment]
Ted, There is a setting in the construction screen for setting that height.

**Comment by TEDSTANDAGE** [comment]
Can you screenshot it? If there is a setting for cleat and cover cleat height then the default needs to be set to 3.64" for top/bottom cleats and 3.68" for cover cleat.

**Comment by CCDevNelson** [comment]
![image](https://user-images.githubusercontent.com/44483142/81958947-96d62780-95c3-11ea-8c9a-b1bce96aab12.png)

**Comment by CCDevNelson** [comment]
You are right that the default needs to be set at 3.64"....this 4" default was put in way back when Micro Velum had put setting in.

**Comment by TEDSTANDAGE** [comment]
Does the cleat or cover cleat height even relate to that setting? It doesn't seem to--In the job for the XML I have in my original posting of this issue, the nailer has that same setting but the XML has 3.65" for the top/bottom cleats and the cover cleat anyway.

![image](https://user-images.githubusercontent.com/61025894/81959413-4612fe80-95c4-11ea-8794-1c7cd742925d.png)

**Comment by ClassyTeddy** [comment]
I just want to add a comment here. The advanced cabinet options have no affect on any of the products in the Closets libraries. I believe that this tab is for the Cabinets-Frameless products that I believe Sarah was working on. This option may need to be disabled by default in order to ignore confusion.

**Comment by ClassyTeddy** [comment]
The fix for this issue is ready on the Teddy-Fixes-5/12/20 Branch. All cleats should be 3.64" and all cover cleats should be 3.68". 

Cover cleats will also adjust if they are connected to a top or bottom cleat, so they are flush with the top or bottom respectively (Have only tested this on the Hanging Partition, and cleats that aren't specified to be top or bottom cleats will most likely act like top cleats).

**Comment by TEDSTANDAGE** [comment]
Thanks Teddy, the top/bottom cleats and cover cleats look good in the carcass as far as being 3.64/3.68. We will need to check the cleats when we add an extra cleat for library items like drawers/hampers, etc. Here is a job I did to check the cleat in various assembly scenarios:

![image](https://user-images.githubusercontent.com/61025894/81977046-4fa96000-95de-11ea-951c-f580605e2c4e.png)

Here is the cleat behind the drawers that still is 3.65:

![image](https://user-images.githubusercontent.com/61025894/81977212-867f7600-95de-11ea-9cf3-cdb6e00ae8b8.png)

The cleat behind the hamper is still 3.65 as well:

![image](https://user-images.githubusercontent.com/61025894/81977275-9e56fa00-95de-11ea-8b6a-2719e0fbfbde.png)

We may need to go library by library item to make those changes but for the basic library items I think the drawers & hamper are the only ones. The other library items I can think of on the top of my head that may need to be looked at are the uppers? But the cleats/cover cleats in those may relate to the changes you made to make the carcass cleats/cover cleats the correct size and I haven't looked into the uppers very much.

**Comment by ClassyTeddy** [comment]
I had gone library by library item, thinking I had got them all. I will go through again. I also changed the default "Cleat Height" prompt that is available and made it so that when a cleat is made it should start at 3.64, but it looks like I missed a few spots.

**Comment by TEDSTANDAGE** [comment]
Teddy, let me know when you make the change to the "Bottom Cleat" behind the drawers and hamper so I can test. Thanks

**Comment by ClassyTeddy** [comment]
Made the changes to the bottom cleats for drawers and hampers so they should now be 3.64"

**Comment by TEDSTANDAGE** [comment]
This looks good to me, not sure if anyone else is testing

**Comment by TEDSTANDAGE** [comment]
Teddy, we need Ryan to merge this fix so we can continue testing.

**Comment by CCDevNelson** [comment]
Cleat and Cover Cleat are sizing correctly through to XML.
Closing this issue.
