### ISSUE TITLE
Option to export XMLs by room and not entire project

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#68]
Would be nice to export an XML where you can choose less than all the rooms within an entire project to export--sometimes designers may create different design options for a client to choose from and it'd be nice to not have to delete the rooms/work put into the other options. Or, with a single project a designer may create multiple rooms for all the closets in someone's house and then the client decides just to move forward with one (or less than all) for now, and wants to wait to do the other rooms later. 

This would also help with our pricing software since it works off the XML--we could provide a price by room/closet and not by entire project.

**Comment by TEDSTANDAGE** [comment]
This option is great and I like how it is laid out. My only change would be about adding room name info to the labels--Mark, is there a place / room on the label for the room name?
