### ISSUE TITLE
Wire basket options

### ISSUE THREAD

**Issue by meltnaz** [CCDevNelson/Snap-Updates#70]
The basket option used to allow users to have a stack of baskets with different heights for each one.
Can we revert to the way they were? Did I miss the reason that option was removed in the first place? Same thing would go for the pant hanger.

We now have more folks on the team working to improve things, but it seems that we are losing some of the options that we used to have without a new/better item to replace them with. It would be nice to have those items back in the catalog just from a sales perspective.

**Comment by TEDSTANDAGE** [comment]
Tbh I don’t remember the accessories being taken out Melissa. All changes I’ve requested are done through issues here in github and if you’ve been silent on things I’ve been taking that as you agree or are good with it since you should be getting emails/alerts with the committee on each of them (or I have specifically tagged you in the post). Also, if these baskets were taken out last year with the pant rack, then that was before more people were here to improve things..

Teddy can you look to see when these types of items / accessories were removed and we can see about getting them back on? It was likely a while back.

**Comment by meltnaz** [comment]
Yes, sorry for not responding on that, but I don't recall when the basket options were changed. It was several months ago maybe back when Matt was working on some of these things? I just wanted to bring that item back up. I forget that they're not there in the same functionality until I need to use them and then remember that I need to bring it up on Github.

**Comment by ClassyTeddy** [comment]
Hey Melissa, I found a lot of the accessories that were taken out for one reason or another and they are still in the code (just commented out so they are non-functional). I can pretty easily re-enable them but I would need more information on which accessories and features we want re-enabled. We should discuss this at the meeting tomorrow in more detail.

**Comment by ClassyTeddy** [comment]
I have added back in 9 accessories that were still in SNaP code. I am currently trying to figure out why the wire baskets prompts were removed, but in the meantime if @meltnaz could test what is in there and what needs to be fixed/removed that would be great. 

Also, I tested to see if the accessories would export and they do. I'm not positive this will be a problem (seeing as how all accessories exported, not just the 9 I added in), but it might be. 

The changes were made on the "Adding_Accessories_Back" Branch.

**Comment by ClassyTeddy** [comment]
Just added the wire basket prompts back to the wire basket. This can be tested on the "Adding_Accessories_Back" branch.

**Comment by TEDSTANDAGE** [comment]
Thanks Teddy, looks good to me. We will wait for Melissa to let us know if there is anything else missing that she notices.

**Comment by meltnaz** [comment]
Awesome!! So glad to have these back. All looks good to me. Seems to be working as they used to.
Thank you!

**Comment by TEDSTANDAGE** [comment]
Was this merged with the master?
