### ISSUE TITLE
Create Short Hang Library Item

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#71]
Right now the available hang options in the SNaP library are as follows: Hang Double, Hang Double Tall, Hang Long, and Hang Medium

![image](https://user-images.githubusercontent.com/61025894/82451311-aa214100-9a62-11ea-8e8b-7df3507a4278.png)

A common hang section we use is a "Short Hang" which (standard) is essentially the Double Hang but the top hang is taken out and 4 additional shelves are added in its place (for a total of 5 shelves). Here, is a picture of a Long Hang, Short Hang, and Double Hang (from left to right):

![image](https://user-images.githubusercontent.com/61025894/82451815-5400cd80-9a63-11ea-8a76-e2d9159f0dc8.png)

The Short Hang is similar to a medium hang except that the hang is located at the bottom of the partition (like the bottom hang of a double hang) and there are a couple more shelves. Right now when you try to manipulate a medium hang into a short hang by moving the hanging section down and adding a couple shelves the bottom shelf of that adjusted medium hang section does not match the vertical location of the bottom shelf of a double hang next to it, and it'd be easier not to have to make those adjustments every time for an item that is so common. See the following:

![image](https://user-images.githubusercontent.com/61025894/82452097-ad68fc80-9a63-11ea-833e-d22463614ddc.png)

So, I'd like Riya & Teddy to create the Short Hang library item. The easiest way to do it I think would be to either copy the medium hang or the double hang and then make the adjustments to make it a short hang. Please make sure that bottom shelf matches the vertical location of the bottom shelf of a double hang. This is another issue I'd like the two of you to tackle together because it will lay the knowledge & skill groundwork for some of the more complex/difficult library items to come. Let me know if you have any questions.

**Comment by ClassyTeddy** [comment]
This new library item is on the new Branch-Short-Hang branch, and is ready for testing.

**Comment by TEDSTANDAGE** [comment]
Looking great, thank you guys. A few things:

1. Let's change the default to have 5 total shelves please (both in the library png and when placed in a section).
2. After looking at what we have named the other hanging library items in SNaP, let's rename this current library item you just created "Hang Single" and 
3. Let's also create a "Hang Single Tall" where the hang would default at 47H (59.96) rather than 37H, and there would be a default of 7 shelves rather than 5.
4. For the single hangs (Hang Single and Hang Single Tall), can we delete the "Add Rod", "Add Dust Shelf", and "Add Shelves" options in the Top Opening Hanging Rod Prompts here? Keep the "Add Rod at Top" option":

![image](https://user-images.githubusercontent.com/61025894/82482473-c1c0ef80-9a8b-11ea-8645-2d014c49f492.png)

5. After doing number 4, I wonder if (and hope) the shelves would space themselves out better up and down the partition instead of just being spread between the bottom dust shelf and where the "Add Rod" Top Opening location is set.

Let me know if you have any questions. Thanks!

**Comment by ClassyTeddy** [comment]
Hey Ted, a couple of replies to your request.

1. Putting more shelves in by default should be really easy.
2. Renaming shouldn't be a problem.
3. Making a new Hang Single Tall should also be fairly simple.
4. I will have to look at how we want to handle this. I also really don't like the UI clutter that comes with the prompt menu of all the hanging openings, but since all 5 Hangs use the same single file for their prompts and construction, it might be fairly complicated to get right. 
5. I was also considering this when creating the Hang Short. But how would you prefer the shelves to be spaced out? I could probably pretty easily have the shelves space between the bottom dust shelf and just the top of the partition, but spacing with specific holes in mind would be a lot more complicated to implement.

**Comment by TEDSTANDAGE** [comment]
4. If it is going to create issues with the other hang types because they all use the same single file then it's fine to keep those options for now. Eventually it'd be nice to get rid of them.
5. I'd like the shelves spaced out from the bottom dust shelf to the top of the partition if possible, we don't need to worry about them sitting on particular holes or anything.

Thanks

**Comment by riyajose96** [comment]
1. Changed the default to total 5 shelves.
2. Renamed library item to "Hang Single".

Library item is on the Branch_Short-Hang branch.

**Comment by riyajose96** [comment]
3. Added library item Hang Single Tall with 7 Shelves by default and hang by default set at 47H(59.06).
Library item is on the branch -- Branch_Short-Hang.
<img width="413" alt="HangSingleTall" src="https://user-images.githubusercontent.com/64493941/82501909-e9738000-9aaa-11ea-9443-1800298dd569.PNG">

**Comment by TEDSTANDAGE** [comment]
It is looking really good Riya, thank you. One thing is that the default you have for Single Hang has 6 shelves (a dust cover shelf and 5 additional shelves) instead of 5 and the default you have for Single Hang Tall has 8 shelves (A dust cover shelf and 7 additional shelves). Please have one less additional shelf for each so that we end up with 5 total shelves for Single Hang and 7 total shelves for Single Hang Tall.

Then, if you guys could figure out shelf spacing after that I think this should be pushed to Ryan and the issue can be closed out unless anyone else is finding something in their testing.

![image](https://user-images.githubusercontent.com/61025894/82563937-c25d9280-9b2c-11ea-88c5-453b4441918b.png)

**Comment by riyajose96** [comment]
Number of shelves of "Hang Single" corred to 5 (a dust cover shelf and 4 additional shelves) and of "Hang Single Tall" corrected to 7  (a dust cover shelf and 6 additional shelves).

Library item is on the branch -- Branch_Short-Hang.

**Comment by riyajose96** [comment]
4. For the single hangs (Hang Single and Hang Single Tall) deleted the "Add Rod", "Add Dust Shelf", and "Add Shelves" from Top Opening Hanging Rod Prompts.
<img width="260" alt="HangSingleTall_HangSinglePrompt" src="https://user-images.githubusercontent.com/64493941/82579080-276fb300-9b42-11ea-8dcb-640af0225ba9.PNG">

**Comment by TEDSTANDAGE** [comment]
Thank you for those recent changes, they look good. 

Also, let's update the .png to match the 5 & 7 shelves (still showing 6 and 8):

![image](https://user-images.githubusercontent.com/61025894/82586105-e2e91500-9b4b-11ea-9232-6149ff586953.png)

**Comment by riyajose96** [comment]
Updated the .png of single hangs (Hang Single and Hang Single Tall).

**Comment by riyajose96** [comment]
Renamed Hang Single and Hang Single Tall to Hang Short and Hang Short Tall.

Library item is on the branch -- Branch_Short-Hang.

**Comment by ClassyTeddy** [comment]
I have updated the shelf spacing for the Hang Short and the Hang Short Tall, making it so that the shelves are now evenly spaced between the bottom shelf and the top of the partition. This only changes the Hang Short and Hang Short Tall items.

**Comment by TEDSTANDAGE** [comment]
It looks like the Hang Short Tall is putting the rod one hole below a 59.96" partition:

![image](https://user-images.githubusercontent.com/61025894/82914501-704db000-9f24-11ea-8f93-67032f9ab082.png)

Let's move it up to match where the Hang Double Tall has its bottom rod (as seen to the right of the hang short tall in the pic above).

Otherwise it is looking really good from what I see.

**Comment by ClassyTeddy** [comment]
Hang Short Tall should now start at the same hole as Hang Double Tall. This is ready for testing on the "Branch_Short-Hang" branch

**Comment by TEDSTANDAGE** [comment]
Looks good to me

**Comment by ClassyTeddy** [comment]
I am going to close this branch and create a pull request to merge the branch with master.
