### ISSUE TITLE
XML export logic for oversizing small topshelf 

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#72]
Currently Ryan is working on the issue of exporting large top shelf lengths in https://github.com/CCDevNelson/SNaP-Dev/issues/96. My understanding is that right now, if a top shelf length is over 96", SNaP exports two 96" lengths. The large top shelf issue above is dealing with situations were we would need more than two 96" top shelf lengths.

For this issue, I'd like to address how SNaP exports top shelf lengths under 96". Right now it appears to just export the top shelf exactly the length as it is in the drawing. Here is an example room:

![image](https://user-images.githubusercontent.com/61025894/82472170-9c78b500-9a7c-11ea-9f1a-663e697aa93a.png)

The left wall partitions, which are tight on the left side of the wall, are 56" wide with a TS with an exposed right end and SNaP exported the TS exactly 56" wide:

![image](https://user-images.githubusercontent.com/61025894/82472294-d1850780-9a7c-11ea-8132-65f1cec7f64c.png)
![image](https://user-images.githubusercontent.com/61025894/82472306-d5b12500-9a7c-11ea-9a3d-bde00c8b5e0d.png)

If I were doing the cut sheet, I would have entered an oversized TS (60" because we do 60, 72, 84, and 96" TS lengths as our standard) with one exposed end just in case that left corner was out of square, etc.

The middle wall is 80" wide with the topshelf spanning the entire width of the wall and SNaP exported the TS there exactly 80" wide:

![image](https://user-images.githubusercontent.com/61025894/82472760-84edfc00-9a7d-11ea-8a58-dbcca1199efc.png)
![image](https://user-images.githubusercontent.com/61025894/82472620-5112d680-9a7d-11ea-9b55-a1fd3d2d891d.png)

If I were doing the cut sheet, I would have entered an oversized TS of 84" to account for potentially out of square corners, etc.

The right wall has a TS with both ends exposed, and SNaP exported the TS exactly 18":

![image](https://user-images.githubusercontent.com/61025894/82472874-a5b65180-9a7d-11ea-92d5-9ac61e2e4b50.png)
![image](https://user-images.githubusercontent.com/61025894/82472916-af3fb980-9a7d-11ea-9dfa-30aa9367f3da.png)

This is correctly exporting this TS because both ends are exposed and you wouldn't want to oversize it because you wouldn't want to / don't need to cut it.

We need to add XML export logic to oversize topshelf that is not exposed on both ends. Do not work on this or pass this up to Ryan yet though--we need to discuss and decide as a committee if we want to (1) keep the standard 60, 72, 84, 96 standard sizes, (2) if we want to just have it add X amount in the export like we do for variable sections/TKs, or (3) if we want to just export full 96" lengths of TS (this would mean the most wasted material)

**Comment by ClassyTeddy** [comment]
Hey Ted, Ryan is waiting for a little more information on this issue before he moves on with CCDevNelson/SNaP-Dev#96. The reason for this is because what we decide on will affect how he moves forward with changing the Top Shelf export logic. I will get back to him with more information after we discuss this topic at the meeting tomorrow.

**Comment by ClassyTeddy** [comment]
This is ready for testing on the `Top-Shelf-Improvements` branch
