### ISSUE TITLE
9 Hanging Opening only has prompt for 8 of the openings

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#73]
The 9 Hanging Opening only has prompts for 8 openings, leaving the 9th opening un-editable. We need to make it functional.

![image](https://user-images.githubusercontent.com/61025894/82564307-68110180-9b2d-11ea-8963-a326cf38e00a.png)

**Comment by ClassyTeddy** [comment]
This issue should be fixed and is ready for testing on the "9_Hanging_Opening_Promp_Fix" branch

**Comment by TEDSTANDAGE** [comment]
Looks good to me
