### ISSUE TITLE
Managing extensive project list view

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#75]
I am wondering how we can manage viewing lengthy/extensive project lists. The number of projects I have is starting to climb, so I can only imagine what a designer might accumulate over time on their computer. I know I can delete mine, and for now it won't be a problem, but a designer would likely not want to delete their projects and lose that work. Right now there doesn't seem to be a limit on how big the window showing the list of projects can get:

![image](https://user-images.githubusercontent.com/61025894/82565373-284b1980-9b2f-11ea-8a7f-257c2f0909f3.png)

Perhaps we can limit the size of that window (big enough to show 10 or so projects?) and then it turns into a list you have to scroll up/down through?

**Comment by meltnaz** [comment]
When you click the X it doesn't delete the project. It just takes it off the list. Designers can eliminate old/unsold projects as needed from that window. No need to keep the list long, but designers can decide what they want to see. Hard part is putting something back on that list when it get clicked accidentally.

**Comment by TEDSTANDAGE** [comment]
How many jobs might a designer have up there at one time and would limiting the window/view size there to be a scroll menu after it reaches 10 or so jobs not help? And if it's hard to put something back on the list, then perhaps making the window/view more manageable would be better?

**Comment by meltnaz** [comment]
I was told you could have an infinite amount of projects there.  Honestly, I think some designers like seeing all of their project there. It keeps client names front of mind, and it is kind of a record of the work that they've done. I haven't had anybody complain about it.

In training, I tell designers that they can click the X to take a project off the list.

**Comment by TEDSTANDAGE** [comment]
Okay I think we are getting off from the point of what I posted. The two lines I have circled in the picture can stretch the viewport/box bigger to have empty space for some reason, but not smaller than showing the entire list of projects all at once:

![Inked82565373-284b1980-9b2f-11ea-8a7f-257c2f0909f3_LI (2)](https://user-images.githubusercontent.com/61025894/82913308-fff25f00-9f22-11ea-8663-992586f9562a.jpg)

![image](https://user-images.githubusercontent.com/61025894/82913311-01238c00-9f23-11ea-87fa-e66329327ebb.png)

I'd like to be able to make that viewbox smaller so that when my project list gets longer like it is, I can shorten it to the size of the square I drew in pic #1 and be able to scroll down through the jobs rather than having the list take up my whole screen like it is. Teddy/Riya, please let me know if this makes sense or if you have any questions.

**Comment by ClassyTeddy** [comment]
I limited the maximum number of visible projects to 5. Take a look at this on "Teddy-Fixes-5/12/20" and let me know what you think.

**Comment by TEDSTANDAGE** [comment]
Looks good, and users can adjust it to what they want from there.
