### ISSUE TITLE
Creating multiple shelf depths in hanging sections

### ISSUE THREAD

**Issue by meltnaz** [CCDevNelson/Snap-Updates#77]
When building a double hang tall section in a 16 or 24 depth pard, both dust shelf and upper shelf have to be the same depth.

 Can we assign a depth/setback prompt to the dust shelf and maybe the upper shelf defaults to the depth of the section? 

Or have ability to change both shelves individually? 

There is currently a depth setback, but it applies to both shelves

**Comment by ClassyTeddy** [comment]
This issue is ready for testing on the `Branch_Short-Hang` branch.

**Comment by TEDSTANDAGE** [comment]
Looking good to me in my initial testing.
