### ISSUE TITLE
Default Hang setback to 12" in sections with partitions 16" and deeper

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#78]
In sections 16" and deeper, the hang rod should default to be setback to 12". 

For double hangs in sections 16" and deeper, the dust cover shelf should default to 12" deep (minus 1/4" if adjustable) and shelves above the top rod should default to the depth of the partition (minus the 1/4" if adjustable). This will probably only be possible after Issue #77 is addressed.

Also, we will need Issue #58 to be addressed for this issue and for Issue #77 to be functional as it relates to manufacturing.

**Comment by ClassyTeddy** [comment]
Couple of questions for this issue.
* Should it default to the depth of the partitions if its less than 16" deep?
* Should the dust shelf only default to 12" if it is a double hang?
* Just the dust shelf default to 12"? Or all shelves except shelves above the top rod?

**Comment by TEDSTANDAGE** [comment]
Should the hang rod default to the depth of the partitions if its less than 16" deep? Yes

Should the dust shelf only default to 12" if it is a double hang? Yes (this includes double hang tall), we do not want it to default to 12" in single hang sections (short, medium, or long), and only the dust shelf above the lower hang. We maybe should just get rid of the "add dust shelf" option in the top opening prompt unless someone objects.

Just the dust shelf default to 12"? Or all shelves except shelves above the top rod? Usually just have the dust shelf between the bottom and top rods in a double hang (including double hang tall), so yes just the dust shelf default to 12". Still should have the option to adjust the depths of the different shelves though.

**Comment by TEDSTANDAGE** [comment]
Actually keep the dust shelf option for the top opening--functionally it allows for a triple hang if we want and the dust shelf can go above the middle rod. Have that dust shelf default to 12" in sections 16" and deeper as well.

So, the rule should be just dust shelves defaulting to 12" in sections 16" and deeper while all other shelves default the full depth.

**Comment by ClassyTeddy** [comment]
This issue is ready for testing on the `Branch_Short-Hang` branch.

**Comment by TEDSTANDAGE** [comment]
A few things to fix on this still--

1. The rods are defaulting back to 12", but the setback amount is not being reflected on the prompts, it just says "0" even though it is setback:

![image](https://user-images.githubusercontent.com/61025894/84180890-19c09580-aa3d-11ea-829b-4d9dee805862.png)

2. Only the dust shelf above the bottom rod in a double hang should default to 12", not the shelves above the top rod:

![image](https://user-images.githubusercontent.com/61025894/84180987-41176280-aa3d-11ea-8a27-46190a2b3588.png)

3. I cannot adjust the depth of the dust shelf--that shelf depth setback should be adjustable and the setback should be reflected in the prompt.

**Comment by TEDSTANDAGE** [comment]
Edit to #3 above - the depth of the dust shelf is adjustable, but it is calling it "bottom shelf setback" rather than "bottom dust shelf setback". Let's change that to bottom dust shelf setback, then let's change the "Middle shelves setback" to bottom shelves setback.  Also, the default setback is not being reflected in the prompt, it just says "0" even when the default sets it back.

**Comment by TEDSTANDAGE** [comment]
Looking good to me in my initial testing
