### ISSUE TITLE
Edgebanding Instructions

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#79]
As discussed in our committee meeting 5/21, change edgebanding instructions in XML export / label to match current system of telling shop how many long and short edges are to be edged. Teddy/Riya, if you haven't already, please make this the highest priority right now.

**Comment by riyajose96** [comment]
Teddy and I have updated the Export logic to assign either S1, L1, S2, or L2 for edgebading depending on the part's dimensions.
Ready for testing.
It's in the branch - Edgebanding-Export -Long/Short

**Comment by ClassyTeddy** [comment]
Hey, just wanted to write this down here.

I added exporting logic for edge banding for the top and bottom of cover cleats
I added exporting logic for edge banding for top shelves with finished ends
I added exporting logic for edge banding for toe kick end caps.

These are all ready for testing on the `Edgebanding-Export-Long/Short` branch

**Comment by TEDSTANDAGE** [comment]
Only place I see missing EBing is the back of top shelf with all four edges edged (front, left, right, and back). This piece should be edged 2L/2S (L1, S1, L2, and S2). Once you get that logic in I think this is good to push to Ryan.

**Comment by ClassyTeddy** [comment]
I managed to get that in there as well, and after I do a few more test with different dimensions and closets, I will make the pull request to Ryan and ask him to make it High Priority.

**Comment by TEDSTANDAGE** [comment]
Should we close this item or is there more that needs to be done?

**Comment by ClassyTeddy** [comment]
Personally, I would like to do at least one more job before we consider this done, and I also think that it is up to Mark if the changes put in were implemented correctly, or if more changes need to be done.

**Comment by CCDevNelson** [comment]
This looks as if it's working correctly. (Sample labels on Ted's desk 7/21/20)
