### ISSUE TITLE
Exporting correct material name to XML

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#82]
During production testing we have discovered that the exported material name in the XML needs to be fixed. If the optimization/inventory systems do not recognize the material name, it assumes a 4' x 8' material with woodgrain when optimizing. 

Currently the XML is taking from the "Name" column of the CCItems csv:

SKU | Name | DisplayName | Description | LocationCode | Thickness | RetailPrice | UOM | ProductType | ItemTypeCode | ItemColorCode | ItemProfileCode | VendorName | VendorItemNum
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

For example, here it would export as "U Mystic 15150" rather than U Mystic or U MYSTIC 3/4:

PM-0000230 | U Mystic 15150 | U Mystic | U MYSTIC 3/4 | 1 | 0.75 | 20.25 | SF | PM | 15150 | 167015 | 0 | UKNOWN | 0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Mark, we need a list of the correct material names that the XML needs to have so that the jobs are exported, optimized, and manufactured correctly. Once we have that list, we can determine whether (1) we should create a new column in the csv to pull from, (2) alter what is currently in the "Name" column (though we were asked by Brock and others not to change what is in that column), or (3) change the display name to match the correct material name for the XML and then have it pull from the display name column. Or, if you have other ideas to address this issue, please let me know and we can alter the XML export accordingly.

**Comment by CCDevNelson** [comment]
Ted,
Talking with Sean, this is my list from the COS program. I will need to check with Ned at CADCode, because he had written a small chunk of code in his program to handle the names of materials and spaces, ".", and hash marks. I'm not sure if it will run through that same chunk of code since it's an XML. I hope to have an answer on that tomorrow.
[BoardColorQry.xlsx](https://github.com/CCDevNelson/Snap-Updates/files/4719652/BoardColorQry.xlsx)

**Comment by TEDSTANDAGE** [comment]
Teddy, as we discussed, the name in Column B of the CCItems csv should match what Mark has in the above spreadsheet (which I think you have already done). The edgebanding export needs to be the same as that spreadsheet as well (no EB preceding the color name). Please let me know if you need more information from me or Mark on this. Thanks

**Comment by ClassyTeddy** [comment]
I have done that, but I need info on one more thing. Do stain materials just need to be the same as on the spreadsheet as well?

**Comment by TEDSTANDAGE** [comment]
The stain/paint materials need to export the base material name in the XML/Column B--for wood veneer it should be exported as "Clear Alder Veneer" and MDF needs to be exported as "MDF".

**Comment by TEDSTANDAGE** [comment]
Teddy, do you need more information on this? If not, let's push the new csv to Ryan to be merged with the master version.

**Comment by ClassyTeddy** [comment]
Alright, I will make the change

**Comment by ClassyTeddy** [comment]
Created a pull request for the change.
