### ISSUE TITLE
KD Drilling info not exported

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#83]
In a test job, the KD drilling info was not exported for the one KD shelf in the attached job. For that particular shelf, I had to manually select it to be a "locked shelf" from the properties menu so I'm not sure if that has something to do with it. 

![image](https://user-images.githubusercontent.com/61025894/83797063-d9d16b00-a656-11ea-9e66-07d9d7339b5f.png)

![image](https://user-images.githubusercontent.com/61025894/83797079-e1910f80-a656-11ea-8018-668e0d9409cf.png)

[snap_job.zip](https://github.com/CCDevNelson/Snap-Updates/files/4732077/snap_job.zip)

**Comment by CCDevNelson** [comment]
Just FYI, the XML did have the KD Fittings, just the shelf didn't change to a KD Shelf.
![image](https://user-images.githubusercontent.com/44483142/83807950-b6172080-a668-11ea-8a50-9634f88e8d58.png)

**Comment by ClassyTeddy** [comment]
I have a branch where I believe I have all KD-Shelves exporting drilling info. This can be tested on the `KD-Shelf_Drilling` branch. I am not sure if I got the holes' center location right, so I would like to see what other people think.

**Comment by TEDSTANDAGE** [comment]
@CCDevNelson will need you to look at the drilling info updates

**Comment by TEDSTANDAGE** [comment]
@CCDevNelson are you able to look at the XML and see if drilling info (whether or not you can tell if it is correct info) is being exported? If so, can you show me where to find it please? I don't know where to look. Thanks

**Comment by TEDSTANDAGE** [comment]
The latest Toll Bros test job shows that there still is no drilling information included for KD shelves in the XML--no barcode is being added to the labels for them for the drill to even read.

**Comment by TEDSTANDAGE** [comment]
Here is a picture of a KD shelf's label that doesn't have a barcode:

![image](https://user-images.githubusercontent.com/61025894/87076933-418b5080-c1d7-11ea-9266-1de44de326ca.png)

**Comment by CCDevNelson** [comment]
requested that I clear up some drilling info from latest XML...it seems to me, that none of the "two-sided" drilled partitions came through. With the exception of possibly the 78.86 partitions which had holes on one side (too many) but no holes on the other side. I think there is obviously something amiss with double side pards.
KD shelf are not exporting any drilling but the shelf is coming through with everything else.
Previously we were getting two labels for a single part with drilling on one side. This has been corrected in CADCode so no changes for the XML are need for this.

**Comment by CCDevNelson** [comment]
KD Drill test 11am 7-28-20 results: KD holes are drilling in what looks to be in-line with all the other parts (that is, from the bottom and flipped front-to-back, but is consistent) Since the drilling is coming up from the bottom, I can not safely determine if the holes are drilling the correct depth, but otherwise I would say that we are passing drilling data through now for KD shelves.
