### ISSUE TITLE
Change to have drilling from top instead of bottom

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#84]
This might be something Mark @CCDevNelson works on rather than anything in the code, but on single partitions and KDs the labels are telling telling the drill to drill from the bottom rather than from the top. This should be changed to drill from the top (This is from talking with Sean, and he also said he and Mark already discussed this). Mark, if there is something in the XML export logic we need to change, let us know.

**Comment by CCDevNelson** [comment]
Ted,
This should be exporting in the XML to tell it which side to drill.

I'm not 100% sure on this but I think the z=1 part should actually be z=-1 and that is what tells it what face to drill. (see attached)
![DrillFace](https://user-images.githubusercontent.com/44483142/83806650-b6aeb780-a666-11ea-859a-ee8b75c7edc6.png)

**Comment by CCDevNelson** [comment]
After speaking with Ned at CADCode his answer on this was:
"_**No.  It's more complicated than that, but straightforward with the right tools.
You have to understand matrix algebra to really use that fully.
There is the normal which points to the positive Z direction.  The orgdisplacement is the distance from the origin to the reference plane.**_"
He also said that Ryan should probably get back in touch with him and he can go over that part again with him. They had  discussed this awhile back. There is also the "two-sided" drilling that is part of that as well.
