### ISSUE TITLE
Full overlay width option for Hampers

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#85]
Hampers don't currently have the option for full overlay width like Doors/Drawers do. We should add the option (though we don't use it often, we should be consistent with the options available)

![image](https://user-images.githubusercontent.com/61025894/83899514-6e96a000-a70d-11ea-93be-d2a215d46903.png)

**Comment by ClassyTeddy** [comment]
This issue is ready for testing on the `Door/Drawer-Face-Overlay-Sizing-Fix` branch.

**Comment by TEDSTANDAGE** [comment]
Looks good, thank you
