### ISSUE TITLE
Change XML export logic for Cover Cleat to export full lengths rather than exact sizes

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#86]
Currently SNaP is exporting exact length cover cleat pieces in 3/4" material, resulting in double the amount of cover cleat material being exported than necessary but also not exporting cleat material for wrap around areas, etc. This is also different than what is currently done through COS and shop manufacturing processes. 

The shop is requesting that we change the logic for cover cleat to match current manufacturing processes, which means only ordering cover cleat material for non-white/almond jobs, and exporting full lengths of cover cleat (96x3.68 in 3/4" material edged 2L that are ripped by the shop 
resulting in two usable 3/8" thick 96x3.68" cover cleat lengths).

If possible, and after talking it over with Sean W., in order to calculate the necessary lengths of cover cleat to export, my proposal would be the following:

**Add together all the opening widths in a room, divide by 96", then round up to the next whole number. Then, if that whole number is 1-2 lengths of cover cleat, add one extra length of cover cleat. If the number is 3-5 lengths, add two extra lengths of cover cleat. If the number is 6 or more lengths of cover cleat, add three extra lengths of cover cleat to the room.** 

This is probably a pretty cautious/conservative approach to be honest, and if it results in too much cover cleat being thrown out after jobs (or if the opposite happens too) we can adjust accordingly.

For example, the following room would export 6 cover cleat lengths. 

The room has a total opening width amount of 302.25" (Wall A - 31" per opening x 3 openings= 93", Wall B - 29.0625" x 4 = 116.25, Wall C - 31"x3 = 93"; 93"+116.25" + 93" = 302.25"). 

302.25" / 96" = 3.148

Round up to 4 lengths.

Because it is between 3-5 lengths, add 2 extra lengths for a total of 6 cover cleat lengths.

![image](https://user-images.githubusercontent.com/61025894/83906925-4876fd00-a719-11ea-999c-1b5a49814742.png)

![image](https://user-images.githubusercontent.com/61025894/83906937-5036a180-a719-11ea-908c-3a6d5a2c9f75.png)

![image](https://user-images.githubusercontent.com/61025894/83906953-588edc80-a719-11ea-8235-379fe5631ad7.png)

**Comment by TEDSTANDAGE** [comment]
No cover cleat should be exported for white/almond material. We keep lengths of those in stock.

**Comment by CCDevNelson** [comment]
Ted,
If NO cover cleat for white/almond is exported to the XML, then I will not be able to cost out the job correctly with the way it is now, so we would need to somehow charge more for a cleat that is white/almond to be able to cover the cost of the "stock" cover cleat that is not accounted for in the XML. Just an FYI....

**Comment by TEDSTANDAGE** [comment]
Perhaps there is a way to export to the XML for pricing/inventory purposes but write a rule so that white/almond cover cleat is not added to any cutsheets?

**Comment by TEDSTANDAGE** [comment]
I'm fine either way

**Comment by CCDevNelson** [comment]
I got with CADCode, and here is what we need to do with White and Almond Cover Cleat in the XML:

![image](https://user-images.githubusercontent.com/44483142/83912074-1918be00-a722-11ea-96fd-dc66d8831543.png)

**Comment by CCDevNelson** [comment]
So, I would suggest that we change it to "draw" then it will be in the XML for costing/pricing but will not be optimized for the shop to cut.

**Comment by ClassyTeddy** [comment]
So, what I am gathering for this issue is that for **JUST** cover cleat, I use the sizing outlined by Ted and export the full lengths of Cover cleat, then if the Cover Cleat is White/Almond, I change the `Class` to `Draw`?

**Comment by TEDSTANDAGE** [comment]
Yes

**Comment by ClassyTeddy** [comment]
A fix for this is available on the `Full-Length-Cover-Cleat-Export` branch.

I managed to get SNaP to export cover cleat in full lengths and if the materials is White/Almond, the class should now be draw.

**Comment by ClassyTeddy** [comment]
Added `Dura White` and `Dura Almond` to the list of colors that change the cover cleat's class to draw

**Comment by ClassyTeddy** [comment]
This issue can now be tested on the master branch.

**Comment by TEDSTANDAGE** [comment]
Teddy/Riya, please change the cover cleat export to have only one long edge with edgebanding rather than both.

**Comment by TEDSTANDAGE** [comment]
Cover cleat is still exporting as "make" rather than "draw" with white/almond colors, so still need to address that issue.

**Comment by ClassyTeddy** [comment]
This issue is ready for testing on the `Cover-Cleat-Export-Changes` branch.
