### ISSUE TITLE
Unique Material option for 1/4" backs isn't available anymore

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#88]
I'm not sure where it went but I can't find the "Unique Material" feature anymore when trying to change 1/4" backing material

**Comment by ClassyTeddy** [comment]
I have the option to add unique material to the backing for both 1/4" and 3/4". Is only 1/4" missing or are both missing?

**Comment by TEDSTANDAGE** [comment]
Here is an example where the unique backing option isn't showing up for a 1/4" back:

![image](https://user-images.githubusercontent.com/61025894/84670370-e79ab200-aeda-11ea-846a-7bf127a8805e.png)

Here are the construction options selected:

![image](https://user-images.githubusercontent.com/61025894/84670488-0ef17f00-aedb-11ea-8cda-34b6a56cd8aa.png)

The unique material option seems to be working in some situations but not others.

**Comment by ClassyTeddy** [comment]
Alright, it appears that the backing only allows for a unique material to be selected if the backing is a single piece (In this case, if you had center and bottom also selected, and the option for it to be a single piece of backing, it would allow you to change the unique material.) I will take a look at how the backing is implemented to see if it can allow for unique materials for each section of backing.

**Comment by ClassyTeddy** [comment]
A fix for this is ready on the `Adding-Unique-Material-to-Top-and-Bottom-Backing` branch. Now, backing should be able to have a unique material if it is a top, center, bottom, or single back.

**Comment by TEDSTANDAGE** [comment]
Looks good to me, thanks
