### ISSUE TITLE
Slow / lag when inserting drawers

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#89]
I think I've had conversations with  @kategodfrey and @ClassyTeddy about this already, but we have made a lot of updates and capabilities to the drawers and I think that has caused the program to slow down when trying to place drawers into the scene. I'm not sure what we can do to speed it up so there is not as long of a lag.

**Comment by ClassyTeddy** [comment]
I am definitely not familiar with actually manipulating load times, so I may have Ryan take a look at this or maybe I will ask him a question or two. I do believe that the lag is being caused by the File Rails that I added, but I am not sure why it slowed down as much as it did.

**Comment by TEDSTANDAGE** [comment]
I think a lot of times the long load times are when it is struggling to find materials--so it could be the 1/2" white paper material for the drawer boxes/file rails that it wasn't trying to find prior to the drawer updates?

**Comment by ClassyTeddy** [comment]
That could also be it. I think I will push this up to Ryan with just standard priority.

**Comment by TEDSTANDAGE** [comment]
Just timed it as 55 second lag on my work computer waiting for the drawers to load after dragging it to the scene. 

Teddy, can you ask Ryan to heighten the priority on this after he finishes the two sided drilling please? If you and Riya can look into this as well I'd appreciate it.

Thanks, Ted

**Comment by ClassyTeddy** [comment]
No problem. I will let Ryan know.
