### ISSUE TITLE
Blind Corner Panel Option

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#90]
Let's create a Blind Corner Panel (BCP) option in the Construction Options of the Opening Starter Prompts, above the base options but below the full back options:

![image](https://user-images.githubusercontent.com/61025894/84686963-bda0ba00-aef1-11ea-8c56-293bff0ec5b8.png)

- Let's have the option for a BCP be for adding a BCP on the left and/or right (a check box for each), which would place the BCP on the left side of first opening or the right side of the last opening. 

- When the box is clicked, another prompt should reveal itself allowing the user to determine the depth of the BCP (we will have to train the designers about having the standard depth of the BCP be 2" deeper than the depth of the cabinet/partition being built perpendicular to the BCP). Let's have the default depth be 18".

- Height/location: The height and vertical location of the BCP will be the same as a full length door height and vertical location would be for that partition, and horizontally the BCP will cover the entire front of the far left or far right partition. 

- Edgebanding: The BCP should be edged 1L/2S (the other long edge of the BCP will go up against the wall, so it doesn't need edgebanding). 

- Drilling: The drilling for the BCP should account for the offset vertical location of the BCP compared to the partition, meaning the vertical location of the holes needs to match/line up with the vertical location of the partitions of that section. We currently use a 3/8" spacer on the top and bottom to account for it when drilling BCPs now, but perhaps we can be more precise with our drilling code here and account for the ~0.91"/2 (0.455") adjustment to the top and bottom of the BCP where we would start drilling the line of holes. We also should have it not drill the top and bottom holes because those holes are close to the edge of the BCP, are not really functional/used, and they sometimes end up being drilled through the edgebanding of the BCP because of how close they are to the edge.

- Relation to doors that are subsequently inserted into the opening: This will need to affect doors that are subsequently added to the openings containing the BCPs. We can go over sizing the widths of those doors (single and double) when the above is finished.

Let me know if I left anything out or if you have any questions.

**Comment by TEDSTANDAGE** [comment]
I have gone over this in person with Teddy explaining the basics of how BCPs work, the above is for documentation purposes, so I apologize if I may have shortcutted the explanation and made some assumptions of everyone knowing about BCPs and their application. If anyone has questions, please feel free to ask me

**Comment by ClassyTeddy** [comment]
This issue is ready for testing on the `Blind-Corner-Panels` branch.

A thing of note is there is currently no drilling info for this new panel, which I will start looking into how to implement.

**Comment by TEDSTANDAGE** [comment]
Looking really good. The panels look to be entering with the right placement, size, edgebanding. When doors are placed into a section with a BCP those doors look to be sizing correctly. 

We will need to look at when we place other items in those sections (Teddy I think I misunderstood your question to me earlier, so I apologize). Let's not worry about drawers, but we will need to look at hangs and shelf stacks for now. Here is what happens when a shelf stack is placed into a BCP section:

![image](https://user-images.githubusercontent.com/61025894/84813707-31f85d80-afc5-11ea-924d-1d5de1443618.png)

Here is what a hang section looks like (functionally for a hang section in a BCP section we would want the depth of the section to be (standard) 24" deep so hangers / clothes will fit, but that should be up to the designer to know that):

![image](https://user-images.githubusercontent.com/61025894/84813816-5fdda200-afc5-11ea-8290-c699d8415291.png)

**Comment by ClassyTeddy** [comment]
I can look at shelves and hangs to have them size correctly.

**Comment by ClassyTeddy** [comment]
This issue is ready for full testing with the addition of shelves and hangs. Let me know if you find anything.

**Comment by TEDSTANDAGE** [comment]
Including drilling info or are you still needing info? Here is what I wrote in the original issue posting:

> Drilling: The drilling for the BCP should account for the offset vertical location of the BCP compared to the partition, meaning the vertical location of the holes needs to match/line up with the vertical location of the partitions of that section. We currently use a 3/8" spacer on the top and bottom to account for it when drilling BCPs now, but perhaps we can be more precise with our drilling code here and account for the ~0.91"/2 (0.455") adjustment to the top and bottom of the BCP where we would start drilling the line of holes. We also should have it not drill the top and bottom holes because those holes are close to the edge of the BCP, are not really functional/used, and they sometimes end up being drilled through the edgebanding of the BCP because of how close they are to the edge.

Currently we just drill it as if it was a single partition (drilling on the side of the BCP in the section) with both the front and back line of holes, and with the 3/8" spacer on the top and bottom like I explained above. Technically we only need the front line of holes though.

**Comment by ClassyTeddy** [comment]
I do still need to work on the drilling. I am going to switch my focus over to 2D views multiple elevations for now however, as I would like to discuss with Ryan (Which we will most likely have a meeting next week) about the specifics of the drilling system and how I might apply it to a situation like this. There are a lot of keywords/variables that I can see in the drilling system that I don't quite understand. Plus, I know that his focus right now is drilling (with drilling from the top as well as stopping from drilling too deep.) and I do not want to work in an area that might conflict with the files he is currently working on.

**Comment by TEDSTANDAGE** [comment]
Teddy, can we ask Ryan to merge this BCP addition with the master and then create a new issue in SNaP-Dev to have Ryan add the drilling information to BCPs please?
