### ISSUE TITLE
Island exporting issue

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#93]
Riya and I have discussed reworking island components, but there are couple items we need to address before we can do that.

The first issue is that no XML is produced when an island is present in a room, whether the room is otherwise empty or even if it has other items/assemblies that normally do export (like partitions, drawers, etc.).

**Comment by ClassyTeddy** [comment]
This issue is ready for testing on the `Island-Exporting-Issues` branch. Please test it by placing new islands into a scene. Keep in mind that I had to slightly change top shelves for this fix, so please test newly placed top shelf too.

**Comment by TEDSTANDAGE** [comment]
I was able to export a room that had an island in it and it even exported the components of the island itself (albeit not constructed the Classy way, but it did export the parts). Thank you Teddy--let's go over island components tomorrow and let's get islands going! I'm excited by this. Would be interested in why it took changing top shelves for this to work as it seems unrelated. Let's talk tomorrow about that too.
