### ISSUE TITLE
Melamine Countertop Improvements

### ISSUE THREAD

**Issue by TedClassy1209** [CCDevNelson/Snap-Updates#95]
A few things on melamine countertops (honestly unsure if some of these items may have been brought up already in other issues). We can get to HPL/stone countertop issues later on.

1. Melamine countertops are showing (and exporting in the XML) as 1.5" thick instead of 0.75", even though the material type is exporting correctly.

![image](https://user-images.githubusercontent.com/61025894/84924046-e1dcd200-b07c-11ea-9bdd-c01c402d285e.png)

![image](https://user-images.githubusercontent.com/61025894/84924211-105aad00-b07d-11ea-9c21-208df49c344b.png)

2. Edgebanding options and XML info need to be added to the melamine CT, which should function similar to top shelf:

![image](https://user-images.githubusercontent.com/61025894/84924415-544db200-b07d-11ea-8b5f-71ba59d5a21a.png)

3. Instead of a "horizontal location" prompt, we should have a left overhang prompt and a right overhang prompt.

4. Need option (or make it automatic) to oversize the export of melamine CT if it is in the corner of a room, similar to top shelf.

5. Should not have "edge-type" options for melamine countertops, is always just flat.

6. We should consider making Melamine Countertops its own library item, separating out from HPL and stone.

**Comment by TEDSTANDAGE** [comment]
(by the way, the addition of backsplash in the countertop-improvements branch re: CCDevNelson
/SNaP-Dev Issue #155 looks good to me)

**Comment by riyajose96** [comment]
3.Deleted prompt "horizontal location" and added "left Overhang" , "Right Overhang" prompts.
5.Eliminated "edge-type" options for melamine countertops.

on the branch -- Melamine-Countertop

**Comment by riyajose96** [comment]
1.Corrected Melamine CT exporting thickness.

**Comment by riyajose96** [comment]
2. Included Edgebanding options and XML info for MelamineCT.
3. Created and fixed type error issues with Left Overhang and Right Overhang prompts.

on the branch -- Melamine-CT

**Comment by TEDSTANDAGE** [comment]
Good changes so far, thank you Riya. Can you tell me where I can find the edgebanding/exposed end options? I can't seem to find them in the prompts:

![image](https://user-images.githubusercontent.com/61025894/88086674-95cdf300-cb3c-11ea-8bbd-df4cbda7b4df.png)

**Comment by TEDSTANDAGE** [comment]
Also the displayed "width" does not look to be adjusting when the left & right overhangs are changed.

**Comment by TEDSTANDAGE** [comment]
Please have the name of the part export in the XML as "Countertop" rather than "Countertop Deck":

![image](https://user-images.githubusercontent.com/61025894/88090902-1c85ce80-cb43-11ea-8c4f-a6f8b832c57b.png)

**Comment by TEDSTANDAGE** [comment]
Even though the drawing is showing finished/edged sides/ends of the countertop, the XML is only putting edgebanding on the front:

![image](https://user-images.githubusercontent.com/61025894/88091202-9918ad00-cb43-11ea-9561-149a07aff8e3.png)

![image](https://user-images.githubusercontent.com/61025894/88091220-9e75f780-cb43-11ea-8c89-7cd12c33edf4.png)

Please have the countertop prompts mimic the top shelf prompts for "exposed ends":

![image](https://user-images.githubusercontent.com/61025894/88091363-cc5b3c00-cb43-11ea-951c-39ca6ea24622.png)

**Comment by riyajose96** [comment]
Alright, I shall fix it.

**Comment by riyajose96** [comment]
-Added prompts for "Exposed Ends"options.
-Changed xml label "Countertop Deck" to "Countertop".
-Added Edgebanding details of CT to xml report.

On the branch -- Melamine-CT

**Comment by ClassyTeddy** [comment]
The countertops I believe now have all the above issues addressed and are ready for testing on the `Melamine-CT` branch.

**Comment by TEDSTANDAGE** [comment]
Sorry I didn't test this timely. Teddy, can we have this branch updated with all the latest changes in the master branch so I can test its compatibility? I don't think there should be any issues, I was just having some performance things going on since this branch was originally created with older versions I think. Thanks

**Comment by ClassyTeddy** [comment]
I just updated it, check it out.

**Comment by TEDSTANDAGE** [comment]
I think this one will have to be reworked, doesn't look like the changes are currently being reflected in the branch:

![image](https://user-images.githubusercontent.com/61025894/91482878-9b190e80-e85b-11ea-8221-e8521c3a0862.png)

**Comment by ClassyTeddy** [comment]
Is that a new counter top that you just placed? I have the changes on my end.

**Comment by TEDSTANDAGE** [comment]
Yes, new project, new room, new pards, new CT. I will re-do a fetch from GitHub, load SNaP defaults, and try again though.

**Comment by TEDSTANDAGE** [comment]
Still having issues:

![image](https://user-images.githubusercontent.com/61025894/91485323-8cccf180-e85f-11ea-9b74-bfdb55148038.png)

Unable to export an XML, still showing a 1.5" thick CT even when melamine is selected.

**Comment by TEDSTANDAGE** [comment]
If you are seeing all the changes on yours still, then perhaps it is something with my laptop and I will test this on my desktop computer in the office on Monday

**Comment by ClassyTeddy** [comment]
Alright. I will make sure everything is working on my end.

**Comment by ClassyTeddy** [comment]
I found the issue. These changes were implemented after Ryan's lag fix, which created blend files for each object in the library to make it draw faster. This means, your Snap was using the old blend file for countertops, which means it was basically using the old countertops even though all the changes were in the code. I just uploaded a new .blend file for countertops, and it should be ready for testing for real now.

**Comment by TEDSTANDAGE** [comment]
Awesome thank you, that worked. The prompts, edgebanding, and display look good. 

I think the only things I'm seeing now are a couple things with the XML export: (1) it is still calling it a "Countertop Deck" rather than just "Countertop" and (2) we still need to add logic to add 3" to the width of the countertop for each unexposed side (left and right for a possible 6"), though I'm not sure I gave clear instructions for that, above. Let me know if you have any questions.

![image](https://user-images.githubusercontent.com/61025894/91488789-b0466b00-e864-11ea-9c97-fd31fd4f4469.png)

![image](https://user-images.githubusercontent.com/61025894/91488773-a91f5d00-e864-11ea-93d3-742c1ae52b63.png)

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Melamine-CT` branch.

**Comment by TEDSTANDAGE** [comment]
Great, thank you. It looks good. We are going to have to address oversized CT soon (>96") but this is good for now I think and we should merge these fixes and address the oversized CT in a separate issue unless someone else is seeing other issues.

**Comment by ClassyTeddy** [comment]
I will keep testing some things on this one myself for a little bit, and unless I find anything, I will create a pull request tomorrow.
