### ISSUE TITLE
Bringing a previously "X'd" out project back onto the project list within SNaP

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#96]
If a project is X'd out from SNaP, it still exists in the SNaP Projects folder in My Documents, and you can access (and ultimately save over) the old blend file by going File>Open in SNaP. However, when you do that, the old Project does not show up on the Project list anymore within SNaP and I can't figure out how to get it to show up again (the "Open Project" function below the list of Projects within SNaP does not seem to do anything either).

**Comment by riyajose96** [comment]
When a project is "X'd" it removes the project_name.ccp file from the corresponding Fie Explorer folder and that is causing it not to show up under snap "Projects".
Now a "Recycle Bin" folder is generated along with SNaP Projects "C:\Users\Owner\Documents\Recycle Bin" and the project_name.ccp file gets stored in to the that.
To recover the project, cut and paste project_name.ccp from "C:\Users\Owner\Documents\Recycle Bin" to "C:\Users\Owner\Documents\SNaP Projects\project_name".

Need help with testing.
On the branch -- bringing-back-previously-X'd-project

**Comment by TEDSTANDAGE** [comment]
Worked for me, I think this is a good fix for this issue. Interested in other's thoughts on this as well.

I think I might change the name of the folder from just "Recycle Bin" to "SNaP Projects Recycle Bin", or if possible move this recycle bin to within the SNaP Projects folder (though the latter could possibly create issues when SNaP looks for jobs to include in the Projects list?)--Because this will be placed in the User's computer's Documents folder it could confuse the user if they have just a "Recycle Bin" folder in their documents folder.

**Comment by riyajose96** [comment]
Ted, 
 I shall rename it to "SNaP Projects Recycle Bin". But keeping the "SNaP Projects Recycle Bin" in SNaP Projects folder will generate issues. I tried that already. Seeing the "project_name.ccp" file, SNaP will create projects named "project_name.001" , "project_name.002" … each time when we restart SNaP.

**Comment by riyajose96** [comment]
Renamed "Recycle Bin" to "SNaP Projects Recycle Bin".

On the branch -- bringing-back-previously-X'd-project.

**Comment by TEDSTANDAGE** [comment]
Thank you--is it possible to have it move the entire folder to the recycle bin (including room blend files, 2D views, any XML files that might be in there, etc.) rather than just the .ccp file?

**Comment by riyajose96** [comment]
It should be possible. I shall look into it.

**Comment by riyajose96** [comment]
Fix done.
Ready for testing.
On the branch -- bringing-back-previously-X'd-project.

**Comment by TEDSTANDAGE** [comment]
Looks good to me--what are others' thoughts on this fix?

**Comment by kategodfrey** [comment]
![image](https://user-images.githubusercontent.com/63115502/87706773-ea482b80-c754-11ea-899c-ff217bd86fe1.png)

**Comment by kategodfrey** [comment]
![image](https://user-images.githubusercontent.com/63115502/87706828-021faf80-c755-11ea-8c6c-1486da97f78f.png)

**Comment by kategodfrey** [comment]
Recycle bin is created but no projects are in it

**Comment by kategodfrey** [comment]
Figured it out. Thanks!

**Comment by riyajose96** [comment]
- Made chages so that if a project with same name already exists in 'SNaP Projects Recycle Bin' it will be replaced by new one.
- Changed the warning "Are you sure you want to delete this project?" to "Are you sure you want to delete this project? If a project already exits in 'SNaP Projects Recycle Bin' with same name it will be replaced by 'project_name '" 

Ready for testing
On the branch -- bringing-back-previously-X'd-project

**Comment by SeanRadvan** [comment]
While i was testing this, it looks like deleting a room correctly removes it from the projects folder, however if you delete a project, it deletes the ccp, but leaves the folder and all room in it. is this correct?

**Comment by TEDSTANDAGE** [comment]
If you delete a project it should move the entire folder to the SNaP Projects Recycle Bin now, not just the ccp. If you delete a room, it deletes it forever.



> Thank you--is it possible to have it move the entire folder to the recycle bin (including room blend files, 2D views, any XML files that might be in there, etc.) rather than just the .ccp file?



> It should be possible. I shall look into it.



> Fix done.
> Ready for testing.
> On the branch -- bringing-back-previously-X'd-project.

**Comment by TEDSTANDAGE** [comment]
Sorry, I think I read your reply wrong--the ccp file should still exist (not be deleted, just moved with the rest of the items in the folder to the SNaP Projects Recycle Bin).

**Comment by TEDSTANDAGE** [comment]
@SeanRadvan is this working correctly for you now?

**Comment by SeanRadvan** [comment]
once i loaded snap defaults, it appears so.

**Comment by TEDSTANDAGE** [comment]
I think this is ready to merge after we release v1.2.0 unless anyone doesn't agree with the approach or has found an issue.
