### ISSUE TITLE
SNaP won't export XML for projects with a single opening that has variable width option selected

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#98]
I am trying to test the variable width parameters but an XML is not being produced when "variable section" is selected in the construction options (when I have a single opening):

![image](https://user-images.githubusercontent.com/61025894/85429829-26141a80-b534-11ea-9955-0d2d26bdbbde.png)

Here I hit Prepare Project XML, but no XML is produced:

![image](https://user-images.githubusercontent.com/61025894/85429944-5065d800-b534-11ea-82f7-8991367a09f0.png)

However, if I un-select the variable width option I can get an XML...:

![image](https://user-images.githubusercontent.com/61025894/85429994-64a9d500-b534-11ea-8d13-1c82881579b9.png)

![image](https://user-images.githubusercontent.com/61025894/85430060-7b502c00-b534-11ea-8b58-696209ceb5c7.png)

If I re-select the variable width option and try preparing an XML again, not only does it not create an XML but it actually deletes the previously-produced XML from the SNaP Projects folder:

![image](https://user-images.githubusercontent.com/61025894/85430179-a5095300-b534-11ea-90cf-a1b4cc9f3562.png)

This same thing occurs when I have a two-opening carcass with both openings having the "variable section" option selected (same with all opening amounts when all sections are selected as variable section). 

We often have a single opening section that is a variable so this needs to be addressed. I assume it has to do with the XML export logic when all openings are set as variable sections, and it's confused so it just doesn't export an XML (or deletes the existing XML).

**Comment by riyajose96** [comment]
Updates are on the branch -- Change-variable-width-parameters#99

**Comment by riyajose96** [comment]
Updates moved to the branch-- multiple-variable-width#98
Issue #98 has not resolved yet.

**Comment by riyajose96** [comment]
Fixed issue #98. Snap is exporting xml when multiple variable sections selected and values are also looking good to me. 
Need help with testing -- Its on the branch multiple-variable-width#98

**Comment by TEDSTANDAGE** [comment]
This looks good to me
