### ISSUE TITLE
Change variable width parameters

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#99]
From my testing it looks like when there is a variable section the XML export has the parts in that section go up to the next standard 3" increment size in width (12", 15", 18", etc.), then it goes up an extra 3" increment when the section width is equal to or less than 0.5" from the next highest standard 3" increment. This is cutting it too close. After talking with various people, let's change the parameter to go up the extra 3" increment when the section width is equal to or less than 2.5" from the next highest standard 3" increment (rather than the current 0.5"). 

Riya, will you please take this one and start on it right away? It should be pretty straightforward.

Thanks, Ted

**Comment by TEDSTANDAGE** [comment]
For further clarification / as an example:

Currently a 14" section with "variable section" selected exports as 15" wide while a 14.5" section with "variable section" selected exports as 18" wide. Under the new parameters, both circumstances should result in exported 18" wide parts (any section 12.5" to 15.49" with "variable section" selected should export as 18" under the new parameters)

**Comment by RyanMDev** [comment]
This is the function that will need modification.

```
   def get_var_sec_length(self, x):
        increment = 3
        offset = unit.inch(0.5)
        max_len = 97

        for length in range(increment, max_len, increment):
            length = unit.inch(length)
            if x < length:
                if length - x <= offset:
                    return length + unit.inch(increment)
                else:
                    return length     
```   

https://github.com/CCDevNelson/SNaP-Dev/blob/57767de3f17ead85f7c07a7664d43852de134279/SNaP/2.78/scripts/addons/snap_db/snap_export.py#L620-L631

This along with the new `write_full_sized_cover_cleat` function is also causing the XML operator to throw an error and not produce an XML (#98).

snap_export.py > write_full_sized_cover_cleat>  line: 1084
`cover_cleat.obj_x.location.x = unit.inch(96)`

This line sets the length to of the cover cleat to 96" then when `get_var_sec_length` is called we can see there is a max_len of 97" this causes `get_var_sec_length` to return None when 96 is passed in.

https://github.com/CCDevNelson/SNaP-Dev/blob/57767de3f17ead85f7c07a7664d43852de134279/SNaP/2.78/scripts/addons/snap_db/snap_export.py#L1084

**Comment by riyajose96** [comment]
Issue #99 resolved.
It's on the branch-- Change-variable-width-parameters#99

**Comment by TEDSTANDAGE** [comment]
Looks good to me. Thanks
